---
sidebar: sidebar
api: true
explorer: false
permalink: 'application_applications_application.uuid_snapshots_endpoint_overview.html'
summary: 'Manage application snapshots'
---

= Manage application snapshots



== Overview

Applications support snapshots across all member storage elements. These snapshots can be created and restored at any time or as scheduled. Most applications have hourly snapshots enabled by default, unless the RPO setting is overridden during the creation of the application. An application snapshot can be flagged as either _application consistent_, or _crash consistent_. From an ONTAP perspective, there is no difference between these two consistency types. These types are available for record keeping so that snapshots taken after the application is quiesced (application consistent) can be tracked separately from those snapshots taken without first quiescing the application (crash consistent). By default, all application snapshots are flagged to be _crash consistent_, and snapshots taken at a scheduled time are also considered _crash consistent_.

The functionality provided by these APIs is not integrated with the host application. Snapshots have limited value without host coordination, so the use of the SnapCenter Backup Management suite is recommended to ensure correct interaction between host applications and ONTAP.


