---
sidebar: sidebar
api: true
explorer: false
permalink: 'cloud_targets_endpoint_overview.html'
summary: 'Manage cloud targets'
---

= Manage cloud targets



== Retrieving a collection of cloud targets

The cloud targets GET API retrieves all cloud targets defined in the cluster.

== Creating cloud targets

The cluster administrator tells ONTAP how to connect to a cloud target. The following pre-requisites must be met before creating an object store configuration in ONTAP.
A valid data bucket or container must be created with the object store provider. This assumes that the user has valid account credentials with the object store provider to access the data bucket.
The ONTAP node must be able to connect to the object store.

This includes:

* Fast, reliable connectivity to the object store.
* An inter-cluster LIF (logical interface) must be configured on the cluster. ONTAP verifies connectivity prior to saving this configuration information.
* If SSL/TLS authentication is required, then valid certificates must be installed.
* FabricPool license (required for all object stores except SGWS).

== Deleting cloud targets

If a cloud target is used by an aggregate, then the aggregate must be deleted before the cloud target can be deleted.


