---
sidebar: sidebar
api: true
explorer: false
permalink: 'cluster_overview.html'
summary: 'ONTAP REST API Cluster endpoints'
---

= ONTAP REST API Cluster endpoints



== Overview

These APIs enable you to perform a number of independent workflows, including:

* Creating the cluster
* Adding nodes to the cluster
* Managing cluster configuration data (including name, version, NTP servers, name servers, and DNS domains)
* Managing node configuration data (including node names, models, serial numbers, and HA group information)
* Discovering the nodes on the cluster network that can be added to the cluster
* Viewing and updating current and recent jobs
* Updating the cluster software

=== Pre-Cluster APIs

A few of the cluster APIs (namely, POST/OPTIONS on /api/cluster, GET/HEAD/OPTIONS on /api/cluster/nodes, and calls on /api/cluster/jobs) are allowed before the cluster is created.  These APIs support creation of the cluster and monitoring of its progress. Any other cluster API used before the cluster is created will fail.


