---
sidebar: sidebar
api: true
explorer: false
permalink: 'delete-protocols-san-igroups-igroups-.html'
summary: 'Remove a nested initiator group from an initiator group'
---

= Remove a nested initiator group from an initiator group

[.api-doc-operation .api-doc-operation-delete]#DELETE# [.api-doc-code-block]#`/protocols/san/igroups/{igroup.uuid}/igroups/{uuid}`#

*Introduced In:* 9.9

Removes a nested initiator group from an initiator group. This API does not delete the nested initiator group itself. It removes the relationship between a parent and child initiator group.

This API only supports removal of initiator groups owned directly by the initiator group. Further nested initiator groups must be removed from the direct parent initiator group.

== Related ONTAP commands

* `lun igroup remove`

== Learn more

* link:protocols_san_igroups_endpoint_overview.html[DOC /protocols/san/igroups]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|igroup.uuid
|string
|path
|True
a|The unique identifier of the parent initiator group.


|uuid
|string
|path
|True
a|The unique identifier of the nested initiator group.


|allow_delete_while_mapped
|boolean
|query
|False
a|Allows the deletion of a nested initiator group from of a mapped initiator group.

Deleting a nested initiator group from a mapped initiator group means that the LUNs, to which the initiator group is mapped, are no longer available to the initiators nested below the initiator group being removed.  This might cause a disruption in the availability of data.

*This parameter should be used with caution.*

* Default value:

|===

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 1254213
| The initiator group is mapped to one or more LUNs and `allow_delete_while_mapped` has not been specified.

| 5374738
| The child initiator group is not owned by the parent initiator group.

| 5374743
| LUN maps exist for a parent initiator group.

| 5374852
| The initiator group specified in the URI does not exist.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
