---
sidebar: sidebar
api: true
explorer: false
permalink: 'delete-security-roles--privileges-.html'
summary: 'Delete a privilege tuple from the role'
---

= Delete a privilege tuple from the role

[.api-doc-operation .api-doc-operation-delete]#DELETE# [.api-doc-code-block]#`/security/roles/{owner.uuid}/{name}/privileges/{path}`#

*Introduced In:* 9.6

Deletes a privilege tuple (of REST URI or command/command directory path, its access level and an optional query) from the role. The REST URI can be a resource-qualified endpoint. Currently, the only supported resource-qualified endpoints are the following&#58;

== Snapshots APIs

&ndash; _/api/storage/volumes/{volume.uuid}/snapshots_

== File System Analytics APIs

&ndash; _/api/storage/volumes/{volume.uuid}/files_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/clients_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/directories_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/files_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/users_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/clients_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/directories_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/files_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/users_

== ONTAP S3 APIs

&ndash; _/api/protocols/s3/services/{svm.uuid}/users_

In the APIs above, and in the context of REST roles, the wildcard character &#42; can be used in place of _{volume.uuid}_ or _{svm.uuid}_ to represent _all_ volumes or _all_ SVMs, depending on whether the REST endpoint references volumes or SVMs. The _{volume.uuid}_ corresponds to the _-instance-uuid_ field in the output of the "volume show" command at the diagnostic privilege level. It can also be retrieved through the REST endpoint _/api/storage/volumes_.

== Required parameters

* `owner.uuid` - UUID of the SVM which houses this role.
* `name` - Name of the role to be updated.
* `path` - Constituent REST API path or command/command directory path to be deleted from this role. Can be a resource-qualified endpoint (example: _/api/svm/svms/43256a71-be02-474d-a2a9-9642e12a6a2c/top-metrics/users_). Currently, resource-qualified endpoints are limited to the _Snapshots_, _File System Analytics_ and _ONTAP S3_ endpoints listed above in the description.

== Related ONTAP commands

* `security login rest-role delete`
* `security login role delete`

== Learn more

* link:security_roles_owner.uuid_name_privileges_path_endpoint_overview.html[DOC /security/roles/{owner.uuid}/\{name}/privileges/\{path}]
* link:security_roles_endpoint_overview.html[DOC /security/roles]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|owner.uuid
|string
|path
|True
a|Role owner UUID


|name
|string
|path
|True
a|Role name


|path
|string
|path
|True
a|REST API path or command/command directory path

|===

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 1263347
| Cannot modify pre-defined roles.

| 5636168
| This role is mapped to a REST role and can only be modified by updating the REST role.

| 13434890
| Vserver-ID failed for Vserver roles.

| 13434893
| The SVM does not exist.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
