---
sidebar: sidebar
api: true
explorer: false
permalink: 'delete-storage-namespaces-.html'
summary: 'Delete an NVMe namespace'
---

= Delete an NVMe namespace

[.api-doc-operation .api-doc-operation-delete]#DELETE# [.api-doc-code-block]#`/storage/namespaces/{uuid}`#

*Introduced In:* 9.6

Deletes an NVMe namespace.

== Related ONTAP commands

* `vserver nvme namespace delete`

== Learn more

* link:storage_namespaces_endpoint_overview.html[DOC /storage/namespaces]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|The unique identifier of the NVMe namespace to delete.


|allow_delete_while_mapped
|boolean
|query
|False
a|Allows deletion of a mapped NVMe namespace.
A mapped NVMe namespace might be in use. Deleting a mapped namespace also deletes the namespace map and makes the data no longer available, possibly causing a disruption in the availability of data.
*This parameter should be used with caution.*

* Default value:


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Response

```
Status: 200, Ok
```

== Response

```
Status: 202, Accepted
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 4
| The specified namespace was not found.

| 72089796
| The namespace must be unmapped before deletion.

| 72090016
| The namespace's aggregate is offline. The aggregate must be online to modify or remove the namespace.

| 72090017
| The namespace's volume is offline. The volume must be online to modify or remove the namespace.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
