---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-vscan.html'
summary: 'Retrieve the Vscan configuration'
---

= Retrieve the Vscan configuration

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/vscan`#

*Introduced In:* 9.6

Retrieves the Vscan configuration.
This includes scanner-pools, On-Access policies, On-Demand policies, and information about whether a Vscan is enabled or disabled on an SVM.

Important notes:

* You can enable only one Vscan configuration at a time for an SVM.
* You can only query using `svm.uuid` or `svm.name`.

== Related ONTAP commands

* `vserver vscan show`
* `vserver vscan scanner-pool show`
* `vserver vscan scanner-pool servers show`
* `vserver vscan scanner-pool privileged-users show`
* `vserver vscan on-access-policy show`
* `vserver vscan on-access-policy file-ext-to-exclude show`
* `vserver vscan on-access-policy file-ext-to-include show`
* `vserver vscan on-access-policy paths-to-exclude show`
* `vserver vscan on-demand-task show`

== Learn more

* link:protocols_vscan_endpoint_overview.html[DOC /protocols/vscan]
* link:protocols_vscan_svm.uuid_scanner-pools_endpoint_overview.html[DOC /protocols/vscan/{svm.uuid}/scanner-pools]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|enabled
|boolean
|query
|False
a|Filter by enabled


|scanner_pools.privileged_users
|string
|query
|False
a|Filter by scanner_pools.privileged_users


|scanner_pools.servers
|string
|query
|False
a|Filter by scanner_pools.servers


|scanner_pools.name
|string
|query
|False
a|Filter by scanner_pools.name

* maxLength: 256
* minLength: 1


|scanner_pools.role
|string
|query
|False
a|Filter by scanner_pools.role


|scanner_pools.cluster.uuid
|string
|query
|False
a|Filter by scanner_pools.cluster.uuid


|scanner_pools.cluster.name
|string
|query
|False
a|Filter by scanner_pools.cluster.name


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|on_demand_policies.scope.exclude_paths
|string
|query
|False
a|Filter by on_demand_policies.scope.exclude_paths

* maxLength: 255
* minLength: 1


|on_demand_policies.scope.scan_without_extension
|boolean
|query
|False
a|Filter by on_demand_policies.scope.scan_without_extension


|on_demand_policies.scope.include_extensions
|string
|query
|False
a|Filter by on_demand_policies.scope.include_extensions


|on_demand_policies.scope.exclude_extensions
|string
|query
|False
a|Filter by on_demand_policies.scope.exclude_extensions


|on_demand_policies.scope.max_file_size
|integer
|query
|False
a|Filter by on_demand_policies.scope.max_file_size

* Max value: 1099511627776
* Min value: 1024


|on_demand_policies.schedule.uuid
|string
|query
|False
a|Filter by on_demand_policies.schedule.uuid


|on_demand_policies.schedule.name
|string
|query
|False
a|Filter by on_demand_policies.schedule.name


|on_demand_policies.name
|string
|query
|False
a|Filter by on_demand_policies.name

* maxLength: 256
* minLength: 1


|on_demand_policies.scan_paths
|string
|query
|False
a|Filter by on_demand_policies.scan_paths


|on_demand_policies.log_path
|string
|query
|False
a|Filter by on_demand_policies.log_path


|on_access_policies.scope.scan_without_extension
|boolean
|query
|False
a|Filter by on_access_policies.scope.scan_without_extension


|on_access_policies.scope.exclude_paths
|string
|query
|False
a|Filter by on_access_policies.scope.exclude_paths

* maxLength: 255
* minLength: 1


|on_access_policies.scope.max_file_size
|integer
|query
|False
a|Filter by on_access_policies.scope.max_file_size

* Max value: 1099511627776
* Min value: 1024


|on_access_policies.scope.only_execute_access
|boolean
|query
|False
a|Filter by on_access_policies.scope.only_execute_access


|on_access_policies.scope.exclude_extensions
|string
|query
|False
a|Filter by on_access_policies.scope.exclude_extensions


|on_access_policies.scope.include_extensions
|string
|query
|False
a|Filter by on_access_policies.scope.include_extensions


|on_access_policies.scope.scan_readonly_volumes
|boolean
|query
|False
a|Filter by on_access_policies.scope.scan_readonly_volumes


|on_access_policies.enabled
|boolean
|query
|False
a|Filter by on_access_policies.enabled


|on_access_policies.mandatory
|boolean
|query
|False
a|Filter by on_access_policies.mandatory


|on_access_policies.protocol
|string
|query
|False
a|Filter by on_access_policies.protocol

* Introduced in: 9.18


|on_access_policies.name
|string
|query
|False
a|Filter by on_access_policies.name

* maxLength: 256
* minLength: 1


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Max value: 120
* Min value: 0
* Default value: 15


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#vscan[vscan]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "on_access_policies": [
        {
          "name": "on-access-test",
          "protocol": "string",
          "scope": {
            "exclude_extensions": [
              "mp*",
              "txt"
            ],
            "exclude_paths": [
              "\\dir1\\dir2\\name",
              "\\vol\\a b",
              "\\vol\\a,b\\"
            ],
            "include_extensions": [
              "mp*",
              "txt"
            ],
            "max_file_size": 2147483648
          }
        }
      ],
      "on_demand_policies": [
        {
          "log_path": "/vol0/report_dir",
          "name": "task-1",
          "scan_paths": [
            "/vol1/",
            "/vol2/cifs/"
          ],
          "schedule": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "weekly",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          },
          "scope": {
            "exclude_extensions": [
              "mp3",
              "mp4"
            ],
            "exclude_paths": [
              "/vol1/cold-files/",
              "/vol1/cifs/names"
            ],
            "include_extensions": [
              "vmdk",
              "mp*"
            ],
            "max_file_size": 10737418240
          }
        }
      ],
      "scanner_pools": [
        {
          "cluster": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "cluster1",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          },
          "name": "scanner-1",
          "privileged_users": [
            "cifs\\u1",
            "cifs\\u2"
          ],
          "role": "string",
          "servers": [
            "1.1.1.1",
            "10.72.204.27",
            "vmwin204-27.fsct.nb"
          ]
        }
      ],
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#scope]
[.api-collapsible-fifth-title]
scope

[cols=3*,options=header]
|===
|Name
|Type
|Description

|exclude_extensions
|array[string]
a|List of file extensions for which scanning is not performed.


|exclude_paths
|array[string]
a|List of file paths for which scanning must not be performed.


|include_extensions
|array[string]
a|List of file extensions to be scanned.


|max_file_size
|integer
a|Maximum file size, in bytes, allowed for scanning.


|only_execute_access
|boolean
a|Scan only files opened with execute-access.


|scan_readonly_volumes
|boolean
a|Specifies whether or not read-only volume can be scanned.


|scan_without_extension
|boolean
a|Specifies whether or not files without any extension can be scanned.


|===


[#vscan_on_access_policy]
[.api-collapsible-fifth-title]
vscan_on_access_policy

An On-Access policy that defines the scope of an On-Access scan. Use On-Access scanning to check for viruses when clients open, read, rename, or close files over CIFS. By default, ONTAP creates an On-Access policy named "default_CIFS" and enables it for all the SVMs in a cluster.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Status of the On-Access Vscan policy


|mandatory
|boolean
a|Specifies if scanning is mandatory. File access is denied if there are no external virus-scanning servers available for virus scanning.


|name
|string
a|On-Access policy name


|protocol
|string
a|Specifies the file access protocol for the on-access policy. The following lists the possible protocols. CIFS  - SMB protocol


|scope
|link:#scope[scope]
a|

|===


[#schedule]
[.api-collapsible-fifth-title]
schedule

Schedule of the task.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#scope]
[.api-collapsible-fifth-title]
scope

[cols=3*,options=header]
|===
|Name
|Type
|Description

|exclude_extensions
|array[string]
a|List of file extensions for which scanning is not performed.


|exclude_paths
|array[string]
a|List of file paths for which scanning must not be performed.


|include_extensions
|array[string]
a|List of file extensions to be scanned.


|max_file_size
|integer
a|Maximum file size, in bytes, allowed for scanning.


|scan_without_extension
|boolean
a|Specifies whether or not files without any extension can be scanned.


|===


[#vscan_on_demand_policy]
[.api-collapsible-fifth-title]
vscan_on_demand_policy

Use On-Demand scanning to check files for viruses on a schedule. An On-Demand policy defines the scope of an On-Demand scan.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|log_path
|string
a|The path from the Vserver root where the task report is created.


|name
|string
a|On-Demand task name


|scan_paths
|array[string]
a|List of paths that need to be scanned.


|schedule
|link:#schedule[schedule]
a|Schedule of the task.


|scope
|link:#scope[scope]
a|

|===


[#cluster_reference]
[.api-collapsible-fifth-title]
cluster_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#scanner_pool]
[.api-collapsible-fifth-title]
scanner_pool

Scanner pool is a set of attributes which are used to validate and manage connections between clustered ONTAP and external virus-scanning server, or "Vscan server".


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster_reference[cluster_reference]
a|

|name
|string
a|Specifies the name of the scanner pool. Scanner pool name can be up to 256 characters long and is a string that can only contain any combination of ASCII-range alphanumeric characters a-z, A-Z, 0-9), "_", "-" and ".".


|privileged_users
|array[string]
a|Specifies a list of privileged users. A valid form of privileged user-name is "domain-name\user-name". Privileged user-names are stored and treated as case-insensitive strings. Virus scanners must use one of the registered privileged users for connecting to clustered Data ONTAP for exchanging virus-scanning protocol messages and to access file for scanning, remedying and quarantining operations.

* example: ["cifs\u1", "cifs\u2"]
* Introduced in: 9.10


|role
|string
a|Specifies the role of the scanner pool. The possible values are:

*** primary   - Always active.

*** secondary - Active only when none of the primary external virus-scanning servers are connected.

*** idle      - Always inactive.


|servers
|array[string]
a|Specifies a list of IP addresses or FQDN for each Vscan server host names which are allowed to connect to clustered ONTAP.

* example: ["1.1.1.1", "10.72.204.27", "vmwin204-27.fsct.nb"]
* Introduced in: 9.10


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#vscan]
[.api-collapsible-fifth-title]
vscan

Vscan can be used to protect data from being compromised by viruses or other malicious code. This combines best-in-class third-party antivirus software with ONTAP features that give you the flexibility you need to control which files get scanned and when. Storage systems offload scanning operations to external servers hosting antivirus software from third-party vendors. An Antivirus Connector on the external server handles communications between the storage system and the antivirus software.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|cache_clear
|boolean
a|Discards the cached information of the files that have been successfully scanned. Once the cache is cleared, files are scanned again when they are accessed. PATCH only


|enabled
|boolean
a|Specifies whether or not Vscan is enabled on the SVM.


|on_access_policies
|array[link:#vscan_on_access_policy[vscan_on_access_policy]]
a|

|on_demand_policies
|array[link:#vscan_on_demand_policy[vscan_on_demand_policy]]
a|

|scanner_pools
|array[link:#scanner_pool[scanner_pool]]
a|

|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
