---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-fpolicy-engines.html'
summary: 'Retrieve the FPolicy engine configuration for all engines of an SVM'
---

= Retrieve the FPolicy engine configuration for all engines of an SVM

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/fpolicy/{svm.uuid}/engines`#

*Introduced In:* 9.6

Retrieves FPolicy engine configurations of all the engines for a specified SVM. ONTAP allows creation of cluster-level FPolicy engines that act as a template for all the SVMs belonging to the cluster. These cluster-level FPolicy engines are also retrieved for the specified SVM.

== Related ONTAP commands

* `fpolicy policy external-engine show`

== Learn more

* link:protocols_fpolicy_svm.uuid_engines_endpoint_overview.html[DOC /protocols/fpolicy/{svm.uuid}/engines]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|secondary_servers
|string
|query
|False
a|Filter by secondary_servers


|name
|string
|query
|False
a|Filter by name


|keep_alive_interval
|string
|query
|False
a|Filter by keep_alive_interval

* Introduced in: 9.13


|request_abort_timeout
|string
|query
|False
a|Filter by request_abort_timeout

* Introduced in: 9.11


|session_timeout
|string
|query
|False
a|Filter by session_timeout

* Introduced in: 9.17


|resiliency.retention_duration
|string
|query
|False
a|Filter by resiliency.retention_duration

* Introduced in: 9.11


|resiliency.enabled
|boolean
|query
|False
a|Filter by resiliency.enabled

* Introduced in: 9.11


|resiliency.directory_path
|string
|query
|False
a|Filter by resiliency.directory_path

* Introduced in: 9.11


|port
|integer
|query
|False
a|Filter by port


|request_cancel_timeout
|string
|query
|False
a|Filter by request_cancel_timeout

* Introduced in: 9.11


|max_connection_retries
|integer
|query
|False
a|Filter by max_connection_retries

* Introduced in: 9.17
* Max value: 20
* Min value: 0


|ssl_option
|string
|query
|False
a|Filter by ssl_option

* Introduced in: 9.11


|buffer_size.send_buffer
|integer
|query
|False
a|Filter by buffer_size.send_buffer

* Introduced in: 9.11
* Max value: 7895160
* Min value: 0


|buffer_size.recv_buffer
|integer
|query
|False
a|Filter by buffer_size.recv_buffer

* Introduced in: 9.11
* Max value: 7895160
* Min value: 0


|primary_servers
|string
|query
|False
a|Filter by primary_servers


|status_request_interval
|string
|query
|False
a|Filter by status_request_interval

* Introduced in: 9.11


|type
|string
|query
|False
a|Filter by type


|max_server_requests
|integer
|query
|False
a|Filter by max_server_requests

* Introduced in: 9.11
* Max value: 10000
* Min value: 1


|certificate.name
|string
|query
|False
a|Filter by certificate.name

* Introduced in: 9.11


|certificate.serial_number
|string
|query
|False
a|Filter by certificate.serial_number

* Introduced in: 9.11


|certificate.ca
|string
|query
|False
a|Filter by certificate.ca

* Introduced in: 9.11


|format
|string
|query
|False
a|Filter by format

* Introduced in: 9.11


|server_progress_timeout
|string
|query
|False
a|Filter by server_progress_timeout

* Introduced in: 9.11


|svm.uuid
|string
|path
|True
a|UUID of the SVM to which this object belongs.


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Max value: 120
* Min value: 0
* Default value: 15


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#fpolicy_engine[fpolicy_engine]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "certificate": {
        "ca": "TASample1",
        "name": "Sample1-FPolicy-Client",
        "serial_number": "8DDE112A114D1FBC"
      },
      "format": "string",
      "keep_alive_interval": "PT2M",
      "max_connection_retries": 5,
      "max_server_requests": 500,
      "name": "fp_ex_eng",
      "port": 9876,
      "primary_servers": [
        "10.132.145.20",
        "10.140.101.109"
      ],
      "request_abort_timeout": "PT40S",
      "request_cancel_timeout": "PT20S",
      "resiliency": {
        "directory_path": "/dir1",
        "retention_duration": "PT3M"
      },
      "secondary_servers": [
        "10.132.145.20",
        "10.132.145.21"
      ],
      "server_progress_timeout": "PT1M",
      "session_timeout": "PT10S",
      "ssl_option": "string",
      "status_request_interval": "PT10S",
      "svm": {
        "uuid": "string"
      },
      "type": "string"
    }
  ]
}
====

== Error

```
Status: Default, 
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#buffer_size]
[.api-collapsible-fifth-title]
buffer_size

Specifies the send and receive buffer size of the connected socket for the FPolicy server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|recv_buffer
|integer
a|Specifies the receive buffer size of the connected socket for the FPolicy server. Default value is 256KB.


|send_buffer
|integer
a|Specifies the send buffer size of the connected socket for the FPolicy server. Default value 1MB.


|===


[#certificate]
[.api-collapsible-fifth-title]
certificate

Provides details about certificate used to authenticate the FPolicy server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ca
|string
a|Specifies the certificate authority (CA) name of the certificate
used for authentication if SSL authentication between the SVM and the FPolicy
server is configured.


|name
|string
a|Specifies the certificate name as a fully qualified domain
name (FQDN) or custom common name. The certificate is used if SSL authentication
between the SVM and the FPolicy server is configured.


|serial_number
|string
a|Specifies the serial number of the certificate used for
authentication if SSL authentication between the SVM and the FPolicy
server is configured.


|===


[#resiliency]
[.api-collapsible-fifth-title]
resiliency

If all primary and secondary servers are down, or if no response is received from the FPolicy servers, file access events are stored inside the storage controller under the specified resiliency-directory-path.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|directory_path
|string
a|Specifies the directory path under the SVM namespace,
where notifications are stored in the files whenever a network outage happens.


|enabled
|boolean
a|Specifies whether the resiliency feature is enabled or not.
Default is false.


|retention_duration
|string
a|Specifies the ISO-8601 duration, for which the notifications are written
to files inside the storage controller during a network outage. The value for
this field must be between 0 and 600 seconds. Default is 180 seconds.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|SVM UUID


|===


[#fpolicy_engine]
[.api-collapsible-fifth-title]
fpolicy_engine

Defines how ONTAP makes and manages connections to external FPolicy servers.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|buffer_size
|link:#buffer_size[buffer_size]
a|Specifies the send and receive buffer size of the connected socket for the FPolicy server.


|certificate
|link:#certificate[certificate]
a|Provides details about certificate used to authenticate the FPolicy server.


|format
|string
a|The format for the notification messages sent to the FPolicy servers.
The possible values are:

***** xml  - Notifications sent to the FPolicy server will be formatted using the XML schema.

***** protobuf - Notifications sent to the FPolicy server will be formatted using Protobuf schema, which is a binary form.


|keep_alive_interval
|string
a|Specifies the ISO-8601 interval time for a storage appliance to send Keep Alive message to an FPolicy server. The allowed range is between 10 to 600 seconds.


|max_connection_retries
|integer
a|This parameter specifies the maximum number of attempts to reconnect to the FPolicy server from an SVM. It is used to specify the number of times a broken connection will be retried. The value for this field must be between 0 and 20. By default, it is 5.


|max_server_requests
|integer
a|Specifies the maximum number of outstanding requests for the FPolicy server. It is used to specify maximum outstanding requests that will be queued up for the FPolicy server. The value for this field must be between 1 and 10000.  The default values are 500, 1000 or 2000 for Low-end(<64 GB memory), Mid-end(>=64 GB memory) and High-end(>=128 GB memory) Platforms respectively.


|name
|string
a|Specifies the name to assign to the external server configuration.


|port
|integer
a|Port number of the FPolicy server application.


|primary_servers
|array[string]
a|

|request_abort_timeout
|string
a|Specifies the ISO-8601 timeout duration for a screen request to be aborted by a storage appliance. The allowed range is between 0 to 200 seconds.


|request_cancel_timeout
|string
a|Specifies the ISO-8601 timeout duration for a screen request to be processed by an FPolicy server. The allowed range is between 0 to 100 seconds.


|resiliency
|link:#resiliency[resiliency]
a|If all primary and secondary servers are down, or if no response is received from the FPolicy servers, file access events are stored inside the storage controller under the specified resiliency-directory-path.


|secondary_servers
|array[string]
a|

|server_progress_timeout
|string
a|Specifies the ISO-8601 timeout duration in which a throttled FPolicy server must complete at least one screen request. If no request is processed within the timeout, connection to the FPolicy server is terminated. The allowed range is between 0 to 100 seconds.


|session_timeout
|string
a|This parameter specifies the interval after which a new session ID is sent to the FPolicy server during reconnection attempts. The default value is set to 10 seconds. If the connection between the storage controller and the FPolicy server is terminated and reconnection is made within the -session-timeout interval, the old session ID is sent to the FPolicy server so that it can send responses for old notifications.


|ssl_option
|string
a|Specifies the SSL option for external communication with the FPolicy server. Possible values include the following:

* no_auth       When set to "no_auth", no authentication takes place.
* server_auth   When set to "server_auth", only the FPolicy server is authenticated by the SVM. With this option, before creating the FPolicy external engine, the administrator must install the public certificate of the certificate authority (CA) that signed the FPolicy server certificate.
* mutual_auth   When set to "mutual_auth", mutual authentication takes place between the SVM and the FPolicy server. This means authentication of the FPolicy server by the SVM along with authentication of the SVM by the FPolicy server. With this option, before creating the FPolicy external engine, the administrator must install the public certificate of the certificate authority (CA) that signed the FPolicy server certificate along with the public certificate and key file for authentication of the SVM.


|status_request_interval
|string
a|Specifies the ISO-8601 interval time for a storage appliance to query a status request from an FPolicy server. The allowed range is between 0 to 50 seconds.


|svm
|link:#svm[svm]
a|

|type
|string
a|The notification mode determines what ONTAP does after sending notifications to FPolicy servers.
The possible values are:

***** synchronous  - After sending a notification, wait for a response from the FPolicy server.

***** asynchronous - After sending a notification, file request processing continues.

* Default value: 1
* enum: ["synchronous", "asynchronous"]
* Introduced in: 9.6
* x-nullable: true


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
