---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-fpolicy-policies.html'
summary: 'Retrieve an FPolicy configuration for an SVM'
---

= Retrieve an FPolicy configuration for an SVM

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/fpolicy/{svm.uuid}/policies`#

*Introduced In:* 9.6

Retrieves the FPolicy policy configuration of an SVM. ONTAP allows the creation of a cluster level FPolicy policy that acts as a template for all the data SVMs belonging to the cluster. This cluster level FPolicy policy is also retrieved for the specified SVM.

== Related ONTAP commands

* `fpolicy policy show`
* `fpolicy policy scope show`

== Learn more

* link:protocols_fpolicy_svm.uuid_policies_endpoint_overview.html[DOC /protocols/fpolicy/{svm.uuid}/policies]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|allow_privileged_access
|boolean
|query
|False
a|Filter by allow_privileged_access

* Introduced in: 9.13


|privileged_user
|string
|query
|False
a|Filter by privileged_user

* Introduced in: 9.10


|enabled
|boolean
|query
|False
a|Filter by enabled


|engine.name
|string
|query
|False
a|Filter by engine.name


|name
|string
|query
|False
a|Filter by name


|priority
|integer
|query
|False
a|Filter by priority

* Max value: 10
* Min value: 1


|passthrough_read
|boolean
|query
|False
a|Filter by passthrough_read

* Introduced in: 9.10


|scope.object_monitoring_with_no_extension
|boolean
|query
|False
a|Filter by scope.object_monitoring_with_no_extension

* Introduced in: 9.11


|scope.exclude_volumes
|string
|query
|False
a|Filter by scope.exclude_volumes


|scope.exclude_shares
|string
|query
|False
a|Filter by scope.exclude_shares


|scope.include_shares
|string
|query
|False
a|Filter by scope.include_shares


|scope.exclude_extension
|string
|query
|False
a|Filter by scope.exclude_extension


|scope.include_volumes
|string
|query
|False
a|Filter by scope.include_volumes


|scope.check_extensions_on_directories
|boolean
|query
|False
a|Filter by scope.check_extensions_on_directories

* Introduced in: 9.11


|scope.exclude_export_policies
|string
|query
|False
a|Filter by scope.exclude_export_policies


|scope.include_export_policies
|string
|query
|False
a|Filter by scope.include_export_policies


|scope.include_extension
|string
|query
|False
a|Filter by scope.include_extension


|mandatory
|boolean
|query
|False
a|Filter by mandatory


|events.name
|string
|query
|False
a|Filter by events.name


|persistent_store
|string
|query
|False
a|Filter by persistent_store

* Introduced in: 9.14


|svm.uuid
|string
|path
|True
a|UUID of the SVM to which this object belongs.


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Max value: 120
* Min value: 0
* Default value: 15


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of Records


|records
|array[link:#fpolicy_policy[fpolicy_policy]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "engine": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "string"
      },
      "events": [
        "event_cifs",
        "event_open"
      ],
      "name": "fp_policy_1",
      "persistent_store": "ps1",
      "priority": 1,
      "privileged_user": "mydomain\\testuser",
      "scope": {
        "exclude_export_policies": [
          "string"
        ],
        "exclude_extension": [
          "string"
        ],
        "exclude_shares": [
          "string"
        ],
        "exclude_volumes": [
          "vol1",
          "vol_svm1",
          "*"
        ],
        "include_export_policies": [
          "string"
        ],
        "include_extension": [
          "string"
        ],
        "include_shares": [
          "sh1",
          "share_cifs"
        ],
        "include_volumes": [
          "vol1",
          "vol_svm1"
        ]
      },
      "svm": {
        "uuid": "string"
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#fpolicy_engine_reference]
[.api-collapsible-fifth-title]
fpolicy_engine_reference

FPolicy external engine


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the FPolicy external engine.


|===


[#fpolicy_event_reference]
[.api-collapsible-fifth-title]
fpolicy_event_reference

FPolicy events


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|===


[#scope]
[.api-collapsible-fifth-title]
scope

[cols=3*,options=header]
|===
|Name
|Type
|Description

|check_extensions_on_directories
|boolean
a|Specifies whether the file name extension checks also apply to directory objects. If this parameter is set to true,
the directory objects are subjected to the same extension checks as regular files. If this parameter is set to false,
the directory names are not matched for extensions and notifications are sent for directories even if their name
extensions do not match. Default is false.


|exclude_export_policies
|array[string]
a|

|exclude_extension
|array[string]
a|

|exclude_shares
|array[string]
a|

|exclude_volumes
|array[string]
a|

|include_export_policies
|array[string]
a|

|include_extension
|array[string]
a|

|include_shares
|array[string]
a|

|include_volumes
|array[string]
a|

|object_monitoring_with_no_extension
|boolean
a|Specifies whether the extension checks also apply to objects with no extension. If this parameter is set to true,
all objects with or without extensions are monitored. Default is false.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|SVM UUID


|===


[#fpolicy_policy]
[.api-collapsible-fifth-title]
fpolicy_policy

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allow_privileged_access
|boolean
a|Specifies whether privileged access is required for FPolicy servers.
Privileged access is used when the FPolicy server requires direct
access to the cluster nodes. When this parameter is set to true,
FPolicy servers can access files on the cluster using a separate
data channel with privileged access.


|enabled
|boolean
a|Specifies if the policy is enabled on the SVM or not. If no value is
mentioned for this field but priority is set, then this policy will be enabled.


|engine
|link:#fpolicy_engine_reference[fpolicy_engine_reference]
a|FPolicy external engine


|events
|array[link:#fpolicy_event_reference[fpolicy_event_reference]]
a|

|mandatory
|boolean
a|Specifies what action to take on a file access event in a case when all primary and secondary servers are down or no response is received from the FPolicy servers within a given timeout period. When this parameter is set to true, file access events will be denied under these circumstances.


|name
|string
a|Specifies the name of the policy.


|passthrough_read
|boolean
a|Specifies whether passthrough-read should be allowed for FPolicy servers
registered for the policy. Passthrough-read is a way to read data for
offline files without restoring the files to primary storage. Offline
files are files that have been moved to secondary storage.


|persistent_store
|string
a|Specifies the persistent storage name. This can then be used
to enable persistent mode for FPolicy events.


|priority
|integer
a|Specifies the priority that is assigned to this policy.


|privileged_user
|string
a|Specifies the privileged user name for accessing files on the cluster
using a separate data channel with privileged access. The input for
this field should be in "domain\username" format.


|scope
|link:#scope[scope]
a|

|svm
|link:#svm[svm]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
