---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-fpolicy.html'
summary: 'Retrieve an FPolicy configuration'
---

= Retrieve an FPolicy configuration

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/fpolicy`#

*Introduced In:* 9.6

Retrieves an FPolicy configuration.

== Related ONTAP commands

* `fpolicy show`
* `fpolicy policy show`
* `fpolicy policy scope show`
* `fpolicy policy event show`
* `fpolicy policy external-engine show`
* `fpolicy persistent-store show`

== Learn more

* link:protocols_fpolicy_endpoint_overview.html[DOC /protocols/fpolicy]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|engines.request_abort_timeout
|string
|query
|False
a|Filter by engines.request_abort_timeout

* Introduced in: 9.11


|engines.keep_alive_interval
|string
|query
|False
a|Filter by engines.keep_alive_interval

* Introduced in: 9.13


|engines.name
|string
|query
|False
a|Filter by engines.name


|engines.secondary_servers
|string
|query
|False
a|Filter by engines.secondary_servers


|engines.request_cancel_timeout
|string
|query
|False
a|Filter by engines.request_cancel_timeout

* Introduced in: 9.11


|engines.port
|integer
|query
|False
a|Filter by engines.port


|engines.max_connection_retries
|integer
|query
|False
a|Filter by engines.max_connection_retries

* Introduced in: 9.17
* Max value: 20
* Min value: 0


|engines.resiliency.enabled
|boolean
|query
|False
a|Filter by engines.resiliency.enabled

* Introduced in: 9.11


|engines.resiliency.retention_duration
|string
|query
|False
a|Filter by engines.resiliency.retention_duration

* Introduced in: 9.11


|engines.resiliency.directory_path
|string
|query
|False
a|Filter by engines.resiliency.directory_path

* Introduced in: 9.11


|engines.session_timeout
|string
|query
|False
a|Filter by engines.session_timeout

* Introduced in: 9.17


|engines.type
|string
|query
|False
a|Filter by engines.type


|engines.status_request_interval
|string
|query
|False
a|Filter by engines.status_request_interval

* Introduced in: 9.11


|engines.primary_servers
|string
|query
|False
a|Filter by engines.primary_servers


|engines.ssl_option
|string
|query
|False
a|Filter by engines.ssl_option

* Introduced in: 9.11


|engines.buffer_size.send_buffer
|integer
|query
|False
a|Filter by engines.buffer_size.send_buffer

* Introduced in: 9.11
* Max value: 7895160
* Min value: 0


|engines.buffer_size.recv_buffer
|integer
|query
|False
a|Filter by engines.buffer_size.recv_buffer

* Introduced in: 9.11
* Max value: 7895160
* Min value: 0


|engines.server_progress_timeout
|string
|query
|False
a|Filter by engines.server_progress_timeout

* Introduced in: 9.11


|engines.certificate.name
|string
|query
|False
a|Filter by engines.certificate.name

* Introduced in: 9.11


|engines.certificate.serial_number
|string
|query
|False
a|Filter by engines.certificate.serial_number

* Introduced in: 9.11


|engines.certificate.ca
|string
|query
|False
a|Filter by engines.certificate.ca

* Introduced in: 9.11


|engines.format
|string
|query
|False
a|Filter by engines.format

* Introduced in: 9.11


|engines.max_server_requests
|integer
|query
|False
a|Filter by engines.max_server_requests

* Introduced in: 9.11
* Max value: 10000
* Min value: 1


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|persistent_stores.size
|integer
|query
|False
a|Filter by persistent_stores.size

* Introduced in: 9.15


|persistent_stores.volume
|string
|query
|False
a|Filter by persistent_stores.volume

* Introduced in: 9.14


|persistent_stores.name
|string
|query
|False
a|Filter by persistent_stores.name

* Introduced in: 9.14


|persistent_stores.autosize_mode
|string
|query
|False
a|Filter by persistent_stores.autosize_mode

* Introduced in: 9.15


|events.file_operations.symlink
|boolean
|query
|False
a|Filter by events.file_operations.symlink


|events.file_operations.open
|boolean
|query
|False
a|Filter by events.file_operations.open


|events.file_operations.lookup
|boolean
|query
|False
a|Filter by events.file_operations.lookup


|events.file_operations.read
|boolean
|query
|False
a|Filter by events.file_operations.read


|events.file_operations.setattr
|boolean
|query
|False
a|Filter by events.file_operations.setattr


|events.file_operations.link
|boolean
|query
|False
a|Filter by events.file_operations.link


|events.file_operations.getattr
|boolean
|query
|False
a|Filter by events.file_operations.getattr


|events.file_operations.write
|boolean
|query
|False
a|Filter by events.file_operations.write


|events.file_operations.close
|boolean
|query
|False
a|Filter by events.file_operations.close


|events.file_operations.access
|boolean
|query
|False
a|Filter by events.file_operations.access

* Introduced in: 9.13


|events.file_operations.create
|boolean
|query
|False
a|Filter by events.file_operations.create


|events.file_operations.rename
|boolean
|query
|False
a|Filter by events.file_operations.rename


|events.file_operations.delete_dir
|boolean
|query
|False
a|Filter by events.file_operations.delete_dir


|events.file_operations.rename_dir
|boolean
|query
|False
a|Filter by events.file_operations.rename_dir


|events.file_operations.create_dir
|boolean
|query
|False
a|Filter by events.file_operations.create_dir


|events.file_operations.delete
|boolean
|query
|False
a|Filter by events.file_operations.delete


|events.protocol
|string
|query
|False
a|Filter by events.protocol


|events.filters.setattr_with_size_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_size_change


|events.filters.setattr_with_creation_time_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_creation_time_change


|events.filters.setattr_with_access_time_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_access_time_change


|events.filters.close_with_modification
|boolean
|query
|False
a|Filter by events.filters.close_with_modification


|events.filters.offline_bit
|boolean
|query
|False
a|Filter by events.filters.offline_bit


|events.filters.setattr_with_allocation_size_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_allocation_size_change


|events.filters.open_with_write_intent
|boolean
|query
|False
a|Filter by events.filters.open_with_write_intent


|events.filters.first_read
|boolean
|query
|False
a|Filter by events.filters.first_read


|events.filters.first_write
|boolean
|query
|False
a|Filter by events.filters.first_write


|events.filters.setattr_with_modify_time_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_modify_time_change


|events.filters.setattr_with_mode_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_mode_change


|events.filters.write_with_size_change
|boolean
|query
|False
a|Filter by events.filters.write_with_size_change


|events.filters.setattr_with_sacl_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_sacl_change


|events.filters.exclude_directory
|boolean
|query
|False
a|Filter by events.filters.exclude_directory


|events.filters.monitor_ads
|boolean
|query
|False
a|Filter by events.filters.monitor_ads


|events.filters.setattr_with_owner_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_owner_change


|events.filters.close_with_read
|boolean
|query
|False
a|Filter by events.filters.close_with_read


|events.filters.setattr_with_group_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_group_change


|events.filters.setattr_with_dacl_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_dacl_change


|events.filters.open_with_delete_intent
|boolean
|query
|False
a|Filter by events.filters.open_with_delete_intent


|events.filters.close_without_modification
|boolean
|query
|False
a|Filter by events.filters.close_without_modification


|events.volume_monitoring
|boolean
|query
|False
a|Filter by events.volume_monitoring


|events.monitor_fileop_failure
|boolean
|query
|False
a|Filter by events.monitor_fileop_failure

* Introduced in: 9.13


|events.name
|string
|query
|False
a|Filter by events.name


|policies.name
|string
|query
|False
a|Filter by policies.name


|policies.enabled
|boolean
|query
|False
a|Filter by policies.enabled


|policies.persistent_store
|string
|query
|False
a|Filter by policies.persistent_store

* Introduced in: 9.14


|policies.scope.exclude_shares
|string
|query
|False
a|Filter by policies.scope.exclude_shares


|policies.scope.object_monitoring_with_no_extension
|boolean
|query
|False
a|Filter by policies.scope.object_monitoring_with_no_extension

* Introduced in: 9.11


|policies.scope.exclude_export_policies
|string
|query
|False
a|Filter by policies.scope.exclude_export_policies


|policies.scope.include_export_policies
|string
|query
|False
a|Filter by policies.scope.include_export_policies


|policies.scope.exclude_extension
|string
|query
|False
a|Filter by policies.scope.exclude_extension


|policies.scope.include_extension
|string
|query
|False
a|Filter by policies.scope.include_extension


|policies.scope.check_extensions_on_directories
|boolean
|query
|False
a|Filter by policies.scope.check_extensions_on_directories

* Introduced in: 9.11


|policies.scope.include_volumes
|string
|query
|False
a|Filter by policies.scope.include_volumes


|policies.scope.exclude_volumes
|string
|query
|False
a|Filter by policies.scope.exclude_volumes


|policies.scope.include_shares
|string
|query
|False
a|Filter by policies.scope.include_shares


|policies.allow_privileged_access
|boolean
|query
|False
a|Filter by policies.allow_privileged_access

* Introduced in: 9.13


|policies.events.name
|string
|query
|False
a|Filter by policies.events.name


|policies.mandatory
|boolean
|query
|False
a|Filter by policies.mandatory


|policies.privileged_user
|string
|query
|False
a|Filter by policies.privileged_user

* Introduced in: 9.11


|policies.priority
|integer
|query
|False
a|Filter by policies.priority

* Max value: 10
* Min value: 1


|policies.engine.name
|string
|query
|False
a|Filter by policies.engine.name


|policies.passthrough_read
|boolean
|query
|False
a|Filter by policies.passthrough_read

* Introduced in: 9.11


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Max value: 120
* Min value: 0
* Default value: 15


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#fpolicy[fpolicy]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "engines": [
        {
          "certificate": {
            "ca": "TASample1",
            "name": "Sample1-FPolicy-Client",
            "serial_number": "8DDE112A114D1FBC"
          },
          "format": "string",
          "keep_alive_interval": "PT2M",
          "max_connection_retries": 5,
          "max_server_requests": 500,
          "name": "fp_ex_eng",
          "port": 9876,
          "primary_servers": [
            "10.132.145.20",
            "10.140.101.109"
          ],
          "request_abort_timeout": "PT40S",
          "request_cancel_timeout": "PT20S",
          "resiliency": {
            "directory_path": "/dir1",
            "retention_duration": "PT3M"
          },
          "secondary_servers": [
            "10.132.145.20",
            "10.132.145.21"
          ],
          "server_progress_timeout": "PT1M",
          "session_timeout": "PT10S",
          "ssl_option": "string",
          "status_request_interval": "PT10S",
          "type": "string"
        }
      ],
      "events": [
        {
          "name": "event_cifs",
          "protocol": "string"
        }
      ],
      "persistent_stores": [
        {
          "autosize_mode": "string",
          "name": "ps1",
          "size": "100M",
          "volume": "psvol"
        }
      ],
      "policies": [
        {
          "engine": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "string"
          },
          "events": [
            "event_cifs",
            "event_open"
          ],
          "name": "fp_policy_1",
          "persistent_store": "ps1",
          "priority": 1,
          "privileged_user": "mydomain\\testuser",
          "scope": {
            "exclude_export_policies": [
              "string"
            ],
            "exclude_extension": [
              "string"
            ],
            "exclude_shares": [
              "string"
            ],
            "exclude_volumes": [
              "vol1",
              "vol_svm1",
              "*"
            ],
            "include_export_policies": [
              "string"
            ],
            "include_extension": [
              "string"
            ],
            "include_shares": [
              "sh1",
              "share_cifs"
            ],
            "include_volumes": [
              "vol1",
              "vol_svm1"
            ]
          }
        }
      ],
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#buffer_size]
[.api-collapsible-fifth-title]
buffer_size

Specifies the send and receive buffer size of the connected socket for the FPolicy server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|recv_buffer
|integer
a|Specifies the receive buffer size of the connected socket for the FPolicy server. Default value is 256KB.


|send_buffer
|integer
a|Specifies the send buffer size of the connected socket for the FPolicy server. Default value 1MB.


|===


[#certificate]
[.api-collapsible-fifth-title]
certificate

Provides details about certificate used to authenticate the FPolicy server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ca
|string
a|Specifies the certificate authority (CA) name of the certificate
used for authentication if SSL authentication between the SVM and the FPolicy
server is configured.


|name
|string
a|Specifies the certificate name as a fully qualified domain
name (FQDN) or custom common name. The certificate is used if SSL authentication
between the SVM and the FPolicy server is configured.


|serial_number
|string
a|Specifies the serial number of the certificate used for
authentication if SSL authentication between the SVM and the FPolicy
server is configured.


|===


[#resiliency]
[.api-collapsible-fifth-title]
resiliency

If all primary and secondary servers are down, or if no response is received from the FPolicy servers, file access events are stored inside the storage controller under the specified resiliency-directory-path.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|directory_path
|string
a|Specifies the directory path under the SVM namespace,
where notifications are stored in the files whenever a network outage happens.


|enabled
|boolean
a|Specifies whether the resiliency feature is enabled or not.
Default is false.


|retention_duration
|string
a|Specifies the ISO-8601 duration, for which the notifications are written
to files inside the storage controller during a network outage. The value for
this field must be between 0 and 600 seconds. Default is 180 seconds.


|===


[#fpolicy_engines]
[.api-collapsible-fifth-title]
fpolicy_engines

Defines how ONTAP makes and manages connections to external FPolicy servers.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|buffer_size
|link:#buffer_size[buffer_size]
a|Specifies the send and receive buffer size of the connected socket for the FPolicy server.


|certificate
|link:#certificate[certificate]
a|Provides details about certificate used to authenticate the FPolicy server.


|format
|string
a|The format for the notification messages sent to the FPolicy servers.
The possible values are:

***** xml  - Notifications sent to the FPolicy server will be formatted using the XML schema.

***** protobuf - Notifications sent to the FPolicy server will be formatted using Protobuf schema, which is a binary form.


|keep_alive_interval
|string
a|Specifies the ISO-8601 interval time for a storage appliance to send Keep Alive message to an FPolicy server. The allowed range is between 10 to 600 seconds.


|max_connection_retries
|integer
a|This parameter specifies the maximum number of attempts to reconnect to the FPolicy server from an SVM. It is used to specify the number of times a broken connection will be retried. The value for this field must be between 0 and 20. By default, it is 5.


|max_server_requests
|integer
a|Specifies the maximum number of outstanding requests for the FPolicy server. It is used to specify maximum outstanding requests that will be queued up for the FPolicy server. The value for this field must be between 1 and 10000.  The default values are 500, 1000 or 2000 for Low-end(<64 GB memory), Mid-end(>=64 GB memory) and High-end(>=128 GB memory) Platforms respectively.


|name
|string
a|Specifies the name to assign to the external server configuration.


|port
|integer
a|Port number of the FPolicy server application.


|primary_servers
|array[string]
a|

|request_abort_timeout
|string
a|Specifies the ISO-8601 timeout duration for a screen request to be aborted by a storage appliance. The allowed range is between 0 to 200 seconds.


|request_cancel_timeout
|string
a|Specifies the ISO-8601 timeout duration for a screen request to be processed by an FPolicy server. The allowed range is between 0 to 100 seconds.


|resiliency
|link:#resiliency[resiliency]
a|If all primary and secondary servers are down, or if no response is received from the FPolicy servers, file access events are stored inside the storage controller under the specified resiliency-directory-path.


|secondary_servers
|array[string]
a|

|server_progress_timeout
|string
a|Specifies the ISO-8601 timeout duration in which a throttled FPolicy server must complete at least one screen request. If no request is processed within the timeout, connection to the FPolicy server is terminated. The allowed range is between 0 to 100 seconds.


|session_timeout
|string
a|This parameter specifies the interval after which a new session ID is sent to the FPolicy server during reconnection attempts. The default value is set to 10 seconds. If the connection between the storage controller and the FPolicy server is terminated and reconnection is made within the -session-timeout interval, the old session ID is sent to the FPolicy server so that it can send responses for old notifications.


|ssl_option
|string
a|Specifies the SSL option for external communication with the FPolicy server. Possible values include the following:

* no_auth       When set to "no_auth", no authentication takes place.
* server_auth   When set to "server_auth", only the FPolicy server is authenticated by the SVM. With this option, before creating the FPolicy external engine, the administrator must install the public certificate of the certificate authority (CA) that signed the FPolicy server certificate.
* mutual_auth   When set to "mutual_auth", mutual authentication takes place between the SVM and the FPolicy server. This means authentication of the FPolicy server by the SVM along with authentication of the SVM by the FPolicy server. With this option, before creating the FPolicy external engine, the administrator must install the public certificate of the certificate authority (CA) that signed the FPolicy server certificate along with the public certificate and key file for authentication of the SVM.


|status_request_interval
|string
a|Specifies the ISO-8601 interval time for a storage appliance to query a status request from an FPolicy server. The allowed range is between 0 to 50 seconds.


|type
|string
a|The notification mode determines what ONTAP does after sending notifications to FPolicy servers.
The possible values are:

***** synchronous  - After sending a notification, wait for a response from the FPolicy server.

***** asynchronous - After sending a notification, file request processing continues.

* Default value: 1
* enum: ["synchronous", "asynchronous"]
* Introduced in: 9.10
* x-nullable: true


|===


[#file_operations]
[.api-collapsible-fifth-title]
file_operations

Specifies the file operations for the FPolicy event. You must specify a valid protocol in the protocol parameter.
The event will check the operations specified from all client requests using the protocol.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|access
|boolean
a|Access operations


|close
|boolean
a|File close operations


|create
|boolean
a|File create operations


|create_dir
|boolean
a|Directory create operations


|delete
|boolean
a|File delete operations


|delete_dir
|boolean
a|Directory delete operations


|getattr
|boolean
a|Get attribute operations


|link
|boolean
a|Link operations


|lookup
|boolean
a|Lookup operations


|open
|boolean
a|File open operations


|read
|boolean
a|File read operations


|rename
|boolean
a|File rename operations


|rename_dir
|boolean
a|Directory rename operations


|setattr
|boolean
a|Set attribute operations


|symlink
|boolean
a|Symbolic link operations


|write
|boolean
a|File write operations


|===


[#filters]
[.api-collapsible-fifth-title]
filters

Specifies the list of filters for a given file operation for the specified protocol.
When you specify the filters, you must specify the valid protocols and a valid file operations.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|close_with_modification
|boolean
a|Filter the client request for close with modification.


|close_with_read
|boolean
a|Filter the client request for close with read.


|close_without_modification
|boolean
a|Filter the client request for close without modification.


|exclude_directory
|boolean
a|Filter the client requests for directory operations. When this filter is specified directory operations are not monitored.


|first_read
|boolean
a|Filter the client requests for the first-read.


|first_write
|boolean
a|Filter the client requests for the first-write.


|monitor_ads
|boolean
a|Filter the client request for alternate data stream.


|offline_bit
|boolean
a|Filter the client request for offline bit set. FPolicy server receives notification only when offline files are accessed.


|open_with_delete_intent
|boolean
a|Filter the client request for open with delete intent.


|open_with_write_intent
|boolean
a|Filter the client request for open with write intent.


|setattr_with_access_time_change
|boolean
a|Filter the client setattr requests for changing the access time of a file or directory.


|setattr_with_allocation_size_change
|boolean
a|Filter the client setattr requests for changing the allocation size of a file.


|setattr_with_creation_time_change
|boolean
a|Filter the client setattr requests for changing the creation time of a file or directory.


|setattr_with_dacl_change
|boolean
a|Filter the client setattr requests for changing dacl on a file or directory.


|setattr_with_group_change
|boolean
a|Filter the client setattr requests for changing group of a file or directory.


|setattr_with_mode_change
|boolean
a|Filter the client setattr requests for changing the mode bits on a file or directory.


|setattr_with_modify_time_change
|boolean
a|Filter the client setattr requests for changing the modification time of a file or directory.


|setattr_with_owner_change
|boolean
a|Filter the client setattr requests for changing owner of a file or directory.


|setattr_with_sacl_change
|boolean
a|Filter the client setattr requests for changing sacl on a file or directory.


|setattr_with_size_change
|boolean
a|Filter the client setattr requests for changing the size of a file.


|write_with_size_change
|boolean
a|Filter the client request for write with size change.


|===


[#fpolicy_events]
[.api-collapsible-fifth-title]
fpolicy_events

The information that a FPolicy process needs to determine what file access operations to monitor and for which of the monitored events notifications should be sent to the external FPolicy server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|file_operations
|link:#file_operations[file_operations]
a|Specifies the file operations for the FPolicy event. You must specify a valid protocol in the protocol parameter.
The event will check the operations specified from all client requests using the protocol.


|filters
|link:#filters[filters]
a|Specifies the list of filters for a given file operation for the specified protocol.
When you specify the filters, you must specify the valid protocols and a valid file operations.


|monitor_fileop_failure
|boolean
a|Specifies whether failed file operations monitoring is required.


|name
|string
a|Specifies the name of the FPolicy event.


|protocol
|string
a|Protocol for which event is created. If you specify protocol, then you
must also specify a valid value for the file operation parameters.
The value of this parameter must be one of the following:

***** cifs  - for the CIFS protocol.

***** nfsv3 - for the NFSv3 protocol.

***** nfsv4 - for the NFSv4 protocol.


|volume_monitoring
|boolean
a|Specifies whether volume operation monitoring is required.


|===


[#fpolicy_persistent_stores]
[.api-collapsible-fifth-title]
fpolicy_persistent_stores

The information that an FPolicy process needs in order to configure a Persistent Store.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|autosize_mode
|string
a|Autosize mode for the volume.
grow &dash; Volume automatically grows in response to the amount of space used.
grow_shrink &dash; Volume grows or shrinks in response to the amount of space used.
off &dash; Autosizing of the volume is disabled.


|name
|string
a|The name specified for the FPolicy Persistent Store.


|size
|integer
a|The size of the Persistent Store volume, in bytes.


|volume
|string
a|The specified volume to store the events for the FPolicy Persistent Store.


|===


[#fpolicy_engine_reference]
[.api-collapsible-fifth-title]
fpolicy_engine_reference

FPolicy external engine


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the FPolicy external engine.


|===


[#fpolicy_event_reference]
[.api-collapsible-fifth-title]
fpolicy_event_reference

FPolicy events


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|===


[#scope]
[.api-collapsible-fifth-title]
scope

[cols=3*,options=header]
|===
|Name
|Type
|Description

|check_extensions_on_directories
|boolean
a|Specifies whether the file name extension checks also apply to directory objects. If this parameter is set to true,
the directory objects are subjected to the same extension checks as regular files. If this parameter is set to false,
the directory names are not matched for extensions and notifications are sent for directories even if their name
extensions do not match. Default is false.


|exclude_export_policies
|array[string]
a|

|exclude_extension
|array[string]
a|

|exclude_shares
|array[string]
a|

|exclude_volumes
|array[string]
a|

|include_export_policies
|array[string]
a|

|include_extension
|array[string]
a|

|include_shares
|array[string]
a|

|include_volumes
|array[string]
a|

|object_monitoring_with_no_extension
|boolean
a|Specifies whether the extension checks also apply to objects with no extension. If this parameter is set to true,
all objects with or without extensions are monitored. Default is false.


|===


[#fpolicy_policies]
[.api-collapsible-fifth-title]
fpolicy_policies

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allow_privileged_access
|boolean
a|Specifies whether privileged access is required for FPolicy servers.
Privileged access is used when the FPolicy server requires direct
access to the cluster nodes. When this parameter is set to true,
FPolicy servers can access files on the cluster using a separate
data channel with privileged access.


|enabled
|boolean
a|Specifies if the policy is enabled on the SVM or not. If no value is
mentioned for this field but priority is set, then this policy will be enabled.


|engine
|link:#fpolicy_engine_reference[fpolicy_engine_reference]
a|FPolicy external engine


|events
|array[link:#fpolicy_event_reference[fpolicy_event_reference]]
a|

|mandatory
|boolean
a|Specifies what action to take on a file access event in a case when all primary and secondary servers are down or no response is received from the FPolicy servers within a given timeout period. When this parameter is set to true, file access events will be denied under these circumstances.


|name
|string
a|Specifies the name of the policy.


|passthrough_read
|boolean
a|Specifies whether passthrough-read should be allowed for FPolicy servers
registered for the policy. Passthrough-read is a way to read data for
offline files without restoring the files to primary storage. Offline
files are files that have been moved to secondary storage.


|persistent_store
|string
a|Specifies the persistent storage name. This can then be used
to enable persistent mode for FPolicy events.


|priority
|integer
a|Specifies the priority that is assigned to this policy.


|privileged_user
|string
a|Specifies the privileged user name for accessing files on the cluster
using a separate data channel with privileged access. The input for
this field should be in "domain\username" format.


|scope
|link:#scope[scope]
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#fpolicy]
[.api-collapsible-fifth-title]
fpolicy

FPolicy is an infrastructure component of ONTAP that enables partner applications connected to your storage systems to monitor and set file access permissions. Every time a client accesses a file from a storage system, based on the configuration of FPolicy, the partner application is notified about file access.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|engines
|array[link:#fpolicy_engines[fpolicy_engines]]
a|

|events
|array[link:#fpolicy_events[fpolicy_events]]
a|

|persistent_stores
|array[link:#fpolicy_persistent_stores[fpolicy_persistent_stores]]
a|

|policies
|array[link:#fpolicy_policies[fpolicy_policies]]
a|

|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
