---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-cluster-counter-tables-rows.html'
summary: 'Retrieve counter rows'
---

= Retrieve counter rows

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/cluster/counter/tables/{counter_table.name}/rows`#

*Introduced In:* 9.11

Returns a collection of counter rows.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|counter_table.name
|string
|path
|True
a|Counter table name.


|counters.value
|integer
|query
|False
a|Filter by counters.value


|counters.name
|string
|query
|False
a|Filter by counters.name


|counters.values
|integer
|query
|False
a|Filter by counters.values


|counters.counters.values
|integer
|query
|False
a|Filter by counters.counters.values


|counters.counters.label
|string
|query
|False
a|Filter by counters.counters.label


|counters.labels
|string
|query
|False
a|Filter by counters.labels


|aggregation.count
|integer
|query
|False
a|Filter by aggregation.count


|aggregation.complete
|boolean
|query
|False
a|Filter by aggregation.complete


|properties.name
|string
|query
|False
a|Filter by properties.name


|properties.value
|string
|query
|False
a|Filter by properties.value


|id
|string
|query
|False
a|Filter by id


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#counter_row[counter_row]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "counter_table": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "string"
      },
      "counters": [
        {
          "counters": [
            {
              "label": "string",
              "values": [
                "integer"
              ]
            }
          ],
          "labels": [
            "string"
          ],
          "name": "string",
          "values": [
            "integer"
          ]
        }
      ],
      "id": "string",
      "properties": [
        {
          "name": "string",
          "value": "string"
        }
      ]
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 8585320
| Table requested is not found

| 8586228
| Invalid counter name request.

| 8586229
| Invalid counter property request.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#instance_counter_aggregation]
[.api-collapsible-fifth-title]
instance_counter_aggregation

Aggregation information about this counter.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|complete
|boolean
a|The aggregation state for this row.
For non-aggregated tables:
Not present
For aggregated tables:
If all requests to remote nodes for counter data are successful, then this value will be 'true'.
If any requests to remote nodes fail, then this value will be 'false'.


|count
|integer
a|Number of nodes included in the aggregation of this counter.


|===


[#counter_table_reference]
[.api-collapsible-fifth-title]
counter_table_reference

Counter table reference.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Counter table name.


|===


[#counter2d]
[.api-collapsible-fifth-title]
counter2d

Counters that represent the second dimension of a two-dimension counter.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|label
|string
a|Second dimension label.


|values
|array[integer]
a|List of values for the counter.


|===


[#counter]
[.api-collapsible-fifth-title]
counter

Representation of a counter and contains one of the following:

* Scalar counter populates the 'name' and 'value' fields.
* A 1D array populates the 'name', 'labels' and 'values' fields.
* A 2D array is represented as a list of counter entries.

----
"counters": [
  // Scalar counter
  {
      "name": "memory",
      "value": 4480
  },
  // one dimensional array "sys_read_latency_hist"
  {
      "name": "sys_read_latency_hist",
      "labels": ["0 - &lt;1ms", "1 - &lt;2ms", ...],
      "values": [0, 0, ...]
  },
  // Two dimensional array "foo" with ["Label 1", "Label 2"] as the first
  // array dimension and labels ["w", "x", "y"] for the 2nd dimension
  {
      "name": "foo",
      "labels": ["Label 1", "Label 2"],
      "counters": [
          {
              "label": "x",
              "values": [0, 0]
          },
          {
              "label": "y",
              "values": [0, 0]
          },
          {
              "label": "z",
              "values": [0, 0]
          }
      ]
  }
----


[cols=3*,options=header]
|===
|Name
|Type
|Description

|counters
|array[link:#counter2d[counter2d]]
a|List of labels and values for the second dimension.


|labels
|array[string]
a|List of labels for the first dimension.


|name
|string
a|Counter name.


|value
|integer
a|Scalar value.


|values
|array[integer]
a|List of values in a one-dimensional counter.


|===


[#counter_property]
[.api-collapsible-fifth-title]
counter_property

Single string counter entry.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Property name.


|value
|string
a|Property value.


|===


[#counter_row]
[.api-collapsible-fifth-title]
counter_row

A single row of counter and property counter data.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|aggregation
|link:#instance_counter_aggregation[instance_counter_aggregation]
a|Aggregation information about this counter.


|counter_table
|link:#counter_table_reference[counter_table_reference]
a|Counter table reference.


|counters
|array[link:#counter[counter]]
a|Array of counter name/value pairs.


|id
|string
a|Unique row identifier.


|properties
|array[link:#counter_property[counter_property]]
a|Array of property name/value pairs.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
