---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-s3-services-users.html'
summary: 'Retrieve the SVM configuration for an S3 user'
---

= Retrieve the SVM configuration for an S3 user

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/s3/services/{svm.uuid}/users`#

*Introduced In:* 9.7

Retrieves the S3 user's SVM configuration.

== Related ONTAP commands

* `vserver object-store-server user show`

== Learn more

* link:protocols_s3_services_svm.uuid_users_endpoint_overview.html[DOC /protocols/s3/services/{svm.uuid}/users]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|name
|string
|query
|False
a|Filter by name

* maxLength: 64
* minLength: 1


|svm.name
|string
|query
|False
a|Filter by svm.name


|access_key
|string
|query
|False
a|Filter by access_key


|keys.id
|integer
|query
|False
a|Filter by keys.id

* Introduced in: 9.19
* Max value: 2
* Min value: 1


|keys.access_key
|string
|query
|False
a|Filter by keys.access_key

* Introduced in: 9.19


|keys.expiry_time
|string
|query
|False
a|Filter by keys.expiry_time

* Introduced in: 9.19


|keys.time_to_live
|string
|query
|False
a|Filter by keys.time_to_live

* Introduced in: 9.19


|comment
|string
|query
|False
a|Filter by comment

* maxLength: 256
* minLength: 0


|key_expiry_time
|string
|query
|False
a|Filter by key_expiry_time

* Introduced in: 9.14


|key_time_to_live
|string
|query
|False
a|Filter by key_time_to_live

* Introduced in: 9.14


|svm.uuid
|string
|path
|True
a|UUID of the SVM to which this object belongs.


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Max value: 120
* Min value: 0
* Default value: 15


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#collection_links[collection_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#s3_user[s3_user]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "access_key": "<AWS-ACCESS-KEY-ID>",
      "comment": "S3 user",
      "key_expiry_time": "2024-01-01 00:00:00 +0000",
      "key_id": 1,
      "key_time_to_live": "PT6H3M",
      "keys": [
        {
          "access_key": "<AWS-ACCESS-KEY-ID>",
          "expiry_time": "2024-01-01 00:00:00 +0000",
          "id": 1,
          "time_to_live": "PT6H3M"
        }
      ],
      "name": "user-1",
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#collection_links]
[.api-collapsible-fifth-title]
collection_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#keys]
[.api-collapsible-fifth-title]
keys

Specifies a key associated with an S3 user. At most only two keys can be associated with a user.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|access_key
|string
a|Specifies the access key for the user.


|expiry_time
|string
a|Specifies the date and time after which keys expire and are no longer valid.


|id
|integer
a|Specifies an S3 user key identifier. Each user can only have a maximum of two keys. The key_id can either be '1' or '2'.


|time_to_live
|string
a|Indicates the time period from when this parameter is specified:

* when creating or modifying a user or
* when the user keys were last regenerated, after which the user keys expire and are no longer valid.
* Valid format is: 'PnDTnHnMnS\|PnW'. For example, P2DT6H3M10S specifies a time period of 2 days, 6 hours, 3 minutes, and 10 seconds.
* If the value specified is '0' seconds, then the keys do not expire.


|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#s3_user]
[.api-collapsible-fifth-title]
s3_user

This is a container of S3 users.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|access_key
|string
a|Specifies the access key for the user.


|comment
|string
a|Can contain any additional information about the user being created or modified.


|key_expiry_time
|string
a|Specifies the date and time after which keys expire and are no longer valid.


|key_id
|integer
a|Specifies the identifier of an S3 user key that needs to be generated or deleted. The key_id can either be '1' or '2'.


|key_time_to_live
|string
a|Indicates the time period from when this parameter is specified:

* when creating or modifying a user or
* when the user keys were last regenerated, after which the user keys expire and are no longer valid.
* Valid format is: 'PnDTnHnMnS\|PnW'. For example, P2DT6H3M10S specifies a time period of 2 days, 6 hours, 3 minutes, and 10 seconds.
* If the value specified is '0' seconds, then the keys won't expire.


|keys
|array[link:#keys[keys]]
a|Specifies the keys associated with an S3 User.


|name
|string
a|Specifies the name of the user. A user name length can range from 1 to 64 characters and can only contain the following combination of characters 0-9, A-Z, a-z, "_", "+", "=", ",", ".","@", and "-".


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
