---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-security-ssh-svms.html'
summary: 'Retrieve the SSH server configuration for all SVMs'
---

= Retrieve the SSH server configuration for all SVMs

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/security/ssh/svms`#

*Introduced In:* 9.10

Retrieves the SSH server configuration for all the data SVMs.

== Related ONTAP commands

* `security ssh`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|login_grace_time
|integer
|query
|False
a|Filter by login_grace_time

* Introduced in: 9.18


|max_authentication_retry_count
|integer
|query
|False
a|Filter by max_authentication_retry_count

* Max value: 6
* Min value: 2


|is_rsa_in_publickey_algorithms_enabled
|boolean
|query
|False
a|Filter by is_rsa_in_publickey_algorithms_enabled

* Introduced in: 9.16


|svm.name
|string
|query
|False
a|Filter by svm.name


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|host_key_algorithms
|string
|query
|False
a|Filter by host_key_algorithms

* Introduced in: 9.16


|mac_algorithms
|string
|query
|False
a|Filter by mac_algorithms


|key_exchange_algorithms
|string
|query
|False
a|Filter by key_exchange_algorithms


|ciphers
|string
|query
|False
a|Filter by ciphers


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Max value: 120
* Min value: 0
* Default value: 15


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records.


|records
|array[link:#svm_ssh_server[svm_ssh_server]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "ciphers": [
        "aes256_ctr",
        "aes192_ctr",
        "aes128_ctr"
      ],
      "host_key_algorithms": [
        "ecdsa_sha2_nistp256",
        "ssh_ed25519",
        "ssh_rsa",
        "rsa_sha2_256",
        "rsa_sha2_512"
      ],
      "key_exchange_algorithms": [
        "diffie_hellman_group_exchange_sha256",
        "ecdh_sha2_nistp256"
      ],
      "mac_algorithms": [
        "hmac_sha2_512",
        "hmac_sha2_512_etm"
      ],
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM name and UUID for which the SSH server is configured.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#svm_ssh_server]
[.api-collapsible-fifth-title]
svm_ssh_server

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|ciphers
|array[string]
a|Ciphers for encrypting the data.


|host_key_algorithms
|array[string]
a|Host key algorithms. The host key algorithms 'ssh_ed25519' and 'ssh_rsa' can be configured only in non-FIPS mode.


|is_rsa_in_publickey_algorithms_enabled
|boolean
a|Enables or disables the _ssh-rsa_ signature scheme, which uses the SHA-1 hash algorithm, for RSA keys in public key algorithms. If this flag is _false_, older SSH implementations might fail to authenticate using RSA keys. This flag should be enabled only as a temporary measure until legacy SSH client implementations can be upgraded or reconfigured with another key type, for example: ECDSA.


|key_exchange_algorithms
|array[string]
a|Key exchange algorithms.


|login_grace_time
|integer
a|The login grace time allowed for SSH connection request timeout.


|mac_algorithms
|array[string]
a|MAC algorithms.


|max_authentication_retry_count
|integer
a|Maximum authentication retries allowed before closing the connection.


|svm
|link:#svm[svm]
a|SVM name and UUID for which the SSH server is configured.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
