---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-s3-services-buckets-rules.html'
summary: 'Retrieve S3 lifecycle rules for a bucket'
---

= Retrieve S3 lifecycle rules for a bucket

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/s3/services/{svm.uuid}/buckets/{s3_bucket.uuid}/rules`#

*Introduced In:* 9.13

Retrieves all S3 Lifecycle rules associated with a bucket. Note that in order to retrieve S3 bucket rule parameters, the 'fields' option should be set to '**'.

== Related ONTAP commands

* `vserver object-store-server bucket lifecycle-management-rule show`

== Learn more

* link:protocols_s3_services_svm.uuid_buckets_s3_bucket.uuid_rules_endpoint_overview.html[DOC /protocols/s3/services/{svm.uuid}/buckets/{s3_bucket.uuid}/rules]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|bucket_name
|string
|query
|False
a|Filter by bucket_name

* maxLength: 63
* minLength: 3
* Introduced in: 9.14


|non_current_version_expiration.non_current_days
|integer
|query
|False
a|Filter by non_current_version_expiration.non_current_days


|non_current_version_expiration.new_non_current_versions
|integer
|query
|False
a|Filter by non_current_version_expiration.new_non_current_versions


|uuid
|string
|query
|False
a|Filter by uuid

* Introduced in: 9.14


|expiration.expired_object_delete_marker
|boolean
|query
|False
a|Filter by expiration.expired_object_delete_marker


|expiration.object_expiry_date
|string
|query
|False
a|Filter by expiration.object_expiry_date


|expiration.object_age_days
|integer
|query
|False
a|Filter by expiration.object_age_days


|name
|string
|query
|False
a|Filter by name

* maxLength: 256
* minLength: 0


|svm.name
|string
|query
|False
a|Filter by svm.name

* Introduced in: 9.14


|object_filter.prefix
|string
|query
|False
a|Filter by object_filter.prefix


|object_filter.size_greater_than
|integer
|query
|False
a|Filter by object_filter.size_greater_than


|object_filter.size_less_than
|integer
|query
|False
a|Filter by object_filter.size_less_than


|object_filter.tags
|string
|query
|False
a|Filter by object_filter.tags


|enabled
|boolean
|query
|False
a|Filter by enabled


|abort_incomplete_multipart_upload.after_initiation_days
|integer
|query
|False
a|Filter by abort_incomplete_multipart_upload.after_initiation_days


|s3_bucket.uuid
|string
|path
|True
a|The unique identifier of the bucket.


|svm.uuid
|string
|path
|True
a|UUID of the SVM to which this object belongs.

* Introduced in: 9.14


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#collection_links[collection_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#s3_bucket_lifecycle_rule[s3_bucket_lifecycle_rule]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "abort_incomplete_multipart_upload": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        }
      },
      "bucket_name": "bucket1",
      "expiration": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "object_age_days": 100,
        "object_expiry_date": "2039-09-23 00:00:00 +0000"
      },
      "name": "string",
      "non_current_version_expiration": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        }
      },
      "object_filter": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "prefix": "/logs",
        "size_greater_than": 10240,
        "size_less_than": 10485760,
        "tags": [
          "project1=projA",
          "project2=projB"
        ]
      },
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "uuid": "414b29a1-3b26-11e9-bd58-0050568ea055"
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#collection_links]
[.api-collapsible-fifth-title]
collection_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#abort_incomplete_multipart_upload]
[.api-collapsible-fifth-title]
abort_incomplete_multipart_upload

Specifies a way to perform abort_incomplete_multipart_upload action on filtered objects within a bucket. It cannot be specified with tags.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|after_initiation_days
|integer
a|Number of days of initiation after which uploads can be aborted.


|===


[#expiration]
[.api-collapsible-fifth-title]
expiration

Specifies a way to perform expiration action on filtered objects within a bucket.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|expired_object_delete_marker
|boolean
a|Cleanup object delete markers.


|object_age_days
|integer
a|Number of days since creation after which objects can be deleted. This cannot be used along with object_expiry_date.


|object_expiry_date
|string
a|Specific date from when objects can expire. This cannot be used with object_age_days.


|===


[#non_current_version_expiration]
[.api-collapsible-fifth-title]
non_current_version_expiration

Specifies a way to perform non_current_version_expiration action on filtered objects within a bucket.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|new_non_current_versions
|integer
a|Number of latest non-current versions to be retained.


|non_current_days
|integer
a|Number of days after which non-current versions can be deleted.


|===


[#object_filter]
[.api-collapsible-fifth-title]
object_filter

Specifies a way to filter objects within a bucket.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|prefix
|string
a|A prefix that is matched against object-names within a bucket.


|size_greater_than
|integer
a|Size of the object greater than specified for which the corresponding lifecycle rule is to be applied.


|size_less_than
|integer
a|Size of the object smaller than specified for which the corresponding lifecycle rule is to be applied.


|tags
|array[string]
a|An array of key-value paired tags of the form \{tag} or {tag=value}.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

Specifies the name of the SVM where this bucket exists.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#s3_bucket_lifecycle_rule]
[.api-collapsible-fifth-title]
s3_bucket_lifecycle_rule

Information about the lifecycle management rule of a bucket.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|abort_incomplete_multipart_upload
|link:#abort_incomplete_multipart_upload[abort_incomplete_multipart_upload]
a|Specifies a way to perform abort_incomplete_multipart_upload action on filtered objects within a bucket. It cannot be specified with tags.


|bucket_name
|string
a|Specifies the name of the bucket. Bucket name is a string that can only contain the following combination of ASCII-range alphanumeric characters 0-9, a-z, ".", and "-".


|enabled
|boolean
a|Specifies whether or not the associated rule is enabled.


|expiration
|link:#expiration[expiration]
a|Specifies a way to perform expiration action on filtered objects within a bucket.


|name
|string
a|Bucket lifecycle management rule identifier. The length of the name can range from 0 to 256 characters.


|non_current_version_expiration
|link:#non_current_version_expiration[non_current_version_expiration]
a|Specifies a way to perform non_current_version_expiration action on filtered objects within a bucket.


|object_filter
|link:#object_filter[object_filter]
a|Specifies a way to filter objects within a bucket.


|svm
|link:#svm[svm]
a|Specifies the name of the SVM where this bucket exists.


|uuid
|string
a|Specifies the unique identifier of the bucket.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
