---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-storage-qos-workloads-.html'
summary: 'Retrieve a QoS workload'
---

= Retrieve a QoS workload

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/storage/qos/workloads/{uuid}`#

*Introduced In:* 9.10

Retrieves a specific QoS workload.

== Related ONTAP command

* `qos workload show`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|

|fields
|array[string]
|query
|False
a|Specify the fields to return.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|file
|string
a|Name of the file.


|lun
|string
a|Name of the LUN. The name of the LUN will be displayed as "(unknown)" if the name cannot be retrieved.


|max_throughput
|string
a|Specifies the maximum throughput in MB/s or B/s as appropriate.


|max_throughput_iops
|integer
a|Specifies the maximum throughput in IOPS, 0 means none.


|min_throughput
|string
a|Specifies the minimum throughput in MB/s or B/s as appropriate.


|min_throughput_iops
|integer
a|Specifies the minimum throughput in IOPS, 0 means none.


|name
|string
a|Name of the QoS workload.


|policy
|link:#policy[policy]
a|QoS policy group reference.


|qtree
|string
a|Name of the Qtree.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|uuid
|string
a|

|volume
|string
a|Name of the volume. The name of the volume will be displayed as "(unknown)" if the name cannot be retrieved.


|wid
|integer
a|Workload ID of the QoS workload.


|workload_class
|string
a|Class of the QoS workload.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "file": "string",
  "lun": "string",
  "max_throughput": "500MB/s",
  "max_throughput_iops": 10000,
  "min_throughput": "100MB/s",
  "min_throughput_iops": 2000,
  "name": "volume1-wid123",
  "policy": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "name": "performance",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "qtree": "string",
  "svm": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412",
  "volume": "volume1",
  "wid": 123,
  "workload_class": "autovolume"
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#policy]
[.api-collapsible-fifth-title]
policy

QoS policy group reference.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The QoS policy group name. This is mutually exclusive with UUID and other QoS attributes during POST and PATCH.


|uuid
|string
a|The QoS policy group UUID. This is mutually exclusive with name and other QoS attributes during POST and PATCH.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
