---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-security-azure-key-vaults.html'
summary: 'Retrieve AKVs configured for all clusters and SVMs'
---

= Retrieve AKVs configured for all clusters and SVMs

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/security/azure-key-vaults`#

*Introduced In:* 9.8

Retrieves AKVs configured for all clusters and SVMs.

== Related ONTAP commands

* `security key-manager external azure show`
* `security key-manager external azure check`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|query
|False
a|Filter by uuid


|configuration.uuid
|string
|query
|False
a|Filter by configuration.uuid

* Introduced in: 9.14


|configuration.name
|string
|query
|False
a|Filter by configuration.name

* Introduced in: 9.14


|scope
|string
|query
|False
a|Filter by scope


|vault_host
|string
|query
|False
a|Filter by vault_host

* Introduced in: 9.14


|state.code
|string
|query
|False
a|Filter by state.code


|state.available
|boolean
|query
|False
a|Filter by state.available


|state.message
|string
|query
|False
a|Filter by state.message


|proxy_type
|string
|query
|False
a|Filter by proxy_type


|skip_verification
|boolean
|query
|False
a|Filter by skip_verification

* Introduced in: 9.16


|tenant_id
|string
|query
|False
a|Filter by tenant_id


|proxy_port
|integer
|query
|False
a|Filter by proxy_port


|azure_reachability.message
|string
|query
|False
a|Filter by azure_reachability.message


|azure_reachability.reachable
|boolean
|query
|False
a|Filter by azure_reachability.reachable


|azure_reachability.code
|string
|query
|False
a|Filter by azure_reachability.code


|oauth_host
|string
|query
|False
a|Filter by oauth_host

* Introduced in: 9.14


|ekmip_reachability.message
|string
|query
|False
a|Filter by ekmip_reachability.message


|ekmip_reachability.node.name
|string
|query
|False
a|Filter by ekmip_reachability.node.name


|ekmip_reachability.node.uuid
|string
|query
|False
a|Filter by ekmip_reachability.node.uuid


|ekmip_reachability.reachable
|boolean
|query
|False
a|Filter by ekmip_reachability.reachable


|ekmip_reachability.code
|string
|query
|False
a|Filter by ekmip_reachability.code


|proxy_host
|string
|query
|False
a|Filter by proxy_host


|verify_host
|boolean
|query
|False
a|Filter by verify_host

* Introduced in: 9.14


|port
|integer
|query
|False
a|Filter by port

* Introduced in: 9.14


|proxy_username
|string
|query
|False
a|Filter by proxy_username


|enabled
|boolean
|query
|False
a|Filter by enabled

* Introduced in: 9.14


|key_id
|string
|query
|False
a|Filter by key_id


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|verify_ip
|boolean
|query
|False
a|Filter by verify_ip

* Introduced in: 9.14


|authentication_method
|string
|query
|False
a|Filter by authentication_method

* Introduced in: 9.10


|client_id
|string
|query
|False
a|Filter by client_id


|name
|string
|query
|False
a|Filter by name


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#azure_key_vault[azure_key_vault]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "authentication_method": "client_secret",
      "azure_reachability": {
        "code": "346758",
        "message": "AKV service is not reachable from all nodes - reason."
      },
      "client_id": "aaaaaaaa-bbbb-aaaa-bbbb-aaaaaaaaaaaa",
      "configuration": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "default",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563434"
      },
      "ekmip_reachability": [
        {
          "code": "346758",
          "message": "embedded KMIP server status unavailable on node.",
          "node": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "node1",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          }
        }
      ],
      "key_id": "https://keyvault1.vault.azure.net/keys/key1/12345678901234567890123456789012",
      "name": "https://kmip-akv-keyvault.vault.azure.net/",
      "oauth_host": "login.microsoftonline.com",
      "port": 443,
      "proxy_host": "proxy.eng.com",
      "proxy_port": 1234,
      "proxy_type": "http",
      "proxy_username": "proxyuser",
      "scope": "string",
      "skip_verification": "",
      "state": {
        "code": "346758",
        "message": "Top-level internal key protection key (KEK) is unavailable on the following nodes with the associated reasons: Node: node1. Reason: No volumes created yet for the SVM. Wrapped KEK status will be available after creating encrypted volumes."
      },
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "tenant_id": "zzzzzzzz-yyyy-zzzz-yyyy-zzzzzzzzzzzz",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412",
      "vault_host": "vault.azure.net",
      "verify_host": "",
      "verify_ip": ""
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 65537549
| The Azure Key Vault Key Management Service is unreachable from one or more nodes.

| 65537551
| Top-level internal key protection key (KEK) unavailable on one or more nodes.

| 65537552
| Embedded KMIP server status not available.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#azure_reachability]
[.api-collapsible-fifth-title]
azure_reachability

Indicates whether or not the AKV service is reachable from all the nodes in the cluster.
This is an advanced property; there is an added computational cost to retrieving its value. The property is not populated for either a collection GET or an instance GET unless it is explicitly requested using the `fields` query parameter or GET for all advanced properties is enabled.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Code corresponding to the status message. Returns a 0 if AKV service is reachable from all nodes in the cluster.


|message
|string
a|Error message set when reachability is false.


|reachable
|boolean
a|Set to true when the AKV service is reachable from all nodes of the cluster.


|===


[#configuration]
[.api-collapsible-fifth-title]
configuration

Security keystore object reference.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Name of the configuration.


|uuid
|string
a|Keystore UUID.


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#ekmip_reachability]
[.api-collapsible-fifth-title]
ekmip_reachability

Provides the connectivity status for the given SVM on the given node to all EKMIP servers configured on all nodes of the cluster.
This is an advanced property; there is an added computational cost to retrieving its value. The property is not populated for either a collection GET or an instance GET unless it is explicitly requested using the `fields` query parameter or GET for all advanced properties is enabled.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Code corresponding to the error message. Returns a 0 if a given SVM is able to communicate to the EKMIP servers of all of the nodes in the cluster.


|message
|string
a|Error message set when cluster-wide EKMIP server availability from the given SVM and node is false.


|node
|link:#node[node]
a|

|reachable
|boolean
a|Set to true if the given SVM on the given node is able to communicate to all EKMIP servers configured on all nodes in the cluster.


|===


[#state]
[.api-collapsible-fifth-title]
state

Indicates whether or not the AKV wrapped internal key is available cluster wide.
This is an advanced property; there is an added computational cost to retrieving its value. The property is not populated for either a collection GET or an instance GET unless it is explicitly requested using the `fields` query parameter or GET for all advanced properties is enabled.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|available
|boolean
a|Set to true when an AKV wrapped internal key is present on all nodes of the cluster.


|code
|string
a|Code corresponding to the status message. Returns a 0 if AKV wrapped key is available on all nodes in the cluster.


|message
|string
a|Error message set when top-level internal key protection key (KEK) availability on cluster is false.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#azure_key_vault]
[.api-collapsible-fifth-title]
azure_key_vault

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|authentication_method
|string
a|Authentication method for the AKV instance.


|azure_reachability
|link:#azure_reachability[azure_reachability]
a|Indicates whether or not the AKV service is reachable from all the nodes in the cluster.
This is an advanced property; there is an added computational cost to retrieving its value. The property is not populated for either a collection GET or an instance GET unless it is explicitly requested using the `fields` query parameter or GET for all advanced properties is enabled.


|client_id
|string
a|Application client ID of the deployed Azure application with appropriate access to an AKV.


|configuration
|link:#configuration[configuration]
a|Security keystore object reference.


|ekmip_reachability
|array[link:#ekmip_reachability[ekmip_reachability]]
a|

|enabled
|boolean
a|Indicates whether the configuration is enabled.


|key_id
|string
a|Key Identifier of AKV key encryption key.


|name
|string
a|Name of the deployed AKV that will be used by ONTAP for storing keys.

* example: https://kmip-akv-keyvault.vault.azure.net/
* format: uri
* Introduced in: 9.8
* readCreate: 1
* x-nullable: true


|oauth_host
|string
a|Open authorization server host name.


|port
|integer
a|Authorization server and vault port number.


|proxy_host
|string
a|Proxy host.


|proxy_port
|integer
a|Proxy port.


|proxy_type
|string
a|Type of proxy.


|proxy_username
|string
a|Proxy username.


|scope
|string
a|Set to "svm" for interfaces owned by an SVM. Otherwise, set to "cluster".


|skip_verification
|boolean
a|Set to true to skip the verification of the updated user credentials when updating credentials. The default value is false.


|state
|link:#state[state]
a|Indicates whether or not the AKV wrapped internal key is available cluster wide.
This is an advanced property; there is an added computational cost to retrieving its value. The property is not populated for either a collection GET or an instance GET unless it is explicitly requested using the `fields` query parameter or GET for all advanced properties is enabled.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|tenant_id
|string
a|Directory (tenant) ID of the deployed Azure application with appropriate access to an AKV.


|uuid
|string
a|A unique identifier for the Azure Key Vault (AKV).


|vault_host
|string
a|AKV host subdomain.


|verify_host
|boolean
a|Verify the identity of the AKV host name.


|verify_ip
|boolean
a|Verify the identity of the AKV IP address.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
