---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-storage-snaplock-file-fingerprints-.html'
summary: 'Retrieve the file fingerprint information for a specific session ID'
---

= Retrieve the file fingerprint information for a specific session ID

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/storage/snaplock/file-fingerprints/{id}`#

*Introduced In:* 9.7

Retrieves the file fingerprint information for a specific session ID.

== Related ONTAP commands

* `volume file fingerprint dump`

== Learn more

* link:storage_snaplock_file-fingerprints_endpoint_overview.html[DOC /storage/snaplock/file-fingerprints]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|id
|string
|path
|True
a|Unique identifier of the operation


|fields
|array[string]
|query
|False
a|Specify the fields to return.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|algorithm
|string
a|The digest algorithm which is used for the fingerprint computation


|data_fingerprint
|string
a|The digest value of data of the file. The fingerprint is base64 encoded. This field is not included if the scope is metadata-only.


|file_size
|integer
a|The size of the file in bytes.


|file_type
|string
a|The type of the file.


|id
|integer
a|A unique identifier for the fingerprint operation


|metadata_fingerprint
|string
a|The digest value of metadata of the file. The metadata fingerprint is calculated for file size, file ctime, file mtime, file crtime, file retention time, file uid, file gid, and file type. The fingerprint is base64 encoded. This field is not included if the scope is data-only.


|path
|string
a|Specifies the path on which file fingerprint operation is running or has completed. Specifies the path relative to the output volume root, of the form "/path". The path can be path to a file or a directory.


|scope
|string
a|The scope of the file which is used for the fingerprint computation


|state
|string
a|Specifies the status of fingerprint operation.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|volume
|link:#volume[volume]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "algorithm": "sha256",
  "data_fingerprint": "MOFJVevxNSJm3C/4Bn5oEEYH51CrudOzZYK4r5Cfy1g=",
  "file_size": 1048576,
  "file_type": "worm",
  "id": 17039367,
  "metadata_fingerprint": "8iMjqJXiNcqgXT5XuRhLiEwIrJEihDmwS0hrexnjgmc=",
  "path": "/homedir/dir1",
  "scope": "data_only",
  "state": "completed",
  "svm": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "volume": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "name": "volume1",
    "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
  }
}
====

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 14090441
| Invalid key values. Provide session ID or Vserver UUID and volume UUID

| 14090449
| File fingerprint operation has not completed
|===



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the volume. This field cannot be specified in a PATCH method.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6
* x-nullable: true


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
