---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-fpolicy-events.html'
summary: 'Retrieve the FPolicy event configuration for all events for an SVM'
---

= Retrieve the FPolicy event configuration for all events for an SVM

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/fpolicy/{svm.uuid}/events`#

*Introduced In:* 9.6

Retrieves FPolicy event configurations for all events for a specified SVM. ONTAP allows the creation of cluster-level FPolicy events that act as a template for all the data SVMs belonging to the cluster. These cluster-level FPolicy events are also retrieved for the specified SVM.

== Related ONTAP commands

* `fpolicy policy event show`

== Learn more

* link:protocols_fpolicy_svm.uuid_events_endpoint_overview.html[DOC /protocols/fpolicy/{svm.uuid}/events]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|protocol
|string
|query
|False
a|Filter by protocol


|filters.first_write
|boolean
|query
|False
a|Filter by filters.first_write


|filters.setattr_with_modify_time_change
|boolean
|query
|False
a|Filter by filters.setattr_with_modify_time_change


|filters.monitor_ads
|boolean
|query
|False
a|Filter by filters.monitor_ads


|filters.setattr_with_dacl_change
|boolean
|query
|False
a|Filter by filters.setattr_with_dacl_change


|filters.close_with_read
|boolean
|query
|False
a|Filter by filters.close_with_read


|filters.write_with_size_change
|boolean
|query
|False
a|Filter by filters.write_with_size_change


|filters.setattr_with_owner_change
|boolean
|query
|False
a|Filter by filters.setattr_with_owner_change


|filters.exclude_directory
|boolean
|query
|False
a|Filter by filters.exclude_directory


|filters.first_read
|boolean
|query
|False
a|Filter by filters.first_read


|filters.open_with_delete_intent
|boolean
|query
|False
a|Filter by filters.open_with_delete_intent


|filters.close_without_modification
|boolean
|query
|False
a|Filter by filters.close_without_modification


|filters.setattr_with_size_change
|boolean
|query
|False
a|Filter by filters.setattr_with_size_change


|filters.setattr_with_access_time_change
|boolean
|query
|False
a|Filter by filters.setattr_with_access_time_change


|filters.setattr_with_sacl_change
|boolean
|query
|False
a|Filter by filters.setattr_with_sacl_change


|filters.setattr_with_mode_change
|boolean
|query
|False
a|Filter by filters.setattr_with_mode_change


|filters.setattr_with_group_change
|boolean
|query
|False
a|Filter by filters.setattr_with_group_change


|filters.setattr_with_allocation_size_change
|boolean
|query
|False
a|Filter by filters.setattr_with_allocation_size_change


|filters.open_with_write_intent
|boolean
|query
|False
a|Filter by filters.open_with_write_intent


|filters.close_with_modification
|boolean
|query
|False
a|Filter by filters.close_with_modification


|filters.setattr_with_creation_time_change
|boolean
|query
|False
a|Filter by filters.setattr_with_creation_time_change


|filters.offline_bit
|boolean
|query
|False
a|Filter by filters.offline_bit


|name
|string
|query
|False
a|Filter by name


|volume_monitoring
|boolean
|query
|False
a|Filter by volume_monitoring


|monitor_fileop_failure
|boolean
|query
|False
a|Filter by monitor_fileop_failure

* Introduced in: 9.13


|file_operations.read
|boolean
|query
|False
a|Filter by file_operations.read


|file_operations.write
|boolean
|query
|False
a|Filter by file_operations.write


|file_operations.getattr
|boolean
|query
|False
a|Filter by file_operations.getattr


|file_operations.create
|boolean
|query
|False
a|Filter by file_operations.create


|file_operations.close
|boolean
|query
|False
a|Filter by file_operations.close


|file_operations.setattr
|boolean
|query
|False
a|Filter by file_operations.setattr


|file_operations.lookup
|boolean
|query
|False
a|Filter by file_operations.lookup


|file_operations.create_dir
|boolean
|query
|False
a|Filter by file_operations.create_dir


|file_operations.delete
|boolean
|query
|False
a|Filter by file_operations.delete


|file_operations.access
|boolean
|query
|False
a|Filter by file_operations.access

* Introduced in: 9.13


|file_operations.open
|boolean
|query
|False
a|Filter by file_operations.open


|file_operations.delete_dir
|boolean
|query
|False
a|Filter by file_operations.delete_dir


|file_operations.rename_dir
|boolean
|query
|False
a|Filter by file_operations.rename_dir


|file_operations.symlink
|boolean
|query
|False
a|Filter by file_operations.symlink


|file_operations.rename
|boolean
|query
|False
a|Filter by file_operations.rename


|file_operations.link
|boolean
|query
|False
a|Filter by file_operations.link


|svm.uuid
|string
|path
|True
a|UUID of the SVM to which this object belongs.


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#fpolicy_event[fpolicy_event]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "name": "event_cifs",
      "protocol": "string",
      "svm": {
        "uuid": "string"
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#file_operations]
[.api-collapsible-fifth-title]
file_operations

Specifies the file operations for the FPolicy event. You must specify a valid protocol in the protocol parameter.
The event will check the operations specified from all client requests using the protocol.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|access
|boolean
a|Access operations


|close
|boolean
a|File close operations


|create
|boolean
a|File create operations


|create_dir
|boolean
a|Directory create operations


|delete
|boolean
a|File delete operations


|delete_dir
|boolean
a|Directory delete operations


|getattr
|boolean
a|Get attribute operations


|link
|boolean
a|Link operations


|lookup
|boolean
a|Lookup operations


|open
|boolean
a|File open operations


|read
|boolean
a|File read operations


|rename
|boolean
a|File rename operations


|rename_dir
|boolean
a|Directory rename operations


|setattr
|boolean
a|Set attribute operations


|symlink
|boolean
a|Symbolic link operations


|write
|boolean
a|File write operations


|===


[#filters]
[.api-collapsible-fifth-title]
filters

Specifies the list of filters for a given file operation for the specified protocol.
When you specify the filters, you must specify the valid protocols and a valid file operations.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|close_with_modification
|boolean
a|Filter the client request for close with modification.


|close_with_read
|boolean
a|Filter the client request for close with read.


|close_without_modification
|boolean
a|Filter the client request for close without modification.


|exclude_directory
|boolean
a|Filter the client requests for directory operations. When this filter is specified directory operations are not monitored.


|first_read
|boolean
a|Filter the client requests for the first-read.


|first_write
|boolean
a|Filter the client requests for the first-write.


|monitor_ads
|boolean
a|Filter the client request for alternate data stream.


|offline_bit
|boolean
a|Filter the client request for offline bit set. FPolicy server receives notification only when offline files are accessed.


|open_with_delete_intent
|boolean
a|Filter the client request for open with delete intent.


|open_with_write_intent
|boolean
a|Filter the client request for open with write intent.


|setattr_with_access_time_change
|boolean
a|Filter the client setattr requests for changing the access time of a file or directory.


|setattr_with_allocation_size_change
|boolean
a|Filter the client setattr requests for changing the allocation size of a file.


|setattr_with_creation_time_change
|boolean
a|Filter the client setattr requests for changing the creation time of a file or directory.


|setattr_with_dacl_change
|boolean
a|Filter the client setattr requests for changing dacl on a file or directory.


|setattr_with_group_change
|boolean
a|Filter the client setattr requests for changing group of a file or directory.


|setattr_with_mode_change
|boolean
a|Filter the client setattr requests for changing the mode bits on a file or directory.


|setattr_with_modify_time_change
|boolean
a|Filter the client setattr requests for changing the modification time of a file or directory.


|setattr_with_owner_change
|boolean
a|Filter the client setattr requests for changing owner of a file or directory.


|setattr_with_sacl_change
|boolean
a|Filter the client setattr requests for changing sacl on a file or directory.


|setattr_with_size_change
|boolean
a|Filter the client setattr requests for changing the size of a file.


|write_with_size_change
|boolean
a|Filter the client request for write with size change.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|SVM UUID


|===


[#fpolicy_event]
[.api-collapsible-fifth-title]
fpolicy_event

The information that a FPolicy process needs to determine what file access operations to monitor and for which of the monitored events notifications should be sent to the external FPolicy server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|file_operations
|link:#file_operations[file_operations]
a|Specifies the file operations for the FPolicy event. You must specify a valid protocol in the protocol parameter.
The event will check the operations specified from all client requests using the protocol.


|filters
|link:#filters[filters]
a|Specifies the list of filters for a given file operation for the specified protocol.
When you specify the filters, you must specify the valid protocols and a valid file operations.


|monitor_fileop_failure
|boolean
a|Specifies whether failed file operations monitoring is required.


|name
|string
a|Specifies the name of the FPolicy event.


|protocol
|string
a|Protocol for which event is created. If you specify protocol, then you
must also specify a valid value for the file operation parameters.
The value of this parameter must be one of the following:

***** cifs  - for the CIFS protocol.

***** nfsv3 - for the NFSv3 protocol.

***** nfsv4 - for the NFSv4 protocol.


|svm
|link:#svm[svm]
a|

|volume_monitoring
|boolean
a|Specifies whether volume operation monitoring is required.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
