---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-snapmirror-policies.html'
summary: 'Retrieve SnapMirror async and sync policy types'
---

= Retrieve SnapMirror async and sync policy types

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/snapmirror/policies`#

*Introduced In:* 9.6

Retrieves SnapMirror policies of type "async" and "sync".

== Related ONTAP commands

* `snapmirror policy show`

== Example

The following example shows how to retrieve a collection of SnapMirror policies.

----
GET "/api/snapmirror/policies"
----

== Learn more

* link:snapmirror_policies_endpoint_overview.html[DOC /snapmirror/policies]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|name
|string
|query
|False
a|Filter by name


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|throttle
|integer
|query
|False
a|Filter by throttle


|copy_latest_source_snapshot
|boolean
|query
|False
a|Filter by copy_latest_source_snapshot

* Introduced in: 9.11


|comment
|string
|query
|False
a|Filter by comment


|transfer_schedule.uuid
|string
|query
|False
a|Filter by transfer_schedule.uuid


|transfer_schedule.name
|string
|query
|False
a|Filter by transfer_schedule.name


|network_compression_enabled
|boolean
|query
|False
a|Filter by network_compression_enabled


|type
|string
|query
|False
a|Filter by type


|create_snapshot_on_source
|boolean
|query
|False
a|Filter by create_snapshot_on_source

* Introduced in: 9.11


|sync_common_snapshot_schedule.uuid
|string
|query
|False
a|Filter by sync_common_snapshot_schedule.uuid


|sync_common_snapshot_schedule.name
|string
|query
|False
a|Filter by sync_common_snapshot_schedule.name


|rpo
|integer
|query
|False
a|Filter by rpo

* Introduced in: 9.10


|copy_all_source_snapshots
|boolean
|query
|False
a|Filter by copy_all_source_snapshots

* Introduced in: 9.10


|sync_type
|string
|query
|False
a|Filter by sync_type


|scope
|string
|query
|False
a|Filter by scope


|uuid
|string
|query
|False
a|Filter by uuid


|retention.prefix
|string
|query
|False
a|Filter by retention.prefix


|retention.period
|string
|query
|False
a|Filter by retention.period

* Introduced in: 9.11


|retention.count
|string
|query
|False
a|Filter by retention.count


|retention.preserve
|boolean
|query
|False
a|Filter by retention.preserve

* Introduced in: 9.13


|retention.label
|string
|query
|False
a|Filter by retention.label


|retention.creation_schedule.uuid
|string
|query
|False
a|Filter by retention.creation_schedule.uuid


|retention.creation_schedule.name
|string
|query
|False
a|Filter by retention.creation_schedule.name


|retention.warn
|integer
|query
|False
a|Filter by retention.warn

* Introduced in: 9.13


|identity_preservation
|string
|query
|False
a|Filter by identity_preservation


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#snapmirror_policy[snapmirror_policy]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "comment": "string",
      "copy_all_source_snapshots": 1,
      "copy_latest_source_snapshot": 1,
      "create_snapshot_on_source": "",
      "identity_preservation": "string",
      "name": "Asynchronous",
      "retention": [
        {
          "count": "7",
          "creation_schedule": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "weekly",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          },
          "label": "hourly",
          "period": "P30D",
          "prefix": "string",
          "preserve": 1,
          "warn": 4
        }
      ],
      "rpo": 0,
      "scope": "string",
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "sync_common_snapshot_schedule": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "weekly",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "sync_type": "string",
      "throttle": 0,
      "transfer_schedule": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "weekly",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "type": "string",
      "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 13303842
| SnapMirror policy is not supported.
|===



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#creation_schedule]
[.api-collapsible-fifth-title]
creation_schedule

Schedule used to create snapshots on the destination for long term retention. Only cron schedules are supported for SnapMirror.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_policy_rule]
[.api-collapsible-fifth-title]
snapmirror_policy_rule

SnapMirror policy rule for retention.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|string
a|Number of snapshots to be kept for retention. Maximum value will differ based on type of relationship and scaling factor.


|creation_schedule
|link:#creation_schedule[creation_schedule]
a|Schedule used to create snapshots on the destination for long term retention. Only cron schedules are supported for SnapMirror.


|label
|string
a|Snapshot label


|period
|string
a|Specifies the duration for which the snapshots are locked. The retention period value represents a duration and must be in the ISO-8601 duration format. Years, months, days, hours, minutes, and seconds are represented as "P+++<num>+++Y","P+++<num>+++M","P+++<num>+++D","PT+++<num>+++H","PT+++<num>+++M" and "PT+++<num>+++S". Value "infinite" is also a valid input for Flexvol volumes and FlexGroup volumes. A duration which combines different periods is not supported, for example "P1Y10M" is not supported. The range of supported retention period values is between 1 second to infinite.+++</num>++++++</num>++++++</num>++++++</num>++++++</num>++++++</num>+++


|prefix
|string
a|Specifies the prefix for the snapshot name to be created as per the schedule. If no value is specified, then the label is used as the prefix.


|preserve
|boolean
a|Specifies the behavior when the snapshot retention count is reached on the SnapMirror destination for the rule. The default value is false, which means that the oldest snapshot is deleted to make room for new ones but only if the number of snapshots has exceeded the retention count specified in the 'count' property. When set to true and where the snapshots have reached the retention count, an incremental SnapMirror transfer will fail or if the rule has a schedule, snapshots will be no longer be created on the SnapMirror destination.


|warn
|integer
a|Specifies the warning threshold count for the rule. The default value is zero. When set to a value greater than zero, an event is generated after the number of snapshots (for the particular rule) retained on a SnapMirror destination reaches the specified warning limit. The preserve property for the rule must be true in order to set the warn property to a value greater than zero.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#sync_common_snapshot_schedule]
[.api-collapsible-fifth-title]
sync_common_snapshot_schedule

Schedule used to create common snapshots for synchronous relationships.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#transfer_schedule]
[.api-collapsible-fifth-title]
transfer_schedule

The schedule used to update asynchronous relationships. Only cron schedules are supported for SnapMirror.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_policy]
[.api-collapsible-fifth-title]
snapmirror_policy

SnapMirror policy information. SnapMirror policy can either be of type "async", "sync" or "continuous".
The policy type "async" can be associated with a SnapMirror relationship that has either a FlexVol volume, FlexGroup volume or SVM as the endpoint.
The policy type "sync" along with "sync_type" as "sync" or "strict_sync" can be associated with a SnapMirror relationship that has a FlexVol volume as the endpoint. The policy type "sync" can have a "sync_type" of either "sync", "strict_sync", "automated_failover" or "automated_failover_duplex". If the "sync_type" is "sync", a write success is returned to the client after writing the data to the source endpoint and before writing the data to the destination endpoint. If the "sync_type" is "strict_sync", a write success is returned to the client after writing the data to both source and destination endpoints.
If the "sync_type" is "automated_failover", the policy can be associated with a SnapMirror active sync relationship that has a consistency group as the endpoint and provides asymmetric active active access to the two storage copies. If the "sync_type" is "automated_failover_duplex", the policy can be associated with a SnapMirror active sync relationship that has a consistency group as the endpoint and provides symmetric active active access to the two storage copies. Use the "sync" policy with "sync_type" as "automated_failover" or "automated_failover_duplex" to establish SnapMirror active sync relationships for business continuity use cases. SnapMirror relationships with policy types as "sync" and "sync_type" as "automated_failover" or "automated_failover_duplex" can be monitored by the Mediator, if configured. If the source Consistency Group endpoint is not reachable, the Mediator might trigger a failover to the destination consistency group endpoint.
A policy type of "continuous" can be associated with SnapMirror relationships that have either ONTAP S3 buckets or non-ONTAP object stores as endpoints. This type of policy is used for FabricLink owned targets.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|comment
|string
a|Comment associated with the policy.


|copy_all_source_snapshots
|boolean
a|Specifies that all the source snapshots (including the one created by SnapMirror before the transfer begins) should be copied to the destination on a transfer. "Retention" properties cannot be specified along with this property. This is applicable only to async policies. Property can only be set to 'true'.


|copy_latest_source_snapshot
|boolean
a|Specifies that the latest source snapshot (created by SnapMirror before the transfer begins) should be copied to the destination on a transfer. "Retention" properties cannot be specified along with this property. This is applicable only to async policies. Property can only be set to 'true'.


|create_snapshot_on_source
|boolean
a|Specifies whether a new snapshot should be created on the source at the beginning of an update or resync operation. This is applicable only to async policies. Property can only be set to 'false'.


|identity_preservation
|string
a|Specifies which configuration of the source SVM is replicated to the destination SVM. This property is applicable only for SVM data protection with "async" policy type.


|name
|string
a|Name of the policy.


|network_compression_enabled
|boolean
a|Specifies whether network compression is enabled for transfers. This is applicable only to the policies of type "async".


|retention
|array[link:#snapmirror_policy_rule[snapmirror_policy_rule]]
a|Rules for snapshot retention.


|rpo
|integer
a|Specifies the duration of time for which a change to be propagated to a mirror should be delayed, in seconds. This is an intentional propagation delay between mirrors and is configurable down to zero, which means an immediate propagation. This is supported for policies of type 'continuous'.


|scope
|string
a|Set to "svm" for policies owned by an SVM, otherwise set to "cluster".


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|sync_common_snapshot_schedule
|link:#sync_common_snapshot_schedule[sync_common_snapshot_schedule]
a|Schedule used to create common snapshots for synchronous relationships.


|sync_type
|string
a|

|throttle
|integer
a|Throttle in KB/s. Default to unlimited.


|transfer_schedule
|link:#transfer_schedule[transfer_schedule]
a|The schedule used to update asynchronous relationships. Only cron schedules are supported for SnapMirror.


|type
|string
a|

|uuid
|string
a|Unique identifier of the SnapMirror policy.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
