---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-cluster-peers.html'
summary: 'Retrieve cluster peers'
---

= Retrieve cluster peers

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/cluster/peers`#

*Introduced In:* 9.6

Retrieves the collection of cluster peers.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#cluster_peer[cluster_peer]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "interfaces": {
          "href": "/api/resourcelink"
        },
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "authentication": {
        "expiry_time": "P1DT2H3M4S or '2017-01-25T11:20:13Z'",
        "generate_passphrase": true,
        "in_use": "string",
        "passphrase": "string",
        "state": "string"
      },
      "encryption": {
        "proposed": "string",
        "state": "string"
      },
      "initial_allowed_svms": [
        {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "svm1",
          "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
        }
      ],
      "ip_address": "10.10.10.7",
      "ipspace": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "Default",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "name": "cluster2",
      "peer_applications": [
        "snapmirror",
        "flexcache"
      ],
      "remote": {
        "ip_addresses": [
          "10.10.10.7"
        ],
        "name": "cluster2",
        "serial_number": "4048820-60-9"
      },
      "status": {
        "state": "available",
        "update_time": "2017-01-25 11:20:13 +0000"
      },
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412",
      "version": {
        "full": "NetApp Release 9.4.0: Sun Nov 05 18:20:57 UTC 2017",
        "generation": 9,
        "major": 4,
        "minor": 0
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|interfaces
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#authentication]
[.api-collapsible-fifth-title]
authentication

[cols=3*,options=header]
|===
|Name
|Type
|Description

|expiry_time
|string
a|The time when the passphrase will expire, in ISO 8601 duration format or date and time format.  The default is 1 hour.


|in_use
|string
a|

|passphrase
|string
a|A password to authenticate the cluster peer relationship.


|state
|string
a|

|===


[#encryption]
[.api-collapsible-fifth-title]
encryption

[cols=3*,options=header]
|===
|Name
|Type
|Description

|proposed
|string
a|

|state
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#initial_allowed_svms]
[.api-collapsible-fifth-title]
initial_allowed_svms

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#ipspace]
[.api-collapsible-fifth-title]
ipspace

The IPspace of the local intercluster LIFs.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|IPspace name


|uuid
|string
a|IPspace UUID


|===


[#interfaces]
[.api-collapsible-fifth-title]
interfaces

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip_address
|string
a|IPv4 or IPv6 address


|===


[#local_network]
[.api-collapsible-fifth-title]
local_network

Cluster peering requires an intercluster LIF on each local node. These can be optionally created by specifying a list of IP addresses corresponding to each node.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|broadcast_domain
|string
a|Broadcast domain that is in use within the IPspace.


|gateway
|string
a|The IPv4 or IPv6 address of the default router.


|interfaces
|array[link:#interfaces[interfaces]]
a|

|netmask
|string
a|IPv4 mask or netmask length.


|===


[#remote]
[.api-collapsible-fifth-title]
remote

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip_addresses
|array[string]
a|The IPv4 addresses, IPv6 addresses, or hostnames of the peers.


|name
|string
a|The name of the remote cluster.


|serial_number
|string
a|The serial number of the remote cluster.


|===


[#status]
[.api-collapsible-fifth-title]
status

[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|

|update_time
|string
a|The last time the state was updated.


|===


[#version]
[.api-collapsible-fifth-title]
version

This returns the cluster version information.  When the cluster has more than one node, the cluster version is equivalent to the lowest of generation, major, and minor versions on all nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|full
|string
a|The full cluster version string.


|generation
|integer
a|The generation portion of the version.


|major
|integer
a|The major portion of the version.


|minor
|integer
a|The minor portion of the version.


|===


[#cluster_peer]
[.api-collapsible-fifth-title]
cluster_peer

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|authentication
|link:#authentication[authentication]
a|

|encryption
|link:#encryption[encryption]
a|

|initial_allowed_svms
|array[link:#initial_allowed_svms[initial_allowed_svms]]
a|The local SVMs allowed to peer with the peer cluster's SVMs. This list can be modified until the remote cluster accepts this cluster peering relationship.


|ip_address
|string
a|IPv4 or IPv6 address


|ipspace
|link:#ipspace[ipspace]
a|The IPspace of the local intercluster LIFs.


|name
|string
a|Optional name for the cluster peer relationship. By default, it is the name of the remote cluster, or a temporary name might be autogenerated for anonymous cluster peer offers.


|peer_applications
|array[string]
a|Peering applications against which allowed SVMs are configured.


|remote
|link:#remote[remote]
a|

|status
|link:#status[status]
a|

|uuid
|string
a|UUID of the cluster peer relationship. For anonymous cluster peer offers, the UUID will change when the remote cluster accepts the relationship.


|version
|link:#version[version]
a|This returns the cluster version information.  When the cluster has more than one node, the cluster version is equivalent to the lowest of generation, major, and minor versions on all nodes.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
