---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-storage-volumes-snapshots.html'
summary: 'Retrieve volume snapshots'
---

= Retrieve volume snapshots

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/storage/volumes/{volume.uuid}/snapshots`#

*Introduced In:* 9.6

Retrieves a collection of volume snapshots.

== Expensive properties

There is an added computational cost to retrieving the amount of reclaimable space for snapshots, as the calculation is done on demand based on the list of snapshots provided.

* `reclaimable_space`
* `delta`

== Related ONTAP commands

* `snapshot show`
* `snapshot compute-reclaimable`
* `snapshot show-delta`

== Learn more

* link:storage_volumes_volume.uuid_snapshots_endpoint_overview.html[DOC /storage/volumes/{volume.uuid}/snapshots]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|volume.uuid
|string
|path
|True
a|Volume


|snapmirror_label
|string
|query
|False
a|Filter by snapmirror_label

* Introduced in: 9.8
* maxLength: 31
* minLength: 1


|vbn0_savings
|integer
|query
|False
a|Filter by vbn0_savings

* Introduced in: 9.17


|delta.time_elapsed
|string
|query
|False
a|Filter by delta.time_elapsed

* Introduced in: 9.12


|delta.size_consumed
|integer
|query
|False
a|Filter by delta.size_consumed

* Introduced in: 9.12


|reclaimable_space
|integer
|query
|False
a|Filter by reclaimable_space

* Introduced in: 9.10


|volume.name
|string
|query
|False
a|Filter by volume.name


|provenance_volume.uuid
|string
|query
|False
a|Filter by provenance_volume.uuid

* Introduced in: 9.11


|logical_size
|integer
|query
|False
a|Filter by logical_size

* Introduced in: 9.12


|comment
|string
|query
|False
a|Filter by comment


|name
|string
|query
|False
a|Filter by name


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|size
|integer
|query
|False
a|Filter by size

* Introduced in: 9.9


|version_uuid
|string
|query
|False
a|Filter by version_uuid

* Introduced in: 9.11


|compress_savings
|integer
|query
|False
a|Filter by compress_savings

* Introduced in: 9.17


|uuid
|string
|query
|False
a|Filter by uuid


|dedup_savings
|integer
|query
|False
a|Filter by dedup_savings

* Introduced in: 9.17


|create_time
|string
|query
|False
a|Filter by create_time


|snaplock.expired
|boolean
|query
|False
a|Filter by snaplock.expired

* Introduced in: 9.15


|snaplock.expiry_time
|string
|query
|False
a|Filter by snaplock.expiry_time

* Introduced in: 9.15


|snaplock.time_until_expiry
|string
|query
|False
a|Filter by snaplock.time_until_expiry

* Introduced in: 9.15


|owners
|string
|query
|False
a|Filter by owners

* Introduced in: 9.7


|expiry_time
|string
|query
|False
a|Filter by expiry_time


|state
|string
|query
|False
a|Filter by state


|snaplock_expiry_time
|string
|query
|False
a|Filter by snaplock_expiry_time


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|delta
|link:#snapshot_delta[snapshot_delta]
a|Reports the amount of space consumed between two WAFL file systems, in bytes. The two WAFL file systems should be specified in a comma-separated format using the "name" parameter. To determine the space consumed between a snapshot and the Active File System, only the snapshot name needs to be mentioned.


|num_records
|integer
a|Number of records


|reclaimable_space
|integer
a|Space reclaimed when the snapshot is deleted, in bytes.


|records
|array[link:#snapshot[snapshot]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "delta": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "size_consumed": 0,
    "time_elapsed": "string"
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "comment": "string",
      "compress_savings": 1131223,
      "create_time": "2019-02-04 19:00:00 +0000",
      "dedup_savings": 1131223,
      "delta": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "size_consumed": 0,
        "time_elapsed": "string"
      },
      "expiry_time": "2019-02-04 19:00:00 +0000",
      "logical_size": 1228800,
      "name": "this_snapshot",
      "owners": [
        "string"
      ],
      "provenance_volume": {
        "uuid": "4cd8a442-86d1-11e0-ae1c-125648563413"
      },
      "size": "122880",
      "snaplock": {
        "expired": 1,
        "expiry_time": "2019-02-04 19:00:00 +0000",
        "time_until_expiry": "PT3H27M45S"
      },
      "snaplock_expiry_time": "2019-02-04 19:00:00 +0000",
      "snapmirror_label": "string",
      "state": "string",
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412",
      "vbn0_savings": 1131223,
      "version_uuid": "1cd8a442-86d1-11e0-ae1c-123478563412",
      "volume": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "volume1",
        "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
      }
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response Code

|===
| Error Code | Description

| 918235
| The specified volume is invalid.

| 9437613
| The operation is not supported on FlexCache Volumes.
|===



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#snapshot_delta]
[.api-collapsible-fifth-title]
snapshot_delta

Reports the amount of space consumed between two WAFL file systems, in bytes. The two WAFL file systems should be specified in a comma-separated format using the "name" parameter. To determine the space consumed between a snapshot and the Active File System, only the snapshot name needs to be mentioned.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|size_consumed
|integer
a|Indicates the space that has changed between two specified WAFL file systems, in bytes.


|time_elapsed
|string
a|Time elapsed between two specified WAFL file systems.


|===


[#provenance_volume]
[.api-collapsible-fifth-title]
provenance_volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|UUID for the volume that is used to identify the source volume in a mirroring relationship. When the mirroring relationship is broken, a volume's Instance UUID and Provenance UUID are made identical. An unmirrored volume's Provenance UUID is the same as its Instance UUID. This field is valid for flexible volumes only.


|===


[#snaplock]
[.api-collapsible-fifth-title]
snaplock

[cols=3*,options=header]
|===
|Name
|Type
|Description

|expired
|boolean
a|Indicates whether a SnapLock snapshot has expired.


|expiry_time
|string
a|SnapLock expiry time for the snapshot, if the snapshot is taken on a SnapLock volume. A snapshot is not allowed to be deleted or renamed until the SnapLock ComplianceClock time goes beyond this retention time. This option can be set during snapshot POST and snapshot PATCH on snapshot locking enabled volumes. It can also be used to extend the expiry time of a locked snapshot on a SnapLock for SnapVault destination consistency-group.


|time_until_expiry
|string
a|Indicates the remaining SnapLock expiry time of a locked snapshot, in seconds. This field is set only when the remaining time interval is less than 136 years.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the volume. This field cannot be specified in a PATCH method.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6
* x-nullable: true


|===


[#snapshot]
[.api-collapsible-fifth-title]
snapshot

The snapshot object represents a point in time snapshot of a volume.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|comment
|string
a|A comment associated with the snapshot. This is an optional attribute for POST or PATCH.


|compress_savings
|integer
a|Savings due to compression at the time the snapshot was taken in bytes.


|create_time
|string
a|Creation time of the snapshot. It is the volume access time when the snapshot was created.


|dedup_savings
|integer
a|Savings due to dedup at the time the snapshot was taken in bytes.


|delta
|link:#snapshot_delta[snapshot_delta]
a|Reports the amount of space consumed between two WAFL file systems, in bytes. The two WAFL file systems should be specified in a comma-separated format using the "name" parameter. To determine the space consumed between a snapshot and the Active File System, only the snapshot name needs to be mentioned.


|expiry_time
|string
a|The expiry time for the snapshot. This is an optional attribute for POST or PATCH. Snapshots with an expiry time set are not allowed to be deleted until the retention time is reached.


|logical_size
|integer
a|Size of the logical used file system at the time the snapshot is captured.


|name
|string
a|Snapshot. Valid in POST or PATCH.


|owners
|array[string]
a|

|provenance_volume
|link:#provenance_volume[provenance_volume]
a|

|reclaimable_space
|integer
a|Space reclaimed when the snapshot is deleted, in bytes.


|size
|integer
a|Size of the active file system at the time the snapshot is captured. The actual size of the snapshot also includes those blocks trapped by other snapshots. On a snapshot deletion, the "size" amount of blocks is the maximum number of blocks available. On a snapshot restore, the "afs-used size" value will match the snapshot "size" value.


|snaplock
|link:#snaplock[snaplock]
a|

|snaplock_expiry_time
|string
a|SnapLock expiry time for the snapshot, if the snapshot is taken on a SnapLock volume. A snapshot is not allowed to be deleted or renamed until the SnapLock ComplianceClock time goes beyond this retention time. This option can be set during snapshot POST and snapshot PATCH on snapshot locking enabled volumes. This field will no longer be supported in a future release. Use snaplock.expiry_time instead.


|snapmirror_label
|string
a|Label for SnapMirror operations


|state
|string
a|State of the FlexGroup volume snapshot. In the "pre_conversion" state, the snapshot was created before converting the FlexVol to a FlexGroup volume. A recently created snapshot can be in the "unknown" state while the system is calculating the state. In the "partial" state, the snapshot is consistent but exists only on the subset of the constituents that existed prior to the FlexGroup's expansion. Partial snapshots cannot be used for a snapshot restore operation. A snapshot is in an "invalid" state when it is present in some FlexGroup constituents but not in others. At all other times, a snapshot is valid.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|uuid
|string
a|The UUID of the snapshot in the volume that uniquely identifies the snapshot in that volume.


|vbn0_savings
|integer
a|Savings due vbn0 at the time the snapshot was taken in bytes.


|version_uuid
|string
a|The 128 bit identifier that uniquely identifies a snapshot and its logical data layout.


|volume
|link:#volume[volume]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
