---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-snapmirror-relationships.html'
summary: 'Retrieve information for SnapMirror relationships'
---

= Retrieve information for SnapMirror relationships

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/snapmirror/relationships`#

*Introduced In:* 9.6

Retrieves information for SnapMirror relationships whose destination endpoints are in the current SVM or the current cluster, depending on the cluster context.

== Related ONTAP commands

* `snapmirror show`
* `snapmirror list-destinations`

== Expensive properties

* `source.consistency_group_volumes.name`
* `destination.consistency_group_volumes.name`
* `svmdr_volumes.name`

== Examples

The following examples show how to retrieve the list of SnapMirror relationships and the list of SnapMirror destinations.

. Retrieving the list of SnapMirror relationships. This API must be run on the cluster containing the destination endpoint.

----
 GET "/api/snapmirror/relationships/"
----

. Retrieving the list of SnapMirror destinations on source. This must be run on the cluster containing the source endpoint.

----
 GET "/api/snapmirror/relationships/?list_destinations_only=true"
----

. Retrieving the relationship UUID of SnapMirror relationships with lag time greater than 2 days. This API must be run on the cluster containing the destination endpoint.

----
 GET "/api/snapmirror/relationships/?fields=uuid&lag_time=>P2DT"
----

. Retrieving the list of SnapMirror relationships with lag time less than 10 hours. This API must be run on the cluster containing the destination endpoint.

----
 GET "/api/snapmirror/relationships/?lag_time=<PT10H"
----

. Retrieving the list of constituent volumes for SVM DR Snapmirror relationships.

----
 GET "/api/snapmirror/relationships/?fields=svmdr_volumes.name"
----

</private>

== Learn more

* link:snapmirror_relationships_endpoint_overview.html[DOC /snapmirror/relationships]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|list_destinations_only
|boolean
|query
|False
a|Set to true to show relationships from the source only.


|transfer.end_time
|string
|query
|False
a|Filter by transfer.end_time

* Introduced in: 9.9


|transfer.uuid
|string
|query
|False
a|Filter by transfer.uuid


|transfer.bytes_transferred
|integer
|query
|False
a|Filter by transfer.bytes_transferred


|transfer.state
|string
|query
|False
a|Filter by transfer.state


|transfer.total_duration
|string
|query
|False
a|Filter by transfer.total_duration

* Introduced in: 9.9


|transfer.type
|string
|query
|False
a|Filter by transfer.type

* Introduced in: 9.14


|transfer.last_updated_time
|string
|query
|False
a|Filter by transfer.last_updated_time

* Introduced in: 9.14


|state
|string
|query
|False
a|Filter by state


|restore
|boolean
|query
|False
a|Filter by restore


|policy.name
|string
|query
|False
a|Filter by policy.name


|policy.type
|string
|query
|False
a|Filter by policy.type


|policy.uuid
|string
|query
|False
a|Filter by policy.uuid


|source.cluster.name
|string
|query
|False
a|Filter by source.cluster.name

* Introduced in: 9.7


|source.cluster.uuid
|string
|query
|False
a|Filter by source.cluster.uuid

* Introduced in: 9.7


|source.consistency_group_volumes.name
|string
|query
|False
a|Filter by source.consistency_group_volumes.name

* Introduced in: 9.8


|source.path
|string
|query
|False
a|Filter by source.path


|source.luns.uuid
|string
|query
|False
a|Filter by source.luns.uuid

* Introduced in: 9.16


|source.luns.name
|string
|query
|False
a|Filter by source.luns.name

* Introduced in: 9.16


|source.svm.name
|string
|query
|False
a|Filter by source.svm.name


|source.svm.uuid
|string
|query
|False
a|Filter by source.svm.uuid


|lag_time
|string
|query
|False
a|Filter by lag_time


|consistency_group_failover.error.arguments.message
|string
|query
|False
a|Filter by consistency_group_failover.error.arguments.message

* Introduced in: 9.8


|consistency_group_failover.error.arguments.code
|string
|query
|False
a|Filter by consistency_group_failover.error.arguments.code

* Introduced in: 9.8


|consistency_group_failover.error.code
|string
|query
|False
a|Filter by consistency_group_failover.error.code

* Introduced in: 9.8


|consistency_group_failover.error.message
|string
|query
|False
a|Filter by consistency_group_failover.error.message

* Introduced in: 9.8


|consistency_group_failover.state
|string
|query
|False
a|Filter by consistency_group_failover.state

* Introduced in: 9.14


|consistency_group_failover.status.message
|string
|query
|False
a|Filter by consistency_group_failover.status.message

* Introduced in: 9.8


|consistency_group_failover.status.code
|string
|query
|False
a|Filter by consistency_group_failover.status.code

* Introduced in: 9.8


|consistency_group_failover.type
|string
|query
|False
a|Filter by consistency_group_failover.type

* Introduced in: 9.14


|group_type
|string
|query
|False
a|Filter by group_type

* Introduced in: 9.11


|master_bias_activated_site
|string
|query
|False
a|Filter by master_bias_activated_site

* Introduced in: 9.14


|destination.luns.uuid
|string
|query
|False
a|Filter by destination.luns.uuid

* Introduced in: 9.16


|destination.luns.name
|string
|query
|False
a|Filter by destination.luns.name

* Introduced in: 9.16


|destination.svm.name
|string
|query
|False
a|Filter by destination.svm.name


|destination.svm.uuid
|string
|query
|False
a|Filter by destination.svm.uuid


|destination.consistency_group_volumes.name
|string
|query
|False
a|Filter by destination.consistency_group_volumes.name

* Introduced in: 9.8


|destination.cluster.name
|string
|query
|False
a|Filter by destination.cluster.name

* Introduced in: 9.7


|destination.cluster.uuid
|string
|query
|False
a|Filter by destination.cluster.uuid

* Introduced in: 9.7


|destination.path
|string
|query
|False
a|Filter by destination.path


|io_serving_copy
|string
|query
|False
a|Filter by io_serving_copy

* Introduced in: 9.14


|throttle
|integer
|query
|False
a|Filter by throttle

* Introduced in: 9.11


|last_transfer_type
|string
|query
|False
a|Filter by last_transfer_type

* Introduced in: 9.11


|preferred_site
|string
|query
|False
a|Filter by preferred_site

* Introduced in: 9.14


|exported_snapshot
|string
|query
|False
a|Filter by exported_snapshot


|identity_preservation
|string
|query
|False
a|Filter by identity_preservation

* Introduced in: 9.11


|unhealthy_reason.message
|string
|query
|False
a|Filter by unhealthy_reason.message


|unhealthy_reason.arguments
|string
|query
|False
a|Filter by unhealthy_reason.arguments

* Introduced in: 9.14


|unhealthy_reason.code
|string
|query
|False
a|Filter by unhealthy_reason.code


|svmdr_volumes.name
|string
|query
|False
a|Filter by svmdr_volumes.name

* Introduced in: 9.13


|total_transfer_duration
|string
|query
|False
a|Filter by total_transfer_duration

* Introduced in: 9.13


|healthy
|boolean
|query
|False
a|Filter by healthy


|uuid
|string
|query
|False
a|Filter by uuid


|total_transfer_bytes
|integer
|query
|False
a|Filter by total_transfer_bytes

* Introduced in: 9.13


|backoff_level
|string
|query
|False
a|Filter by backoff_level

* Introduced in: 9.14


|transfer_schedule.name
|string
|query
|False
a|Filter by transfer_schedule.name

* Introduced in: 9.11


|transfer_schedule.uuid
|string
|query
|False
a|Filter by transfer_schedule.uuid

* Introduced in: 9.11


|last_transfer_network_compression_ratio
|string
|query
|False
a|Filter by last_transfer_network_compression_ratio

* Introduced in: 9.13


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#snapmirror_relationship[snapmirror_relationship]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "backoff_level": "medium",
      "consistency_group_failover": {
        "error": {
          "arguments": [
            {
              "code": "string",
              "message": "string"
            }
          ],
          "code": "4",
          "message": "entry doesn't exist"
        },
        "state": "string",
        "status": {
          "code": "string",
          "message": "string"
        },
        "type": "string"
      },
      "destination": {
        "cluster": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "cluster1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "consistency_group_volumes": [
          {
            "name": "volume1"
          }
        ],
        "luns": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "/vol/volume1/lun1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "path": "svm1:volume1",
        "svm": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "svm1",
          "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
        }
      },
      "exported_snapshot": "string",
      "group_type": "consistency_group",
      "identity_preservation": "string",
      "io_serving_copy": "C1_sti85-vsim-ucs209a_cluster, C1_sti85-vsim-ucs209c_cluster",
      "lag_time": "PT8H35M42S",
      "last_transfer_network_compression_ratio": 61,
      "last_transfer_type": "initialize",
      "master_bias_activated_site": "C1_sti85-vsim-ucs209a_cluster",
      "policy": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "Asynchronous",
        "type": "string",
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      },
      "preferred_site": "C1_sti85-vsim-ucs209a_cluster",
      "restore_to_snapshot": "string",
      "source": {
        "cluster": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "cluster1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "consistency_group_volumes": [
          {
            "name": "volume1"
          }
        ],
        "luns": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "/vol/volume1/lun1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "path": "svm1:volume1",
        "svm": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "svm1",
          "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
        }
      },
      "state": "snapmirrored",
      "svmdr_volumes": [
        {
          "name": "volume1"
        }
      ],
      "throttle": 0,
      "total_transfer_bytes": 1098210312,
      "total_transfer_duration": "PT3M21S",
      "transfer": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "end_time": "2020-12-02 18:36:19 -0800",
        "last_updated_time": "2023-09-14 15:39:19 -0700",
        "state": "string",
        "total_duration": "PT28M41S",
        "type": "initialize",
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      },
      "transfer_schedule": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "weekly",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "unhealthy_reason": [
        {
          "arguments": [],
          "code": "6621444",
          "message": "Failed to complete update operation on one or more item relationships."
        },
        {
          "arguments": [],
          "code": "6621445",
          "message": "Group Update failed"
        }
      ],
      "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 13303825
| Could not retrieve information for the SnapMirror policy type

| 13303817
| Unknown value for the Snapmirror State
|===



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

SnapMirror Consistency Group failover error message.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|===


[#status]
[.api-collapsible-fifth-title]
status

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Status code


|message
|string
a|SnapMirror Consistency Group failover status.


|===


[#snapmirror_consistency_group_failover]
[.api-collapsible-fifth-title]
snapmirror_consistency_group_failover

SnapMirror Consistency Group failover information. The SnapMirror Consistency Group failover can be a planned or an unplanned operation. Only active SnapMirror Consistency Group failover operation progress can be monitored using this object. In case of an error during the failover operation, the property "consistency_group_failover.error" holds the reason for the error. ONTAP automatically retries any failed SnapMirror Consistency Group failover operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|SnapMirror Consistency Group failover error message.


|state
|string
a|SnapMirror Consistency Group failover state.


|status
|link:#status[status]
a|

|type
|string
a|SnapMirror Consistency Group failover type.


|===


[#bucket_retention]
[.api-collapsible-fifth-title]
bucket_retention

Specifies the retention-mode and default retention period configured on the destination bucket.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|default_period
|string
a|Specifies the default retention period that is applied to objects while committing them to the WORM state without an associated retention period. The retention period can be in years, or days. The retention period value represents a duration and must be specified in the ISO-8601 duration format.  A period specified for years and days is represented in the ISO-8601 format as "P+++<num>+++Y" and "P+++<num>+++D" respectively, for example "P10Y" represents a duration of 10 years. The period string must contain only a single time element that is, either years, or days. A duration which combines different periods is not supported, for example "P1Y10D" is not supported.+++</num>++++++</num>+++


|mode
|string
a|The lock mode of the bucket.
compliance &dash; A SnapLock Compliance (SLC) bucket provides the highest level of WORM protection and an administrator cannot destroy a compliance bucket if it contains unexpired WORM objects.
 governance &dash; An administrator can delete a Governance bucket.
 no_lock &dash; Indicates the bucket does not support object locking.


|===


[#storage_service]
[.api-collapsible-fifth-title]
storage_service

[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|This property indicates whether to create the destination endpoint using storage service. This property is supported for Unified ONTAP destination endpoints only.

* Introduced in: 9.7
* x-nullable: true


|enforce_performance
|boolean
a|Optional property to enforce storage service performance on the destination endpoint. This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints. This property is supported for Unified ONTAP destination endpoints only.

* Default value:
* Introduced in: 9.7
* x-nullable: true


|name
|string
a|Optional property to specify the storage service name for the destination endpoint. This property is considered when the property "create_destination.storage_service.enabled" is set to "true". When the property "create_destination.storage_service.enabled" is set to "true" and the "create_destination.storage_service.name" for the endpoint is not specified, then ONTAP selects the highest storage service available on the cluster to provision the destination endpoint. This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints. This property is supported for Unified ONTAP destination endpoints only.

* enum: ["extreme", "performance", "value"]
* Introduced in: 9.6
* x-nullable: true


|===


[#tiering]
[.api-collapsible-fifth-title]
tiering

[cols=3*,options=header]
|===
|Name
|Type
|Description

|policy
|string
a|Optional property to specify the destination endpoint's tiering policy when "create_destination.tiering.supported" is set to "true". This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints. This property determines whether the user data blocks of the destination endpoint in a FabricPool will be tiered to the cloud store when they become cold. FabricPool combines flash (performance tier) with a cloud store into a single aggregate. Temperature of the destination endpoint volume blocks increases if they are accessed frequently and decreases when they are not.
all &dash; This policy allows tiering of both destination endpoint snapshots and the user transferred data blocks to the cloud store as soon as possible by ignoring the temperature on the volume blocks. This tiering policy is not applicable for Consistency Group destination endpoints or for synchronous relationships.
auto &dash; This policy allows tiering of both destination endpoint snapshots and the active file system user data to the cloud store
none &dash; Destination endpoint volume blocks will not be tiered to the cloud store.
snapshot_only &dash; This policy allows tiering of only the destination endpoint volume snapshots not associated with the active file system. The default tiering policy is "snapshot_only" for a FlexVol volume and "none" for a FlexGroup volume. This property is supported for Unified ONTAP destination endpoints only.

* enum: ["all", "auto", "none", "snapshot_only"]
* Introduced in: 9.6
* x-nullable: true


|supported
|boolean
a|Optional property to enable provisioning of the destination endpoint volumes on FabricPool aggregates. This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints. Only FabricPool aggregates are used if this property is set to "true" and only non FabricPool aggregates are used if this property is set to "false". Tiering support for a FlexGroup volume can be changed by moving all of the constituents to the required aggregates. Note that in order to tier data, not only do the destination endpoint volumes need to support tiering by using FabricPools, the "create_destination.tiering.policy" must not be "none". A destination endpoint that uses FabricPools but has a tiering "policy" of "none" supports tiering but will not tier any data. This property is supported for Unified ONTAP destination endpoints only.

* Introduced in: 9.6
* x-nullable: true


|===


[#snapmirror_destination_creation]
[.api-collapsible-fifth-title]
snapmirror_destination_creation

Use this object to provision the destination endpoint when establishing a SnapMirror relationship for a FlexVol volume, FlexGroup volume, SVM, Consistency Group or ONTAP S3 Bucket. Given a source endpoint, the destination endpoint is provisioned in the SVM specified in the "destination.path" property. While protecting an SVM, the SVM destination endpoint can only be provisioned on the local cluster. To provision the SVM destination endpoint use the optional "source.cluster.name" property to specify the remote cluster name or use the optional "source.cluster.uuid" property to specify the remote cluster UUID. When "create_destination.enabled" option is specified while making a POST for a SnapMirror relationship, the relationship can be automatically initialized by setting the "state" either to "snapmirrored" when the policy is of type "async" or to "in_sync" when the policy is of type "sync". The "destination.path" property must specify the destination endpoint path. For example, for FlexVol volume and FlexGroup volume, the "destination.path" can be specified as +++<destination-svm-name:dp-volume-name>+++, for SVM data protection, the "destination.path" must be specified as <destination-svm-name:>, and for Consistency Group, the "destination.path" must be specified as <destination-svm-name:> along with the "destination.consistency_group_volumes" or "destination.luns" property to indicate the list of destination volumes or LUNs of type "DP" in the Consistency Group. For a FlexVol volume, a FlexGroup volume, Consistency Group or a Bucket destination endpoint, the properties in this object can be specified either from the source or the destination cluster. For an SVM destination endpoint, the properties in this object can be specified from the destination cluster only. This object is not supported for non ONTAP endpoints. While protecting a S3 Bucket, the optional "size" property can be used to create ONTAP S3 Bucket destination endpoint of the specified size.</destination-svm-name:></destination-svm-name:>+++</destination-svm-name:dp-volume-name>+++


[cols=3*,options=header]
|===
|Name
|Type
|Description

|bucket_retention
|link:#bucket_retention[bucket_retention]
a|Specifies the retention-mode and default retention period configured on the destination bucket.


|enabled
|boolean
a|Optional property to create the destination endpoint when establishing a SnapMirror relationship. It is assumed to be "false" if no other property is set and assumed to be "true" if any other property is set.


|size
|integer
a|Optional property to specify the size of destination endpoint in bytes. This property is applicable only to ONTAP S3 Bucket endpoints. The minimum size for S3 bucket is 80MB and maximum size is 64TB. If not specified, system will create destination with default size of 800GB.

* Introduced in: 9.10
* x-nullable: true


|snapshot_locking_enabled
|boolean
a|Optional property to create the destination endpoint with snapshot locking enabled when establishing a SnapMirror relationship. This property is applicable to FlexVol volumes and FlexGroup volumes.


|storage_service
|link:#storage_service[storage_service]
a|

|tiering
|link:#tiering[tiering]
a|

|===


[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#consistency_group_volumes]
[.api-collapsible-fifth-title]
consistency_group_volumes

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|===


[#luns]
[.api-collapsible-fifth-title]
luns

Optional property for a SnapMirror endpoint. Specifies the list of source LUNs and optionally list of destination LUNs during SnapMirror Consistency Group LUN restore operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of a LUN.
A LUN is located within a volume. Optionally, it can be located within a qtree in a volume.

LUN names are paths of the form "/vol/<volume>[/<qtree>]/<namespace>" where the qtree name is optional.


|uuid
|string
a|The unique identifier of the LUN.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#snapmirror_endpoint]
[.api-collapsible-fifth-title]
snapmirror_endpoint

Endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to create the destination SVM endpoint or to establish an SVM DR relationship must have the property "cluster" populated with the remote cluster details. A POST request to create the destination FlexVol volume, FlexGroup volume, Consistency Group, ONTAP S3 bucket and NON-ONTAP object-store endpoints can optionally specify the "cluster" property when the source SVM and the destination SVM are peered. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster[cluster]
a|

|consistency_group_volumes
|array[link:#consistency_group_volumes[consistency_group_volumes]]
a|This property specifies the list of FlexVol volumes or LUNs of a Consistency Group. Optional on the ASA r2 platform. Mandatory for all other platforms.


|luns
|link:#luns[luns]
a|Optional property for a SnapMirror endpoint. Specifies the list of source LUNs and optionally list of destination LUNs during SnapMirror Consistency Group LUN restore operation.


|path
|string
a|ONTAP FlexVol/FlexGroup - svm1:volume1
ONTAP SVM               - svm1:
ONTAP Consistency Group - svm1:/cg/cg_name
ONTAP S3                - svm1:/bucket/bucket1
NON-ONTAP               - objstore1:/objstore

* example: svm1:volume1
* Introduced in: 9.6
* x-nullable: true


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#policy]
[.api-collapsible-fifth-title]
policy

Basic policy information of the relationship.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Name of the SnapMirror policy.


|type
|string
a|

|uuid
|string
a|Unique identifier of the SnapMirror policy.


|===


[#snapmirror_source_endpoint]
[.api-collapsible-fifth-title]
snapmirror_source_endpoint

Source endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster[cluster]
a|

|consistency_group_volumes
|array[link:#consistency_group_volumes[consistency_group_volumes]]
a|This property specifies the list of FlexVol volumes or LUNs of a Consistency Group. Optional on the ASA r2 platform. Mandatory for all other platforms.


|luns
|link:#luns[luns]
a|Optional property for a SnapMirror endpoint. Specifies the list of source LUNs and optionally list of destination LUNs during SnapMirror Consistency Group LUN restore operation.


|path
|string
a|ONTAP FlexVol/FlexGroup - svm1:volume1
ONTAP SVM               - svm1:
ONTAP Consistency Group - svm1:/cg/cg_name
ONTAP S3                - svm1:/bucket/bucket1
NON-ONTAP               - objstore1:/objstore

* example: svm1:volume1
* Introduced in: 9.14
* x-nullable: true


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#svmdr_volumes]
[.api-collapsible-fifth-title]
svmdr_volumes

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|===


[#transfer]
[.api-collapsible-fifth-title]
transfer

Basic information on the current transfer or the last transfer if there is no active transfer at the time of the request.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|bytes_transferred
|integer
a|Total bytes transferred in the current or last successful transfer.


|end_time
|string
a|End time of the last transfer.


|last_updated_time
|string
a|Last updated time of the bytes transferred in the current transfer.


|state
|string
a|

|total_duration
|string
a|Elapsed time to transfer all snapshots for the last successful transfer.


|type
|string
a|Specifies the operation type of the current transfer on the relationship. The _initialize_ transfer occurs when the relationship state changes from "uninitialized" to "snapmirrored" or "in_sync". The _update_ transfer occurs when snapshots are being transferred from the source endpoint to the destination endpoint as part of a scheduled or manual update. The _resync_ transfer occurs when the relationship state changes from "broken_off" to "snapmirrored" or "in_sync". The _restore_ transfer occurs when a snapshot is being restored from a destination endpoint to another endpoint.


|uuid
|string
a|Transfer UUID. This property is applicable only for active transfers.


|===


[#transfer_schedule]
[.api-collapsible-fifth-title]
transfer_schedule

Schedule used to update asynchronous relationships. This "transfer_schedule" overrides the "transfer_schedule" set on the SnapMirror relationship's policy. To remove the "transfer_schedule", set its value to null (no-quotes). Only cron schedules are supported for SnapMirror.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_error]
[.api-collapsible-fifth-title]
snapmirror_error

SnapMirror error


[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[string]
a|Arguments present in the error message encountered.


|code
|string
a|Error code


|message
|string
a|Error message


|===


[#snapmirror_relationship]
[.api-collapsible-fifth-title]
snapmirror_relationship

SnapMirror relationship information. The SnapMirror relationship can be either "async" or "sync" based on the type of SnapMirror policy associated with the relationship. The source and destination endpoints of a SnapMirror relationship must be of the same type, for example, if the source endpoint is a FlexVol volume then the destination endpoint must be a FlexVol volume.
The SnapMirror policy type "async" can be used when the SnapMirror relationship has FlexVol volume or FlexGroup volume or SVM as the endpoint. The SnapMirror policy type "sync" can be used when the SnapMirror relationship has FlexVol volume as the endpoint. The SnapMirror policy type "sync" with "sync_type" as "automated_failover" can be used when the SnapMirror relationship has Consistency Group as the endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|backoff_level
|string
a|Specifies the SnapMirror backoff level due to Client Ops for FlexVol SnapMirror relationships.


|consistency_group_failover
|link:#snapmirror_consistency_group_failover[snapmirror_consistency_group_failover]
a|SnapMirror Consistency Group failover information. The SnapMirror Consistency Group failover can be a planned or an unplanned operation. Only active SnapMirror Consistency Group failover operation progress can be monitored using this object. In case of an error during the failover operation, the property "consistency_group_failover.error" holds the reason for the error. ONTAP automatically retries any failed SnapMirror Consistency Group failover operation.

* Introduced in: 9.8
* readOnly: 1


|destination
|link:#snapmirror_endpoint[snapmirror_endpoint]
a|Endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to create the destination SVM endpoint or to establish an SVM DR relationship must have the property "cluster" populated with the remote cluster details. A POST request to create the destination FlexVol volume, FlexGroup volume, Consistency Group, ONTAP S3 bucket and NON-ONTAP object-store endpoints can optionally specify the "cluster" property when the source SVM and the destination SVM are peered. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.

* Introduced in: 9.6


|exported_snapshot
|string
a|Snapshot exported to clients on destination.


|group_type
|string
a|Specifies the group type of the top level SnapMirror relationship. The volume relationships are shown as _none_, the SVMDR relationships are shown as _svm_dr_, the Consistency Group relationships are shown as _consistency_group_, and the FlexGroup volume relationships are shown as _flexgroup_.


|healthy
|boolean
a|Is the relationship healthy?


|identity_preservation
|string
a|Specifies which configuration of the source SVM is replicated to the destination SVM. This property is applicable only for SVM data protection with "async" policy type. This "identity_preservation" overrides the "identity_preservation" set on the SnapMirror relationship's policy.


|io_serving_copy
|string
a|Specifies the sites serving I/O for the SnapMirror active sync relationship.


|lag_time
|string
a|Time since the exported snapshot was created.


|last_transfer_network_compression_ratio
|string
a|Specifies the compression ratio achieved for the data sent over the wire with network compression enabled for the last successful transfer.


|last_transfer_type
|string
a|Specifies the operation type of the last transfer that occurred on the relationship. The _initialize_ transfer occurs when the relationship state changes from uninitialized to snapmirrored or in_sync. The _update_ transfer occurs when the snapshots are transferred from the source endpoint to the destination endpoint as part of scheduled or manual update. The _resync_ transfer occurs when the relationship state changes from broken_off to snapmirrored or in_sync. The _restore_ transfer occurs when the snapshot is restored from a destination endpoint to another endpoint.


|master_bias_activated_site
|string
a|Specifies the Master Bias Activated Site for the SnapMirror active sync relationship.


|policy
|link:#policy[policy]
a|Basic policy information of the relationship.


|preferred_site
|string
a|Specifies the Primary Site of the SnapMirror active sync relationship.


|preserve
|boolean
a|Set to true on resync to preserve snapshots on the destination that are newer than the latest common snapshot. This property is applicable only for relationships with FlexVol volume or FlexGroup volume endpoints and when the PATCH state is being changed to "snapmirrored".


|quick_resync
|boolean
a|Set to true to reduce resync time by not preserving storage efficiency. This property is applicable only for relationships with FlexVol volume endpoints and SVMDR relationships when the PATCH state is being changed to "snapmirrored".


|recover_after_break
|boolean
a|Set to true to recover from a failed SnapMirror break operation on a FlexGroup volume relationship. This restores all destination FlexGroup constituent volumes to the latest snapshot, and any writes to the read-write constituents are lost. This property is applicable only for SnapMirror relationships with FlexGroup volume endpoints and when the PATCH state is being changed to "broken_off".


|restore
|boolean
a|Set to true to create a relationship for restore. To trigger restore-transfer, use transfers POST on the restore relationship. SnapMirror relationships with the policy type "async" can be restored. SnapMirror relationships with the policy type "sync" cannot be restored.


|restore_to_snapshot
|string
a|Specifies the snapshot to restore to on the destination during the break operation. This property is applicable only for SnapMirror relationships with FlexVol volume endpoints and when the PATCH state is being changed to "broken_off".


|source
|link:#snapmirror_source_endpoint[snapmirror_source_endpoint]
a|Source endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.


|state
|string
a|State of the relationship.
To initialize the relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".
To break the relationship, PATCH the state to "broken_off" for relationships with a policy of type "async" or "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" cannot be "broken_off".
To resync the relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" can be in "broken_off" state due to a failed attempt of SnapMirror failover.
To pause the relationship, suspending further transfers, PATCH the state to "paused" for relationships with a policy of type "async" or "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" cannot be "paused".
To resume transfers for a paused relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".
The entries "in_sync", "out_of_sync", "synchronizing", "expanding", and "shrinking" are only applicable to relationships with a policy of type "sync". A PATCH call on the state change only triggers the transition to the specified state. You must poll on the "state", "healthy" and "unhealthy_reason" properties using a GET request to determine if the transition is successful. To automatically initialize the relationship when specifying "create_destination" property, set the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".


|svmdr_volumes
|array[link:#svmdr_volumes[svmdr_volumes]]
a|Specifies the list of constituent FlexVol volumes and FlexGroup volumes for an SVM DR SnapMirror relationship. FlexGroup constituents are not considered.


|throttle
|integer
a|Throttle, in KBs per second. This "throttle" overrides the "throttle" set on the SnapMirror relationship's policy. If neither of these are set, defaults to 0, which is interpreted as unlimited.


|total_transfer_bytes
|integer
a|Cumulative bytes transferred for the relationship.


|total_transfer_duration
|string
a|Indicates the cumulative duration of all transfers since the last aggregate relocation, takeover/giveback, or metrocluster switchover/switchback involving the node that hosts the relationship.


|transfer
|link:#transfer[transfer]
a|Basic information on the current transfer or the last transfer if there is no active transfer at the time of the request.


|transfer_schedule
|link:#transfer_schedule[transfer_schedule]
a|Schedule used to update asynchronous relationships. This "transfer_schedule" overrides the "transfer_schedule" set on the SnapMirror relationship's policy. To remove the "transfer_schedule", set its value to null (no-quotes). Only cron schedules are supported for SnapMirror.


|unhealthy_reason
|array[link:#snapmirror_error[snapmirror_error]]
a|Reason the relationship is not healthy. It is a concatenation of up to four levels of error messages.


|uuid
|string
a|Unique identifier of the SnapMirror relationship.


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
