---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-nfs-services-metrics.html'
summary: 'Retrieve NFS protocol historical performance metrics'
---

= Retrieve NFS protocol historical performance metrics

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/nfs/services/{svm.uuid}/metrics`#

*Introduced In:* 9.7

Retrieves historical performance metrics for the NFS protocol of an SVM.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|v3.throughput.write
|integer
|query
|False
a|Filter by v3.throughput.write


|v3.throughput.total
|integer
|query
|False
a|Filter by v3.throughput.total


|v3.throughput.read
|integer
|query
|False
a|Filter by v3.throughput.read


|v3.iops.read
|integer
|query
|False
a|Filter by v3.iops.read


|v3.iops.other
|integer
|query
|False
a|Filter by v3.iops.other


|v3.iops.total
|integer
|query
|False
a|Filter by v3.iops.total


|v3.iops.write
|integer
|query
|False
a|Filter by v3.iops.write


|v3.duration
|string
|query
|False
a|Filter by v3.duration


|v3.latency.read
|integer
|query
|False
a|Filter by v3.latency.read


|v3.latency.other
|integer
|query
|False
a|Filter by v3.latency.other


|v3.latency.total
|integer
|query
|False
a|Filter by v3.latency.total


|v3.latency.write
|integer
|query
|False
a|Filter by v3.latency.write


|v3.status
|string
|query
|False
a|Filter by v3.status


|v4.duration
|string
|query
|False
a|Filter by v4.duration

* Introduced in: 9.8


|v4.latency.read
|integer
|query
|False
a|Filter by v4.latency.read

* Introduced in: 9.8


|v4.latency.other
|integer
|query
|False
a|Filter by v4.latency.other

* Introduced in: 9.8


|v4.latency.total
|integer
|query
|False
a|Filter by v4.latency.total

* Introduced in: 9.8


|v4.latency.write
|integer
|query
|False
a|Filter by v4.latency.write

* Introduced in: 9.8


|v4.status
|string
|query
|False
a|Filter by v4.status

* Introduced in: 9.8


|v4.throughput.write
|integer
|query
|False
a|Filter by v4.throughput.write

* Introduced in: 9.8


|v4.throughput.total
|integer
|query
|False
a|Filter by v4.throughput.total

* Introduced in: 9.8


|v4.throughput.read
|integer
|query
|False
a|Filter by v4.throughput.read

* Introduced in: 9.8


|v4.iops.read
|integer
|query
|False
a|Filter by v4.iops.read

* Introduced in: 9.8


|v4.iops.other
|integer
|query
|False
a|Filter by v4.iops.other

* Introduced in: 9.8


|v4.iops.total
|integer
|query
|False
a|Filter by v4.iops.total

* Introduced in: 9.8


|v4.iops.write
|integer
|query
|False
a|Filter by v4.iops.write

* Introduced in: 9.8


|timestamp
|string
|query
|False
a|Filter by timestamp


|v41.latency.read
|integer
|query
|False
a|Filter by v41.latency.read

* Introduced in: 9.8


|v41.latency.other
|integer
|query
|False
a|Filter by v41.latency.other

* Introduced in: 9.8


|v41.latency.total
|integer
|query
|False
a|Filter by v41.latency.total

* Introduced in: 9.8


|v41.latency.write
|integer
|query
|False
a|Filter by v41.latency.write

* Introduced in: 9.8


|v41.duration
|string
|query
|False
a|Filter by v41.duration

* Introduced in: 9.8


|v41.status
|string
|query
|False
a|Filter by v41.status

* Introduced in: 9.8


|v41.iops.read
|integer
|query
|False
a|Filter by v41.iops.read

* Introduced in: 9.8


|v41.iops.other
|integer
|query
|False
a|Filter by v41.iops.other

* Introduced in: 9.8


|v41.iops.total
|integer
|query
|False
a|Filter by v41.iops.total

* Introduced in: 9.8


|v41.iops.write
|integer
|query
|False
a|Filter by v41.iops.write

* Introduced in: 9.8


|v41.throughput.write
|integer
|query
|False
a|Filter by v41.throughput.write

* Introduced in: 9.8


|v41.throughput.total
|integer
|query
|False
a|Filter by v41.throughput.total

* Introduced in: 9.8


|v41.throughput.read
|integer
|query
|False
a|Filter by v41.throughput.read

* Introduced in: 9.8


|svm.uuid
|string
|path
|True
a|Unique identifier of the SVM.


|interval
|string
|query
|False
a|The time range for the data. Examples can be 1h, 1d, 1m, 1w, 1y.
The period for each time range is as follows:

* 1h: Metrics over the most recent hour sampled over 15 seconds.
* 1d: Metrics over the most recent day sampled over 5 minutes.
* 1w: Metrics over the most recent week sampled over 30 minutes.
* 1m: Metrics over the most recent month sampled over 2 hours.
* 1y: Metrics over the most recent year sampled over a day.
* Default value: 1
* enum: ["1h", "1d", "1w", "1m", "1y"]


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#records[records]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "v3": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "duration": "PT15S",
        "iops": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "latency": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "status": "ok",
        "throughput": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "timestamp": "2017-01-25 11:20:13 +0000"
      },
      "v4": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "duration": "PT15S",
        "iops": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "latency": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "status": "ok",
        "throughput": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "timestamp": "2017-01-25 11:20:13 +0000"
      },
      "v41": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "duration": "PT15S",
        "iops": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "latency": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "status": "ok",
        "throughput": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "timestamp": "2017-01-25 11:20:13 +0000"
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#iops]
[.api-collapsible-fifth-title]
iops

The rate of I/O operations observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#latency]
[.api-collapsible-fifth-title]
latency

The round trip latency in microseconds observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#throughput]
[.api-collapsible-fifth-title]
throughput

The rate of throughput bytes per second observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#v3]
[.api-collapsible-fifth-title]
v3

The NFSv3 operations


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|iops
|link:#iops[iops]
a|The rate of I/O operations observed at the storage object.


|latency
|link:#latency[latency]
a|The round trip latency in microseconds observed at the storage object.


|status
|string
a|Any errors associated with the sample. For example, if the aggregation of data over multiple nodes fails then any of the partial errors might be returned, "ok" on success, or "error" on any internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the storage object.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#v4]
[.api-collapsible-fifth-title]
v4

The NFSv4 operations


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|iops
|link:#iops[iops]
a|The rate of I/O operations observed at the storage object.


|latency
|link:#latency[latency]
a|The round trip latency in microseconds observed at the storage object.


|status
|string
a|Any errors associated with the sample. For example, if the aggregation of data over multiple nodes fails then any of the partial errors might be returned, "ok" on success, or "error" on any internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the storage object.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#v41]
[.api-collapsible-fifth-title]
v41

The NFSv4.1 operations


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|iops
|link:#iops[iops]
a|The rate of I/O operations observed at the storage object.


|latency
|link:#latency[latency]
a|The round trip latency in microseconds observed at the storage object.


|status
|string
a|Any errors associated with the sample. For example, if the aggregation of data over multiple nodes fails then any of the partial errors might be returned, "ok" on success, or "error" on any internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the storage object.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#records]
[.api-collapsible-fifth-title]
records

Historical performance numbers, such as IOPS latency and throughput, for SVM-NFS protocol.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|v3
|link:#v3[v3]
a|The NFSv3 operations


|v4
|link:#v4[v4]
a|The NFSv4 operations


|v41
|link:#v41[v41]
a|The NFSv4.1 operations


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
