---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-cluster-metrocluster-diagnostics.html'
summary: 'Retrieve diagnostic operation results for a MetroCluster configuration'
---

= Retrieve diagnostic operation results for a MetroCluster configuration

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/cluster/metrocluster/diagnostics`#

*Introduced In:* 9.8

Retrieves the results of a completed diagnostic operation for the MetroCluster configuration.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregate
|link:#aggregate[aggregate]
a|

|cluster
|link:#cluster[cluster]
a|

|config-replication
|link:#config-replication[config-replication]
a|

|connection
|link:#connection[connection]
a|

|interface
|link:#interface[interface]
a|

|node
|link:#node[node]
a|

|volume
|link:#volume[volume]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "aggregate": {
    "details": [
      {
        "aggregate": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "aggr1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "checks": [
          {
            "additional_info": {
              "code": "string",
              "message": "string"
            },
            "name": "mirror_status",
            "result": "string"
          }
        ],
        "cluster": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "cluster1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "node": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "node1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "timestamp": "2016-03-10 14:35:16 -0800",
        "volume": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "volume1",
          "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
        }
      }
    ],
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10 14:35:16 -0800"
  },
  "cluster": {
    "details": [
      {
        "aggregate": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "aggr1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "checks": [
          {
            "additional_info": {
              "code": "string",
              "message": "string"
            },
            "name": "mirror_status",
            "result": "string"
          }
        ],
        "cluster": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "cluster1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "node": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "node1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "timestamp": "2016-03-10 14:35:16 -0800",
        "volume": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "volume1",
          "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
        }
      }
    ],
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10 14:35:16 -0800"
  },
  "config-replication": {
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-14 14:35:16 -0800"
  },
  "connection": {
    "details": [
      {
        "cluster": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "cluster1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "connections": [
          {
            "destination_address": "string",
            "partner": {
              "node": {
                "_links": {
                  "self": {
                    "href": "/api/resourcelink"
                  }
                },
                "name": "node1",
                "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
              },
              "type": "string"
            },
            "port": "string",
            "result": "string",
            "source_address": "string",
            "state": "string"
          }
        ],
        "node": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "node1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      }
    ],
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10 14:35:16 -0800"
  },
  "interface": {
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10 14:35:16 -0800"
  },
  "node": {
    "details": [
      {
        "aggregate": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "aggr1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "checks": [
          {
            "additional_info": {
              "code": "string",
              "message": "string"
            },
            "name": "mirror_status",
            "result": "string"
          }
        ],
        "cluster": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "cluster1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "node": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "node1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "timestamp": "2016-03-10 14:35:16 -0800",
        "volume": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "volume1",
          "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
        }
      }
    ],
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10 14:35:16 -0800"
  },
  "volume": {
    "details": [
      {
        "aggregate": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "aggr1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "checks": [
          {
            "additional_info": {
              "code": "string",
              "message": "string"
            },
            "name": "mirror_status",
            "result": "string"
          }
        ],
        "cluster": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "cluster1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "node": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "node1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "timestamp": "2016-03-10 14:35:16 -0800",
        "volume": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "volume1",
          "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
        }
      }
    ],
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10 14:35:16 -0800"
  }
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 2425734
| An internal error occurred. Wait a few minutes, and try the operation again. For further assistance, contact technical support.

| 2426405
| MetroCluster is not configured in cluster "cluster". Run "metrocluster show" to verify both the local and the remote clusters are configured as MetroCluster, and then try the command again.

| 2432856
| MetroCluster diagnostics result is not available. Use the REST API GET method on "/api/cluster/metrocluster/operations?type=check&fields=*" for more information.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#aggregate]
[.api-collapsible-fifth-title]
aggregate

Aggregate


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#additional_info]
[.api-collapsible-fifth-title]
additional_info

Additional information or recovery steps to take on this component.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#metrocluster_diag_check]
[.api-collapsible-fifth-title]
metrocluster_diag_check

Generic object which can be used for various components which holds details of the checks of a component.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|additional_info
|link:#additional_info[additional_info]
a|Additional information or recovery steps to take on this component.


|name
|string
a|Name of type of diagnostic operation run for the component.


|result
|string
a|Result of the diagnostic operation on this component.


|===


[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the volume. This field cannot be specified in a PATCH method.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6
* x-nullable: true


|===


[#metrocluster_diag_details]
[.api-collapsible-fifth-title]
metrocluster_diag_details

[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregate
|link:#aggregate[aggregate]
a|Aggregate


|checks
|array[link:#metrocluster_diag_check[metrocluster_diag_check]]
a|Collection of MetroCluster checks done for component.


|cluster
|link:#cluster[cluster]
a|

|node
|link:#node[node]
a|

|timestamp
|string
a|Time check was done.


|volume
|link:#volume[volume]
a|

|===


[#summary]
[.api-collapsible-fifth-title]
summary

Additional information or recovery steps to take.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#aggregate]
[.api-collapsible-fifth-title]
aggregate

[cols=3*,options=header]
|===
|Name
|Type
|Description

|details
|array[link:#metrocluster_diag_details[metrocluster_diag_details]]
a|Display details of the MetroCluster check for aggregates.


|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|details
|array[link:#metrocluster_diag_details[metrocluster_diag_details]]
a|Display details of the MetroCluster check for clusters.


|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#config-replication]
[.api-collapsible-fifth-title]
config-replication

[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#partner]
[.api-collapsible-fifth-title]
partner

[cols=3*,options=header]
|===
|Name
|Type
|Description

|node
|link:#node[node]
a|

|type
|string
a|

|===


[#metrocluster_diag_connection]
[.api-collapsible-fifth-title]
metrocluster_diag_connection

[cols=3*,options=header]
|===
|Name
|Type
|Description

|destination_address
|string
a|

|partner
|link:#partner[partner]
a|

|port
|string
a|

|result
|string
a|Result of the diagnostic operation on this component.


|source_address
|string
a|

|state
|string
a|

|===


[#metrocluster_diag_connection_details]
[.api-collapsible-fifth-title]
metrocluster_diag_connection_details

[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster[cluster]
a|

|connections
|array[link:#metrocluster_diag_connection[metrocluster_diag_connection]]
a|

|node
|link:#node[node]
a|

|===


[#connection]
[.api-collapsible-fifth-title]
connection

[cols=3*,options=header]
|===
|Name
|Type
|Description

|details
|array[link:#metrocluster_diag_connection_details[metrocluster_diag_connection_details]]
a|Display details of the MetroCluster check for connections.


|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#interface]
[.api-collapsible-fifth-title]
interface

[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|details
|array[link:#metrocluster_diag_details[metrocluster_diag_details]]
a|Displays details of the MetroCluster check for nodes.


|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|details
|array[link:#metrocluster_diag_details[metrocluster_diag_details]]
a|Display details of the MetroCluster check for volumes.


|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
