---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-network-ip-bgp-peer-groups.html'
summary: 'Retrieve all BGP peer group details for VIP'
---

= Retrieve all BGP peer group details for VIP

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/network/ip/bgp/peer-groups`#

*Introduced In:* 9.7

Retrieves the details of all BGP peer groups for VIP.

== Related ONTAP Commands

* `network bgp peer-group show`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|ipspace.name
|string
|query
|False
a|Filter by ipspace.name


|ipspace.uuid
|string
|query
|False
a|Filter by ipspace.uuid


|peer.is_next_hop
|boolean
|query
|False
a|Filter by peer.is_next_hop

* Introduced in: 9.9


|peer.md5_secret
|string
|query
|False
a|Filter by peer.md5_secret

* Introduced in: 9.16
* maxLength: 79
* minLength: 1


|peer.asn
|integer
|query
|False
a|Filter by peer.asn


|peer.md5_enabled
|boolean
|query
|False
a|Filter by peer.md5_enabled

* Introduced in: 9.16


|peer.address
|string
|query
|False
a|Filter by peer.address


|state
|string
|query
|False
a|Filter by state


|uuid
|string
|query
|False
a|Filter by uuid


|local.port.name
|string
|query
|False
a|Filter by local.port.name


|local.port.uuid
|string
|query
|False
a|Filter by local.port.uuid


|local.port.node.name
|string
|query
|False
a|Filter by local.port.node.name


|local.interface.uuid
|string
|query
|False
a|Filter by local.interface.uuid


|local.interface.name
|string
|query
|False
a|Filter by local.interface.name


|local.interface.ip.address
|string
|query
|False
a|Filter by local.interface.ip.address


|name
|string
|query
|False
a|Filter by name


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#bgp_peer_group[bgp_peer_group]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "ipspace": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "Default",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "local": {
        "interface": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "ip": {
            "address": "10.10.10.7"
          },
          "name": "lif1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "port": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "e1b",
          "node": {
            "name": "node1"
          },
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      },
      "name": "bgpv4peer",
      "peer": {
        "address": "10.10.10.7",
        "md5_enabled": 1,
        "md5_secret": "SECRET_WORD"
      },
      "state": "string",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#ipspace]
[.api-collapsible-fifth-title]
ipspace

Either the UUID or name is supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|IPspace name


|uuid
|string
a|IPspace UUID


|===


[#ip]
[.api-collapsible-fifth-title]
ip

IP information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|===


[#interface]
[.api-collapsible-fifth-title]
interface

A network interface. Either UUID or name may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|ip
|link:#ip[ip]
a|IP information


|name
|string
a|The name of the interface. If only the name is provided, the SVM scope
must be provided by the object this object is embedded in.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#ip]
[.api-collapsible-fifth-title]
ip

IP information to create a new interface.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|netmask
|string
a|Input as netmask length (16) or IPv4 mask (255.255.0.0). For IPv6, the default value is 64 with a valid range of 1 to 127. Output is always the netmask length.


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of node on which the port is located.


|===


[#port]
[.api-collapsible-fifth-title]
port

Port UUID along with readable names. Either the UUID or both names may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|node
|link:#node[node]
a|

|uuid
|string
a|

|===


[#local]
[.api-collapsible-fifth-title]
local

Information describing the local interface that is being used to peer with a router using BGP. On a POST operation, an existing BGP interface is used by specifying the interface, or create a new one by specifying the port and IP address.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|interface
|link:#interface[interface]
a|A network interface. Either UUID or name may be supplied on input.


|port
|link:#port[port]
a|Port UUID along with readable names. Either the UUID or both names may be supplied on input.


|===


[#peer]
[.api-collapsible-fifth-title]
peer

Information describing the router to peer with


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|Peer router address


|asn
|integer
a|Autonomous system number of peer


|is_next_hop
|boolean
a|Use peer address as next hop.


|md5_enabled
|boolean
a|Enable or disable TCP MD5 signatures per RFC 2385.


|md5_secret
|string
a|The shared TCP MD5 secret key. This can either be given as a password or hexadecimal key.


|===


[#bgp_peer_group]
[.api-collapsible-fifth-title]
bgp_peer_group

A BGP peer group between a local network interface and a router, for the purpose of announcing VIP interface locations for SVMs in this IPspace.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ipspace
|link:#ipspace[ipspace]
a|Either the UUID or name is supplied on input.


|local
|link:#local[local]
a|Information describing the local interface that is being used to peer with a router using BGP. On a POST operation, an existing BGP interface is used by specifying the interface, or create a new one by specifying the port and IP address.


|name
|string
a|Name of the peer group


|peer
|link:#peer[peer]
a|Information describing the router to peer with


|state
|string
a|State of the peer group


|uuid
|string
a|UUID of the peer group


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
