---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-security-multi-admin-verify-requests-.html'
summary: 'Retrieve a multi-admin-verify request'
---

= Retrieve a multi-admin-verify request

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/security/multi-admin-verify/requests/{index}`#

*Introduced In:* 9.11

Retrieves a multi-admin-verify request.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|index
|string
|path
|True
a|

|fields
|array[string]
|query
|False
a|Specify the fields to return.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|approve_expiry_time
|string
a|

|approve_time
|string
a|

|approved_users
|array[string]
a|The users that have approved the request.


|comment
|string
a|Optional user-provided comment that is sent to the approval-group email indicating why the request was made.


|create_time
|string
a|

|execute_on_approval
|boolean
a|Specifies that the operation is executed automatically on final approval.


|execution_expiry_time
|string
a|

|index
|integer
a|Unique index that represents a request.


|operation
|string
a|The command to execute.


|owner
|link:#owner[owner]
a|The owner of the request. This can identify the cluster or an SVM.


|pending_approvers
|integer
a|The number of approvers remaining that are required to approve.


|permitted_users
|array[string]
a|List of users that can execute the operation once approved. If not set, any authorized user can perform the operation.


|potential_approvers
|array[string]
a|The users that are able to approve the request.


|query
|string
a|Identifies the specific entry upon which the user wants to operate.


|required_approvers
|integer
a|The number of required approvers, excluding the user that made the request.


|state
|string
a|The state of the request. PATCH supports approved and vetoed. The state only changes after setting to approved once no more approvers are required.


|user_requested
|string
a|The user that created the request. Automatically set by ONTAP.

* readOnly: 1
* Introduced in: 9.11
* x-nullable: true


|user_vetoed
|string
a|The user that vetoed the request.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "approve_expiry_time": "string",
  "approve_time": "string",
  "approved_users": [
    "string"
  ],
  "comment": "string",
  "create_time": "string",
  "execution_expiry_time": "string",
  "index": 0,
  "operation": "string",
  "owner": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "pending_approvers": 0,
  "permitted_users": [
    "string"
  ],
  "potential_approvers": [
    "string"
  ],
  "query": "string",
  "required_approvers": 0,
  "state": "string",
  "user_requested": "string",
  "user_vetoed": "string"
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#owner]
[.api-collapsible-fifth-title]
owner

The owner of the request. This can identify the cluster or an SVM.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
