---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-network-ethernet-ports.html'
summary: 'Retrieve ports'
---

= Retrieve ports

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/network/ethernet/ports`#

*Introduced In:* 9.6

Retrieves a collection of ports (physical, VLAN and LAG) for an entire cluster.

== Related ONTAP commands

* `network port show`
* `network port ifgrp show`
* `network port vlan show`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|rdma_protocols
|string
|query
|False
a|Filter by rdma_protocols

* Introduced in: 9.10


|flowcontrol_admin
|string
|query
|False
a|Filter by flowcontrol_admin

* Introduced in: 9.16


|lag.distribution_policy
|string
|query
|False
a|Filter by lag.distribution_policy


|lag.member_ports.name
|string
|query
|False
a|Filter by lag.member_ports.name


|lag.member_ports.uuid
|string
|query
|False
a|Filter by lag.member_ports.uuid


|lag.member_ports.node.name
|string
|query
|False
a|Filter by lag.member_ports.node.name


|lag.active_ports.name
|string
|query
|False
a|Filter by lag.active_ports.name


|lag.active_ports.uuid
|string
|query
|False
a|Filter by lag.active_ports.uuid


|lag.active_ports.node.name
|string
|query
|False
a|Filter by lag.active_ports.node.name


|lag.mode
|string
|query
|False
a|Filter by lag.mode


|uuid
|string
|query
|False
a|Filter by uuid


|mac_address
|string
|query
|False
a|Filter by mac_address


|mtu
|integer
|query
|False
a|Filter by mtu

* Min value: 68


|type
|string
|query
|False
a|Filter by type


|state
|string
|query
|False
a|Filter by state


|reachability
|string
|query
|False
a|Filter by reachability

* Introduced in: 9.8


|metric.timestamp
|string
|query
|False
a|Filter by metric.timestamp

* Introduced in: 9.8


|metric.status
|string
|query
|False
a|Filter by metric.status

* Introduced in: 9.8


|metric.duration
|string
|query
|False
a|Filter by metric.duration

* Introduced in: 9.8


|metric.throughput.write
|integer
|query
|False
a|Filter by metric.throughput.write

* Introduced in: 9.8


|metric.throughput.total
|integer
|query
|False
a|Filter by metric.throughput.total

* Introduced in: 9.8


|metric.throughput.read
|integer
|query
|False
a|Filter by metric.throughput.read

* Introduced in: 9.8


|statistics.device.receive_raw.errors
|integer
|query
|False
a|Filter by statistics.device.receive_raw.errors

* Introduced in: 9.8


|statistics.device.receive_raw.packets
|integer
|query
|False
a|Filter by statistics.device.receive_raw.packets

* Introduced in: 9.8


|statistics.device.receive_raw.discards
|integer
|query
|False
a|Filter by statistics.device.receive_raw.discards

* Introduced in: 9.8


|statistics.device.timestamp
|string
|query
|False
a|Filter by statistics.device.timestamp

* Introduced in: 9.8


|statistics.device.link_down_count_raw
|integer
|query
|False
a|Filter by statistics.device.link_down_count_raw

* Introduced in: 9.8


|statistics.device.transmit_raw.errors
|integer
|query
|False
a|Filter by statistics.device.transmit_raw.errors

* Introduced in: 9.8


|statistics.device.transmit_raw.packets
|integer
|query
|False
a|Filter by statistics.device.transmit_raw.packets

* Introduced in: 9.8


|statistics.device.transmit_raw.discards
|integer
|query
|False
a|Filter by statistics.device.transmit_raw.discards

* Introduced in: 9.8


|statistics.timestamp
|string
|query
|False
a|Filter by statistics.timestamp

* Introduced in: 9.8


|statistics.status
|string
|query
|False
a|Filter by statistics.status

* Introduced in: 9.8


|statistics.throughput_raw.write
|integer
|query
|False
a|Filter by statistics.throughput_raw.write

* Introduced in: 9.8


|statistics.throughput_raw.total
|integer
|query
|False
a|Filter by statistics.throughput_raw.total

* Introduced in: 9.8


|statistics.throughput_raw.read
|integer
|query
|False
a|Filter by statistics.throughput_raw.read

* Introduced in: 9.8


|node.name
|string
|query
|False
a|Filter by node.name


|node.uuid
|string
|query
|False
a|Filter by node.uuid


|pfc_queues_admin
|integer
|query
|False
a|Filter by pfc_queues_admin

* Introduced in: 9.16
* Min value: 0
* Max value: 7


|vlan.tag
|integer
|query
|False
a|Filter by vlan.tag

* Min value: 1
* Max value: 4094


|vlan.base_port.name
|string
|query
|False
a|Filter by vlan.base_port.name


|vlan.base_port.uuid
|string
|query
|False
a|Filter by vlan.base_port.uuid


|vlan.base_port.node.name
|string
|query
|False
a|Filter by vlan.base_port.node.name


|broadcast_domain.uuid
|string
|query
|False
a|Filter by broadcast_domain.uuid


|broadcast_domain.name
|string
|query
|False
a|Filter by broadcast_domain.name


|broadcast_domain.ipspace.name
|string
|query
|False
a|Filter by broadcast_domain.ipspace.name


|interface_count
|integer
|query
|False
a|Filter by interface_count

* Introduced in: 9.11


|reachable_broadcast_domains.uuid
|string
|query
|False
a|Filter by reachable_broadcast_domains.uuid

* Introduced in: 9.8


|reachable_broadcast_domains.name
|string
|query
|False
a|Filter by reachable_broadcast_domains.name

* Introduced in: 9.8


|reachable_broadcast_domains.ipspace.name
|string
|query
|False
a|Filter by reachable_broadcast_domains.ipspace.name

* Introduced in: 9.8


|enabled
|boolean
|query
|False
a|Filter by enabled


|speed
|integer
|query
|False
a|Filter by speed


|discovered_devices.name
|string
|query
|False
a|Filter by discovered_devices.name

* Introduced in: 9.11


|discovered_devices.remaining_hold_time
|integer
|query
|False
a|Filter by discovered_devices.remaining_hold_time

* Introduced in: 9.11


|discovered_devices.version
|string
|query
|False
a|Filter by discovered_devices.version

* Introduced in: 9.11


|discovered_devices.remote_port
|string
|query
|False
a|Filter by discovered_devices.remote_port

* Introduced in: 9.11


|discovered_devices.capabilities
|string
|query
|False
a|Filter by discovered_devices.capabilities

* Introduced in: 9.11


|discovered_devices.protocol
|string
|query
|False
a|Filter by discovered_devices.protocol

* Introduced in: 9.11


|discovered_devices.system_name
|string
|query
|False
a|Filter by discovered_devices.system_name

* Introduced in: 9.11


|discovered_devices.chassis_id
|string
|query
|False
a|Filter by discovered_devices.chassis_id

* Introduced in: 9.11


|discovered_devices.platform
|string
|query
|False
a|Filter by discovered_devices.platform

* Introduced in: 9.11


|discovered_devices.ip_addresses
|string
|query
|False
a|Filter by discovered_devices.ip_addresses

* Introduced in: 9.11


|name
|string
|query
|False
a|Filter by name


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Min value: 0
* Max value: 120
* Default value: 15


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#port[port]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "broadcast_domain": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "ipspace": {
          "name": "ipspace1"
        },
        "name": "bd1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "discovered_devices": [
        {
          "capabilities": [
            "router",
            "switch"
          ],
          "chassis_id": "string",
          "ip_addresses": [
            "192.168.100.24",
            "192.168.100.26"
          ],
          "name": "ETY-R1S4-510Q13.datacenter.example.com",
          "platform": "93180YC-EX",
          "protocol": "cdp",
          "remote_port": "FastEthernet0/12",
          "system_name": "string",
          "version": "Cisco Nexus Operating System (NX-OS) Software, Version 8.1"
        }
      ],
      "flowcontrol_admin": "string",
      "interface_count": 0,
      "lag": {
        "active_ports": [
          {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "e1b",
            "node": {
              "name": "node1"
            },
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          }
        ],
        "distribution_policy": "string",
        "member_ports": [
          {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "e1b",
            "node": {
              "name": "node1"
            },
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          }
        ],
        "mode": "string"
      },
      "mac_address": "01:02:03:04:05:06",
      "metric": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "duration": "PT15S",
        "status": "ok",
        "throughput": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "timestamp": "2017-01-25 11:20:13 +0000"
      },
      "mtu": 1500,
      "name": "e1b",
      "node": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "pfc_queues_admin": [
        "integer"
      ],
      "rdma_protocols": [
        "roce"
      ],
      "reachability": "ok",
      "reachable_broadcast_domains": [
        {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "ipspace": {
            "name": "ipspace1"
          },
          "name": "bd1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      ],
      "speed": 1000,
      "state": "string",
      "statistics": {
        "device": {
          "link_down_count_raw": 3,
          "receive_raw": {
            "discards": 100,
            "errors": 200,
            "packets": 500
          },
          "timestamp": "2017-01-25 11:20:13 +0000",
          "transmit_raw": {
            "discards": 100,
            "errors": 200,
            "packets": 500
          }
        },
        "status": "ok",
        "throughput_raw": {
          "read": 200,
          "total": 1000,
          "write": 100
        },
        "timestamp": "2017-01-25 11:20:13 +0000"
      },
      "type": "string",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412",
      "vlan": {
        "base_port": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "e1b",
          "node": {
            "name": "node1"
          },
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "tag": 100
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#ipspace]
[.api-collapsible-fifth-title]
ipspace

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the broadcast domain's IPspace


|===


[#broadcast_domain]
[.api-collapsible-fifth-title]
broadcast_domain

Broadcast domain UUID along with a readable name. Either the UUID or both names may be provided on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|ipspace
|link:#ipspace[ipspace]
a|

|name
|string
a|Name of the broadcast domain, scoped to its IPspace


|uuid
|string
a|Broadcast domain UUID


|===


[#discovered_devices]
[.api-collapsible-fifth-title]
discovered_devices

[cols=3*,options=header]
|===
|Name
|Type
|Description

|capabilities
|array[string]
a|The list of the capabilities of the discovered device.


|chassis_id
|string
a|Identifier associated with this specific discovered device, useful for locating the device in a data center.


|ip_addresses
|array[string]
a|The IP addresses on the discovered device.


|name
|string
a|Name of the discovered device.


|platform
|string
a|Hardware platform of the discovered device.


|protocol
|string
a|The protocol used to identify the discovered device. This can have a value of CDP or LLDP.


|remaining_hold_time
|integer
a|The number of seconds until the discovered device entry expires and is removed.


|remote_port
|string
a|The name of the remote port on the discovered device. The format is dependent on the reporting device.


|system_name
|string
a|Additional name used to identify a specific piece of equipment.


|version
|string
a|The version of the software running on the discovered device.


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of node on which the port is located.


|===


[#active_ports]
[.api-collapsible-fifth-title]
active_ports

Port UUID along with readable names. Either the UUID or both names may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|node
|link:#node[node]
a|

|uuid
|string
a|

|===


[#member_ports]
[.api-collapsible-fifth-title]
member_ports

Port UUID along with readable names. Either the UUID or both names may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|node
|link:#node[node]
a|

|uuid
|string
a|

|===


[#lag]
[.api-collapsible-fifth-title]
lag

[cols=3*,options=header]
|===
|Name
|Type
|Description

|active_ports
|array[link:#active_ports[active_ports]]
a|Active ports of a LAG (ifgrp). (Some member ports may be inactive.)


|distribution_policy
|string
a|Policy for mapping flows to ports for outbound packets through a LAG (ifgrp).


|member_ports
|array[link:#member_ports[member_ports]]
a|Array of ports belonging to the LAG, regardless of their state.


|mode
|string
a|Determines how the ports interact with the switch.


|===


[#throughput]
[.api-collapsible-fifth-title]
throughput

The rate of throughput bytes per second observed at the interface.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#metric]
[.api-collapsible-fifth-title]
metric

The most recent sample of I/O metrics for the port.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the interface.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#reachable_broadcast_domains]
[.api-collapsible-fifth-title]
reachable_broadcast_domains

Broadcast domain UUID along with a readable name. Either the UUID or both names may be provided on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|ipspace
|link:#ipspace[ipspace]
a|

|name
|string
a|Name of the broadcast domain, scoped to its IPspace


|uuid
|string
a|Broadcast domain UUID


|===


[#receive_raw]
[.api-collapsible-fifth-title]
receive_raw

Packet receive counters for the Ethernet port.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|discards
|integer
a|Total number of discarded packets.


|errors
|integer
a|Number of packet errors.


|packets
|integer
a|Total packet count.


|===


[#transmit_raw]
[.api-collapsible-fifth-title]
transmit_raw

Packet transmit counters for the Ethernet port.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|discards
|integer
a|Total number of discarded packets.


|errors
|integer
a|Number of packet errors.


|packets
|integer
a|Total packet count.


|===


[#device]
[.api-collapsible-fifth-title]
device

Device-related counters for the port object. These counters are applicable at the lowest layer of the networking stack. These values can be used to calculate both transmit and receive packet and error rates by comparing two samples taken at different times and calculating the increase in counter value divided by the elapsed time between the two samples.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|link_down_count_raw
|integer
a|The number of link state changes from up to down seen on the device.


|receive_raw
|link:#receive_raw[receive_raw]
a|Packet receive counters for the Ethernet port.


|timestamp
|string
a|The timestamp when the device specific counters were collected.


|transmit_raw
|link:#transmit_raw[transmit_raw]
a|Packet transmit counters for the Ethernet port.


|===


[#throughput_raw]
[.api-collapsible-fifth-title]
throughput_raw

Throughput bytes observed at the port object. This can be used along with delta time to calculate the rate of throughput bytes per unit of time.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#statistics]
[.api-collapsible-fifth-title]
statistics

The real time I/O statistics for the port.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|device
|link:#device[device]
a|Device-related counters for the port object. These counters are applicable at the lowest layer of the networking stack. These values can be used to calculate both transmit and receive packet and error rates by comparing two samples taken at different times and calculating the increase in counter value divided by the elapsed time between the two samples.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput_raw
|link:#throughput_raw[throughput_raw]
a|Throughput bytes observed at the port object. This can be used along with delta time to calculate the rate of throughput bytes per unit of time.


|timestamp
|string
a|The timestamp of the throughput_raw performance data.


|===


[#base_port]
[.api-collapsible-fifth-title]
base_port

Port UUID along with readable names. Either the UUID or both names may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|node
|link:#node[node]
a|

|uuid
|string
a|

|===


[#vlan]
[.api-collapsible-fifth-title]
vlan

[cols=3*,options=header]
|===
|Name
|Type
|Description

|base_port
|link:#base_port[base_port]
a|Port UUID along with readable names. Either the UUID or both names may be supplied on input.


|tag
|integer
a|VLAN ID


|===


[#port]
[.api-collapsible-fifth-title]
port

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|broadcast_domain
|link:#broadcast_domain[broadcast_domain]
a|Broadcast domain UUID along with a readable name. Either the UUID or both names may be provided on input.


|discovered_devices
|array[link:#discovered_devices[discovered_devices]]
a|Discovered devices


|enabled
|boolean
a|

|flowcontrol_admin
|string
a|Requested flow control


|interface_count
|integer
a|Number of interfaces hosted. This field is only applicable for cluster administrators. No value is returned for SVM administrators. If the node hosting a port is not healthy no value will be returned.


|lag
|link:#lag[lag]
a|

|mac_address
|string
a|

|metric
|link:#metric[metric]
a|The most recent sample of I/O metrics for the port.


|mtu
|integer
a|MTU of the port in bytes. Set by broadcast domain.


|name
|string
a|Portname, such as e0a, e1b-100 (VLAN on Ethernet), a0c (LAG/ifgrp), a0d-200 (VLAN on LAG/ifgrp), e0a.pv1 (p-VLAN, in select environments only)


|node
|link:#node[node]
a|

|pfc_queues_admin
|array[integer]
a|List of PFC queues


|rdma_protocols
|array[string]
a|Supported RDMA offload protocols


|reachability
|string
a|Reachability status of the port. Enum value "ok" is the only acceptable value for a PATCH request to repair a port.


|reachable_broadcast_domains
|array[link:#reachable_broadcast_domains[reachable_broadcast_domains]]
a|Reachable broadcast domains.


|speed
|integer
a|Link speed in Mbps


|state
|string
a|Operational state of the port. The state is set to 'down' if the operational state of the port is down. The state is set to 'up' if the link state of the port is up and the port is healthy. The state is set to 'up' if the link state of the port is up and configured to ignore health status. The state is 'degraded' if the link state of the port is up, and the port is not healthy.


|statistics
|link:#statistics[statistics]
a|The real time I/O statistics for the port.


|type
|string
a|Type of physical or virtual port


|uuid
|string
a|Port UUID


|vlan
|link:#vlan[vlan]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
