---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-cifs-group-policies.html'
summary: 'Retrieve unapplied group policy objects for all SVMs'
---

= Retrieve unapplied group policy objects for all SVMs

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/cifs/group-policies`#

*Introduced In:* 9.12

Retrieves group policy objects that are yet to be applied for all SVMs.

== Related ONTAP commands

* `vserver cifs group-policy show-defined`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|registry_settings.branchcache.supported_hash_version
|string
|query
|False
a|Filter by registry_settings.branchcache.supported_hash_version


|registry_settings.branchcache.hash_publication_mode
|string
|query
|False
a|Filter by registry_settings.branchcache.hash_publication_mode


|registry_settings.refresh_time_random_offset
|string
|query
|False
a|Filter by registry_settings.refresh_time_random_offset


|registry_settings.refresh_time_interval
|string
|query
|False
a|Filter by registry_settings.refresh_time_interval


|name
|string
|query
|False
a|Filter by name

* minLength: 1


|svm.name
|string
|query
|False
a|Filter by svm.name


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|central_access_policy_settings
|string
|query
|False
a|Filter by central_access_policy_settings


|file_system_path
|string
|query
|False
a|Filter by file_system_path


|enabled
|boolean
|query
|False
a|Filter by enabled


|central_access_policy_staging_audit_type
|string
|query
|False
a|Filter by central_access_policy_staging_audit_type


|ldap_path
|string
|query
|False
a|Filter by ldap_path


|extensions
|string
|query
|False
a|Filter by extensions


|security_settings.event_audit_settings.object_access_type
|string
|query
|False
a|Filter by security_settings.event_audit_settings.object_access_type


|security_settings.event_audit_settings.logon_type
|string
|query
|False
a|Filter by security_settings.event_audit_settings.logon_type


|security_settings.restrict_anonymous.no_enumeration_of_sam_accounts
|boolean
|query
|False
a|Filter by security_settings.restrict_anonymous.no_enumeration_of_sam_accounts


|security_settings.restrict_anonymous.combined_restriction_for_anonymous_user
|string
|query
|False
a|Filter by security_settings.restrict_anonymous.combined_restriction_for_anonymous_user


|security_settings.restrict_anonymous.no_enumeration_of_sam_accounts_and_shares
|boolean
|query
|False
a|Filter by security_settings.restrict_anonymous.no_enumeration_of_sam_accounts_and_shares


|security_settings.restrict_anonymous.anonymous_access_to_shares_and_named_pipes_restricted
|boolean
|query
|False
a|Filter by security_settings.restrict_anonymous.anonymous_access_to_shares_and_named_pipes_restricted


|security_settings.files_or_folders
|string
|query
|False
a|Filter by security_settings.files_or_folders


|security_settings.registry_values.signing_required
|boolean
|query
|False
a|Filter by security_settings.registry_values.signing_required


|security_settings.privilege_rights.change_notify_users
|string
|query
|False
a|Filter by security_settings.privilege_rights.change_notify_users


|security_settings.privilege_rights.security_privilege_users
|string
|query
|False
a|Filter by security_settings.privilege_rights.security_privilege_users


|security_settings.privilege_rights.take_ownership_users
|string
|query
|False
a|Filter by security_settings.privilege_rights.take_ownership_users


|security_settings.restricted_groups
|string
|query
|False
a|Filter by security_settings.restricted_groups


|security_settings.kerberos.max_ticket_age
|string
|query
|False
a|Filter by security_settings.kerberos.max_ticket_age


|security_settings.kerberos.max_renew_age
|string
|query
|False
a|Filter by security_settings.kerberos.max_renew_age


|security_settings.kerberos.max_clock_skew
|string
|query
|False
a|Filter by security_settings.kerberos.max_clock_skew


|security_settings.event_log_settings.max_size
|integer
|query
|False
a|Filter by security_settings.event_log_settings.max_size


|security_settings.event_log_settings.retention_method
|string
|query
|False
a|Filter by security_settings.event_log_settings.retention_method


|link
|string
|query
|False
a|Filter by link


|version
|integer
|query
|False
a|Filter by version


|index
|integer
|query
|False
a|Filter by index


|uuid
|string
|query
|False
a|Filter by uuid


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of central access rules.


|records
|array[link:#policies_and_rules_to_be_applied[policies_and_rules_to_be_applied]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "to_be_applied": {
        "access_policies": [
          {
            "create_time": "2018-01-01 12:00:00 -0400",
            "description": "policy #1",
            "member_rules": [
              "r1",
              "r2"
            ],
            "name": "p1",
            "sid": "S-1-5-21-256008430-3394229847-3930036330-1001",
            "svm": {
              "_links": {
                "self": {
                  "href": "/api/resourcelink"
                }
              },
              "name": "svm1",
              "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
            },
            "update_time": "2018-01-01 12:00:00 -0400"
          }
        ],
        "access_rules": [
          {
            "create_time": "2018-01-01 12:00:00 -0400",
            "current_permission": "O:SYG:SYD:AR(A;;FA;;;WD)",
            "description": "rule #1",
            "name": "p1",
            "proposed_permission": "O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)",
            "resource_criteria": "department",
            "svm": {
              "_links": {
                "self": {
                  "href": "/api/resourcelink"
                }
              },
              "name": "svm1",
              "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
            },
            "update_time": "2018-01-01 12:00:00 -0400"
          }
        ],
        "objects": [
          {
            "central_access_policy_settings": [
              "p1",
              "p2"
            ],
            "central_access_policy_staging_audit_type": "none",
            "extensions": [
              "audit",
              "security"
            ],
            "file_system_path": "\\test.com\\SysVol\\test.com\\policies\\{42474212-3f9d-4489-ae01-6fcf4f805d4c}",
            "index": 1,
            "ldap_path": "cn={42474212-3f9d-4489-ae01-6fcf4f805d4c},cn=policies,cn=system,DC=TEST,DC=COM",
            "link": "domain",
            "name": "test_policy",
            "registry_settings": {
              "branchcache": {
                "hash_publication_mode": "disabled",
                "supported_hash_version": "version1"
              },
              "refresh_time_interval": "P15M",
              "refresh_time_random_offset": "P1D"
            },
            "security_settings": {
              "event_audit_settings": {
                "logon_type": "failure",
                "object_access_type": "failure"
              },
              "event_log_settings": {
                "max_size": 2048,
                "retention_method": "do_not_overwrite"
              },
              "files_or_folders": [
                "/vol1/home",
                "/vol1/dir1"
              ],
              "kerberos": {
                "max_clock_skew": "P15M",
                "max_renew_age": "P2D",
                "max_ticket_age": "P24H"
              },
              "privilege_rights": {
                "change_notify_users": [
                  "usr1",
                  "usr2"
                ],
                "security_privilege_users": [
                  "usr1",
                  "usr2"
                ],
                "take_ownership_users": [
                  "usr1",
                  "usr2"
                ]
              },
              "restrict_anonymous": {
                "combined_restriction_for_anonymous_user": "no_access"
              },
              "restricted_groups": [
                "test_grp1",
                "test_grp2"
              ]
            },
            "svm": {
              "_links": {
                "self": {
                  "href": "/api/resourcelink"
                }
              },
              "name": "svm1",
              "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
            },
            "uuid": "42474212-3f9d-4489-ae01-6fcf4f805d4c",
            "version": 7
          }
        ],
        "restricted_groups": [
          {
            "group_name": "test_group",
            "link": "domain",
            "members": [
              "DOMAIN/test_user",
              "DOMAIN/user2"
            ],
            "memberships": [
              "DOMAIN/AdministratorGrp",
              "DOMAIN/deptMark"
            ],
            "policy_name": "test_policy",
            "svm": {
              "_links": {
                "self": {
                  "href": "/api/resourcelink"
                }
              },
              "name": "svm1",
              "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
            },
            "version": 7
          }
        ]
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

Will not be populated for objects that are yet to be applied.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#group_policy_object_central_access_policy]
[.api-collapsible-fifth-title]
group_policy_object_central_access_policy

[cols=3*,options=header]
|===
|Name
|Type
|Description

|create_time
|string
a|Policy creation timestamp.


|description
|string
a|Description about the policy.


|member_rules
|array[string]
a|Names of all central access rules applied to members.


|name
|string
a|

|sid
|string
a|Security ID, unique identifier of the central policy.


|svm
|link:#svm[svm]
a|Will not be populated for objects that are yet to be applied.


|update_time
|string
a|Last policy modification timestamp.


|===


[#group_policy_object_central_access_rule]
[.api-collapsible-fifth-title]
group_policy_object_central_access_rule

[cols=3*,options=header]
|===
|Name
|Type
|Description

|create_time
|string
a|Policy creation timestamp.


|current_permission
|string
a|Effective security policy in security descriptor definition language format.


|description
|string
a|Description about the policy.


|name
|string
a|

|proposed_permission
|string
a|Proposed security policy in security descriptor definition language format.


|resource_criteria
|string
a|Criteria to scope resources for which access rules apply.


|svm
|link:#svm[svm]
a|Will not be populated for objects that are yet to be applied.


|update_time
|string
a|Last policy modification timestamp.


|===


[#group_policy_object_branchcache]
[.api-collapsible-fifth-title]
group_policy_object_branchcache

[cols=3*,options=header]
|===
|Name
|Type
|Description

|hash_publication_mode
|string
a|Hash publication mode.


|supported_hash_version
|string
a|Hash version.


|===


[#group_policy_object_registry_setting]
[.api-collapsible-fifth-title]
group_policy_object_registry_setting

[cols=3*,options=header]
|===
|Name
|Type
|Description

|branchcache
|link:#group_policy_object_branchcache[group_policy_object_branchcache]
a|

|refresh_time_interval
|string
a|Refresh time interval in ISO-8601 format.


|refresh_time_random_offset
|string
a|Random offset in ISO-8601 format.


|===


[#group_policy_object_event_audit]
[.api-collapsible-fifth-title]
group_policy_object_event_audit

[cols=3*,options=header]
|===
|Name
|Type
|Description

|logon_type
|string
a|Type of logon event to be audited.


|object_access_type
|string
a|Type of object access to be audited.


|===


[#group_policy_object_event_log]
[.api-collapsible-fifth-title]
group_policy_object_event_log

[cols=3*,options=header]
|===
|Name
|Type
|Description

|max_size
|integer
a|Maximum size of security log, in kilobytes.


|retention_method
|string
a|Audit log retention method.


|===


[#group_policy_object_kerberos]
[.api-collapsible-fifth-title]
group_policy_object_kerberos

[cols=3*,options=header]
|===
|Name
|Type
|Description

|max_clock_skew
|string
a|Kerberos clock skew in ISO-8601 format.


|max_renew_age
|string
a|Kerberos max renew age in ISO-8601 format.


|max_ticket_age
|string
a|Kerberos max ticket age in ISO-8601 format.


|===


[#group_policy_object_privilege_right]
[.api-collapsible-fifth-title]
group_policy_object_privilege_right

[cols=3*,options=header]
|===
|Name
|Type
|Description

|change_notify_users
|array[string]
a|Users with traversing bypass privileges.


|security_privilege_users
|array[string]
a|Users with security privileges.


|take_ownership_users
|array[string]
a|Users who can take ownership of securable objects.


|===


[#group_policy_object_registry_value]
[.api-collapsible-fifth-title]
group_policy_object_registry_value

[cols=3*,options=header]
|===
|Name
|Type
|Description

|signing_required
|boolean
a|SMB signing required.


|===


[#group_policy_object_restrict_anonymous]
[.api-collapsible-fifth-title]
group_policy_object_restrict_anonymous

[cols=3*,options=header]
|===
|Name
|Type
|Description

|anonymous_access_to_shares_and_named_pipes_restricted
|boolean
a|Restrict anonymous access to shares and named pipes.


|combined_restriction_for_anonymous_user
|string
a|Combined restriction for anonymous user.


|no_enumeration_of_sam_accounts
|boolean
a|No enumeration of SAM accounts.


|no_enumeration_of_sam_accounts_and_shares
|boolean
a|No enumeration of SAM accounts and shares.


|===


[#group_policy_object_security_setting]
[.api-collapsible-fifth-title]
group_policy_object_security_setting

[cols=3*,options=header]
|===
|Name
|Type
|Description

|event_audit_settings
|link:#group_policy_object_event_audit[group_policy_object_event_audit]
a|

|event_log_settings
|link:#group_policy_object_event_log[group_policy_object_event_log]
a|

|files_or_folders
|array[string]
a|Files/Directories for file security.


|kerberos
|link:#group_policy_object_kerberos[group_policy_object_kerberos]
a|

|privilege_rights
|link:#group_policy_object_privilege_right[group_policy_object_privilege_right]
a|

|registry_values
|link:#group_policy_object_registry_value[group_policy_object_registry_value]
a|

|restrict_anonymous
|link:#group_policy_object_restrict_anonymous[group_policy_object_restrict_anonymous]
a|

|restricted_groups
|array[string]
a|List of restricted groups.


|===


[#group_policy_object]
[.api-collapsible-fifth-title]
group_policy_object

[cols=3*,options=header]
|===
|Name
|Type
|Description

|central_access_policy_settings
|array[string]
a|List of central access policies.


|central_access_policy_staging_audit_type
|string
a|Types of events to be audited.


|enabled
|boolean
a|Specifies whether group policies are enabled for the SVM.


|extensions
|array[string]
a|List of extensions.


|file_system_path
|string
a|File system path.


|index
|integer
a|Group policy object index.


|ldap_path
|string
a|LDAP path to the GPO.


|link
|string
a|Link info.


|name
|string
a|

|registry_settings
|link:#group_policy_object_registry_setting[group_policy_object_registry_setting]
a|

|security_settings
|link:#group_policy_object_security_setting[group_policy_object_security_setting]
a|

|svm
|link:#svm[svm]
a|Will not be populated for objects that are yet to be applied.


|uuid
|string
a|Policy UUID.


|version
|integer
a|Group policy object version.


|===


[#group_policy_object_restricted_group]
[.api-collapsible-fifth-title]
group_policy_object_restricted_group

[cols=3*,options=header]
|===
|Name
|Type
|Description

|group_name
|string
a|

|link
|string
a|Link info.


|members
|array[string]
a|Members of the group.


|memberships
|array[string]
a|Group is member of Group/OU.


|policy_name
|string
a|

|svm
|link:#svm[svm]
a|Will not be populated for objects that are yet to be applied.


|version
|integer
a|Group policy object version.


|===


[#to_be_applied]
[.api-collapsible-fifth-title]
to_be_applied

[cols=3*,options=header]
|===
|Name
|Type
|Description

|access_policies
|array[link:#group_policy_object_central_access_policy[group_policy_object_central_access_policy]]
a|

|access_rules
|array[link:#group_policy_object_central_access_rule[group_policy_object_central_access_rule]]
a|

|objects
|array[link:#group_policy_object[group_policy_object]]
a|

|restricted_groups
|array[link:#group_policy_object_restricted_group[group_policy_object_restricted_group]]
a|

|===


[#policies_and_rules_to_be_applied]
[.api-collapsible-fifth-title]
policies_and_rules_to_be_applied

[cols=3*,options=header]
|===
|Name
|Type
|Description

|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|to_be_applied
|link:#to_be_applied[to_be_applied]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
