---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-support-auto-update-updates-.html'
summary: 'Retrieve the status of an update'
---

= Retrieve the status of an update

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/support/auto-update/updates/{uuid}`#

*Introduced In:* 9.10

Retrieves the status of an update.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|Update identifier


|fields
|array[string]
|query
|False
a|Specify the fields to return.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|action
|string
a|Action to be applied to the automatic update.


|content_category
|string
a|Category of the update


|content_type
|string
a|Image or package type.


|creation_time
|string
a|The date and time at which the update request was received.


|description
|string
a|Description of the update.


|end_time
|string
a|The date and time at which the update request processing ended.


|expiry_time
|string
a|The date and time at which the update request will expire.


|last_state_change_time
|string
a|The date and time at which the state of the update changed last.


|package_id
|string
a|Unique identifier provided by the back-end.


|percent_complete
|integer
a|Percentage of update completed


|remaining_time
|string
a|The time remaining for the update processing to complete in an ISO-8601 duration formatted string.


|schedule_time
|string
a|Date and time when an automatic update action is scheduled.
This field is required when the action field is set to "schedule".


|scheduled_time
|string
a|The date and time at which the update request is currently scheduled for.


|start_time
|string
a|The date and time at which the update request processing started.


|state
|string
a|Current state of the update.


|status
|link:#status[status]
a|Status of the update.

ONTAP Message Codes

Code -- Description

8650878 -- Get-url request to AutoSupport OnDemand Server failed.

131072105 -- Package installation successful.

131072106 -- Package installation failed.

131072107 -- Package installation is in progress.

131072108 -- An internal error occurred.

131072109 -- No errors found.

131072110 -- Failed to extract package.

131072111 -- Failed to create entry in status table.

131072209 -- Failed to download package.

131072210 -- Failed to obtain download links. Will be retried.

131072211 -- Installation cannot start because the following nodes are not up. Will be retried.

131072212 -- Automatic update cannot start. Will be retried.

131072213 -- Installation complete.

131072214 -- Installation in progress.

131072215 -- Scheduled to start.

131072301 -- Unable to create directory.

131072302 -- Update not required. It is already on the target firmware version.

131072303 -- Unable to move installable to installation location.

131072304 -- Successfully updated. All nodes already updated and skipped.

131072306 -- Firmware distribution starting.

131072307 -- Firmware distribution restarting.

131072308 -- Firmware distribution failed.

131072309 -- Firmware installation successful on node.

131072310 -- Firmware installable is corrupt on node.

131072311 -- Could not apply firmware update on nodes.

131072312 -- Firmware update operation failed.

131072313 -- Install failed to initiate on node.

131072314 -- Install initiated on node.

131072315 -- Install failed on node.

131072316 -- Update in progress on node.

131072317 -- Unexpected state occurred during firmware installation on node.

131072318 -- Successfully updated SP/BMC firmware.

131072319 -- Backup SP image is running. Firmware installation failed prematurely on node.

131072320 -- SP rebooted with an unexpected firmware version on node.

131072321 -- Waiting for shelf firmware to update.

131072322 -- Update complete.

131072323 -- Shelf update timed out.

131072324 -- Successfully updated shelves on nodes.

131072325 -- Waiting for disk firmware to update.

131072326 -- Disk update completed.

131072327 -- Disk update timed out.

131072328 -- Successfully updated disks on nodes.

131072329 -- Waiting for DQP firmware to update.

131072330 -- Successfully updated DQP on nodes.

131072331 -- DQP update timed out.

131072332 -- Failed to copy firmware.


|uuid
|string
a|Unique identifier for this update.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "self": {
      "self": {
        "href": "/api/resourcelink"
      }
    }
  },
  "action": "schedule_now",
  "content_category": "Firmware",
  "content_type": "disk_fw",
  "creation_time": "2020-12-01 09:12:23 +0000",
  "description": "disk_fw version 3.0",
  "end_time": "2020-12-01 09:12:23 +0000",
  "expiry_time": "2021-06-01 09:12:23 +0000",
  "last_state_change_time": "2020-12-01 09:12:23 +0000",
  "package_id": "572361f3-e769-439d-9c04-2ba48a08ff47",
  "percent_complete": 85,
  "remaining_time": "PT1H45M13S",
  "schedule_time": "2020-12-20 21:00:00 +0000",
  "scheduled_time": "2020-12-05 09:12:23 +0000",
  "start_time": "2020-12-01 09:12:23 +0000",
  "state": "pending_confirmation",
  "status": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist"
  },
  "uuid": "440ae2e4-fd8f-4225-9bee-94e2da3f9d8d"
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#self]
[.api-collapsible-fifth-title]
self

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#self[self]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#status]
[.api-collapsible-fifth-title]
status

Status of the update.
ONTAP Message Codes

|===
| Code | Description

| 8650878
| Get-url request to AutoSupport OnDemand Server failed.

| 131072105
| Package installation successful.

| 131072106
| Package installation failed.

| 131072107
| Package installation is in progress.

| 131072108
| An internal error occurred.

| 131072109
| No errors found.

| 131072110
| Failed to extract package.

| 131072111
| Failed to create entry in status table.

| 131072209
| Failed to download package.

| 131072210
| Failed to obtain download links. Will be retried.

| 131072211
| Installation cannot start because the following nodes are not up. Will be retried.

| 131072212
| Automatic update cannot start. Will be retried.

| 131072213
| Installation complete.

| 131072214
| Installation in progress.

| 131072215
| Scheduled to start.

| 131072301
| Unable to create directory.

| 131072302
| Update not required. It is already on the target firmware version.

| 131072303
| Unable to move installable to installation location.

| 131072304
| Successfully updated. All nodes already updated and skipped.

| 131072306
| Firmware distribution starting.

| 131072307
| Firmware distribution restarting.

| 131072308
| Firmware distribution failed.

| 131072309
| Firmware installation successful on node.

| 131072310
| Firmware installable is corrupt on node.

| 131072311
| Could not apply firmware update on nodes.

| 131072312
| Firmware update operation failed.

| 131072313
| Install failed to initiate on node.

| 131072314
| Install initiated on node.

| 131072315
| Install failed on node.

| 131072316
| Update in progress on node.

| 131072317
| Unexpected state occurred during firmware installation on node.

| 131072318
| Successfully updated SP/BMC firmware.

| 131072319
| Backup SP image is running. Firmware installation failed prematurely on node.

| 131072320
| SP rebooted with an unexpected firmware version on node.

| 131072321
| Waiting for shelf firmware to update.

| 131072322
| Update complete.

| 131072323
| Shelf update timed out.

| 131072324
| Successfully updated shelves on nodes.

| 131072325
| Waiting for disk firmware to update.

| 131072326
| Disk update completed.

| 131072327
| Disk update timed out.

| 131072328
| Successfully updated disks on nodes.

| 131072329
| Waiting for DQP firmware to update.

| 131072330
| Successfully updated DQP on nodes.

| 131072331
| DQP update timed out.

| 131072332
| Failed to copy firmware.
|===


[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
