---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-cluster-jobs.html'
summary: 'Retrieve recent asynchronous jobs'
---

= Retrieve recent asynchronous jobs

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/cluster/jobs`#

*Introduced In:* 9.6

Retrieves a list of recently running asynchronous jobs. After a job transitions to a failure or success state, it is deleted after a default time of 300 seconds.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|code
|integer
|query
|False
a|Filter by code


|end_time
|string
|query
|False
a|Filter by end_time


|message
|string
|query
|False
a|Filter by message


|uuid
|string
|query
|False
a|Filter by uuid


|svm.name
|string
|query
|False
a|Filter by svm.name

* Introduced in: 9.8


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid

* Introduced in: 9.8


|description
|string
|query
|False
a|Filter by description


|state
|string
|query
|False
a|Filter by state


|error.arguments.message
|string
|query
|False
a|Filter by error.arguments.message

* Introduced in: 9.9


|error.arguments.code
|string
|query
|False
a|Filter by error.arguments.code

* Introduced in: 9.9


|error.code
|string
|query
|False
a|Filter by error.code

* Introduced in: 9.9


|error.message
|string
|query
|False
a|Filter by error.message

* Introduced in: 9.9


|start_time
|string
|query
|False
a|Filter by start_time


|node.name
|string
|query
|False
a|Filter by node.name

* Introduced in: 9.11


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#job[job]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "code": 0,
      "description": "App Snapshot Job",
      "end_time": "string",
      "error": {
        "arguments": [
          {
            "code": "string",
            "message": "string"
          }
        ],
        "code": "4",
        "message": "entry doesn't exist"
      },
      "message": "Complete: Successful",
      "node": {
        "name": "string"
      },
      "start_time": "string",
      "state": "string",
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

The error that caused the job to fail. This property is only populated when the job fails and it matches the API response error structure used by all APIs. The message and code match the dedicated message and code properties once the job has failed.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|===


[#node]
[.api-collapsible-fifth-title]
node

The node where this job was run


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the node


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#job]
[.api-collapsible-fifth-title]
job

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|code
|integer
a|If the state indicates "failure", this is the final error code.


|description
|string
a|The description of the job to help identify it independent of the UUID.


|end_time
|string
a|The time the job ended.


|error
|link:#error[error]
a|The error that caused the job to fail. This property is only populated when the job fails and it matches the API response error structure used by all APIs. The message and code match the dedicated message and code properties once the job has failed.


|message
|string
a|A message corresponding to the state of the job providing additional details about the current state.


|node
|link:#node[node]
a|The node where this job was run


|start_time
|string
a|The time the job started.


|state
|string
a|The state of the job.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|uuid
|string
a|

|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
