---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-cluster-software.html'
summary: 'Retrieve the cluster software profile'
---

= Retrieve the cluster software profile

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/cluster/software`#

*Introduced In:* 9.6

Retrieves the software profile of a cluster.

== Related ONTAP commands

* `cluster image show`
* `cluster image show-update-progress`
* `system node image package show`

== Learn more

* link:cluster_software_endpoint_overview.html[DOC /cluster/software]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|fields
|array[string]
|query
|False
a|Specify the fields to return.


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|action
|string
a|User triggered action to apply to the install operation


|elapsed_duration
|integer
a|Elapsed time during the upgrade or validation operation


|estimated_duration
|integer
a|Overall estimated time for completion of the upgrade or validation operation.


|metrocluster
|link:#metrocluster[metrocluster]
a|

|nodes
|array[link:#software_node_reference[software_node_reference]]
a|List of nodes, active versions, and firmware update progressions.


|pending_version
|string
a|Version being installed on the system.

* example: ONTAP_X_1
* readOnly: 1
* Introduced in: 9.6
* x-nullable: true


|post_update_checks
|array[link:#software_validation_reference[software_validation_reference]]
a|List of failed post-update checks' warnings, errors, and advice.


|state
|string
a|Operational state of the upgrade


|status_details
|array[link:#software_status_details_reference[software_status_details_reference]]
a|Display status details.


|update_details
|array[link:#software_update_details_reference[software_update_details_reference]]
a|Display update progress details.


|validation_results
|array[link:#software_validation_reference[software_validation_reference]]
a|List of validation warnings, errors, and advice.


|version
|string
a|Version of ONTAP installed and currently active on the system. During PATCH, using the 'validate_only' parameter on the request executes pre-checks, but does not perform the full installation.

* example: ONTAP_X
* Introduced in: 9.6
* x-nullable: true


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "action": "pause",
  "elapsed_duration": 2140,
  "estimated_duration": 5220,
  "metrocluster": {
    "clusters": [
      {
        "elapsed_duration": 2140,
        "estimated_duration": 3480,
        "name": "cluster_A",
        "state": "in_progress"
      }
    ],
    "progress_details": {
      "message": "Switchover in progress"
    },
    "progress_summary": {
      "message": "MetroCluster updated successfully."
    }
  },
  "nodes": [
    {
      "firmware": {
        "cluster_fw_progress": [
          {
            "job": {
              "_links": {
                "self": {
                  "href": "/api/resourcelink"
                }
              },
              "uuid": "string"
            },
            "update_state": [
              {
                "attempts": 3,
                "code": 2228325,
                "message": "Cannot open local staging ZIP file disk_firmware.zip",
                "status": "string",
                "worker_node": {
                  "_links": {
                    "self": {
                      "href": "/api/resourcelink"
                    }
                  },
                  "name": "node1",
                  "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
                }
              }
            ],
            "update_type": "string",
            "zip_file_name": "disk_firmware.zip"
          }
        ],
        "disk": {
          "average_duration_per_disk": 120,
          "num_waiting_download": 0,
          "total_completion_estimate": 0,
          "update_status": "running"
        },
        "dqp": {
          "file_name": "qual_devices_v3",
          "record_count": {
            "alias": 200,
            "device": 29,
            "drive": 680,
            "system": 3
          },
          "revision": "20200117",
          "version": "3.18"
        },
        "shelf": {
          "in_progress_count": 2,
          "update_status": "running"
        },
        "sp_bmc": {
          "autoupdate": "",
          "end_time": "2020-05-17 20:00:00 +0000",
          "fw_type": "SP",
          "image": "primary",
          "is_current": 1,
          "last_update_state": "passed",
          "percent_done": 100,
          "running_version": "1.2.3.4",
          "start_time": "2020-05-17 20:00:00 +0000",
          "state": "installed"
        },
        "system_firmware": {
          "boot_media_bios_version": "13.16",
          "boot_media_loader_version": "8.2.0",
          "install_pending": "",
          "running_bios_version": "13.16",
          "running_loader_version": "8.2.0"
        }
      },
      "model": "AFF-A800",
      "name": "node1",
      "software_images": [
        {
          "package": "image.tgz"
        }
      ],
      "version": "ONTAP_X"
    }
  ],
  "pending_version": "ONTAP_X_1",
  "post_update_checks": [
    {
      "action": {
        "message": "Use NFS hard mounts, if possible."
      },
      "issue": {
        "message": "Cluster HA is not configured in the cluster."
      },
      "status": "warning",
      "update_check": "nfs_mounts"
    }
  ],
  "state": "completed",
  "status_details": [
    {
      "action": {
        "message": "string"
      },
      "end_time": "2019-02-02 19:00:00 +0000",
      "issue": {
        "code": 10551399,
        "message": "Image update complete"
      },
      "name": "initialize",
      "node": {
        "name": "node1"
      },
      "start_time": "2019-02-02 19:00:00 +0000",
      "state": "failed"
    }
  ],
  "update_details": [
    {
      "elapsed_duration": 2100,
      "estimated_duration": 4620,
      "node": {
        "name": "node1"
      },
      "phase": "Post-update checks",
      "state": "failed"
    }
  ],
  "validation_results": [
    {
      "action": {
        "message": "Use NFS hard mounts, if possible."
      },
      "issue": {
        "message": "Cluster HA is not configured in the cluster."
      },
      "status": "warning",
      "update_check": "nfs_mounts"
    }
  ],
  "version": "ONTAP_X"
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 1048576
| Error initializing software image information.

| 1048577
| Software image information not initialized.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#software_mcc_reference]
[.api-collapsible-fifth-title]
software_mcc_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|elapsed_duration
|integer
a|Elapsed duration of update time (in seconds) of MetroCluster.


|estimated_duration
|integer
a|Estimated duration of update time (in seconds) of MetroCluster.


|name
|string
a|Name of the site in MetroCluster.


|state
|
a|Upgrade state of MetroCluster.


|===


[#progress_details]
[.api-collapsible-fifth-title]
progress_details

[cols=3*,options=header]
|===
|Name
|Type
|Description

|message
|string
a|MetroCluster update progress details.


|===


[#progress_summary]
[.api-collapsible-fifth-title]
progress_summary

[cols=3*,options=header]
|===
|Name
|Type
|Description

|message
|string
a|MetroCluster update progress summary.


|===


[#metrocluster]
[.api-collapsible-fifth-title]
metrocluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|clusters
|array[link:#software_mcc_reference[software_mcc_reference]]
a|List of MetroCluster sites, statuses, and active ONTAP versions.

* readOnly: 1
* Introduced in: 9.6


|progress_details
|link:#progress_details[progress_details]
a|

|progress_summary
|link:#progress_summary[progress_summary]
a|

|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#worker_node]
[.api-collapsible-fifth-title]
worker_node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#firmware_update_progress_state]
[.api-collapsible-fifth-title]
firmware_update_progress_state

[cols=3*,options=header]
|===
|Name
|Type
|Description

|attempts
|integer
a|

|code
|integer
a|Code corresponding to the status message.


|message
|string
a|Error message returned when a cluster firmware update job fails.


|status
|string
a|

|worker_node
|link:#worker_node[worker_node]
a|

|===


[#firmware_update_progress]
[.api-collapsible-fifth-title]
firmware_update_progress

[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|update_state
|array[link:#firmware_update_progress_state[firmware_update_progress_state]]
a|

|update_type
|string
a|Specifies the type of update.


|zip_file_name
|string
a|

|===


[#firmware_disk]
[.api-collapsible-fifth-title]
firmware_disk

[cols=3*,options=header]
|===
|Name
|Type
|Description

|average_duration_per_disk
|integer
a|Average firmware update duration per disk (in seconds).


|num_waiting_download
|integer
a|The number of disks waiting to download the firmware update.


|total_completion_estimate
|integer
a|Estimated firmware update duration to completion (in minutes).


|update_status
|
a|Status of the background disk firmware update.


|===


[#firmware_dqp_record_count]
[.api-collapsible-fifth-title]
firmware_dqp_record_count

[cols=3*,options=header]
|===
|Name
|Type
|Description

|alias
|integer
a|Alias record count


|device
|integer
a|Device record count


|drive
|integer
a|Drive record count


|system
|integer
a|System record count


|===


[#firmware_dqp]
[.api-collapsible-fifth-title]
firmware_dqp

[cols=3*,options=header]
|===
|Name
|Type
|Description

|file_name
|string
a|Firmware file name


|record_count
|link:#firmware_dqp_record_count[firmware_dqp_record_count]
a|

|revision
|string
a|Firmware revision


|version
|string
a|Firmware version


|===


[#firmware_shelf]
[.api-collapsible-fifth-title]
firmware_shelf

[cols=3*,options=header]
|===
|Name
|Type
|Description

|in_progress_count
|integer
a|

|update_status
|
a|Status of the shelf firmware update.


|===


[#firmware_sp_bmc]
[.api-collapsible-fifth-title]
firmware_sp_bmc

[cols=3*,options=header]
|===
|Name
|Type
|Description

|autoupdate
|boolean
a|

|end_time
|string
a|

|fw_type
|string
a|

|image
|string
a|

|in_progress
|boolean
a|

|is_current
|boolean
a|

|last_update_state
|string
a|

|percent_done
|integer
a|

|running_version
|string
a|

|start_time
|string
a|

|state
|string
a|

|===


[#system_firmware]
[.api-collapsible-fifth-title]
system_firmware

[cols=3*,options=header]
|===
|Name
|Type
|Description

|boot_media_bios_version
|string
a|BIOS version that is currently staged on the boot media of the node.


|boot_media_loader_version
|string
a|LOADER version that is currently staged on the boot media of the node.


|install_pending
|boolean
a|Flag that indicates if the system firmware install is pending. A true value suggests that a node reboot or cluster upgrade is required for completing installation.


|running_bios_version
|string
a|BIOS version that is currently installed on the node.


|running_loader_version
|string
a|LOADER version that is currently installed on the node.


|===


[#firmware]
[.api-collapsible-fifth-title]
firmware

[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster_fw_progress
|array[link:#firmware_update_progress[firmware_update_progress]]
a|

|disk
|link:#firmware_disk[firmware_disk]
a|

|dqp
|link:#firmware_dqp[firmware_dqp]
a|

|shelf
|link:#firmware_shelf[firmware_shelf]
a|

|sp_bmc
|link:#firmware_sp_bmc[firmware_sp_bmc]
a|

|system_firmware
|link:#system_firmware[system_firmware]
a|

|===


[#software_images]
[.api-collapsible-fifth-title]
software_images

[cols=3*,options=header]
|===
|Name
|Type
|Description

|package
|string
a|Package file name.


|===


[#software_node_reference]
[.api-collapsible-fifth-title]
software_node_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|firmware
|link:#firmware[firmware]
a|

|model
|string
a|Model number of the node.


|name
|string
a|Name of the node.


|software_images
|array[link:#software_images[software_images]]
a|List of software image information.


|version
|string
a|ONTAP version of the node.

* example: ONTAP_X
* readOnly: 1
* Introduced in: 9.6
* x-nullable: true


|===


[#action]
[.api-collapsible-fifth-title]
action

[cols=3*,options=header]
|===
|Name
|Type
|Description

|message
|string
a|Specifies the corrective action to take to resolve an error.


|===


[#issue]
[.api-collapsible-fifth-title]
issue

[cols=3*,options=header]
|===
|Name
|Type
|Description

|message
|string
a|Details of the error or warning encountered by the update checks.


|===


[#software_validation_reference]
[.api-collapsible-fifth-title]
software_validation_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|action
|link:#action[action]
a|

|issue
|link:#issue[issue]
a|

|status
|string
a|Status of the update check.


|update_check
|string
a|Name of the update check.


|===


[#action]
[.api-collapsible-fifth-title]
action

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|integer
a|Error code corresponding the status error


|message
|string
a|Corrective action to be taken to resolve the status error.


|===


[#issue]
[.api-collapsible-fifth-title]
issue

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|integer
a|Error code corresponding to update status


|message
|string
a|Update status details


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the node to be retrieved for status details.


|===


[#software_status_details_reference]
[.api-collapsible-fifth-title]
software_status_details_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|action
|link:#action[action]
a|

|end_time
|string
a|End time for each status phase.


|issue
|link:#issue[issue]
a|

|name
|string
a|Name of the phase to be retrieved for status details.


|node
|link:#node[node]
a|

|start_time
|string
a|Start time for each status phase.


|state
|string
a|Status of the phase


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the node to be retrieved for update details.


|===


[#software_update_details_reference]
[.api-collapsible-fifth-title]
software_update_details_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|elapsed_duration
|integer
a|Elapsed duration for each update phase


|estimated_duration
|integer
a|Estimated duration for each update phase


|node
|link:#node[node]
a|

|phase
|string
a|Phase details


|state
|string
a|State of the update phase


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
