---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-ndmp-sessions.html'
summary: 'Retrieve NDMP sessions'
---

= Retrieve NDMP sessions

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/ndmp/sessions`#

*Introduced In:* 9.7

Retrieves a collection of NDMP sessions. In the case of SVM-scope, if this API is executed on a data IP, it displays the list of NDMP sessions under the specified SVM; otherwise it displays the list of NDMP sessions for all the SVMs under the cluster. In the case of node-scope, it displays the list of NDMP sessions for all nodes.

== Related ONTAP commands

* `vserver services ndmp probe`
* `system services ndmp probe`

== Learn more

* link:protocols_ndmp_sessions_endpoint_overview.html[DOC /protocols/ndmp/sessions]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|query
|False
a|Filter by uuid

* Introduced in: 9.9


|client_address
|string
|query
|False
a|Filter by client_address


|id
|string
|query
|False
a|Filter by id


|mover.connection.address
|string
|query
|False
a|Filter by mover.connection.address


|mover.connection.port
|integer
|query
|False
a|Filter by mover.connection.port


|mover.connection.type
|string
|query
|False
a|Filter by mover.connection.type


|mover.state
|string
|query
|False
a|Filter by mover.state


|mover.reason
|string
|query
|False
a|Filter by mover.reason


|mover.bytes_moved
|integer
|query
|False
a|Filter by mover.bytes_moved


|mover.mode
|string
|query
|False
a|Filter by mover.mode


|node.name
|string
|query
|False
a|Filter by node.name


|node.uuid
|string
|query
|False
a|Filter by node.uuid


|tape_device
|string
|query
|False
a|Filter by tape_device


|data_path
|string
|query
|False
a|Filter by data_path


|client_port
|integer
|query
|False
a|Filter by client_port


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|scsi.host_adapter
|integer
|query
|False
a|Filter by scsi.host_adapter


|scsi.target_id
|integer
|query
|False
a|Filter by scsi.target_id


|scsi.lun_id
|integer
|query
|False
a|Filter by scsi.lun_id


|scsi.device_id
|string
|query
|False
a|Filter by scsi.device_id


|tape_mode
|string
|query
|False
a|Filter by tape_mode


|data.state
|string
|query
|False
a|Filter by data.state


|data.bytes_processed
|integer
|query
|False
a|Filter by data.bytes_processed


|data.connection.address
|string
|query
|False
a|Filter by data.connection.address


|data.connection.port
|integer
|query
|False
a|Filter by data.connection.port


|data.connection.type
|string
|query
|False
a|Filter by data.connection.type


|data.operation
|string
|query
|False
a|Filter by data.operation


|data.reason
|string
|query
|False
a|Filter by data.reason


|backup_engine
|string
|query
|False
a|Filter by backup_engine


|source_address
|string
|query
|False
a|Filter by source_address


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of Records.


|records
|array[link:#ndmp_session[ndmp_session]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "backup_engine": "string",
      "client_address": "string",
      "data": {
        "bytes_processed": 5000,
        "connection": {
          "address": "string",
          "port": 18600,
          "type": "local"
        },
        "operation": "backup",
        "reason": "aborted",
        "state": "halted"
      },
      "data_path": "/vserver1/vol1",
      "id": "string",
      "mover": {
        "bytes_moved": 645120,
        "connection": {
          "address": "string",
          "port": 18600,
          "type": "local"
        },
        "mode": "read",
        "reason": "end_of_media",
        "state": "connected"
      },
      "node": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "scsi": {
        "device_id": "string"
      },
      "source_address": "string",
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "tape_device": "nrst0a",
      "tape_mode": "write",
      "uuid": "string"
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 68812805
| Failed to obtain the NDMP mode of the operation.
|===



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#ndmp_connect]
[.api-collapsible-fifth-title]
ndmp_connect

Indicates the NDMP connection attributes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|Indicates the NDMP data connection address.


|port
|integer
a|Indicates the NDMP data connection port.


|type
|string
a|The different NDMP connection types.


|===


[#ndmp_data]
[.api-collapsible-fifth-title]
ndmp_data

Information about the NDMP data server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|bytes_processed
|integer
a|Indicates the NDMP data bytes processed.


|connection
|link:#ndmp_connect[ndmp_connect]
a|Indicates the NDMP connection attributes.


|operation
|string
a|Indicates the NDMP data server operation.


|reason
|string
a|If the NDMP mover or data server is in the paused or halted state, then this property provides additional information for the state.


|state
|string
a|The various states of the NDMP state machine during a backup or restore workflow.


|===


[#ndmp_mover]
[.api-collapsible-fifth-title]
ndmp_mover

Information about the NDMP mover.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|bytes_moved
|integer
a|Indicates the NDMP mover bytes moved.


|connection
|link:#ndmp_connect[ndmp_connect]
a|Indicates the NDMP connection attributes.


|mode
|string
a|The modes of a NDMP mover instance.


|reason
|string
a|If the NDMP mover or data server is in the paused or halted state, then this property provides additional information for the state.


|state
|string
a|The various states of the NDMP state machine during a backup or restore workflow.


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#ndmp_scsi]
[.api-collapsible-fifth-title]
ndmp_scsi

Information about the NDMP SCSI server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|device_id
|string
a|Indicates the NDMP SCSI device ID.


|host_adapter
|integer
a|Indicates the NDMP SCSI host adapter.


|lun_id
|integer
a|Indicates the NDMP SCSI LUN ID.


|target_id
|integer
a|Indicates the NDMP SCSI target ID.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#ndmp_session]
[.api-collapsible-fifth-title]
ndmp_session

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|backup_engine
|string
a|Indicates the NDMP backup engine.


|client_address
|string
a|Indicates the NDMP client address.


|client_port
|integer
a|Indicates the NDMP client port.


|data
|link:#ndmp_data[ndmp_data]
a|Information about the NDMP data server.


|data_path
|string
a|Indicates the NDMP backup or restore path.


|id
|string
a|NDMP session identifier.


|mover
|link:#ndmp_mover[ndmp_mover]
a|Information about the NDMP mover.


|node
|link:#node[node]
a|

|scsi
|link:#ndmp_scsi[ndmp_scsi]
a|Information about the NDMP SCSI server.


|source_address
|string
a|Indicates the NDMP local address on which connection was established.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|tape_device
|string
a|Indicates the NDMP tape device.


|tape_mode
|string
a|The modes of a NDMP mover instance.


|uuid
|string
a|The NDMP node or SVM UUID based on whether NDMP is operating in node-scope or SVM-scope mode.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
