---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-name-services-dns.html'
summary: 'Retrieve DNS configurations for all SVMs'
---

= Retrieve DNS configurations for all SVMs

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/name-services/dns`#

*Introduced In:* 9.6

Retrieves the DNS configurations of all SVMs.
Specify 'scope' as 'svm' to retrieve the DNS configuration of all the data SVMs.
Specify 'scope' as 'cluster' to retrieve the DNS configuration of the cluster.

== Advanced properties

* 'tld_query_enabled'
* 'source_address_match'
* 'packet_query_match'
* 'status' property retrieves the status of each name server of the DNS configuration for an SVM.
* 'service_ips' property is displayed only when both service.name and SVM are set.

== Related ONTAP commands

* `vserver services name-service dns show`
* `vserver services name-service dns check`
* `vserver services name-service dns dynamic-update show`
* `vserver services access-check dns srv-lookup`

== Learn more

* link:name-services_dns_endpoint_overview.html[DOC /name-services/dns]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|timeout
|integer
|query
|False
a|Filter by timeout

* Max value: 5
* Min value: 1
* Introduced in: 9.9


|service_ips
|string
|query
|False
a|Filter by service_ips

* Introduced in: 9.14


|packet_query_match
|boolean
|query
|False
a|Filter by packet_query_match

* Introduced in: 9.9


|dynamic_dns.enabled
|boolean
|query
|False
a|Filter by dynamic_dns.enabled

* Introduced in: 9.9


|dynamic_dns.time_to_live
|string
|query
|False
a|Filter by dynamic_dns.time_to_live

* Introduced in: 9.9


|dynamic_dns.use_secure
|boolean
|query
|False
a|Filter by dynamic_dns.use_secure

* Introduced in: 9.9


|dynamic_dns.fqdn
|string
|query
|False
a|Filter by dynamic_dns.fqdn

* Introduced in: 9.9


|uuid
|string
|query
|False
a|Filter by uuid

* Introduced in: 9.13


|domains
|string
|query
|False
a|Filter by domains

* maxLength: 255
* minLength: 1


|source_address_match
|boolean
|query
|False
a|Filter by source_address_match

* Introduced in: 9.9


|status.message
|string
|query
|False
a|Filter by status.message

* Introduced in: 9.9


|status.state
|string
|query
|False
a|Filter by status.state

* Introduced in: 9.9


|status.name_server
|string
|query
|False
a|Filter by status.name_server

* Introduced in: 9.9


|status.code
|integer
|query
|False
a|Filter by status.code

* Introduced in: 9.9


|tld_query_enabled
|boolean
|query
|False
a|Filter by tld_query_enabled

* Introduced in: 9.9


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|attempts
|integer
|query
|False
a|Filter by attempts

* Max value: 4
* Min value: 1
* Introduced in: 9.9


|servers
|string
|query
|False
a|Filter by servers


|scope
|string
|query
|False
a|Filter by scope

* Introduced in: 9.9


|service.name
|string
|query
|False
a|The string required to look up the SRV record on the DNS server.

* Introduced in: 9.14


|service.address_type
|string
|query
|False
a|The type of IP address to be looked up on the DNS server.

* Introduced in: 9.14
* Default value: 1


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Max value: 120
* Min value: 0
* Default value: 15


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of DNS domain records.


|records
|array[link:#dns[dns]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "attempts": 1,
      "domains": [
        "example.com",
        "example2.example3.com"
      ],
      "dynamic_dns": {
        "fqdn": "example.com",
        "time_to_live": "P2D"
      },
      "scope": "string",
      "servers": [
        "10.224.65.20",
        "2001:db08:a0b:12f0::1"
      ],
      "service_ips": [
        "10.224.65.20",
        "2001:db08:a0b:12f0::1"
      ],
      "skip_config_validation": true,
      "status": [
        {
          "code": 6684732,
          "message": "string",
          "name_server": "10.10.10.10",
          "state": "up"
        }
      ],
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "timeout": 2,
      "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#dynamic_dns]
[.api-collapsible-fifth-title]
dynamic_dns

[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Enable or disable Dynamic DNS (DDNS) updates for the specified SVM.


|fqdn
|string
a|Fully Qualified Domain Name (FQDN) to be used for dynamic DNS updates.


|skip_fqdn_validation
|boolean
a|Enable or disable FQDN validation.


|time_to_live
|string
a|Time to live value for the dynamic DNS updates, in an ISO-8601 duration formatted string.
Maximum Time To Live is 720 hours(P30D in ISO-8601 format) and the default is 24 hours(P1D in ISO-8601 format).


|use_secure
|boolean
a|Enable or disable secure dynamic DNS updates for the specified SVM.


|===


[#status]
[.api-collapsible-fifth-title]
status

Status of each of the DNS name server configured for the specified SVM.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|integer
a|Code corresponding to the status message. Code is 0 when the state is 'up'.


|message
|string
a|Detailed description of the validation state if the state is 'down' or
the response time of the DNS server if the state is 'up'.


|name_server
|string
a|The IP address of the DNS server. The address can be either an IPv4 or an IPv6 address.


|state
|string
a|The validation status of the DNS server.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#dns]
[.api-collapsible-fifth-title]
dns

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|attempts
|integer
a|Number of attempts allowed when querying the DNS name servers.


|domains
|array[string]
a|A list of DNS domains.
Domain names have the following requirements:

* The name must contain only the following characters: A through Z,
a through z, 0 through 9, ".", "-" or "_".
* The first character of each label, delimited by ".", must be one
of the following characters: A through Z or a through z or 0
through 9.
* The last character of each label, delimited by ".", must be one of
the following characters: A through Z, a through z, or 0 through 9.
* The top level domain must contain only the following characters: A
through Z, a through z.
* The system reserves the following names:"all", "local", and "localhost".


|dynamic_dns
|link:#dynamic_dns[dynamic_dns]
a|

|packet_query_match
|boolean
a|Indicates whether or not the query section of the reply packet is equal to that of the query packet.


|scope
|string
a|Set to "svm" for DNS owned by an SVM, otherwise set to "cluster".


|servers
|array[string]
a|The list of IP addresses of the DNS servers. Addresses can be either
IPv4 or IPv6 addresses.


|service_ips
|array[string]
a|List of IP addresses for a DNS service. Addresses can be IPv4, IPv6 or both.


|source_address_match
|boolean
a|Indicates whether or not the DNS responses are from a different IP address to the IP address the request was sent to.


|status
|array[link:#status[status]]
a|Status of all the DNS name servers configured for the specified SVM.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|timeout
|integer
a|Timeout values for queries to the name servers, in seconds.


|tld_query_enabled
|boolean
a|Enable or disable top-level domain (TLD) queries.


|uuid
|string
a|UUID of the DNS object.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
