---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-storage-snapshot-policies.html'
summary: 'Retrieve snapshot policies'
---

= Retrieve snapshot policies

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/storage/snapshot-policies`#

*Introduced In:* 9.6

Retrieves a collection of snapshot policies.

== Related ONTAP commands

* `snapshot policy show`

== Learn more

* link:storage_snapshot-policies_endpoint_overview.html[DOC /storage/snapshot-policies]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|enabled
|boolean
|query
|False
a|Filter by enabled


|name
|string
|query
|False
a|Filter by name


|svm.name
|string
|query
|False
a|Filter by svm.name


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|uuid
|string
|query
|False
a|Filter by uuid


|copies.count
|integer
|query
|False
a|Filter by copies.count


|copies.snapmirror_label
|string
|query
|False
a|Filter by copies.snapmirror_label


|copies.schedule.name
|string
|query
|False
a|Filter by copies.schedule.name


|copies.schedule.uuid
|string
|query
|False
a|Filter by copies.schedule.uuid

* Introduced in: 9.14


|copies.retention_period
|string
|query
|False
a|Filter by copies.retention_period

* Introduced in: 9.12


|copies.prefix
|string
|query
|False
a|Filter by copies.prefix


|scope
|string
|query
|False
a|Filter by scope


|comment
|string
|query
|False
a|Filter by comment


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#snapshot_policy[snapshot_policy]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "comment": "string",
      "copies": [
        {
          "prefix": "string",
          "retention_period": "string",
          "schedule": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "weekly",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          },
          "snapmirror_label": "string"
        }
      ],
      "enabled": 1,
      "name": "default",
      "scope": "string",
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#schedule]
[.api-collapsible-fifth-title]
schedule

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#copies]
[.api-collapsible-fifth-title]
copies

[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|The number of snapshots to maintain for this schedule.


|prefix
|string
a|The prefix to use while creating snapshots at regular intervals.


|retention_period
|string
a|The retention period of snapshots for this schedule. The retention period value represents a duration and must be specified in the ISO-8601 duration format. The retention period can be in years, months, days, hours, and minutes. A period specified for years, months, and days is represented in the ISO-8601 format as "P+++<num>+++Y", "P+++<num>+++M", "P+++<num>+++D" respectively, for example "P10Y" represents a duration of 10 years. A duration in hours and minutes is represented by "PT+++<num>+++H" and "PT+++<num>+++M" respectively. The period string must contain only a single time element that is, either years, months, days, hours, or minutes. A duration which combines different periods is not supported, for example "P1Y10M" is not supported.+++</num>++++++</num>++++++</num>++++++</num>++++++</num>+++


|schedule
|link:#schedule[schedule]
a|

|snapmirror_label
|string
a|Label for SnapMirror operations


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#snapshot_policy]
[.api-collapsible-fifth-title]
snapshot_policy

The snapshot policy object is associated with a read-write volume used to create and delete snapshots at regular intervals.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|comment
|string
a|A comment associated with the snapshot policy.


|copies
|array[link:#copies[copies]]
a|

|enabled
|boolean
a|Is the snapshot policy enabled?


|name
|string
a|Name of the snapshot policy.


|scope
|string
a|Set to "svm" when the request is on a data SVM, otherwise set to "cluster".


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|uuid
|string
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
