---
sidebar: sidebar
api: true
explorer: false
permalink: 'name-services_unix-groups_endpoint_overview.html'
summary: 'Manage UNIX group configurations'
---

= Manage UNIX group configurations



== Overview

You can use this API to display local UNIX group information and to control UNIX group configurations.

== Retrieving UNIX group information

The UNIX group GET endpoint retrieves all of the local UNIX groups configurations for data SVMs.

== Examples

=== Retrieving all of the fields for all of the UNIX group configurations

The UNIX group GET endpoint retrieves all of the local UNIX groups configurations for data SVMs.

----

# The API:
/api/name-services/unix-groups

# The call:
curl -X GET "https://<mgmt-ip>/api/name-services/unix-groups?fields=*" -H "accept: application/hal+json"

# The response:
{
"records": [
  {
    "svm": {
      "uuid": "b009a9e7-4081-b576-7575-ada21efcaf16",
      "name": "vs1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/b009a9e7-4081-b576-7575-ada21efcaf16"
        }
      }
    },
    "name": "group1",
    "id": 11,
    "users": [
      {
        "name": "user1"
      },
      {
        "name": "user2"
      },
      {
        "name": "user3"
      }
    ],
    "_links": {
      "self": {
        "href": "/api/name-services/unix-groups/b009a9e7-4081-b576-7575-ada21efcaf16/group1"
      }
    }
  },
  {
    "svm": {
      "uuid": "b009a9e7-4081-b576-7575-ada21efcaf16",
      "name": "vs1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/b009a9e7-4081-b576-7575-ada21efcaf16"
        }
      }
    },
    "name": "group2",
    "id": 12,
    "users": [
      {
        "name": "user1"
      },
      {
        "name": "user2"
      }
    ],
    "_links": {
      "self": {
        "href": "/api/name-services/unix-groups/b009a9e7-4081-b576-7575-ada21efcaf16/group2"
      }
    }
  },
  {
    "svm": {
      "uuid": "b009a9e7-4081-b576-7575-ada21efcad17",
      "name": "vs2",
      "_links": {
        "self": {
          "href": "/api/svm/svms/b009a9e7-4081-b576-7575-ada21efcad17"
        }
      }
    },
    "name": "group1",
    "id": 11,
    "users": [
      {
        "name": "user2"
      },
      {
        "name": "user3"
      }
    ],
    "_links": {
      "self": {
        "href": "/api/name-services/unix-groups/b009a9e7-4081-b576-7575-ada21efcad17/group1"
      }
    }
  }
],
"num_records": 3,
"_links": {
  "self": {
    "href": "/api/name-services/unix-groups?fields=*"
  }
}
}
----

=== Retrieving all of the UNIX group configurations whose group name is 'group1'.

----

# The API:
/api/name-services/unix-groups

# The call:
curl -X GET "https://<mgmt-ip>/api/name-services/unix-groups?name=group1" -H "accept: application/hal+json"

# The response:
{
"records": [
  {
    "svm": {
      "uuid": "b009a9e7-4081-b576-7575-ada21efcaf16",
      "name": "vs1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/b009a9e7-4081-b576-7575-ada21efcaf16"
        }
      }
    },
    "name": "group1",
    "id": 11,
    "_links": {
      "self": {
        "href": "/api/name-services/unix-groups/b009a9e7-4081-b576-7575-ada21efcaf16/group1"
      }
    }
  },
],
"num_records": 1,
"_links": {
  "self": {
    "href": "/api/name-services/unix-groups?name=group1"
  }
}
}
----

== Creating a UNIX group configuration

The UNIX group POST endpoint creates a UNIX group configuration for the specified SVM.

== Example

----

# The API:
/api/name-services/unix-groups

# The call:
curl -X POST "https://<mgmt-ip>/api/name-services/unix-groups" -H "accept: application/hal+json" -H "Content-Type: application/json" -d '{ "svm": {"uuid": "179d3c85-7053-11e8-b9b8-005056b41bd1"}, "name": "group1", "id": 111}'
----

== Updating a UNIX group configuration

The UNIX group PATCH endpoint updates the UNIX group ID of the specified UNIX group and the specified SVM.

== Example

=== Modify the group ID of group1 to 112

----

# The API:
/api/name-services/unix-groups/{svm.uuid}/{name}

# The call:
curl -X PATCH "https://<mgmt-ip>/api/name-services/unix-groups/179d3c85-7053-11e8-b9b8-005056b41bd1/group1" -H "accept: application/hal+json" -H "Content-Type: application/json" -d '{ "id": 112}'
----

== Deleting a UNIX group configuration

The UNIX group DELETE endpoint deletes the specified UNIX group of the specified SVM.

== Example

=== Delete the group 'group1'

----

# The API:
/api/name-services/unix-groups/{svm.uuid}/{name}

# The call:
curl -X DELETE "https://<mgmt-ip>/api/name-services/unix-groups/179d3c85-7053-11e8-b9b8-005056b41bd1/group1" -H "accept: application/hal+json"
----


