---
sidebar: sidebar
api: true
explorer: false
permalink: 'ndmp_overview.html'
summary: 'ONTAP REST API NDMP endpoints'
---

= ONTAP REST API NDMP endpoints



NDMP (Network Data Management Protocol) provides an open standard for network-based backup of network-attached storage (NAS). NDMP minimizes the coding required for different applications by providing standard commands for backing up and restoring file servers. NDMP increases the speed and efficiency of NAS data protection, as data can bypass backup servers and be written directly to tape storage. Starting from ONTAP 8.2, the software supports SVM aware NDMP backups. This helps in optimizing NDMP backup performance by choosing efficient data transfer paths and is fully compatible with integrated non-disruptive operations and volume mobility capabilities of ONTAP software. In order to support this feature, a CAB extension must be implemented by backup vendors.
These APIs allow you to manage the following endpoints:

* ndmp
* ndmp nodes
* ndmp svms
* ndmp sessions

== APIs

=== NDMP

These APIs are used to manage NDMP mode, SVM-scope or node-scope.

=== NDMP nodes

These APIs are used to manage node configurations.

=== NDMP SVMs

These APIs are used to manage NDMP configurations of SVMs.

=== NDMP sessions

These APIs are used to manage diagnostic information on NDMP sessions belonging to a specific SVM in the case of SVM-scope or to a specific node in the case of node-scope.


