---
sidebar: sidebar
api: true
explorer: false
permalink: 'network_http-proxy_endpoint_overview.html'
summary: 'Manage HTTP proxy configuration'
---

= Manage HTTP proxy configuration



== Overview

Configuration of an HTTP proxy for an SVM or a Cluster IPspace.

== Retrieve HTTP proxy information

The HTTP proxy GET operation retrieves all configurations for an SVM or a Cluster IPspace via '/api/cluster'.

== Examples

=== Retrieving all fields for all HTTP proxy configurations

----

# The API:
/api/network/http-proxy

# The call:
curl -X GET "https://<mgmt-ip>/api/network/http-proxy?fields=*&return_records=true&return_timeout=15" -H  "accept: application/json"

# The response:
{
"records": [
  {
    "uuid": "4133a1fc-7228-11e9-b40c-005056bb4f0c",
    "svm": {
        "name": "vs1",
        "uuid": "4133a1fc-7228-11e9-b40c-005056bb4f0c"
    },
    "server": "server1.example.com",
    "port": 3128,
    "authentication_enabled": false
  },
  {
    "uuid": "96219ce3-7214-11e9-828c-005056bb4f0c",
    "svm": {
        "name": "cluster-1",
        "uuid": "96219ce3-7214-11e9-828c-005056bb4f0c"
    },
    "ipspace": {
        "uuid": "7433520f-7214-11e9-828c-005056bb4f0c",
        "name": "Default"
    },
    "server": "1.1.1.",
    "port": 3128,
    "authentication_enabled": true
   }
],
"num_records": 2
}
----

=== Retrieving the HTTP proxy configuration for a specific SVM

----

# The API:
/api/network/http-proxy/{uuid}

# The call:
curl -X GET "https://<mgmt-ip>/api/network/http-proxy/96219ce3-7214-11e9-828c-005056bb4f0c" -H  "accept: application/json"

# The response
{
"uuid": "96219ce3-7214-11e9-828c-005056bb4f0c",
"svm": {
    "name": "cluster-1",
    "uuid": "96219ce3-7214-11e9-828c-005056bb4f0c"
},
"ipspace": {
    "uuid": "7433520f-7214-11e9-828c-005056bb4f0c",
    "name": "Default"
},
"server": "1.1.1.1",
"port": 3128,
"authentication_enabled": false
}
----

== Creating an HTTP proxy configuration

You can use the HTTP proxy POST operation to create an HTTP proxy configuration for the specified SVM.

== Examples

=== Creating an HTTP proxy configuration for a particular SVM

----

# The API:
/api/network/http-proxy

# The call:
curl -X POST "https://<mgmt-ip>/api/network/http-proxy" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{    \"port\": 3128,  \"server\": \"1.1.1.1\",  \"svm\": {      \"name\": \"cluster-1\"  }}"
----

=== Creating an HTTP proxy configuration for a particular IPspace

----

# The API:
/api/network/http-proxy

# The call:
curl -X POST "https://<mgmt-ip>/api/network/http-proxy" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"ipspace\": {    \"name\": \"Default\"  },  \"port\": 3128,  \"server\": \"1.1.1.1\"}"
----

=== Creating an HTTP proxy configuration with authentication enabled

----

# The API:
/api/network/http-proxy

# The call:
curl -X POST "https://<mgmt-ip>/api/network/http-proxy" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"ipspace\": {    \"name\": \"Default\"  },  \"port\": 3128,  \"server\": \"1.1.1.1\", \"authentication_enabled\":true, \"username\":\"test\", \"password\":\"test\"}"
----

== Update an HTTP proxy configuration for a specified SVM

You can use the HTTP proxy PATCH operation to update the HTTP proxy configuration for the specified SVM.

== Example

The following example shows how a PATCH operation is used to update an HTTP proxy configuration for a specific SVM:

----

# The API:
/api/network/http-proxy/{uuid}

# The call:
curl -X PATCH "https://<mgmt-ip>/api/network/http-proxy/96219ce3-7214-11e9-828c-005056bb4f0c" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{    \"port\": 3128,  \"server\": \"server2.example.com\"}"
----

== Delete an HTTP proxy configuration for a specified SVM

You can use the HTTP proxy DELETE operation to delete the HTTP proxy configuration for the specified SVM.

== Example

The following example shows how a DELETE operation is used to delete an HTTP proxy configuration for a specific SVM:

----

# The API:
/api/network/http-proxy/{uuid}

# The call:
curl -X DELETE "https://<mgmt-ip>/api/network/http-proxy/96219ce3-7214-11e9-828c-005056bb4f0c" -H  "accept: application/json"
----


