---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-cluster-mediators-.html'
summary: 'Modify the mediator configuration'
---

= Modify the mediator configuration

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/cluster/mediators/{uuid}`#

*Introduced In:* 9.17

Modifies the mediator configuration.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|* format: uuid


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|dr_group
|link:#dr_group[dr_group]
a|DR group reference.


|local_mediator_connectivity
|string
a|Indicates the mediator connectivity status of the local cluster. Possible values are connected, unreachable, unusable and down-high-latency. This field is only applicable to the mediators in SnapMirror active sync configuration.


|peer_mediator_connectivity
|string
a|Indicates the mediator connectivity status of the peer cluster. Possible values are connected, unreachable, unknown and down-high-latency.


|reachable
|boolean
a|Indicates the connectivity status of the mediator.


|strict_cert_validation
|boolean
a|Indicates if strict validation of certificates is performed while making REST API calls to the mediator. This field is only applicable to the ONTAP Cloud Mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* x-nullable: true


|use_http_proxy_local
|boolean
a|Indicates if the local cluster should use an http-proxy server while making REST API calls to the mediator. This field is only applicable to the ONTAP cloud mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* x-nullable: true


|use_http_proxy_remote
|boolean
a|Indicates if the remote cluster should use an http-proxy server while making REST API calls to the mediator. This field is only applicable to the ONTAP cloud mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* writeOnly: 1
* x-nullable: true


|uuid
|string
a|The unique identifier for the mediator service.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "dr_group": {
    "id": 0
  },
  "local_mediator_connectivity": "connected",
  "peer_mediator_connectivity": "connected",
  "reachable": 1,
  "strict_cert_validation": 1,
  "use_http_proxy_local": 1,
  "use_http_proxy_remote": 1,
  "uuid": "string"
}
====

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Response

```
Status: 202, Accepted
```

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 13369377
| Mediator field "mediator.id" does not exist.

| 13369412
| Modification of the mediator configuration succeeded on the peer cluster but failed on the local cluster. Reason : {Reason of failure}. Wait a few minutes, then try the operation again.

| 13369421
| Failed to modify mediator configuration on the cluster. Reason : {Reason of failure}. Wait a few minutes, then try the operation again.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#dr_group]
[.api-collapsible-fifth-title]
dr_group

DR group reference.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|integer
a|DR Group ID


|===


[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#peer_cluster]
[.api-collapsible-fifth-title]
peer_cluster

The peer cluster that the mediator service is used for.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#mediator]
[.api-collapsible-fifth-title]
mediator

Mediator information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|dr_group
|link:#dr_group[dr_group]
a|DR group reference.


|local_mediator_connectivity
|string
a|Indicates the mediator connectivity status of the local cluster. Possible values are connected, unreachable, unusable and down-high-latency. This field is only applicable to the mediators in SnapMirror active sync configuration.


|peer_mediator_connectivity
|string
a|Indicates the mediator connectivity status of the peer cluster. Possible values are connected, unreachable, unknown and down-high-latency.


|reachable
|boolean
a|Indicates the connectivity status of the mediator.


|strict_cert_validation
|boolean
a|Indicates if strict validation of certificates is performed while making REST API calls to the mediator. This field is only applicable to the ONTAP Cloud Mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* x-nullable: true


|use_http_proxy_local
|boolean
a|Indicates if the local cluster should use an http-proxy server while making REST API calls to the mediator. This field is only applicable to the ONTAP cloud mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* x-nullable: true


|use_http_proxy_remote
|boolean
a|Indicates if the remote cluster should use an http-proxy server while making REST API calls to the mediator. This field is only applicable to the ONTAP cloud mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* writeOnly: 1
* x-nullable: true


|uuid
|string
a|The unique identifier for the mediator service.


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
