---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-snapmirror-relationships-.html'
summary: 'Update a SnapMirror relationship'
---

= Update a SnapMirror relationship

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/snapmirror/relationships/{uuid}`#

*Introduced In:* 9.6

Updates a SnapMirror relationship. This API is used to initiate SnapMirror operations such as "initialize", "resync", "break", "quiesce", and "resume" by specifying the appropriate value for the "state" field. It is also used to modify the SnapMirror policy associated with the specified relationship. Additionally, a SnapMirror relationship can be failed over to the destination endpoint or a failed over SnapMirror relationship can be failed back to the original state or a SnapMirror relationship direction can be reversed using this API. This API can also be used to expand the SnapMirror active sync relationship with the specified source and destination volumes.

To initialize the relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or "in_sync" for relationships with a policy of type "sync".

To break the relationship or to failover to the destination endpoint and start serving data from the destination endpoint, PATCH the state to "broken_off" for relationships with a policy of type "async" or "sync". SnapMirror relationships with the policy type as "sync" and sync_type as "automated_failover" cannot be "broken_off".

To resync the broken relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or "in_sync" for relationships with a policy of type "sync".

To failback the failed over relationship and start serving data from the source endpoint, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or "in_sync" for relationships with a policy of type "sync" and set the query flag "failback" as "true". SnapMirror relationships with the policy type as "sync" and sync_type as "automated_failover" can be in "broken_off" state due to a failed attempt of automated SnapMirror failover operation.

To pause the relationship, suspending further transfers, PATCH the state to "paused" for relationships with a policy of type "async" or "sync". SnapMirror relationships with the policy type as "sync" and sync_type as "automated_failover" cannot be "paused".

To resume transfers for a paused relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or "in_sync" for relationships with a policy of type "sync".

To reverse the direction of the relationship, PATCH the "source.path" with the destination endpoint and the "destination.path" with the source endpoint and the relationship state to "snapmirrored" for relationships with a policy of type "async" or "in_sync" for relationships with a policy of type "sync". For relationships with a policy of type "async" and relationship state as "snapmirrored", stop IO on the source endpoint and perform a SnapMirror transfer POST operation before reversing the direction of the relationship to prevent any loss of data.

The values "in_sync", "out_of_sync", and "synchronizing" are only applicable to relationships with a policy of type "sync".

When "transfer_schedule" is specified along with "state" during PATCH, first the schedule is modified on the relationship and then the respective SnapMirror operation is initiated. The "transfer_schedule" specified is used to update asynchronous relationships.

When "throttle" is specified along with "state" during PATCH, first the throttle is modified on the relationship, which will be used by any upcoming transfers and then the respective SnapMirror operation is initiated. If the SnapMirror operation initiated a transfer then it will also use the new throttle. If "throttle" needs to be applied for a specific transfer use SnapMirror Transfer REST API.

For SnapMirror active sync relationships, when "consistency_group_volumes" is specified during PATCH, first the existing FlexVol volume relationship is deleted and released and then the volumes are added to the SnapMirror active sync relationship.

== Examples

== Related ONTAP commands

* `snapmirror modify`
* `snapmirror initialize`
* `snapmirror resync`
* `snapmirror break`
* `snapmirror quiesce`
* `snapmirror resume`

== Important notes

* The property "transfer_schedule" if set on a SnapMirror relationship overrides the "transfer_schedule" set on the policy being used with the SnapMirror relationship.
* The property "throttle" if set on a SnapMirror relationship overrides the "throttle" set on the policy being used with the SnapMirror relationship.
* The properties "transfer_schedule" and "throttle" are not supported when "failback" is set to "true".
* The properties "transfer_schedule" and "throttle" are not supported when "failover" is set to "true".
* The properties "transfer_schedule" and "throttle" are not supported when "force_failover" is set to "true".
* The properties "transfer_schedule" and "throttle" are not supported when the direction of the relationship is being reversed.
* To remove a transfer_schedule on a SnapMirror relationship set the "transfer_schedule" to null (no-quotes) during SnapMirror relationship PATCH.
* The property "identity_preservation" value can be changed from a higher "identity_preservation" threshold value to a lower "identity_preservation" threshold value but not vice-versa. For example, the threshold value of the "identity_preservation" property can be changed from "full" to "exclude_network_config", but cannot be increased from "exclude_network_and_protocol_config" to "exclude_network_config" to "full". The threshold value of the "identity_preservation" cannot be changed to "exclude_network_and_protocol_config" for IDP SVMDR.
* Policies with the property "retention.creation_schedule" are supported only on the final SnapMirror destination volume in the cascade.
* The property "backoff_level" is only applicable for FlexVol SnapMirror relationships.

== Examples

The following examples show how to perform the SnapMirror "resync", "initialize", "resume", "quiesce", and "break" operations. In addition, a relationship can be failed over to the destination endpoint and start serving data from the destination endpoint. A failed over relationship can be failed back to the source endpoint and serve data from the source endpoint. Also a relationship can be reversed by making the source endpoint as the new destination endpoint and the destination endpoint as the new source endpoint.

To update an associated SnapMirror policy.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"policy": { "name" : "MirrorAndVaultDiscardNetwork"}}'
----

To perform SnapMirror "resync" for an asynchronous SnapMirror relationship.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"state":"snapmirrored"}'
----

To perform SnapMirror "initialize" for an asynchronous SnapMirror relationship.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"state":"snapmirrored"}'
----

To perform SnapMirror "resume" for an asynchronous SnapMirror relationship.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"state":"snapmirrored"}'
----

To perform SnapMirror "quiesce" for an asynchronous SnapMirror relationship.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff" '{"state":"paused"}'
----

To perform SnapMirror "break" for an asynchronous SnapMirror relationship. This operation does a failover to the destination endpoint. After a the failover, data can then be served from the destination endpoint.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff" '{"state":"broken_off"}'
----

To forcefully failover to the destination endpoint and start serving data from the destination endpoint.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/?force=true" '{"state":"broken_off"}'
----

To failback to the source endpoint and start serving data from the source endpoint for an asynchronous relationship.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/?failback=true" '{"state":"snapmirrored"}'
----

To failback to the source endpoint and start serving data from the source endpoint for a synchronous relationship.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/?failback=true" '{"state":"in_sync"}'
----

To reverse the direction of an asynchronous relationship, that is, make the source endpoint as the new destination endpoint and make the destination endpoint as the new source endpoint.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"source": {"path": "dst_svm:dst_vol"}, "destination": {"path": "src_svm:src_vol"}, "state": "snapmirrored"}'
----

To reverse the direction of a synchronous relationship, that is, make the source endpoint as the new destination endpoint and make the destination endpoint as the new source endpoint.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"source": {"path": "dst_svm:dst_vol"}, "destination": {"path": "src_svm:src_vol"}, "state": "in_sync"}'
----

Updating SnapMirror transfer_schedule and throttle for an asynchronous SnapMirror relationship. Transfer_schedule can be specified as UUID or name or both.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"transfer_schedule":{"uuid":"817500fa-092d-44c5-9c10-7b54f7b2f20a", "name":"5min"}, "throttle":100}'
----

Removing the SnapMirror transfer_schedule for an asynchronous SnapMirror relationship.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"transfer_schedule":{"uuid":null, "name":null}}'
----

Removing the SnapMirror throttle for an asynchronous SnapMirror relationship.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"throttle":0}'
----

To perform SnapMirror "resync" and update the SnapMirror transfer_schedule for an asynchronous SnapMirror relationship. First the transfer_schedule is modified and then the resync transfer is initiated.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"state":"snapmirrored", transfer_schedule":{"uuid":"817500fa-092d-44c5-9c10-7b54f7b2f20a", "name":"5min"}}'
----

To perform SnapMirror "initialize" and update the SnapMirror throttle for an asynchronous SnapMirror relationship. First the throttle is modified and then the initialize transfer is initiated. The initialize transfer will use this new throttle.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"state":"snapmirrored", "throttle":100}'
----

To perform SnapMirror "resync" and update the SnapMirror throttle for an asynchronous SnapMirror relationship. First the throttle is modified and then the resync transfer is initiated. The resync transfer will use this new throttle.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"state":"snapmirrored", "throttle":100}'
----

To perform a SnapMirror active sync or Asynchronous Consistency Group expansion.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{ "source" : {"consistency_group_volumes":[{"name":"vol"}]}, "destination" : {"consistency_group_volumes":[{"name":"voldp"}]} }'
----

Updating SnapMirror backoff_level for an asynchronous SnapMirror relationship.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"backoff_level": "none"}'
----

To perform SnapMirror "initialize" and update the SnapMirror backoff_level for an asynchronous SnapMirror relationship. First the backoff_level is modified and then the initialize transfer is initiated. The initialize transfer will use this new backoff_level.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"state":"snapmirrored", "backoff_level": "medium"}'
----

To perform SnapMirror "resync" and update the SnapMirror backoff_level for an asynchronous SnapMirror relationship. First the backoff_level is modified and then the resync transfer is initiated. The resync transfer will use this new backoff_level.

----
 PATCH "/api/snapmirror/relationships/98bb2608-fc60-11e8-aa13-005056a707ff/" '{"state":"snapmirrored", "backoff_level": "medium"}'
----

== Learn more

* link:snapmirror_relationships_endpoint_overview.html[DOC /snapmirror/relationships]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|SnapMirror relationship UUID


|failover
|boolean
|query
|False
a|If this parameter is set, validation and failover will occur to the SVM-DR SnapMirror relationship destination endpoint. Any other fields specified with this parameter will be ignored. This parameter is supported only for SVM-DR SnapMirror relationships.

* Introduced in: 9.7
* Default value:


|force-failover
|boolean
|query
|False
a|If this parameter is set, failover will occur to the SVM-DR SnapMirror relationship destination endpoint, overriding the validation errors. Any other fields specified with this parameter will be ignored. This parameter is supported only for SVM-DR SnapMirror relationships.

* Introduced in: 9.7
* Default value:


|force
|boolean
|query
|False
a|If this parameter is set while specifying the state as "broken_off", indicates a forced failover overriding the validation errors.

* Introduced in: 9.8
* Default value:


|failback
|boolean
|query
|False
a|If this parameter is set while specifying the state as "snapmirrored", indicates recovery of the failed over SnapMirror relationship by preserving the data written on the destination endpoint when the SnapMirror relationship was in failed over state. This flag is only applicable to SVM-DR SnapMirror relationships.

* Introduced in: 9.8
* Default value:


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0


|validate_only
|boolean
|query
|False
a|Validate the operation and its parameters, without actually performing the operation.

* Introduced in: 9.7

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|backoff_level
|string
a|Specifies the SnapMirror backoff level due to Client Ops for FlexVol SnapMirror relationships.


|destination
|link:#snapmirror_endpoint[snapmirror_endpoint]
a|Endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to create the destination SVM endpoint or to establish an SVM DR relationship must have the property "cluster" populated with the remote cluster details. A POST request to create the destination FlexVol volume, FlexGroup volume, Consistency Group, ONTAP S3 bucket and NON-ONTAP object-store endpoints can optionally specify the "cluster" property when the source SVM and the destination SVM are peered. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.

* Introduced in: 9.6


|exported_snapshot
|string
a|Snapshot exported to clients on destination.


|group_type
|string
a|Specifies the group type of the top level SnapMirror relationship. The volume relationships are shown as _none_, the SVMDR relationships are shown as _svm_dr_, the Consistency Group relationships are shown as _consistency_group_, FlexGroup volume relationships are shown as _flexgroup_ and in Snapmirror Active Sync NAS relationships the group type is _coordination_group_.


|healthy
|boolean
a|Is the relationship healthy?


|identity_preservation
|string
a|Specifies which configuration of the source SVM is replicated to the destination SVM. This property is applicable only for SVM data protection with "async" policy type. This "identity_preservation" overrides the "identity_preservation" set on the SnapMirror relationship's policy.


|io_serving_copy
|string
a|Specifies the sites serving I/O for the SnapMirror active sync relationship.


|lag_time
|string
a|Time since the exported snapshot was created.


|last_transfer_network_compression_ratio
|string
a|Specifies the compression ratio achieved for the data sent over the wire with network compression enabled for the last successful transfer.


|last_transfer_type
|string
a|Specifies the operation type of the last transfer that occurred on the relationship. The _initialize_ transfer occurs when the relationship state changes from uninitialized to snapmirrored or in_sync. The _update_ transfer occurs when the snapshots are transferred from the source endpoint to the destination endpoint as part of scheduled or manual update. The _resync_ transfer occurs when the relationship state changes from broken_off to snapmirrored or in_sync. The _restore_ transfer occurs when the snapshot is restored from a destination endpoint to another endpoint.


|master_bias_activated_site
|string
a|Specifies the Master Bias Activated Site for the SnapMirror active sync relationship.


|policy
|link:#policy[policy]
a|Basic policy information of the relationship.


|preferred_site
|string
a|Specifies the Primary Site of the SnapMirror active sync relationship.


|preserve
|boolean
a|Set to true on resync to preserve snapshots on the destination that are newer than the latest common snapshot. This property is applicable only for relationships with FlexVol volume or FlexGroup volume endpoints and when the PATCH state is being changed to "snapmirrored".


|quick_resync
|boolean
a|Set to true to reduce resync time by not preserving storage efficiency. This property is applicable only for relationships with FlexVol volume endpoints and SVMDR relationships when the PATCH state is being changed to "snapmirrored".


|recover_after_break
|boolean
a|Set to true to recover from a failed SnapMirror break operation on a FlexGroup volume relationship. This restores all destination FlexGroup constituent volumes to the latest snapshot, and any writes to the read-write constituents are lost. This property is applicable only for SnapMirror relationships with FlexGroup volume endpoints and when the PATCH state is being changed to "broken_off".


|restore_to_snapshot
|string
a|Specifies the snapshot to restore to on the destination during the break operation. This property is applicable only for SnapMirror relationships with FlexVol volume endpoints and when the PATCH state is being changed to "broken_off".


|selective_volumes
|array[link:#selective_volumes[selective_volumes]]
a|This field specifies the list of volumes to be protected under a vserver.


|source
|link:#snapmirror_source_endpoint[snapmirror_source_endpoint]
a|Source endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.


|state
|string
a|State of the relationship.
To initialize the relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".
To break the relationship, PATCH the state to "broken_off" for relationships with a policy of type "async" or "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" cannot be "broken_off".
To resync the relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" can be in "broken_off" state due to a failed attempt of SnapMirror failover.
To pause the relationship, suspending further transfers, PATCH the state to "paused" for relationships with a policy of type "async" or "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" cannot be "paused".
To resume transfers for a paused relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".
The entries "in_sync", "out_of_sync", "synchronizing", "expanding", and "shrinking" are only applicable to relationships with a policy of type "sync". A PATCH call on the state change only triggers the transition to the specified state. You must poll on the "state", "healthy" and "unhealthy_reason" properties using a GET request to determine if the transition is successful. To automatically initialize the relationship when specifying "create_destination" property, set the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".


|throttle
|integer
a|Throttle, in KBs per second. This "throttle" overrides the "throttle" set on the SnapMirror relationship's policy. If neither of these are set, defaults to 0, which is interpreted as unlimited.


|total_transfer_bytes
|integer
a|Cumulative bytes transferred for the relationship.


|total_transfer_duration
|string
a|Indicates the cumulative duration of all transfers since the last aggregate relocation, takeover/giveback, or metrocluster switchover/switchback involving the node that hosts the relationship.


|transfer
|link:#transfer[transfer]
a|Basic information on the current transfer or the last transfer if there is no active transfer at the time of the request.


|transfer_schedule
|link:#transfer_schedule[transfer_schedule]
a|Schedule used to update asynchronous relationships. This "transfer_schedule" overrides the "transfer_schedule" set on the SnapMirror relationship's policy. To remove the "transfer_schedule", set its value to null (no-quotes). Only cron schedules are supported for SnapMirror.


|unhealthy_reason
|array[link:#snapmirror_error[snapmirror_error]]
a|Reason the relationship is not healthy. It is a concatenation of up to four levels of error messages.


|uuid
|string
a|Unique identifier of the SnapMirror relationship.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "backoff_level": "medium",
  "destination": {
    "cluster": {
      "name": "cluster1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    },
    "luns": {
      "name": "/vol/volume1/lun1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    },
    "path": "svm1:volume1",
    "svm": {
      "name": "svm1",
      "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
    }
  },
  "exported_snapshot": "string",
  "group_type": "consistency_group",
  "identity_preservation": "string",
  "io_serving_copy": "C1_sti85-vsim-ucs209a_cluster, C1_sti85-vsim-ucs209c_cluster",
  "lag_time": "PT8H35M42S",
  "last_transfer_network_compression_ratio": 61,
  "last_transfer_type": "initialize",
  "master_bias_activated_site": "C1_sti85-vsim-ucs209a_cluster",
  "policy": {
    "name": "Asynchronous",
    "type": "string",
    "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
  },
  "preferred_site": "C1_sti85-vsim-ucs209a_cluster",
  "restore": true,
  "restore_to_snapshot": "string",
  "selective_volumes": [
    {
      "mode": "string",
      "name": "volume1"
    }
  ],
  "source": {
    "cluster": {
      "name": "cluster1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    },
    "luns": {
      "name": "/vol/volume1/lun1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    },
    "path": "svm1:volume1",
    "svm": {
      "name": "svm1",
      "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
    }
  },
  "state": "snapmirrored",
  "throttle": 0,
  "total_transfer_bytes": 1098210312,
  "total_transfer_duration": "PT3M21S",
  "transfer": {
    "end_time": "2020-12-02 18:36:19 -0800",
    "last_updated_time": "2023-09-14 15:39:19 -0700",
    "state": "string",
    "total_duration": "PT28M41S",
    "type": "initialize",
    "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
  },
  "transfer_schedule": {
    "name": "weekly",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "unhealthy_reason": [
    {
      "arguments": [],
      "code": "6621444",
      "message": "Failed to complete update operation on one or more item relationships."
    },
    {
      "arguments": [],
      "code": "6621445",
      "message": "Group Update failed"
    }
  ],
  "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
}
====

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Response

```
Status: 202, Accepted
```

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 13303825
| Could not retrieve information for the SnapMirror policy type

| 13303817
| Unknown value for the SnapMirror state

| 13303829
| Invalid state

| 13303830
| Transient state

| 13303831
| Invalid state for async SnapMirror relationship

| 13303834
| Given input valid only for FlexGroup SnapMirror relationship

| 13303835
| Given flag is valid only when PATCH state is broken_off

| 13303836
| Given flag is valid only when PATCH state is snapmirrored or in_sync

| 13303818
| Invalid state transition requested

| 13303828
| Given state change is not possible for SVM SnapMirror relationship

| 13303833
| Requested state change is not possible

| 13303832
| SnapMirror relationship is already initialized

| 13303824
| Quiescing the SnapMirror relationship has failed

| 13303826
| Required environment variables are not set

| 13303827
| Internal Error

| 13303823
| Quiesce operation timed out

| 13303821
| Invalid SnapMirror policy name/UUID

| 13303819
| Could not retrieve SnapMirror policy information

| 13303851
| Cannot modify attributes of SnapMirror restore relationship

| 13303816
| Could not retrieve the state or status values for the relationship. Wait a few minutes and try the operation again

| 13303837
| Given flags are valid only if SnapMirror state change is requested

| 6619546
| Destination must be a dp volume

| 13303808
| Transition to broken_off state failed

| 13303809
| Transition to paused state failed

| 13303810
| Transition to snapmirrored state failed

| 13303811
| Transition from paused state failed

| 13303820
| SnapMirror policy, transfer_schedule, and throttle, if specified were successfully updated, state transition failed

| 13303856
| SVM is not configured with any data protocol

| 13303857
| SVM is not configured with any network interface

| 13303858
| Internal error. Failed to check LIF and protocols details for SVM

| 13303859
| Internal error. SVM Failover operation failed. SVM operational state is unavailable.

| 13303865
| Modifying the specified SnapMirror policy is not supported.

| 13303866
| Cannot use the specified policy to modify the policy of the relationship.

| 13303867
| Modifying the policy of an async-mirror or a vault relationship is not supported.

| 13303884
| LIF and protocols details are configured incorrectly for SVM.

| 13303996
| The source and destination clusters both have a policy with the same name, but they have different properties.

| 13304062
| Cannot reverse the direction of a SnapMirror DP relationship when the source cluster version is earlier than the destination cluster version.

| 13304070
| Remote peer cluster requires the dp_rest_support capability to support reversing the direction of a DP relationship.

| 13304071
| Failed to access capabilities on remote cluster.

| 13304080
| Specified uuid and name do not match.

| 13304081
| Modifying a property during the operation is not supported.

| 13304082
| The specified properties are mutually exclusive.

| 13304083
| The specified property is not supported because all nodes in the cluster are not capable of supporting the property.

| 13304086
| Reversing the direction of a SnapMirror relationship associated with a policy containing the property create_snapshot_on_source set to false is not supported.

| 6619715
| Modification of relationship is in progress. Retry the command after a few minutes.

| 6619699
| Schedule not found.

| 13304108
| Schedule not found in the Administrative SVM or the SVM for the relationship.

| 13304111
| The SnapMirror active sync relationship consistency groups are nested. Expanding an SnapMirror active sync relationship with a pre-existing DP volume is only supported for flat consistency groups.

| 6621458
| The destination Consistency Group is the source of a SnapMirror Synchronous (SM-S) relationship. Sources of SM-S relationships cannot be the destination of any other SnapMirror relationship.

| 6621782
| A property of the policy is not valid for relationships between these endpoints.
|===

| 13304120    | Values specified for the source.path and destination.path properties do not match the relationship's source.path or destination.path properties.
| 13304003    | IntraCluster flip operation is not supported. |
| 6621125     | The policy is not valid for relationships with FlexGroup volume endpoints. Only policies without snapshot creation schedules are supported for these relationships. |
| 13304093    | The property specified is not supported for the specified relationships. |
| 6622077     | The expand operation has failed on the SnapMirror active sync relationship with specified destination path. |

[cols=2*]
|===
| 6619720
| Relationship information has been updated and is being propagated. Wait a few minutes and try the operation again.

| 13304156
| Either use state as broken-off or failover as true for SVM-DR fail-over operation.

| 13304159
| Could not retrieve the state or status values for the relationship. Wait a few minutes and try the operation again. If the error persists, address the error condition shown.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

SnapMirror Consistency Group failover error message.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|===


[#status]
[.api-collapsible-fifth-title]
status

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Status code


|message
|string
a|SnapMirror Consistency Group failover status.


|===


[#snapmirror_consistency_group_failover]
[.api-collapsible-fifth-title]
snapmirror_consistency_group_failover

SnapMirror Consistency Group failover information. The SnapMirror Consistency Group failover can be a planned or an unplanned operation. Only active SnapMirror Consistency Group failover operation progress can be monitored using this object. In case of an error during the failover operation, the property "consistency_group_failover.error" holds the reason for the error. ONTAP automatically retries any failed SnapMirror Consistency Group failover operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|SnapMirror Consistency Group failover state.


|status
|link:#status[status]
a|

|type
|string
a|SnapMirror Consistency Group failover type.


|===


[#bucket_retention]
[.api-collapsible-fifth-title]
bucket_retention

Specifies the retention-mode and default retention period configured on the destination bucket.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|default_period
|string
a|Specifies the default retention period that is applied to objects while committing them to the WORM state without an associated retention period. The retention period can be in years, or days. The retention period value represents a duration and must be specified in the ISO-8601 duration format.  A period specified for years and days is represented in the ISO-8601 format as "P+++<num>+++Y" and "P+++<num>+++D" respectively, for example "P10Y" represents a duration of 10 years. The period string must contain only a single time element that is, either years, or days. A duration which combines different periods is not supported, for example "P1Y10D" is not supported.+++</num>++++++</num>+++


|===


[#storage_service]
[.api-collapsible-fifth-title]
storage_service

[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|This property indicates whether to create the destination endpoint using storage service.


|enforce_performance
|boolean
a|Optional property to enforce storage service performance on the destination endpoint. This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints.


|name
|string
a|Optional property to specify the storage service name for the destination endpoint. This property is considered when the property "create_destination.storage_service.enabled" is set to "true". When the property "create_destination.storage_service.enabled" is set to "true" and the "create_destination.storage_service.name" for the endpoint is not specified, then ONTAP selects the highest storage service available on the cluster to provision the destination endpoint. This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints.

* enum: ["extreme", "performance", "value"]
* Introduced in: 9.6
* x-nullable: true


|===


[#tiering]
[.api-collapsible-fifth-title]
tiering

[cols=3*,options=header]
|===
|Name
|Type
|Description

|policy
|string
a|Optional property to specify the destination endpoint's tiering policy when "create_destination.tiering.supported" is set to "true". This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints. This property determines whether the user data blocks of the destination endpoint in a FabricPool will be tiered to the cloud store when they become cold. FabricPool combines flash (performance tier) with a cloud store into a single aggregate. Temperature of the destination endpoint volume blocks increases if they are accessed frequently and decreases when they are not.
all &dash; This policy allows tiering of both destination endpoint snapshots and the user transferred data blocks to the cloud store as soon as possible by ignoring the temperature on the volume blocks. This tiering policy is not applicable for Consistency Group destination endpoints or for synchronous relationships.
auto &dash; This policy allows tiering of both destination endpoint snapshots and the active file system user data to the cloud store
none &dash; Destination endpoint volume blocks will not be tiered to the cloud store.
snapshot_only &dash; This policy allows tiering of only the destination endpoint volume snapshots not associated with the active file system. The default tiering policy is "snapshot_only" for a FlexVol volume and "none" for a FlexGroup volume.


|supported
|boolean
a|Optional property to enable provisioning of the destination endpoint volumes on FabricPool aggregates. This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints. Only FabricPool aggregates are used if this property is set to "true" and only non FabricPool aggregates are used if this property is set to "false". Tiering support for a FlexGroup volume can be changed by moving all of the constituents to the required aggregates. Note that in order to tier data, not only do the destination endpoint volumes need to support tiering by using FabricPools, the "create_destination.tiering.policy" must not be "none".


|===


[#snapmirror_destination_creation]
[.api-collapsible-fifth-title]
snapmirror_destination_creation

Use this object to provision the destination endpoint when establishing a SnapMirror relationship for a FlexVol volume, FlexGroup volume, SVM, Consistency Group or ONTAP S3 Bucket. Given a source endpoint, the destination endpoint is provisioned in the SVM specified in the "destination.path" property. While protecting an SVM, the SVM destination endpoint can only be provisioned on the local cluster. To provision the SVM destination endpoint use the optional "source.cluster.name" property to specify the remote cluster name or use the optional "source.cluster.uuid" property to specify the remote cluster UUID. When "create_destination.enabled" option is specified while making a POST for a SnapMirror relationship, the relationship can be automatically initialized by setting the "state" either to "snapmirrored" when the policy is of type "async" or to "in_sync" when the policy is of type "sync". The "destination.path" property must specify the destination endpoint path. For example, for FlexVol volume and FlexGroup volume, the "destination.path" can be specified as +++<destination-svm-name:dp-volume-name>+++, for SVM data protection, the "destination.path" must be specified as <destination-svm-name:>, and for Consistency Group, the "destination.path" must be specified as <destination-svm-name:> along with the "destination.consistency_group_volumes" or "destination.luns" property to indicate the list of destination volumes or LUNs of type "DP" in the Consistency Group. For a FlexVol volume, a FlexGroup volume, Consistency Group or a Bucket destination endpoint, the properties in this object can be specified either from the source or the destination cluster. For an SVM destination endpoint, the properties in this object can be specified from the destination cluster only. This object is not supported for non ONTAP endpoints. While protecting a S3 Bucket, the optional "size" property can be used to create ONTAP S3 Bucket destination endpoint of the specified size.</destination-svm-name:></destination-svm-name:>+++</destination-svm-name:dp-volume-name>+++


[cols=3*,options=header]
|===
|Name
|Type
|Description

|bucket_retention
|link:#bucket_retention[bucket_retention]
a|Specifies the retention-mode and default retention period configured on the destination bucket.


|enabled
|boolean
a|Optional property to create the destination endpoint when establishing a SnapMirror relationship. It is assumed to be "false" if no other property is set and assumed to be "true" if any other property is set.


|size
|integer
a|Optional property to specify the size of destination endpoint in bytes. This property is applicable only to ONTAP S3 Bucket endpoints. The minimum size for S3 bucket is 80MB and maximum size is 64TB. If not specified, system will create destination with default size of 800GB.

* Introduced in: 9.10
* x-nullable: true


|snapshot_locking_enabled
|boolean
a|Optional property to create the destination endpoint with snapshot locking enabled when establishing a SnapMirror relationship. This property is applicable to FlexVol volumes and FlexGroup volumes.


|storage_service
|link:#storage_service[storage_service]
a|

|tiering
|link:#tiering[tiering]
a|

|===


[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#consistency_group_volumes]
[.api-collapsible-fifth-title]
consistency_group_volumes

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|===


[#luns]
[.api-collapsible-fifth-title]
luns

Optional property for a SnapMirror endpoint. Specifies the list of source LUNs and optionally list of destination LUNs during SnapMirror Consistency Group LUN restore operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of a LUN.
A LUN is located within a volume. Optionally, it can be located within a qtree in a volume.

LUN names are paths of the form "/vol/<volume>[/<qtree>]/<namespace>" where the qtree name is optional.


|uuid
|string
a|The unique identifier of the LUN.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#snapmirror_endpoint]
[.api-collapsible-fifth-title]
snapmirror_endpoint

Endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to create the destination SVM endpoint or to establish an SVM DR relationship must have the property "cluster" populated with the remote cluster details. A POST request to create the destination FlexVol volume, FlexGroup volume, Consistency Group, ONTAP S3 bucket and NON-ONTAP object-store endpoints can optionally specify the "cluster" property when the source SVM and the destination SVM are peered. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster[cluster]
a|

|luns
|link:#luns[luns]
a|Optional property for a SnapMirror endpoint. Specifies the list of source LUNs and optionally list of destination LUNs during SnapMirror Consistency Group LUN restore operation.


|path
|string
a|ONTAP FlexVol/FlexGroup - svm1:volume1
ONTAP SVM               - svm1:
ONTAP Consistency Group - svm1:/cg/cg_name
ONTAP S3                - svm1:/bucket/bucket1
NON-ONTAP               - objstore1:/objstore

* example: svm1:volume1
* Introduced in: 9.6
* x-nullable: true


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#policy]
[.api-collapsible-fifth-title]
policy

Basic policy information of the relationship.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the SnapMirror policy.


|type
|string
a|

|uuid
|string
a|Unique identifier of the SnapMirror policy.


|===


[#selective_volumes]
[.api-collapsible-fifth-title]
selective_volumes

[cols=3*,options=header]
|===
|Name
|Type
|Description

|mode
|string
a|Indicates whether volumes need to be included or excluded for SnapMirror Active Sync NAS relationship. Default behavior is to protect all volumes under a vserver.


|name
|string
a|The name of the volume.


|===


[#snapmirror_source_endpoint]
[.api-collapsible-fifth-title]
snapmirror_source_endpoint

Source endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster[cluster]
a|

|luns
|link:#luns[luns]
a|Optional property for a SnapMirror endpoint. Specifies the list of source LUNs and optionally list of destination LUNs during SnapMirror Consistency Group LUN restore operation.


|path
|string
a|ONTAP FlexVol/FlexGroup - svm1:volume1
ONTAP SVM               - svm1:
ONTAP Consistency Group - svm1:/cg/cg_name
ONTAP S3                - svm1:/bucket/bucket1
NON-ONTAP               - objstore1:/objstore

* example: svm1:volume1
* Introduced in: 9.14
* x-nullable: true


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#svmdr_volumes]
[.api-collapsible-fifth-title]
svmdr_volumes

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|===


[#transfer]
[.api-collapsible-fifth-title]
transfer

Basic information on the current transfer or the last transfer if there is no active transfer at the time of the request.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|bytes_transferred
|integer
a|Total bytes transferred in the current or last successful transfer.


|end_time
|string
a|End time of the last transfer.


|last_updated_time
|string
a|Last updated time of the bytes transferred in the current transfer.


|state
|string
a|

|total_duration
|string
a|Elapsed time to transfer all snapshots for the last successful transfer.


|type
|string
a|Specifies the operation type of the current transfer on the relationship. The _initialize_ transfer occurs when the relationship state changes from "uninitialized" to "snapmirrored" or "in_sync". The _update_ transfer occurs when snapshots are being transferred from the source endpoint to the destination endpoint as part of a scheduled or manual update. The _resync_ transfer occurs when the relationship state changes from "broken_off" to "snapmirrored" or "in_sync". The _restore_ transfer occurs when a snapshot is being restored from a destination endpoint to another endpoint.


|uuid
|string
a|Transfer UUID. This property is applicable only for active transfers.


|===


[#transfer_schedule]
[.api-collapsible-fifth-title]
transfer_schedule

Schedule used to update asynchronous relationships. This "transfer_schedule" overrides the "transfer_schedule" set on the SnapMirror relationship's policy. To remove the "transfer_schedule", set its value to null (no-quotes). Only cron schedules are supported for SnapMirror.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_error]
[.api-collapsible-fifth-title]
snapmirror_error

SnapMirror error


[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[string]
a|Arguments present in the error message encountered.


|code
|string
a|Error code


|message
|string
a|Error message


|===


[#snapmirror_relationship]
[.api-collapsible-fifth-title]
snapmirror_relationship

SnapMirror relationship information. The SnapMirror relationship can be either "async" or "sync" based on the type of SnapMirror policy associated with the relationship. The source and destination endpoints of a SnapMirror relationship must be of the same type, for example, if the source endpoint is a FlexVol volume then the destination endpoint must be a FlexVol volume.
The SnapMirror policy type "async" can be used when the SnapMirror relationship has FlexVol volume or FlexGroup volume or SVM as the endpoint. The SnapMirror policy type "sync" can be used when the SnapMirror relationship has FlexVol volume as the endpoint. The SnapMirror policy type "sync" with "sync_type" as "automated_failover" can be used when the SnapMirror relationship has Consistency Group as the endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|backoff_level
|string
a|Specifies the SnapMirror backoff level due to Client Ops for FlexVol SnapMirror relationships.


|destination
|link:#snapmirror_endpoint[snapmirror_endpoint]
a|Endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to create the destination SVM endpoint or to establish an SVM DR relationship must have the property "cluster" populated with the remote cluster details. A POST request to create the destination FlexVol volume, FlexGroup volume, Consistency Group, ONTAP S3 bucket and NON-ONTAP object-store endpoints can optionally specify the "cluster" property when the source SVM and the destination SVM are peered. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.

* Introduced in: 9.6


|exported_snapshot
|string
a|Snapshot exported to clients on destination.


|group_type
|string
a|Specifies the group type of the top level SnapMirror relationship. The volume relationships are shown as _none_, the SVMDR relationships are shown as _svm_dr_, the Consistency Group relationships are shown as _consistency_group_, FlexGroup volume relationships are shown as _flexgroup_ and in Snapmirror Active Sync NAS relationships the group type is _coordination_group_.


|healthy
|boolean
a|Is the relationship healthy?


|identity_preservation
|string
a|Specifies which configuration of the source SVM is replicated to the destination SVM. This property is applicable only for SVM data protection with "async" policy type. This "identity_preservation" overrides the "identity_preservation" set on the SnapMirror relationship's policy.


|io_serving_copy
|string
a|Specifies the sites serving I/O for the SnapMirror active sync relationship.


|lag_time
|string
a|Time since the exported snapshot was created.


|last_transfer_network_compression_ratio
|string
a|Specifies the compression ratio achieved for the data sent over the wire with network compression enabled for the last successful transfer.


|last_transfer_type
|string
a|Specifies the operation type of the last transfer that occurred on the relationship. The _initialize_ transfer occurs when the relationship state changes from uninitialized to snapmirrored or in_sync. The _update_ transfer occurs when the snapshots are transferred from the source endpoint to the destination endpoint as part of scheduled or manual update. The _resync_ transfer occurs when the relationship state changes from broken_off to snapmirrored or in_sync. The _restore_ transfer occurs when the snapshot is restored from a destination endpoint to another endpoint.


|master_bias_activated_site
|string
a|Specifies the Master Bias Activated Site for the SnapMirror active sync relationship.


|policy
|link:#policy[policy]
a|Basic policy information of the relationship.


|preferred_site
|string
a|Specifies the Primary Site of the SnapMirror active sync relationship.


|preserve
|boolean
a|Set to true on resync to preserve snapshots on the destination that are newer than the latest common snapshot. This property is applicable only for relationships with FlexVol volume or FlexGroup volume endpoints and when the PATCH state is being changed to "snapmirrored".


|quick_resync
|boolean
a|Set to true to reduce resync time by not preserving storage efficiency. This property is applicable only for relationships with FlexVol volume endpoints and SVMDR relationships when the PATCH state is being changed to "snapmirrored".


|recover_after_break
|boolean
a|Set to true to recover from a failed SnapMirror break operation on a FlexGroup volume relationship. This restores all destination FlexGroup constituent volumes to the latest snapshot, and any writes to the read-write constituents are lost. This property is applicable only for SnapMirror relationships with FlexGroup volume endpoints and when the PATCH state is being changed to "broken_off".


|restore_to_snapshot
|string
a|Specifies the snapshot to restore to on the destination during the break operation. This property is applicable only for SnapMirror relationships with FlexVol volume endpoints and when the PATCH state is being changed to "broken_off".


|selective_volumes
|array[link:#selective_volumes[selective_volumes]]
a|This field specifies the list of volumes to be protected under a vserver.


|source
|link:#snapmirror_source_endpoint[snapmirror_source_endpoint]
a|Source endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.


|state
|string
a|State of the relationship.
To initialize the relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".
To break the relationship, PATCH the state to "broken_off" for relationships with a policy of type "async" or "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" cannot be "broken_off".
To resync the relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" can be in "broken_off" state due to a failed attempt of SnapMirror failover.
To pause the relationship, suspending further transfers, PATCH the state to "paused" for relationships with a policy of type "async" or "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" cannot be "paused".
To resume transfers for a paused relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".
The entries "in_sync", "out_of_sync", "synchronizing", "expanding", and "shrinking" are only applicable to relationships with a policy of type "sync". A PATCH call on the state change only triggers the transition to the specified state. You must poll on the "state", "healthy" and "unhealthy_reason" properties using a GET request to determine if the transition is successful. To automatically initialize the relationship when specifying "create_destination" property, set the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".


|throttle
|integer
a|Throttle, in KBs per second. This "throttle" overrides the "throttle" set on the SnapMirror relationship's policy. If neither of these are set, defaults to 0, which is interpreted as unlimited.


|total_transfer_bytes
|integer
a|Cumulative bytes transferred for the relationship.


|total_transfer_duration
|string
a|Indicates the cumulative duration of all transfers since the last aggregate relocation, takeover/giveback, or metrocluster switchover/switchback involving the node that hosts the relationship.


|transfer
|link:#transfer[transfer]
a|Basic information on the current transfer or the last transfer if there is no active transfer at the time of the request.


|transfer_schedule
|link:#transfer_schedule[transfer_schedule]
a|Schedule used to update asynchronous relationships. This "transfer_schedule" overrides the "transfer_schedule" set on the SnapMirror relationship's policy. To remove the "transfer_schedule", set its value to null (no-quotes). Only cron schedules are supported for SnapMirror.


|unhealthy_reason
|array[link:#snapmirror_error[snapmirror_error]]
a|Reason the relationship is not healthy. It is a concatenation of up to four levels of error messages.


|uuid
|string
a|Unique identifier of the SnapMirror relationship.


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
