---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-storage-aggregates-cloud-stores-.html'
summary: 'Update a cloud store'
---

= Update a cloud store

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/storage/aggregates/{aggregate.uuid}/cloud-stores/{target.uuid}`#

*Introduced In:* 9.6

Updates the cloud store specified by the UUID with the fields in the body. This request starts a job and returns a link to that job.

== Related ONTAP commands

* `storage aggregate object-store modify`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|aggregate.uuid
|string
|path
|True
a|Aggregate UUID


|target.uuid
|string
|path
|True
a|Cloud target UUID


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|availability
|string
a|Availability of the object store.


|availability_at_partner
|string
a|Availability of the object store at the HA partner.


|mirror_degraded
|boolean
a|This field identifies if the mirror cloud store is in sync with the primary cloud store of a FabricPool.


|primary
|boolean
a|This field indicates whether the cloud store is the primary cloud store of a mirrored FabricPool.


|resync-progress
|integer
a|Resync progress of the mirror object store in percentage.


|unavailable_reason
|link:#unavailable_reason[unavailable_reason]
a|

|unreclaimed_space_threshold
|integer
a|Usage threshold for reclaiming unused space in the cloud store. Valid values are 0 to 99. The default value depends on the provider type. This can be specified in PATCH but not POST.


|used
|integer
a|The amount of object space used. Calculated every 5 minutes and cached.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "availability": "string",
  "availability_at_partner": "string",
  "resync-progress": 0,
  "unavailable_reason": {
    "message": "string"
  },
  "unreclaimed_space_threshold": 20,
  "used": 0
}
====

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Response

```
Status: 202, Accepted
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 787154
| The Object stores are currently not synchronized. Check the mirror resync status.

| 787156
| Modifying the attributes of a mirror object store is not allowed.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#aggregate]
[.api-collapsible-fifth-title]
aggregate

Aggregate


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|===


[#target]
[.api-collapsible-fifth-title]
target

Cloud target


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#unavailable_reason]
[.api-collapsible-fifth-title]
unavailable_reason

[cols=3*,options=header]
|===
|Name
|Type
|Description

|message
|string
a|Indicates why the object store is unavailable.


|===


[#cloud_store]
[.api-collapsible-fifth-title]
cloud_store

[cols=3*,options=header]
|===
|Name
|Type
|Description

|availability
|string
a|Availability of the object store.


|availability_at_partner
|string
a|Availability of the object store at the HA partner.


|mirror_degraded
|boolean
a|This field identifies if the mirror cloud store is in sync with the primary cloud store of a FabricPool.


|primary
|boolean
a|This field indicates whether the cloud store is the primary cloud store of a mirrored FabricPool.


|resync-progress
|integer
a|Resync progress of the mirror object store in percentage.


|unavailable_reason
|link:#unavailable_reason[unavailable_reason]
a|

|unreclaimed_space_threshold
|integer
a|Usage threshold for reclaiming unused space in the cloud store. Valid values are 0 to 99. The default value depends on the provider type. This can be specified in PATCH but not POST.


|used
|integer
a|The amount of object space used. Calculated every 5 minutes and cached.


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
