---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-protocols-fpolicy-events-.html'
summary: 'Update a specific FPolicy event configuration for an SVM'
---

= Update a specific FPolicy event configuration for an SVM

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/protocols/fpolicy/{svm.uuid}/events/{name}`#

*Introduced In:* 9.6

Updates a specific FPolicy event configuration for an SVM. A cluster-level FPolicy event configuration cannot be modified for a data SVM through REST. When the file operations and filters fields are modified, the previous values are retained and new values are added to the list of previous values. To remove a particular file operation or filter, set its value to false in the request.

== Related ONTAP commands

* `fpolicy policy event modify`

== Learn more

* link:protocols_fpolicy_svm.uuid_events_endpoint_overview.html[DOC /protocols/fpolicy/{svm.uuid}/events]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|name
|string
|path
|True
a|

|svm.uuid
|string
|path
|True
a|UUID of the SVM to which this object belongs.

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|file_operations
|link:#file_operations[file_operations]
a|Specifies the file operations for the FPolicy event. You must specify a valid protocol in the protocol parameter.
The event will check the operations specified from all client requests using the protocol.


|filters
|link:#filters[filters]
a|Specifies the list of filters for a given file operation for the specified protocol.
When you specify the filters, you must specify the valid protocols and a valid file operations.


|monitor_fileop_failure
|boolean
a|Specifies whether failed file operations monitoring is required.


|protocol
|string
a|Protocol for which event is created. If you specify protocol, then you
must also specify a valid value for the file operation parameters.
The value of this parameter must be one of the following:

***** cifs  - for the CIFS protocol.

***** nfsv3 - for the NFSv3 protocol.

***** nfsv4 - for the NFSv4 protocol.


|svm
|link:#svm[svm]
a|

|volume_monitoring
|boolean
a|Specifies whether volume operation monitoring is required.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "protocol": "string",
  "svm": {
    "uuid": "string"
  }
}
====

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default
```

|===
| Error Code | Description

| 9764873
| The event is a cluster event

| 9764929
| The file operation is not supported by the protocol

| 9764955
| The filter is not supported by the protocol

| 9764930
| The filter is not supported by any of the file operations

| 9764946
| The protocol is specified without file operation or a file operation and filter pair

| 9765048
| The monitor fileop failure option is set without protocol and file operations
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#file_operations]
[.api-collapsible-fifth-title]
file_operations

Specifies the file operations for the FPolicy event. You must specify a valid protocol in the protocol parameter.
The event will check the operations specified from all client requests using the protocol.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|access
|boolean
a|Access operations


|close
|boolean
a|File close operations


|create
|boolean
a|File create operations


|create_dir
|boolean
a|Directory create operations


|delete
|boolean
a|File delete operations


|delete_dir
|boolean
a|Directory delete operations


|getattr
|boolean
a|Get attribute operations


|link
|boolean
a|Link operations


|lookup
|boolean
a|Lookup operations


|open
|boolean
a|File open operations


|read
|boolean
a|File read operations


|rename
|boolean
a|File rename operations


|rename_dir
|boolean
a|Directory rename operations


|setattr
|boolean
a|Set attribute operations


|symlink
|boolean
a|Symbolic link operations


|write
|boolean
a|File write operations


|===


[#filters]
[.api-collapsible-fifth-title]
filters

Specifies the list of filters for a given file operation for the specified protocol.
When you specify the filters, you must specify the valid protocols and a valid file operations.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|close_with_modification
|boolean
a|Filter the client request for close with modification.


|close_with_read
|boolean
a|Filter the client request for close with read.


|close_without_modification
|boolean
a|Filter the client request for close without modification.


|exclude_directory
|boolean
a|Filter the client requests for directory operations. When this filter is specified directory operations are not monitored.


|first_read
|boolean
a|Filter the client requests for the first-read.


|first_write
|boolean
a|Filter the client requests for the first-write.


|monitor_ads
|boolean
a|Filter the client request for alternate data stream.


|offline_bit
|boolean
a|Filter the client request for offline bit set. FPolicy server receives notification only when offline files are accessed.


|open_with_delete_intent
|boolean
a|Filter the client request for open with delete intent.


|open_with_write_intent
|boolean
a|Filter the client request for open with write intent.


|setattr_with_access_time_change
|boolean
a|Filter the client setattr requests for changing the access time of a file or directory.


|setattr_with_allocation_size_change
|boolean
a|Filter the client setattr requests for changing the allocation size of a file.


|setattr_with_creation_time_change
|boolean
a|Filter the client setattr requests for changing the creation time of a file or directory.


|setattr_with_dacl_change
|boolean
a|Filter the client setattr requests for changing dacl on a file or directory.


|setattr_with_group_change
|boolean
a|Filter the client setattr requests for changing group of a file or directory.


|setattr_with_mode_change
|boolean
a|Filter the client setattr requests for changing the mode bits on a file or directory.


|setattr_with_modify_time_change
|boolean
a|Filter the client setattr requests for changing the modification time of a file or directory.


|setattr_with_owner_change
|boolean
a|Filter the client setattr requests for changing owner of a file or directory.


|setattr_with_sacl_change
|boolean
a|Filter the client setattr requests for changing sacl on a file or directory.


|setattr_with_size_change
|boolean
a|Filter the client setattr requests for changing the size of a file.


|write_with_size_change
|boolean
a|Filter the client request for write with size change.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|SVM UUID


|===


[#fpolicy_event]
[.api-collapsible-fifth-title]
fpolicy_event

The information that a FPolicy process needs to determine what file access operations to monitor and for which of the monitored events notifications should be sent to the external FPolicy server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|file_operations
|link:#file_operations[file_operations]
a|Specifies the file operations for the FPolicy event. You must specify a valid protocol in the protocol parameter.
The event will check the operations specified from all client requests using the protocol.


|filters
|link:#filters[filters]
a|Specifies the list of filters for a given file operation for the specified protocol.
When you specify the filters, you must specify the valid protocols and a valid file operations.


|monitor_fileop_failure
|boolean
a|Specifies whether failed file operations monitoring is required.


|protocol
|string
a|Protocol for which event is created. If you specify protocol, then you
must also specify a valid value for the file operation parameters.
The value of this parameter must be one of the following:

***** cifs  - for the CIFS protocol.

***** nfsv3 - for the NFSv3 protocol.

***** nfsv4 - for the NFSv4 protocol.


|svm
|link:#svm[svm]
a|

|volume_monitoring
|boolean
a|Specifies whether volume operation monitoring is required.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
