---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-cluster-ntp-keys-.html'
summary: 'Update NTP symmetric authentication key details'
---

= Update NTP symmetric authentication key details

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/cluster/ntp/keys/{id}`#

*Introduced In:* 9.7

Updates the details of a specific NTP symmetric authentication key by numeric
identifier or index (ID).

== Required properties

* `digest_type` - Shared private key cryptographic hash type.
* `value` - Value of shared private key.

== Related ONTAP commands

* `cluster time-service ntp key modify`

== Learn more

* link:cluster_ntp_keys_endpoint_overview.html[DOC /cluster/ntp/keys]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|id
|integer
|path
|True
a|Key identifier

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|digest_type
|string
a|The type of cryptographic hash used to create and verify the NTP's message authentication code appended to each NTP packet header.


|value
|string
a|A hexadecimal digit string that represents the cryptographic key that is shared with the remote NTP server.
The current expected length is 40 characters.

Use the cryptographic key and key ID to create a unique hash value used to authenticate the rest of the NTP data.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "digest_type": "sha1",
  "value": "da39a3ee5e6b4b0d3255bfef95601890afd80709"
}
====

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 2097187
| An invalid SHA1 key was provided.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#ntp_key]
[.api-collapsible-fifth-title]
ntp_key

[cols=3*,options=header]
|===
|Name
|Type
|Description

|digest_type
|string
a|The type of cryptographic hash used to create and verify the NTP's message authentication code appended to each NTP packet header.


|value
|string
a|A hexadecimal digit string that represents the cryptographic key that is shared with the remote NTP server.
The current expected length is 40 characters.

Use the cryptographic key and key ID to create a unique hash value used to authenticate the rest of the NTP data.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
