---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-support-snmp-users-.html'
summary: 'Update the comment parameter of an SNMP user'
---

= Update the comment parameter of an SNMP user

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/support/snmp/users/{engine_id}/{name}`#

*Introduced In:* 9.7

Updates the comment parameter of an SNMP user.

== Optional properties

* `comment` - Comment text.

== Related ONTAP commands

* `security login modify`

== Learn more

* link:support_snmp_users_engine_id_name_endpoint_overview.html[DOC /support/snmp/users/\{engine_id}/\{name}]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|engine_id
|string
|path
|True
a|Engine ID of owning SVM or remote switch.


|name
|string
|path
|True
a|SNMP user name.


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|Optional comment text.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "comment": "This is a comment."
}
====

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 2621475
| This operation is not allowed on a node SVM.

| 2621699
| This operation is not allowed on a system SVM.

| 5636123
| Cannot create an SNMP user with a role other than readonly, none, or admin.

| 5636124
| Cannot create an SNMP user with a role other than vsadmin-readonly, none, or vsadmin.

| 5832712
| Cannot modify attributes for user "diag."

| 7077906
| Cannot use given role with this SVM because a role with that name has not been defined for the SVM.

| 9043999
| ONTAP failed to create an SNMPv3 user because SNMPv3 is disabled in the cluster.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#owner]
[.api-collapsible-fifth-title]
owner

Optional name and UUID of owning Storage Virtual Machine (SVM).


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#snmpv3]
[.api-collapsible-fifth-title]
snmpv3

Optional parameter that can be specified only for an SNMPv3 user i.e. when 'authentication_method' is either 'usm' or 'both'. This parameter defines the SNMPv3 credentials for an SNMPv3 user.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|authentication_protocol
|string
a|Authentication protocol.


|privacy_protocol
|string
a|Privacy protocol.


|===


[#snmp_user]
[.api-collapsible-fifth-title]
snmp_user

An SNMP user can be an SNMPv1/SNMPv2c user or an SNMPv3 user. SNMPv1/SNMPv2c user is also called a "community" user. An SNMPv3 user, also called a User-based Security Model (USM) user, can be a local SNMPv3 user or a remote SNMPv3 user. A local SNMPv3 user can be used for querying ONTAP SNMP server over SNMPv3 and/or for sending SNMPv3 traps. The local SNMPv3 user used for sending SNMPv3 traps must be configured with the same authentication and privacy credentials on the traphost receiver as well. A remote SNMPv3 user is also configured on a remote switch and used by ONTAP SNMP client functionality to query the remote switch over SNMPv3. An SNMP user is scoped to its owning Storage Virtual Machine (SVM). Owning SVM could be a data SVM or the administrative SVM.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|Optional comment text.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
