---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-protocols-active-directory-.html'
summary: 'Modify an Active Directory account for an SVM'
---

= Modify an Active Directory account for an SVM

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/protocols/active-directory/{svm.uuid}`#

*Introduced In:* 9.12

Modifies the Active Directory account for a given SVM.

== Related ONTAP commands

* `vserver active-directory modify`
* `vserver cifs security modify`

== Important notes

* Patching Active Directory account is asynchronous. Response contains Task UUID and Link that can be queried to get the status.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|svm.uuid
|string
|path
|True
a|UUID of the SVM to which this object belongs.

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|discovered_servers
|array[link:#discovered_servers[discovered_servers]]
a|Specifies the discovered servers records.


|force_account_overwrite
|boolean
a|If set to true and a machine account exists with the same name as specified in "name" in Active Directory, it will be overwritten and reused.


|fqdn
|string
a|Fully qualified domain name.


|password
|string
a|Administrator password required for Active Directory account creation, modification and deletion.


|preferred_dcs
|array[link:#preferred_dcs[preferred_dcs]]
a|Specifies the preferred domain controller (DC) records.


|security
|link:#active_directory_security[active_directory_security]
a|

|username
|string
a|Administrator username required for Active Directory account creation, modification and deletion.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "discovered_servers": [
    {
      "domain": "server1.com",
      "node": {
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "preference": "preferred",
      "server": {
        "ip": "7.4.3.1",
        "name": "scspk0659102001",
        "type": "kerberos"
      },
      "state": "ok"
    }
  ],
  "force_account_overwrite": "",
  "fqdn": "server1.com",
  "password": "testpwd",
  "security": {
    "advertised_kdc_encryptions": [
      "string"
    ]
  },
  "username": "admin"
}
====

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|discovered_servers
|array[link:#discovered_servers[discovered_servers]]
a|Specifies the discovered servers records.


|force_account_overwrite
|boolean
a|If set to true and a machine account exists with the same name as specified in "name" in Active Directory, it will be overwritten and reused.


|fqdn
|string
a|Fully qualified domain name.


|password
|string
a|Administrator password required for Active Directory account creation, modification and deletion.


|preferred_dcs
|array[link:#preferred_dcs[preferred_dcs]]
a|Specifies the preferred domain controller (DC) records.


|security
|link:#active_directory_security[active_directory_security]
a|

|username
|string
a|Administrator username required for Active Directory account creation, modification and deletion.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "discovered_servers": [
    {
      "domain": "server1.com",
      "node": {
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "preference": "preferred",
      "server": {
        "ip": "7.4.3.1",
        "name": "scspk0659102001",
        "type": "kerberos"
      },
      "state": "ok"
    }
  ],
  "force_account_overwrite": "",
  "fqdn": "server1.com",
  "password": "testpwd",
  "security": {
    "advertised_kdc_encryptions": [
      "string"
    ]
  },
  "username": "admin"
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 656464
| Failed to modify the Active Directory machine account. Reason: Invalid Credentials.

| 656465
| Failed to create the Active Directory machine account. Reason: An account with this name already exists.

| 656466
| Failed to create the Active Directory machine account. Reason: Unable to connect to any domain controllers.

| 656467
| Failed to modify the Active Directory machine account. Reason: Organizational-Unit not found.

| 656478
| Failed to create the Active Directory machine account. Reason: KDC has no support for encryption type.

| 656490
| Unable to modify the Active Directory account. The Active Directory account name is already used by another SVM.

| 656495
| Failed to update Active Directory security settings for SVM.

| 656496
| Failed to update Active Directory security settings for SVM. Reason: KDC has no support for encryption type.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#active_directory_discovered_server_reference]
[.api-collapsible-fifth-title]
active_directory_discovered_server_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|string
a|The IP address of the server that was discovered.


|name
|string
a|Server Name


|type
|string
a|The type of the server that was discovered.


|===


[#discovered_servers]
[.api-collapsible-fifth-title]
discovered_servers

[cols=3*,options=header]
|===
|Name
|Type
|Description

|domain
|string
a|The Active Directory domain that the discovered server is a member of.


|node
|link:#node[node]
a|

|preference
|string
a|The preference level of the server that was discovered.


|server
|link:#active_directory_discovered_server_reference[active_directory_discovered_server_reference]
a|

|state
|string
a|The status of the connection to the server that was discovered.


|===


[#preferred_dcs]
[.api-collapsible-fifth-title]
preferred_dcs
[#active_directory_security]
[.api-collapsible-fifth-title]
active_directory_security

[cols=3*,options=header]
|===
|Name
|Type
|Description

|advertised_kdc_encryptions
|array[string]
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#active_directory]
[.api-collapsible-fifth-title]
active_directory

[cols=3*,options=header]
|===
|Name
|Type
|Description

|discovered_servers
|array[link:#discovered_servers[discovered_servers]]
a|Specifies the discovered servers records.


|force_account_overwrite
|boolean
a|If set to true and a machine account exists with the same name as specified in "name" in Active Directory, it will be overwritten and reused.


|fqdn
|string
a|Fully qualified domain name.


|password
|string
a|Administrator password required for Active Directory account creation, modification and deletion.


|preferred_dcs
|array[link:#preferred_dcs[preferred_dcs]]
a|Specifies the preferred domain controller (DC) records.


|security
|link:#active_directory_security[active_directory_security]
a|

|username
|string
a|Administrator username required for Active Directory account creation, modification and deletion.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
