---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-svm-peers-.html'
summary: 'Update an SVM peer relationship'
---

= Update an SVM peer relationship

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/svm/peers/{uuid}`#

*Introduced In:* 9.6

Updates the SVM peer relationship.

== Related ONTAP commands

* `vserver peer modify`

== Examples

The following examples show how to update an SVM peer relationship. The input parameter 'name' refers to the local name of the peer SVM.

. Accepts an SVM peer relationship

----
 PATCH "/api/svm/peers/d3268a74-ee76-11e8-a9bb-005056ac6dc9" '{"state":"peered"}'
----

. Updates the local name of an SVM peer relationship

----
 PATCH "/api/svm/peers/d3268a74-ee76-11e8-a9bb-005056ac6dc9" '{"name":"vs2"}'
----

. Suspends an SVM peer relationship using force flag

----
 PATCH "/api/svm/peers/d3268a74-ee76-11e8-a9bb-005056ac6dc9" '{"state":"suspended", "force": "true"}'
----

== Learn more

* link:svm_peers_endpoint_overview.html[DOC /svm/peers]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|SVM peer relationship UUID

* Introduced in: 9.7


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|applications
|array[string]
a|A list of applications for an SVM peer relationship.


|force
|boolean
a|Use this to suspend, resume or delete the SVM peer relationship even if the remote cluster is not accessible due to, for example, network connectivity issues.


|name
|string
a|A peer SVM alias name to avoid a name conflict on the local cluster.


|state
|string
a|SVM peering state. To accept a pending SVM peer request, PATCH the state to "peered". To reject a pending SVM peer request, PATCH the state to "rejected". To suspend a peered SVM peer relationship, PATCH the state to "suspended". To resume a suspended SVM peer relationship, PATCH the state to "peered". The states "initiated", "pending", and "initializing" are system-generated and cannot be used for PATCH.


|uuid
|string
a|SVM peer relationship UUID


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "applications": [
    "snapmirror",
    "lun_copy"
  ],
  "name": "string",
  "state": "peered",
  "uuid": "string"
}
====

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Response

```
Status: 202, Accepted
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error codes | Description

| 13434889
| Internal error. Wait and retry.

| 26345575
| The specified peer cluster name and peer cluster UUID do not match.

| 26345576
| Given peer state is invalid.

| 26345577
| One of the following is required: applications, state, or name.

| 26345578
| Internal error. Unable to retrieve local or peer SVM name.

| 26345579
| The specified field is invalid.

| 26345581
| Peer cluster name could not be retrieved or validated.

| 9896077
| The peer relationship is in use by FlexCache. View the FlexCache relationships, delete them and retry the operation.

| 9896088
| System generated a name for the peer SVM because of a naming conflict. Use the name property to uniquely identify the peer SVM alias name.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#peer]
[.api-collapsible-fifth-title]
peer

Details for a peer SVM object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster[cluster]
a|

|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

Local SVM details


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#svm_peer]
[.api-collapsible-fifth-title]
svm_peer

An SVM peer relationship object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|applications
|array[string]
a|A list of applications for an SVM peer relationship.


|force
|boolean
a|Use this to suspend, resume or delete the SVM peer relationship even if the remote cluster is not accessible due to, for example, network connectivity issues.


|name
|string
a|A peer SVM alias name to avoid a name conflict on the local cluster.


|state
|string
a|SVM peering state. To accept a pending SVM peer request, PATCH the state to "peered". To reject a pending SVM peer request, PATCH the state to "rejected". To suspend a peered SVM peer relationship, PATCH the state to "suspended". To resume a suspended SVM peer relationship, PATCH the state to "peered". The states "initiated", "pending", and "initializing" are system-generated and cannot be used for PATCH.


|uuid
|string
a|SVM peer relationship UUID


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
