---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-storage-snapshot-policies-.html'
summary: 'Update a snapshot policy'
---

= Update a snapshot policy

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/storage/snapshot-policies/{uuid}`#

*Introduced In:* 9.6

Updates a snapshot policy

== Related ONTAP commands

* `snapshot policy modify`
* `snapshot policy modify-schedule`
* `snapshot policy add-schedule`

== Learn more

* link:storage_snapshot-policies_endpoint_overview.html[DOC /storage/snapshot-policies]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|Snapshot policy UUID

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment associated with the snapshot policy.


|enabled
|boolean
a|Is the snapshot policy enabled?


|scope
|string
a|Set to "svm" when the request is on a data SVM, otherwise set to "cluster".


|uuid
|string
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "comment": "string",
  "enabled": 1,
  "scope": "string",
  "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
}
====

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default
```

ONTAP Error Response Code

|===
| Error Code | Description

| 1638414
| Cannot enable policy. Reason: Schedule not found.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#schedule]
[.api-collapsible-fifth-title]
schedule

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#copies]
[.api-collapsible-fifth-title]
copies

[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|The number of snapshots to maintain for this schedule.


|prefix
|string
a|The prefix to use while creating snapshots at regular intervals.


|retention_period
|string
a|The retention period of snapshots for this schedule. The retention period value represents a duration and must be specified in the ISO-8601 duration format. The retention period can be in years, months, days, hours, and minutes. A period specified for years, months, and days is represented in the ISO-8601 format as "P+++<num>+++Y", "P+++<num>+++M", "P+++<num>+++D" respectively, for example "P10Y" represents a duration of 10 years. A duration in hours and minutes is represented by "PT+++<num>+++H" and "PT+++<num>+++M" respectively. The period string must contain only a single time element that is, either years, months, days, hours, or minutes. A duration which combines different periods is not supported, for example "P1Y10M" is not supported.+++</num>++++++</num>++++++</num>++++++</num>++++++</num>+++


|schedule
|link:#schedule[schedule]
a|

|snapmirror_label
|string
a|Label for SnapMirror operations


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#snapshot_policy]
[.api-collapsible-fifth-title]
snapshot_policy

The snapshot policy object is associated with a read-write volume used to create and delete snapshots at regular intervals.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment associated with the snapshot policy.


|enabled
|boolean
a|Is the snapshot policy enabled?


|scope
|string
a|Set to "svm" when the request is on a data SVM, otherwise set to "cluster".


|uuid
|string
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
