---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-cluster-metrocluster.html'
summary: 'Initiate a switchover, heal, or switchback operation'
---

= Initiate a switchover, heal, or switchback operation

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/cluster/metrocluster`#

*Introduced In:* 9.8

Initiates a switchover, heal or switchback operation.

== Related ONTAP commands

* `metrocluster switchover`
* `metrocluster switchback`
* `metrocluster heal`
* `metrocluster modify`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|action
|string
|query
|False
a|Action to perform on the MetroCluster.

* enum: ["switchover", "negotiated_switchover", "negotiated_switchover_simulate", "switchback", "switchback_simulate", "heal_aggregates", "heal_root_aggregates"]


|encryption_enabled
|boolean
|query
|False
a|Specifies if encryption for NVLog and storage traffic is enabled.

* Introduced in: 9.16


|dr_group_id
|integer
|query
|False
a|DR group ID.

* Introduced in: 9.16


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|configuration_type
|string
a|Displays the MetroCluster configuration type.


|encryption_enabled
|boolean
a|Indicates if the encryption for NVLog and storage traffic is enabled.


|local
|link:#local[local]
a|

|remote
|link:#remote[remote]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "configuration_type": "string",
  "local": {
    "automatic_uso_failure_domain": "string",
    "cluster": {
      "name": "cluster1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    },
    "configuration_state": "string",
    "mode": "string"
  },
  "remote": {
    "automatic_uso_failure_domain": "string",
    "cluster": {
      "name": "cluster1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    },
    "configuration_state": "string",
    "mode": "string"
  }
}
====

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Response

```
Status: 202, Accepted
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 2424873
| Failed to validate the node and cluster components before the "action" operation.

| 2425138
| Switchover cannot be performed in the current DR mode. Run "metrocluster show" to view the DR mode of the local cluster, and run "switchover" only in one of the following situations: 1. The DR mode of the local cluster is "normal". 2. The DR mode of the local cluster is "partial-switchover".

| 2425333
| Heal DR data aggregates cannot be performed in the current DR mode. Run "metrocluster show" and "metrocluster node show" to view the DR mode of the local cluster and the DR mode of the local nodes respectively, and run "heal aggregates" only in one of the following situations: 1. The DR mode of the local cluster is "switchover", and the DR mode of all local nodes is "switchover completed". 2. The DR mode of at least one local node is "heal aggrs failed".

| 2425335
| Heal DR root aggregates cannot be performed in the current DR mode. Run "metrocluster node show" to view the DR mode of the local nodes, and run "heal root-aggregates" only in one of the following situations: 1. The DR mode of all local nodes is "heal aggrs completed". 2. The DR mode of at least one local node is "heal roots failed".

| 2425734
| An internal error occurred. Wait a few minutes, and try the operation again. For further assistance, contact technical support.

| 2427558
| This MetroCluster operation cannot be run because another "action" operation is currently in progress. Run "metrocluster operation history show -job-id id -instance" to view the status of the currently running operation.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#self_link]
[.api-collapsible-fifth-title]
self_link
[#_links]
[.api-collapsible-fifth-title]
_links
[#node]
[.api-collapsible-fifth-title]
node

Local node of the DR Group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#partner]
[.api-collapsible-fifth-title]
partner

Partner node of the DR Group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#dr_pairs]
[.api-collapsible-fifth-title]
dr_pairs

[cols=3*,options=header]
|===
|Name
|Type
|Description

|node
|link:#node[node]
a|Local node of the DR Group.


|partner
|link:#partner[partner]
a|Partner node of the DR Group.


|===


[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#local]
[.api-collapsible-fifth-title]
local

[cols=3*,options=header]
|===
|Name
|Type
|Description

|automatic_uso_failure_domain
|string
a|This parameter specifies the configuration of automatic switchover.
The valid values for the parameter are ':'
cluster':' triggers an unplanned switchover if all nodes in a DR cluster are down.
dr_group':' triggers an unplanned switchover if both nodes of a DR group are down.
disabled':' automatic switchover is disabled.
If the cluster is not reachable due to errors, the parameter value will be set to
not_reachable. This value is read only.
If the cluster configuration is unknown, the parameter value will be set to
unknown and the value is read only.


|cluster
|link:#cluster[cluster]
a|

|configuration_state
|string
a|Indicates the state of the local cluster configuration.


|mode
|string
a|Specifies the mode of operation of the local cluster.


|partner_cluster_reachable
|boolean
a|Specifies whether the partner cluster is reachable from the local cluster.


|periodic_check_enabled
|boolean
a|Indicates whether or not a periodic check is enabled on the local cluster.


|===


[#ipv4_interface]
[.api-collapsible-fifth-title]
ipv4_interface

Object to setup an interface along with its default router.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|gateway
|string
a|The IPv4 or IPv6 address of the default router.


|netmask
|string
a|Input as netmask length (16) or IPv4 mask (255.255.0.0). For IPv6, the default value is 64 with a valid range of 1 to 127. Output is always the netmask length.


|===


[#l3_config]
[.api-collapsible-fifth-title]
l3_config

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ipv4_interface
|link:#ipv4_interface[ipv4_interface]
a|Object to setup an interface along with its default router.


|===


[#node]
[.api-collapsible-fifth-title]
node

Node information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#mccip_ports]
[.api-collapsible-fifth-title]
mccip_ports

Port configuration specification.
l3_config information is only needed when configuring a MetroCluster IP for use in a layer 3 network.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|l3_config
|link:#l3_config[l3_config]
a|

|name
|string
a|Port name


|node
|link:#node[node]
a|Node information


|uuid
|string
a|Port UUID


|vlan_id
|integer
a|VLAN ID


|===


[#dr_group]
[.api-collapsible-fifth-title]
dr_group

DR group reference.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|integer
a|DR Group ID


|===


[#peer_cluster]
[.api-collapsible-fifth-title]
peer_cluster

The peer cluster that the mediator service is used for.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#mediator]
[.api-collapsible-fifth-title]
mediator

Mediator information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|dr_group
|link:#dr_group[dr_group]
a|DR group reference.


|local_mediator_connectivity
|string
a|Indicates the mediator connectivity status of the local cluster. Possible values are connected, unreachable, unusable and down-high-latency. This field is only applicable to the mediators in SnapMirror active sync configuration.


|peer_mediator_connectivity
|string
a|Indicates the mediator connectivity status of the peer cluster. Possible values are connected, unreachable, unknown and down-high-latency.


|reachable
|boolean
a|Indicates the connectivity status of the mediator.


|strict_cert_validation
|boolean
a|Indicates if strict validation of certificates is performed while making REST API calls to the mediator. This field is only applicable to the ONTAP Cloud Mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* x-nullable: true


|use_http_proxy_local
|boolean
a|Indicates if the local cluster should use an http-proxy server while making REST API calls to the mediator. This field is only applicable to the ONTAP cloud mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* x-nullable: true


|use_http_proxy_remote
|boolean
a|Indicates if the remote cluster should use an http-proxy server while making REST API calls to the mediator. This field is only applicable to the ONTAP cloud mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* writeOnly: 1
* x-nullable: true


|uuid
|string
a|The unique identifier for the mediator service.


|===


[#partner_cluster]
[.api-collapsible-fifth-title]
partner_cluster

Partner cluster information.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#remote]
[.api-collapsible-fifth-title]
remote

[cols=3*,options=header]
|===
|Name
|Type
|Description

|automatic_uso_failure_domain
|string
a|This parameter specifies the configuration of automatic switchover.
The valid values for the parameter are ':'
cluster':' triggers an unplanned switchover if all nodes in a DR cluster are down.
dr_group':' triggers an unplanned switchover if both nodes of a DR group are down.
disabled':' automatic switchover is disabled.
If the cluster is not reachable due to errors, the parameter value will be set to
not_reachable. This value is read only.
If the cluster configuration is unknown, the parameter value will be set to
unknown and the value is read only.


|cluster
|link:#cluster[cluster]
a|

|configuration_state
|string
a|Indicates the state of the remote cluster configuration.


|mode
|string
a|Specifies the mode of operation of the remote cluster.


|periodic_check_enabled
|boolean
a|Indicates whether or not a periodic check is enabled on the remote cluster.


|===


[#metrocluster]
[.api-collapsible-fifth-title]
metrocluster

Holds MetroCluster status and configuration parameters for the local and remote clusters. REST: /api/cluster/metrocluster


[cols=3*,options=header]
|===
|Name
|Type
|Description

|configuration_type
|string
a|Displays the MetroCluster configuration type.


|encryption_enabled
|boolean
a|Indicates if the encryption for NVLog and storage traffic is enabled.


|local
|link:#local[local]
a|

|remote
|link:#remote[remote]
a|

|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
