---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-cluster.html'
summary: 'Update the cluster configuration'
---

= Update the cluster configuration

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/cluster`#

*Introduced In:* 9.6

Updates the cluster configuration after the cluster is created.

== Related ONTAP commands

* `cluster identity modify`
* `system node modify`
* `vserver services dns modify`
* `vserver services name-service dns modify`
* `timezone`
* `vserver active-directory create`
* `vserver active-directory modify`
* `vserver active-directory delete`
* `vserver cifs security modify`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_tags
|array[string]
a|Tags are an optional way to track the uses of a resource. Tag values must be formatted as key:value strings.


|active_directory
|link:#active_directory[active_directory]
a|

|auto_enable_activity_tracking
|boolean
a|Indicates how new SVMs will default "auto_enable_activity_tracking" for new volumes.


|auto_enable_analytics
|boolean
a|Indicates how new SVMs will default "auto_enable_analytics" for new volumes.


|certificate
|link:#certificate[certificate]
a|Support for this field will be removed in a future release. Please use /api/cluster/web for this field. Certificate used by cluster and node management interfaces for TLS connection requests.


|contact
|string
a|

|disaggregated
|boolean
a|Specifies whether the cluster is designed for disaggregated storage.


|dns_domains
|array[string]
a|A list of DNS domains.
Domain names have the following requirements:

* The name must contain only the following characters: A through Z,
a through z, 0 through 9, ".", "-" or "_".
* The first character of each label, delimited by ".", must be one
of the following characters: A through Z or a through z or 0
through 9.
* The last character of each label, delimited by ".", must be one of
the following characters: A through Z, a through z, or 0 through 9.
* The top level domain must contain only the following characters: A
through Z, a through z.
* The system reserves the following names:"all", "local", and "localhost".


|location
|string
a|

|management_interfaces
|array[link:#management_interfaces[management_interfaces]]
a|

|name
|string
a|

|name_servers
|array[string]
a|The list of IP addresses of the DNS servers. Addresses can be either
IPv4 or IPv6 addresses.


|peering_policy
|link:#peering_policy[peering_policy]
a|

|san_optimized
|boolean
a|Specifies if this cluster is an All SAN Array.


|timezone
|link:#timezone[timezone]
a|Provides the cluster-wide time zone information that localizes time found on messages displayed on each node's:

* console messages;
* logging to internal ONTAP log files; and
* localized REST API full ISO-8601 date, time, and time zone format information.
Machine-to-machine interfaces, such as file access protocols (NFS, CIFS), block access protocols (SAN), and other protocols
such as Manage ONTAP (ONTAPI), use second or subsecond time values that are based on world time or UTC.
* Introduced in: 9.7


|uuid
|string
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_tags": [
    "team:csi",
    "environment:test"
  ],
  "active_directory": {
    "force_account_overwrite": "",
    "fqdn": "server1.com",
    "name": "account1",
    "organizational_unit": "CN=Test",
    "password": "testpwd",
    "security": {
      "advertised_kdc_encryptions": [
        "string"
      ]
    },
    "username": "admin"
  },
  "certificate": {
    "name": "string",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "cluster_network_overlay_enabled": true,
  "contact": "support@company.com",
  "dns_domains": [
    "example.com",
    "example2.example3.com"
  ],
  "location": "building 1",
  "management_interfaces": [
    {
      "name": "lif1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "name": "cluster1",
  "name_servers": [
    "10.224.65.20",
    "2001:db08:a0b:12f0::1"
  ],
  "peering_policy": {
    "minimum_passphrase_length": 0
  },
  "timezone": {
    "name": "America/New_York"
  },
  "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
}
====

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Response

```
Status: 202, Accepted
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 655414
| Failed to the remove Active Directory machine.

| 655431
| Username cannot be empty.

| 655432
| Password cannot be empty.

| 655562
| The NetBIOS name cannot be longer than 15 characters.

| 655563
| NetBIOS name contains characters that are not allowed.

| 655914
| Failed to create the Active Directory machine account.

| 655915
| A CIFS server for this SVM already exists. Having both a CIFS server and an Active Directory account for the same SVM is not supported. Use the \"vserver cifs delete\" command to delete the existing CIFS server and try the command again.

| 656464
| Failed to create the Active Directory machine account. Reason: Invalid Credentials.

| 656465
| Failed to create the Active Directory machine account. Reason: An account with this name already exists.

| 656466
| Failed to create the Active Directory machine account. Reason: Unable to connect to any domain controllers.

| 656467
| Failed to create the Active Directory machine account. Reason: Organizational-Unit not found.

| 656478
| Failed to create the Active Directory machine account. Reason: KDC has no support for encryption type.

| 656483
| Active Directory account creation for the admin SVM requires an effective cluster version of 9.16.0 or later.

| 3604491
| Updating timezone failed.

| 3604520
| Internal error. System state is not correct to read or change timezone.

| 8847361
| Too many DNS domains provided.

| 8847362
| Too many name servers provided.

| 8847400
| The "dns_domains" field is required when "name_servers" is specified.

| 9240587
| A name must be provided.

| 9240588
| The name is too long.

| 12451843
| Certificate does not exist.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#active_directory_security]
[.api-collapsible-fifth-title]
active_directory_security

[cols=3*,options=header]
|===
|Name
|Type
|Description

|advertised_kdc_encryptions
|array[string]
a|

|===


[#active_directory]
[.api-collapsible-fifth-title]
active_directory

[cols=3*,options=header]
|===
|Name
|Type
|Description

|force_account_overwrite
|boolean
a|If set to true and a machine account exists with the same name as specified in "name" in Active Directory, it is overwritten and reused.


|fqdn
|string
a|Fully qualified domain name.


|name
|string
a|Active Directory account NetBIOS name.


|organizational_unit
|string
a|Organizational unit under which the Active Directory account is created.


|password
|string
a|Administrator password required for Active Directory account creation, modification, and deletion.


|security
|link:#active_directory_security[active_directory_security]
a|

|username
|string
a|Administrator username required for Active Directory account creation, modification, and deletion.


|===


[#certificate]
[.api-collapsible-fifth-title]
certificate

Support for this field will be removed in a future release. Please use /api/cluster/web for this field. Certificate used by cluster and node management interfaces for TLS connection requests.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Certificate name


|uuid
|string
a|Certificate UUID


|===


[#configuration_backup]
[.api-collapsible-fifth-title]
configuration_backup

[cols=3*,options=header]
|===
|Name
|Type
|Description

|password
|string
a|

|rest_method
|string
a|The REST API HTTP method (POST/PUT).


|url
|string
a|An external backup location for the cluster configuration. This is mostly required for single node clusters where node and cluster configuration backups cannot be copied to other nodes in the cluster.


|username
|string
a|

|validate_certificate
|boolean
a|Use this parameter with the value "true" to validate the digital certificate of the remote server. Digital certificate validation is available only when the HTTPS protocol is used in the URL; it is disabled by default.


|===


[#license]
[.api-collapsible-fifth-title]
license

License keys or NLF contents.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|keys
|array[string]
a|

|===


[#ip]
[.api-collapsible-fifth-title]
ip

Object to setup an interface along with its default router.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|gateway
|string
a|The IPv4 or IPv6 address of the default router.


|netmask
|string
a|Input as netmask length (16) or IPv4 mask (255.255.0.0). For IPv6, the default value is 64 with a valid range of 1 to 127. Output is always the netmask length.


|===


[#management_interface]
[.api-collapsible-fifth-title]
management_interface

The management interface of the cluster. The subnet mask and gateway for this interface are used for the node management interfaces provided in the node configuration.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#ip[ip]
a|Object to setup an interface along with its default router.


|===


[#ip]
[.api-collapsible-fifth-title]
ip

IP information

[#management_interfaces]
[.api-collapsible-fifth-title]
management_interfaces

A network interface. Either UUID or name may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#ip[ip]
a|IP information


|name
|string
a|The name of the interface. If only the name is provided, the SVM scope
must be provided by the object this object is embedded in.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#iops]
[.api-collapsible-fifth-title]
iops

The rate of I/O operations observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#latency]
[.api-collapsible-fifth-title]
latency

The round trip latency in microseconds observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#throughput]
[.api-collapsible-fifth-title]
throughput

The rate of throughput bytes per second observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#metric]
[.api-collapsible-fifth-title]
metric

Performance numbers, such as IOPS latency and throughput.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|iops
|link:#iops[iops]
a|The rate of I/O operations observed at the storage object.


|latency
|link:#latency[latency]
a|The round trip latency in microseconds observed at the storage object.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the storage object.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#node_setup_ip]
[.api-collapsible-fifth-title]
node_setup_ip

The IP configuration for cluster setup.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|===


[#cluster_interface]
[.api-collapsible-fifth-title]
cluster_interface

The cluster network IP address of the node to be added.

[#cluster_interfaces]
[.api-collapsible-fifth-title]
cluster_interfaces

Network interface


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#ip[ip]
a|IP information


|name
|string
a|The name of the interface. If only the name is provided, the SVM scope
must be provided by the object this object is embedded in.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#cpu]
[.api-collapsible-fifth-title]
cpu

CPU information.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Number of CPUs on the node.


|firmware_release
|string
a|Firmware release number. Defined by the CPU manufacturer.


|processor
|string
a|CPU type on the node.


|===


[#message]
[.api-collapsible-fifth-title]
message

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Error code describing the current condition of chassis fans.


|message
|string
a|Message describing the current condition of chassis fans. It is only of use when `failed_fan.count` is not zero.


|===


[#failed_fan]
[.api-collapsible-fifth-title]
failed_fan

[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Specifies a count of the number of chassis fans that are not operating within the recommended RPM range.


|message
|link:#message[message]
a|

|===


[#message]
[.api-collapsible-fifth-title]
message

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Error code describing the current condition of power supply.


|message
|string
a|Message describing the state of any power supplies that are currently degraded. It is only of use when `failed_power_supply.count` is not zero.


|===


[#failed_power_supply]
[.api-collapsible-fifth-title]
failed_power_supply

[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Number of failed power supply units.


|message
|link:#message[message]
a|

|===


[#flash_cache]
[.api-collapsible-fifth-title]
flash_cache

[cols=3*,options=header]
|===
|Name
|Type
|Description

|capacity
|integer
a|Size in bytes


|device_id
|integer
a|

|firmware_file
|string
a|

|firmware_version
|string
a|

|hardware_revision
|string
a|

|model
|string
a|

|part_number
|string
a|

|serial_number
|string
a|

|slot
|string
a|

|state
|string
a|

|===


[#frus]
[.api-collapsible-fifth-title]
frus

[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|string
a|

|state
|string
a|

|type
|string
a|

|===


[#controller]
[.api-collapsible-fifth-title]
controller

Controller information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|board
|string
a|Type of the system board. This is defined by vendor.


|cpu
|link:#cpu[cpu]
a|CPU information.


|failed_fan
|link:#failed_fan[failed_fan]
a|

|failed_power_supply
|link:#failed_power_supply[failed_power_supply]
a|

|flash_cache
|array[link:#flash_cache[flash_cache]]
a|A list of Flash-Cache devices. Only returned when requested by name.


|frus
|array[link:#frus[frus]]
a|List of FRUs on the node. Only returned when requested by name.


|memory_size
|integer
a|Memory available on the node, in bytes.


|over_temperature
|string
a|Specifies whether the hardware is currently operating outside of its recommended temperature range. The hardware shuts down if the temperature exceeds critical thresholds.


|===


[#external_cache]
[.api-collapsible-fifth-title]
external_cache

Cache used for buffer management.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|is_enabled
|boolean
a|Indicates whether the external cache is enabled.


|is_hya_enabled
|boolean
a|Indicates whether HyA caching is enabled.


|is_rewarm_enabled
|boolean
a|Indicates whether rewarm is enabled.


|pcs_size
|integer
a|PCS size in gigabytes.


|===


[#external_cache_bypass]
[.api-collapsible-fifth-title]
external_cache_bypass

External cache bypass management.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Indicates whether external cache bypass is enabled.


|large_read_ops_allow_percent
|integer
a|External cache bypass allowed operations percentage for large reads.


|reset
|boolean
a|Initiates an external cache bypass threshold reset action.


|===


[#failure]
[.api-collapsible-fifth-title]
failure

Indicates the failure code and message. This property is not supported on the ASA r2 platform.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|integer
a|Message code


|message
|string
a|Detailed message based on the state.


|===


[#aggregate]
[.api-collapsible-fifth-title]
aggregate

Aggregate name and UUID.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#error]
[.api-collapsible-fifth-title]
error

Indicates the failed aggregate giveback code and message.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Message code.


|message
|string
a|Detailed message based on the state.


|===


[#status]
[.api-collapsible-fifth-title]
status

[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregate
|link:#aggregate[aggregate]
a|Aggregate name and UUID.


|error
|link:#error[error]
a|Indicates the failed aggregate giveback code and message.


|state
|string
a|Giveback state of the aggregate.

Possible values include no aggregates to giveback(nothing_to_giveback), failed to disable background disk firmware update(BDFU) on source node(failed_bdfu_source),

giveback delayed as disk firmware update is in progress on source node(delayed_bdfu_source), performing veto checks(running_checks).


|===


[#giveback]
[.api-collapsible-fifth-title]
giveback

Represents the state of the node that is giving storage back to its HA partner.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|failure
|link:#failure[failure]
a|Indicates the failure code and message. This property is not supported on the ASA r2 platform.


|state
|string
a|

|status
|array[link:#status[status]]
a|Giveback status of each aggregate. This property is not supported on the ASA r2 platform.


|===


[#interconnect]
[.api-collapsible-fifth-title]
interconnect

[cols=3*,options=header]
|===
|Name
|Type
|Description

|adapter
|string
a|HA interconnect device name.


|state
|string
a|Indicates the HA interconnect status.


|===


[#partners]
[.api-collapsible-fifth-title]
partners

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#ports]
[.api-collapsible-fifth-title]
ports

[cols=3*,options=header]
|===
|Name
|Type
|Description

|number
|integer
a|HA port number


|state
|string
a|HA port state:

* _down_ - Logical HA link is down.
* _initialized_ - Logical HA link is initialized. The physical link is up, but the subnet manager hasn't started to configure the port.
* _armed_ - Logical HA link is armed. The physical link is up and the subnet manager started but did not yet complete configuring the port.
* _active_ - Logical HA link is active.
* _reserved_ - Logical HA link is active, but the physical link is down.


|===


[#takeover]
[.api-collapsible-fifth-title]
takeover

This represents the state of the node that is taking over storage from its HA partner.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|failure
|link:#failure[failure]
a|Indicates the failure code and message. This property is not supported on the ASA r2 platform.


|state
|string
a|

|===


[#takeover_check]
[.api-collapsible-fifth-title]
takeover_check

The takeover check response.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|reasons
|array[string]
a|Reasons why the takeover is not possible.


|takeover_possible
|boolean
a|Indicates whether the takeover is possible.


|===


[#ha]
[.api-collapsible-fifth-title]
ha

[cols=3*,options=header]
|===
|Name
|Type
|Description

|auto_giveback
|boolean
a|Specifies whether giveback is automatically initiated when the node that owns the storage is ready.


|enabled
|boolean
a|Specifies whether or not storage failover is enabled.


|giveback
|link:#giveback[giveback]
a|Represents the state of the node that is giving storage back to its HA partner.


|interconnect
|link:#interconnect[interconnect]
a|

|partners
|array[link:#partners[partners]]
a|Nodes in this node's High Availability (HA) group.


|ports
|array[link:#ports[ports]]
a|

|takeover
|link:#takeover[takeover]
a|This represents the state of the node that is taking over storage from its HA partner.


|takeover_check
|link:#takeover_check[takeover_check]
a|The takeover check response.


|type
|string
a|Type of storage.


|===


[#local]
[.api-collapsible-fifth-title]
local

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|string
a|The hardware assist IP address.


|port
|integer
a|The hardware assist port.


|state
|string
a|The hardware assist monitor status.


|===


[#partner]
[.api-collapsible-fifth-title]
partner

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|string
a|The hardware assist IP address.


|port
|integer
a|The hardware assist port.


|state
|string
a|The hardware assist monitor status.


|===


[#status]
[.api-collapsible-fifth-title]
status

[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Indicates whether hardware assist is enabled on the node.


|===


[#hw_assist]
[.api-collapsible-fifth-title]
hw_assist

The hardware assist information.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|status
|link:#status[status]
a|

|===


[#management_interface]
[.api-collapsible-fifth-title]
management_interface

The management interface of the node to be added. The subnet mask is set based on the management interface of the cluster or the management interfaces of other nodes.

[#management_interfaces]
[.api-collapsible-fifth-title]
management_interfaces

Network interface


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#ip[ip]
a|IP information


|name
|string
a|The name of the interface. If only the name is provided, the SVM scope
must be provided by the object this object is embedded in.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#metric]
[.api-collapsible-fifth-title]
metric

CPU performance for the nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|processor_utilization
|integer
a|Average CPU Utilization for the node


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|timestamp
|string
a|The timestamp of the performance data.


|uuid
|string
a|

|===


[#ports]
[.api-collapsible-fifth-title]
ports

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|===


[#metrocluster]
[.api-collapsible-fifth-title]
metrocluster

Metrocluster


[cols=3*,options=header]
|===
|Name
|Type
|Description

|custom_vlan_capable
|boolean
a|Indicates whether the MetroCluster over IP platform supports custom VLAN IDs.


|ports
|array[link:#ports[ports]]
a|MetroCluster over IP ports.


|type
|string
a|The Metrocluster configuration type


|===


[#nvlog]
[.api-collapsible-fifth-title]
nvlog

Non-volatile write log settings.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|backing_type
|string
a|Indicates the current NVLog journal backing type.


|swap_mode
|string
a|Indicates the current NVLog journal swap mode.


|===


[#nvram]
[.api-collapsible-fifth-title]
nvram

[cols=3*,options=header]
|===
|Name
|Type
|Description

|battery_state
|string
a|Specifies status of the NVRAM battery. Possible values:

* _battery_ok_
* _battery_partially_discharged_
* _battery_fully_discharged_
* _battery_not_present_
* _battery_near_end_of_life_
* _battery_at_end_of_life_
* _battery_unknown_
* _battery_over_charged_
* _battery_fully_charged_


|id
|integer
a|Vendor specific NVRAM ID of the node.


|===


[#api_service]
[.api-collapsible-fifth-title]
api_service

Provides the properties of the service processor (SP) or baseboard management controller (BMC) API service.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Indicates whether the SP API service of the SP or BMC is enabled or disabled. When the SP API service is disabled, features such as network-based firmware updates and network-based down node log collection are not available, and the slower serial-interface is used for firmware updates and down node log collection.


|limit_access
|boolean
a|Restricts SP API service access to cluster nodes only. By default, limit_access is set to true.


|port
|integer
a|Specifies the port number on the SP or BMC used for the SP API service. By default, port 50000 is used.


|===


[#auto_config]
[.api-collapsible-fifth-title]
auto_config

Provides the properties of the service processor auto configuration.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ipv4_subnet
|string
a|Indicates the service processor auto configuration IPv4 subnet name. To enable IPv4 auto-config give the subnet name, give the value as null or an empty string "" to disable auto-config.


|ipv6_subnet
|string
a|Indicates the service processor auto configuration IPv6 subnet name. To enable IPv6 auto-config give the subnet name, give the value as null or an empty string "" to disable auto-config.


|===


[#backup]
[.api-collapsible-fifth-title]
backup

Provides the properties of the service processor backup partition.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|is_current
|boolean
a|Indicates whether the service processor is currently booted from the backup partition.


|state
|string
a|Status of the backup partition.


|version
|string
a|Firmware version of the backup partition.


|===


[#ipv4_interface]
[.api-collapsible-fifth-title]
ipv4_interface

Object to set up an interface along with its default router.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 address


|enabled
|boolean
a|Indicates whether the IPv4 interfaces is enabled. It expects dhcp_enabled as "true" or values for address, netmask and gateway when set to "true".


|gateway
|string
a|The IPv4 address of the default router.


|netmask
|string
a|Input as IPv4 mask (255.255.0.0). Output is always the netmask length.


|setup_state
|string
a|Indicates the setup state of the interface.


|===


[#ipv6_interface]
[.api-collapsible-fifth-title]
ipv6_interface

Object to setup an interface along with its default router.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv6 address


|enabled
|boolean
a|Indicates whether the IPv6 interfaces is enabled. It expects values for address, netmask and gateway when set to "true".


|gateway
|string
a|The IPv6 address of the default router.


|is_ipv6_ra_enabled
|boolean
a|Indicates whether IPv6 RA is enabled.


|link_local_ip
|string
a|Link local IP address.


|netmask
|integer
a|The IPv6 netmask/prefix length. The default value is 64 with a valid range of 1 to 127.


|router_ip
|string
a|Router assigned IP address.


|setup_state
|string
a|Indicates the setup state of the interface.


|===


[#primary]
[.api-collapsible-fifth-title]
primary

Provides the properties of the service processor primary partition.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|is_current
|boolean
a|Indicates whether the service processor is currently booted from the primary partition.


|state
|string
a|Status of the primary partition.


|version
|string
a|Firmware version of the primary partition.


|===


[#ssh_info]
[.api-collapsible-fifth-title]
ssh_info

Service processor SSH allowed IP address configuration applied across the cluster.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed_addresses
|array[string]
a|Allowed IP addresses


|===


[#web_service]
[.api-collapsible-fifth-title]
web_service

Provides the properties of SP or BMC web service.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Indicates whether the web service of the SP or BMC is enabled or disabled. When the web service is disabled, features such as network-based firmware updates and network-based down node log collection are not available, and the slower serial-interface is used for firmware updates and down node log collection.


|limit_access
|boolean
a|Restricts web service access to cluster nodes only. By default, limit_access is set to true.


|===


[#service_processor]
[.api-collapsible-fifth-title]
service_processor

[cols=3*,options=header]
|===
|Name
|Type
|Description

|api_service
|link:#api_service[api_service]
a|Provides the properties of the service processor (SP) or baseboard management controller (BMC) API service.


|auto_config
|link:#auto_config[auto_config]
a|Provides the properties of the service processor auto configuration.


|autoupdate_enabled
|boolean
a|Indicates whether the service processor can be automatically updated from ONTAP.

* Introduced in: 9.10
* x-ntap-readModify: true
* x-nullable: true


|backup
|link:#backup[backup]
a|Provides the properties of the service processor backup partition.


|dhcp_enabled
|boolean
a|Set to "true" to use DHCP to configure an IPv4 interface. Do not provide values for address, netmask and gateway when set to "true".


|firmware_version
|string
a|The version of firmware installed.


|ipv4_interface
|link:#ipv4_interface[ipv4_interface]
a|Object to set up an interface along with its default router.


|ipv6_interface
|link:#ipv6_interface[ipv6_interface]
a|Object to setup an interface along with its default router.


|is_ip_configured
|boolean
a|Indicates whether the service processor network is configured.


|last_update_state
|string
a|Provides the "update status" of the last service processor update.


|link_status
|string
a|

|mac_address
|string
a|

|primary
|link:#primary[primary]
a|Provides the properties of the service processor primary partition.


|ssh_info
|link:#ssh_info[ssh_info]
a|Service processor SSH allowed IP address configuration applied across the cluster.


|state
|string
a|

|type
|string
a|

|web_service
|link:#web_service[web_service]
a|Provides the properties of SP or BMC web service.


|===


[#snaplock]
[.api-collapsible-fifth-title]
snaplock

SnapLock-related properties.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|compliance_clock_time
|string
a|SnapLock compliance clock time.


|===


[#statistics]
[.api-collapsible-fifth-title]
statistics

Raw CPU performance for the nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|processor_utilization_base
|integer
a|Base counter for CPU Utilization.


|processor_utilization_raw
|integer
a|Raw CPU utilization for the node. The change in this value over time should be divided by corresponding change in processor_utilization_base, then multiplied by 100 to calculate the percentage CPU utilization for the node. For example: ((processor_utilization_raw_t2 - processor_utilization_raw_t1) / (processor_utilization_base_t2 - processor_utilization_base_t1)) * 100.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#system_aggregate]
[.api-collapsible-fifth-title]
system_aggregate

Aggregate


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#version]
[.api-collapsible-fifth-title]
version

This returns the cluster version information.  When the cluster has more than one node, the cluster version is equivalent to the lowest of generation, major, and minor versions on all nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|full
|string
a|The full cluster version string.


|generation
|integer
a|The generation portion of the version.


|major
|integer
a|The major portion of the version.


|minor
|integer
a|The minor portion of the version.


|===


[#vm]
[.api-collapsible-fifth-title]
vm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|provider_type
|string
a|Cloud provider where the VM is hosted.


|===


[#nodes]
[.api-collapsible-fifth-title]
nodes

Complete node information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|anti_ransomware_version
|string
a|Anti ransomware version.


|cluster_interfaces
|array[link:#cluster_interfaces[cluster_interfaces]]
a|

|controller
|link:#controller[controller]
a|Controller information


|date
|string
a|The current or "wall clock" time of the node in ISO-8601 date, time, and time zone format.
The ISO-8601 date and time are localized based on the ONTAP cluster's timezone setting.

* example: 2019-04-17 11:49:26 -0400
* format: date-time
* readOnly: 1
* Introduced in: 9.6
* x-nullable: true


|external_cache
|link:#external_cache[external_cache]
a|Cache used for buffer management.


|external_cache_bypass
|link:#external_cache_bypass[external_cache_bypass]
a|External cache bypass management.


|ha
|link:#ha[ha]
a|

|is_spares_low
|boolean
a|Specifies whether or not the node is in spares low condition.


|location
|string
a|

|management_interfaces
|array[link:#management_interfaces[management_interfaces]]
a|

|membership
|string
a|Possible values:

* _available_ - A node is detected on the internal cluster network and can be added to the cluster.  Nodes that have a membership of "available" are not returned when a GET request is called when the cluster exists. Provide a query on the "membership" property for _available_ to scan for nodes on the cluster network. Nodes that have a membership of "available" are returned automatically before a cluster is created.
* _joining_ - Joining nodes are in the process of being added to the cluster. The node might be progressing through the steps to become a member or might have failed. The job to add the node or create the cluster provides details on the current progress of the node.
* _member_ - Nodes that are members have successfully joined the cluster.


|metrocluster
|link:#metrocluster[metrocluster]
a|Metrocluster


|model
|string
a|

|name
|string
a|

|nvlog
|link:#nvlog[nvlog]
a|Non-volatile write log settings.


|nvram
|link:#nvram[nvram]
a|

|owner
|string
a|Owner of the node.


|serial_number
|string
a|

|service_processor
|link:#service_processor[service_processor]
a|

|snaplock
|link:#snaplock[snaplock]
a|SnapLock-related properties.


|state
|string
a|State of the node:

* _up_ - Node is up and operational.
* _booting_ - Node is booting up.
* _down_ - Node has stopped or is dumping core.
* _taken_over_ - Node has been taken over by its HA partner and is not yet waiting for giveback.
* _waiting_for_giveback_ - Node has been taken over by its HA partner and is waiting for the HA partner to giveback disks.
* _degraded_ - Node has one or more critical services offline.
* _unknown_ - Node or its HA partner cannot be contacted and there is no information on the node's state.


|storage_configuration
|string
a|The storage configuration in the system. Possible values:

* _mixed_path_
* _single_path_
* _multi_path_
* _tri_path_
* _quad_path_
* _mixed_path_ha_
* _single_path_ha_
* _multi_path_ha_
* _tri_path_ha_
* _quad_path_ha_
* _unknown_
* _virtual_


|system_aggregate
|link:#system_aggregate[system_aggregate]
a|Aggregate


|system_id
|string
a|

|system_machine_type
|string
a|OEM system machine type.


|uptime
|integer
a|The total time, in seconds, that the node has been up.


|uuid
|string
a|

|vendor_serial_number
|string
a|OEM vendor serial number.


|vm
|link:#vm[vm]
a|

|===


[#peering_policy]
[.api-collapsible-fifth-title]
peering_policy

[cols=3*,options=header]
|===
|Name
|Type
|Description

|authentication_required
|boolean
a|Indicates whether authentication is required in the communication between cluster peers. If true, authentication is required to establish communication between cluster peers.


|encryption_required
|boolean
a|Indicates whether encryption is required in the communication between cluster peers. If true, encryption is required to establish communication between cluster peers.


|minimum_passphrase_length
|integer
a|Minimum required length for a passphrase. For more information on password strength best practices, see: https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls


|===


[#iops_raw]
[.api-collapsible-fifth-title]
iops_raw

The number of I/O operations observed at the storage object. This can be used along with delta time to calculate the rate of I/O operations per unit of time.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#latency_raw]
[.api-collapsible-fifth-title]
latency_raw

The raw latency in microseconds observed at the storage object. This can be divided by the raw IOPS value to calculate the average latency per I/O operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#throughput_raw]
[.api-collapsible-fifth-title]
throughput_raw

Throughput bytes observed at the storage object. This can be used along with delta time to calculate the rate of throughput bytes per unit of time.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Performance metric for write I/O operations.


|===


[#statistics]
[.api-collapsible-fifth-title]
statistics

These are raw performance numbers, such as IOPS latency and throughput. These numbers are aggregated across all nodes in the cluster and increase with the uptime of the cluster.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|iops_raw
|link:#iops_raw[iops_raw]
a|The number of I/O operations observed at the storage object. This can be used along with delta time to calculate the rate of I/O operations per unit of time.


|latency_raw
|link:#latency_raw[latency_raw]
a|The raw latency in microseconds observed at the storage object. This can be divided by the raw IOPS value to calculate the average latency per I/O operation.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput_raw
|link:#throughput_raw[throughput_raw]
a|Throughput bytes observed at the storage object. This can be used along with delta time to calculate the rate of throughput bytes per unit of time.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#timezone]
[.api-collapsible-fifth-title]
timezone

Provides the cluster-wide time zone information that localizes time found on messages displayed on each node's:

* console messages;
* logging to internal ONTAP log files; and
* localized REST API full ISO-8601 date, time, and time zone format information.
Machine-to-machine interfaces, such as file access protocols (NFS, CIFS), block access protocols (SAN), and other protocols
such as Manage ONTAP (ONTAPI), use second or subsecond time values that are based on world time or UTC.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The ONTAP time zone name or identification in either IANA time zone format "Area/Location", or an ONTAP traditional time zone.

The initial first node in cluster setting for time zone is "Etc/UTC".
"Etc/UTC" is the IANA timezone "Area/Location" specifier for
Coordinated Universal Time (UTC), which is an offset of 0.

===== IANA time zone format

The IANA time zone, formatted as "Area/Location", is based on geographic areas that have had the same time zone offset for many years.

"Location" represents a compound name using additional forward slashes.

An example of the "Area/Location" time zone is "America/New_York" and represents most of the United States Eastern Time Zone.
Examples of "Area/Location" with "Location" as a compound name are "America/Argentina/Buenos_Aires" and "America/Indiana/Indianapolis".

===== ONTAP traditional time zone

Examples of the traditional time zones are "EST5EDT" for the United States Eastern Time Zone and "CET" for Central European Time Zone.

* example: America/New_York
* Introduced in: 9.7
* x-nullable: true


|===


[#cluster]
[.api-collapsible-fifth-title]
cluster

Complete cluster information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_tags
|array[string]
a|Tags are an optional way to track the uses of a resource. Tag values must be formatted as key:value strings.


|active_directory
|link:#active_directory[active_directory]
a|

|auto_enable_activity_tracking
|boolean
a|Indicates how new SVMs will default "auto_enable_activity_tracking" for new volumes.


|auto_enable_analytics
|boolean
a|Indicates how new SVMs will default "auto_enable_analytics" for new volumes.


|certificate
|link:#certificate[certificate]
a|Support for this field will be removed in a future release. Please use /api/cluster/web for this field. Certificate used by cluster and node management interfaces for TLS connection requests.


|contact
|string
a|

|disaggregated
|boolean
a|Specifies whether the cluster is designed for disaggregated storage.


|dns_domains
|array[string]
a|A list of DNS domains.
Domain names have the following requirements:

* The name must contain only the following characters: A through Z,
a through z, 0 through 9, ".", "-" or "_".
* The first character of each label, delimited by ".", must be one
of the following characters: A through Z or a through z or 0
through 9.
* The last character of each label, delimited by ".", must be one of
the following characters: A through Z, a through z, or 0 through 9.
* The top level domain must contain only the following characters: A
through Z, a through z.
* The system reserves the following names:"all", "local", and "localhost".


|location
|string
a|

|management_interfaces
|array[link:#management_interfaces[management_interfaces]]
a|

|name
|string
a|

|name_servers
|array[string]
a|The list of IP addresses of the DNS servers. Addresses can be either
IPv4 or IPv6 addresses.


|peering_policy
|link:#peering_policy[peering_policy]
a|

|san_optimized
|boolean
a|Specifies if this cluster is an All SAN Array.


|timezone
|link:#timezone[timezone]
a|Provides the cluster-wide time zone information that localizes time found on messages displayed on each node's:

* console messages;
* logging to internal ONTAP log files; and
* localized REST API full ISO-8601 date, time, and time zone format information.
Machine-to-machine interfaces, such as file access protocols (NFS, CIFS), block access protocols (SAN), and other protocols
such as Manage ONTAP (ONTAPI), use second or subsecond time values that are based on world time or UTC.
* Introduced in: 9.7


|uuid
|string
a|

|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
