---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-protocols-cifs-domains-.html'
summary: 'Modify the CIFS domain-related information for an SVM'
---

= Modify the CIFS domain-related information for an SVM

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/protocols/cifs/domains/{svm.uuid}`#

*Introduced In:* 9.13

Modifies the CIFS domain-related information of the specified SVM.

== Related ONTAP commands

* `vserver cifs domain password schedule modify`
* `vserver cifs domain discovered-servers discovery-mode modify`
* `vserver cifs domain password reset`
* `vserver cifs domain password change`

== Important notes

* If the query is set to cifs_password_operation=reset and ad_domain_user and ad_domain_password is included in the body,a CIFS password reset is executed.
* If the query is set to cifs_password_operation=reset and tenant_id, client_id and client_certificate is included in the body,a CIFS password reset is executed in Azure EntraId for hybrid user.
* If the body is empty when the query is set to cifs_password_operation=reset, a CIFS password change is executed.

== Learn more

* link:protocols_cifs_domains_svm.uuid_endpoint_overview.html[DOC /protocols/cifs/domains/{svm.uuid}]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|cifs_password_operation
|string
|query
|False
a|Specifies the operation to be performed on the domain password.

* enum: ["reset"]
* Introduced in: 9.14


|svm.uuid
|string
|path
|True
a|UUID of the SVM to which this object belongs.

* Introduced in: 9.14

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ad_domain
|link:#ad_domain[ad_domain]
a|Specifies the credentials of a user with permissions to reset the password in the organizational unit for the machine account.


|client_certificate
|string
a|PKCS12 certificate used by the application to prove its identity to AKV.


|client_id
|string
a|Application client ID of the deployed Azure application with appropriate access to an AKV or EntraId.


|discovered_servers
|array[link:#discovered_servers[discovered_servers]]
a|Specifies the discovered servers records.


|name_mapping
|link:#name_mapping[name_mapping]
a|Specifies the name mapping search records.


|password_schedule
|link:#password_schedule[password_schedule]
a|Specifies the password schedule records.


|preferred_dcs
|array[link:#preferred_dcs[preferred_dcs]]
a|Specifies the preferred DC records.


|server_discovery_mode
|string
a|Specifies the mode of server discovery.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|tenant_id
|string
a|Directory (tenant) ID of the deployed Azure application with appropriate access to an AKV or EntraId.


|trust_relationships
|array[link:#trust_relationships[trust_relationships]]
a|Specifies the trusted domain records.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "ad_domain": {
    "password": "string",
    "user": "string"
  },
  "client_certificate": "PEM Cert",
  "client_id": "e959d1b5-5a63-4284-9268-851e30e3eceb",
  "discovered_servers": [
    {
      "domain": "test.com",
      "node": {
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "preference": "string",
      "server_ip": "string",
      "server_name": "string",
      "server_type": "string",
      "state": "string"
    }
  ],
  "name_mapping": {
    "trusted_domains": [
      "domain.com"
    ]
  },
  "password_schedule": {
    "schedule_day_of_week": "Sunday",
    "schedule_description": "string",
    "schedule_last_changed_time": "string",
    "schedule_time_of_day": 36900,
    "schedule_warn_message": "string"
  },
  "preferred_dcs": [
    {
      "fqdn": "test.com",
      "server_ip": "4.4.4.4"
    }
  ],
  "server_discovery_mode": "string",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "tenant_id": "c9f32fcb-4ab7-40fe-af1b-1850d46cfbbe",
  "trust_relationships": [
    {
      "home_domain": "string",
      "node": {
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "trusted_domains": [
        "string"
      ]
    }
  ]
}
====

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 262278
| Domain user and password are required fields.

| 655513
| Password update failed due to invalid credentials.

| 656392
| Preferred DC's need to be configured if CIFS discovery mode is set to none.

| 656393
| Default site needs to be configured if CIFS discovery mode is set to site.

| 656487
| Missing fields when doing CIFS operation with hybrid auth user type.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#ad_domain]
[.api-collapsible-fifth-title]
ad_domain

Specifies the credentials of a user with permissions to reset the password in the organizational unit for the machine account.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|password
|string
a|The account password of the user with permissions to reset the password in the organizational unit for the machine account.


|user
|string
a|The username of a user with permissions to reset the password in the organizational unit for the machine account.


|===


[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#discovered_servers]
[.api-collapsible-fifth-title]
discovered_servers

[cols=3*,options=header]
|===
|Name
|Type
|Description

|domain
|string
a|Fully Qualified Domain Name.


|node
|link:#node[node]
a|

|preference
|string
a|Server Preference


|server_ip
|string
a|Server IP address


|server_name
|string
a|Server Name


|server_type
|string
a|Server Type


|state
|string
a|Server status


|===


[#name_mapping]
[.api-collapsible-fifth-title]
name_mapping

Specifies the name mapping search records.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|trusted_domains
|array[string]
a|

|===


[#password_schedule]
[.api-collapsible-fifth-title]
password_schedule

Specifies the password schedule records.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|schedule_day_of_week
|string
a|Day of the week for password change schedule.


|schedule_description
|string
a|Schedule description.


|schedule_enabled
|boolean
a|Is password schedule enabled.


|schedule_last_changed_time
|string
a|Last successful password change time.


|schedule_randomized_minute
|integer
a|Minutes within which schedule start can be randomized.


|schedule_time_of_day
|string
a|Start time for password change schedule.


|schedule_warn_message
|string
a|Warning message in case job is deleted.


|schedule_weekly_interval
|integer
a|Interval in weeks for password change schedule.


|===


[#preferred_dcs]
[.api-collapsible-fifth-title]
preferred_dcs

[cols=3*,options=header]
|===
|Name
|Type
|Description

|fqdn
|string
a|Fully Qualified Domain Name.


|server_ip
|string
a|IP address of the preferred domain controller (DC). The address can be either an IPv4 or an IPv6 address.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#trust_relationships]
[.api-collapsible-fifth-title]
trust_relationships

[cols=3*,options=header]
|===
|Name
|Type
|Description

|home_domain
|string
a|Home Domain Name


|node
|link:#node[node]
a|

|trusted_domains
|array[string]
a|Trusted Domain Name


|===


[#cifs_domain]
[.api-collapsible-fifth-title]
cifs_domain

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ad_domain
|link:#ad_domain[ad_domain]
a|Specifies the credentials of a user with permissions to reset the password in the organizational unit for the machine account.


|client_certificate
|string
a|PKCS12 certificate used by the application to prove its identity to AKV.


|client_id
|string
a|Application client ID of the deployed Azure application with appropriate access to an AKV or EntraId.


|discovered_servers
|array[link:#discovered_servers[discovered_servers]]
a|Specifies the discovered servers records.


|name_mapping
|link:#name_mapping[name_mapping]
a|Specifies the name mapping search records.


|password_schedule
|link:#password_schedule[password_schedule]
a|Specifies the password schedule records.


|preferred_dcs
|array[link:#preferred_dcs[preferred_dcs]]
a|Specifies the preferred DC records.


|server_discovery_mode
|string
a|Specifies the mode of server discovery.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|tenant_id
|string
a|Directory (tenant) ID of the deployed Azure application with appropriate access to an AKV or EntraId.


|trust_relationships
|array[link:#trust_relationships[trust_relationships]]
a|Specifies the trusted domain records.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
