---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-protocols-cifs-local-users.html'
summary: 'Create the local user configuration for an SVM'
---

= Create the local user configuration for an SVM

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/protocols/cifs/local-users`#

*Introduced In:* 9.9

Creates the local user configuration for an SVM.

== Important notes

* The user name can contain up to 20 characters.
* The user name cannot be terminated by a period.
* The user name does not support any of the following characters: " / ? [ ] , : \| < > + = ; ? * @ or ASCII characters in the range 1-31.
* The password must be at least six characters in length and must not contain the user account name.
* The password must contain characters from three of the following four categories:
* English uppercase characters (A through Z)
* English lowercase characters (a through z)
* Base 10 digits (0 through 9)
* Special characters: ~ ! @ # 0 {caret} & * _ - + = ` ? \| ( ) [ ] : ; " ' < > , . ? /

== Required properties

* `svm.uuid` or `svm.name` - Existing SVM in which to create the local user.
* `name` - Name of the local user.
* `password` - Password for the local user.

== Default property values

If not specified in POST, the following default property value is assigned:

* `account_disabled` - false

== Related ONTAP commands

* `vserver cifs users-and-groups local-user create`

== Learn more

* link:protocols_cifs_local-users_endpoint_overview.html[DOC /protocols/cifs/local-users]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|account_disabled
|boolean
a|Indicates whether the user account is enabled or disabled.


|description
|string
a|Description for the local user.


|full_name
|string
a|User's full name.


|membership
|array[link:#membership[membership]]
a|Specifies local groups of which this local user is a member.


|name
|string
a|Local user name. The maximum supported length of an user name is 20 characters.


|password
|string
a|Password for the local user.


|sid
|string
a|The security ID of the local user which uniquely identifies the user. The user SID is automatically generated in POST and it is retrieved using the GET method.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "description": "This is local user.",
  "full_name": "user name",
  "membership": [
    {
      "name": "SMB_SERVER01\\group",
      "sid": "S-1-5-21-256008430-3394229847-3930036330-1001"
    }
  ],
  "name": "SMB_SERVER01\\user",
  "password": "string",
  "sid": "S-1-5-21-256008430-3394229847-3930036330-1001",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  }
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|Number of local user records.


|records
|array[link:#local_cifs_user[local_cifs_user]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "num_records": 1,
  "records": [
    {
      "description": "This is local user.",
      "full_name": "user name",
      "membership": [
        {
          "name": "SMB_SERVER01\\group",
          "sid": "S-1-5-21-256008430-3394229847-3930036330-1001"
        }
      ],
      "name": "SMB_SERVER01\\user",
      "password": "string",
      "sid": "S-1-5-21-256008430-3394229847-3930036330-1001",
      "svm": {
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    }
  ]
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 262278
| Name and password are required fields.

| 655399
| CIFS server must exist to create a local user.

| 655660
| The operation is allowed only on data SVMs.

| 655661
| The user name should not exceed 20 characters. Also full_name and description should not exceed 256 characters.

| 655665
| The user name must not match the CIFS server name of the specified SVM.

| 655668
| The specified user name contains illegal characters.

| 655675
| The local domain name specified in user name doesn't exist.

| 655682
| The user name cannot be blank.

| 655733
| The password does not meet the password complexity requirements.

| 655736
| The specified user name already exists.

| 2621706
| The specified SVM UUID is incorrect for the specified SVM name.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#membership]
[.api-collapsible-fifth-title]
membership

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Local group name. The maximum supported length of a group name is 256 characters.


|sid
|string
a|The security ID of the local group which uniquely identifies the group. The group SID is automatically generated in POST and it is retrieved using the GET method.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#local_cifs_user]
[.api-collapsible-fifth-title]
local_cifs_user

[cols=3*,options=header]
|===
|Name
|Type
|Description

|account_disabled
|boolean
a|Indicates whether the user account is enabled or disabled.


|description
|string
a|Description for the local user.


|full_name
|string
a|User's full name.


|membership
|array[link:#membership[membership]]
a|Specifies local groups of which this local user is a member.


|name
|string
a|Local user name. The maximum supported length of an user name is 20 characters.


|password
|string
a|Password for the local user.


|sid
|string
a|The security ID of the local user which uniquely identifies the user. The user SID is automatically generated in POST and it is retrieved using the GET method.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
