---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-resource-tags-resources.html'
summary: 'Create a new tag for a resource'
---

= Create a new tag for a resource

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/resource-tags/{resource_tag.value}/resources`#

*Introduced In:* 9.13

Creates a new tag on a specific resource.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|resource_tag.value
|string
|path
|True
a|* format: key:value


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|This property provides the address in the API at which the tagged resource is available. Additional queries can be made on this
endpoint to fetch the resource's properties.


|label
|string
a|This is a human-readable classifier representing the type of thing that is pointed to by the href.


|svm
|link:#svm[svm]
a|If the tagged resource belongs to an SVM, this property will be set. If the resource does not belong to an SVM (i.e. it belongs
to the cluster as a whole), then this property will be empty and unreturned.


|value
|string
a|The text value of the tag formatted as `key:value`.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "href": "string",
  "label": "volume",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "value": "string"
}
====

== Response

```
Status: 201, Created
```

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 262257
| The API specified in the href cannot be found.

| 262258
| The resource specified in the href does not support tagging.

| 262259
| The specified href cannot be parsed.

| 262260
| The provided href is missing a key to a specific resource.

| 262261
| The specified href points to a resource that does not exist.

| 262262
| The specified href cannot be an empty string.

| 262263
| Tag key-value pairs cannot be longer than 200 characters.

| 263148
| Specified resource cannot be tagged because it reached allowed tags limit.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#svm]
[.api-collapsible-fifth-title]
svm

If the tagged resource belongs to an SVM, this property will be set. If the resource does not belong to an SVM (i.e. it belongs
to the cluster as a whole), then this property will be empty and unreturned.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#resource_tag_resource]
[.api-collapsible-fifth-title]
resource_tag_resource

This object provides a pointer to the tagged resource in the API. Details about the tagged object are available by querying
the address of the href property.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|This property provides the address in the API at which the tagged resource is available. Additional queries can be made on this
endpoint to fetch the resource's properties.


|label
|string
a|This is a human-readable classifier representing the type of thing that is pointed to by the href.


|svm
|link:#svm[svm]
a|If the tagged resource belongs to an SVM, this property will be set. If the resource does not belong to an SVM (i.e. it belongs
to the cluster as a whole), then this property will be empty and unreturned.


|value
|string
a|The text value of the tag formatted as `key:value`.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
