---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-cluster-mediators.html'
summary: 'Create and connect an ONTAP Mediator'
---

= Create and connect an ONTAP Mediator

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/cluster/mediators`#

*Introduced In:* 9.8

Creates and connect a mediator.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|account_token
|string
a|NetApp Console account token. This field is only applicable to the ONTAP cloud mediator.

* x-ntap-createOnly: true
* Introduced in: 9.19
* x-nullable: true


|bluexp_account_token
|string
a|BlueXP account token. This field is only applicable to the ONTAP cloud mediator. This has been replaced by account_token. Support for this field will be removed in a future release.

* x-ntap-createOnly: true
* x-ntap-deprecated: 9.19.1
* Introduced in: 9.17
* x-nullable: true


|bluexp_org_id
|string
a|BlueXP organization ID. This field is only applicable to the ONTAP cloud mediator. This has been replaced by org_id. Support for this field will be removed in a future release.

* x-ntap-createOnly: true
* x-ntap-deprecated: 9.19.1
* Introduced in: 9.17
* x-nullable: true


|ca_certificate
|string
a|CA certificate for ONTAP Mediator. This is optional if the certificate is already installed.

* x-ntap-createOnly: true
* Introduced in: 9.8
* x-nullable: true


|connection_type
|string
a|Connection type from ONTAP MetroCluster to mediator. Applicable only to on-prem mediator used in ONTAP MetroCluster configurations.

* Default value: 1
* enum: ["iscsi_mediator", "https_mediator"]
* Introduced in: 9.19
* readCreate: 1
* x-nullable: true


|dr_group
|link:#dr_group[dr_group]
a|DR group reference.


|ip_address
|string
a|The IP address of the mediator.


|local_mediator_connectivity
|string
a|Indicates the mediator connectivity status of the local cluster. Possible values are connected, unreachable, unusable and down-high-latency. This field is only applicable to the mediators in SnapMirror active sync configuration.


|org_id
|string
a|NetApp Console organization ID. This field is only applicable to the ONTAP cloud mediator.

* x-ntap-createOnly: true
* Introduced in: 9.19
* x-nullable: true


|password
|string
a|The password used to connect to the REST server on the mediator.


|peer_cluster
|link:#peer_cluster[peer_cluster]
a|The peer cluster that the mediator service is used for.


|peer_mediator_connectivity
|string
a|Indicates the mediator connectivity status of the peer cluster. Possible values are connected, unreachable, unknown and down-high-latency.


|port
|integer
a|The REST server's port number on the mediator.


|reachable
|boolean
a|Indicates the connectivity status of the mediator.


|service_account_client_id
|string
a|Client ID of the NetApp Console service account. This field is only applicable to the ONTAP cloud mediator.

* x-ntap-createOnly: true
* Introduced in: 9.17
* x-nullable: true


|service_account_client_secret
|string
a|Client secret token of the NetApp Console service account. This field is only applicable to the ONTAP cloud mediator.

* x-ntap-createOnly: true
* Introduced in: 9.17
* x-nullable: true


|strict_cert_validation
|boolean
a|Indicates if strict validation of certificates is performed while making REST API calls to the mediator. This field is only applicable to the ONTAP Cloud Mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* x-nullable: true


|type
|string
a|Mediator type. This field is only applicable to the mediators in SnapMirror active sync configuration.


|use_http_proxy_local
|boolean
a|Indicates if the local cluster should use an http-proxy server while making REST API calls to the mediator. This field is only applicable to the ONTAP cloud mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* x-nullable: true


|use_http_proxy_remote
|boolean
a|Indicates if the remote cluster should use an http-proxy server while making REST API calls to the mediator. This field is only applicable to the ONTAP cloud mediator.

* Default value: 1
* example: true
* Introduced in: 9.17
* writeOnly: 1
* x-nullable: true


|user
|string
a|The username used to connect to the REST server on the mediator.


|uuid
|string
a|The unique identifier for the mediator service.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "account_token": "string",
  "bluexp_account_token": "string",
  "bluexp_org_id": "string",
  "ca_certificate": "string",
  "connection_type": "string",
  "dr_group": {
    "id": 0
  },
  "ip_address": "10.10.10.7",
  "local_mediator_connectivity": "connected",
  "org_id": "string",
  "password": "mypassword",
  "peer_cluster": {
    "name": "cluster2",
    "uuid": "ebe27c49-1adf-4496-8335-ab862aebebf2"
  },
  "peer_mediator_connectivity": "connected",
  "port": 31784,
  "reachable": 1,
  "service_account_client_id": "string",
  "service_account_client_secret": "string",
  "strict_cert_validation": 1,
  "type": "string",
  "use_http_proxy_local": 1,
  "use_http_proxy_remote": 1,
  "user": "myusername",
  "uuid": "string"
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Response

```
Status: 201, Created
```

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 13369351
| Update to mediator failed. Reason: does not authorized for that command. Check that the peer cluster and mediator are reachable.

| 2430758
| Mediator cannot be added. Reason: Some of the nodes in the cluster have incorrect MetroCluster IP configuration.

| 2430734
| Unable to add Mediator. Reason : Authentication failed.

| 2430774
| Failed to add Mediator. Reason : Node is not reachable or does not exist.

| 2432871
| Failed to add Mediator. Reason : Some of the parameters in the request is invalid.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#dr_group]
[.api-collapsible-fifth-title]
dr_group

DR group reference.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|integer
a|DR Group ID


|===


[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#peer_cluster]
[.api-collapsible-fifth-title]
peer_cluster

The peer cluster that the mediator service is used for.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#mediator]
[.api-collapsible-fifth-title]
mediator

Mediator information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|account_token
|string
a|NetApp Console account token. This field is only applicable to the ONTAP cloud mediator.

* x-ntap-createOnly: true
* Introduced in: 9.19
* x-nullable: true


|bluexp_account_token
|string
a|BlueXP account token. This field is only applicable to the ONTAP cloud mediator. This has been replaced by account_token. Support for this field will be removed in a future release.

* x-ntap-createOnly: true
* x-ntap-deprecated: 9.19.1
* Introduced in: 9.17
* x-nullable: true


|bluexp_org_id
|string
a|BlueXP organization ID. This field is only applicable to the ONTAP cloud mediator. This has been replaced by org_id. Support for this field will be removed in a future release.

* x-ntap-createOnly: true
* x-ntap-deprecated: 9.19.1
* Introduced in: 9.17
* x-nullable: true


|ca_certificate
|string
a|CA certificate for ONTAP Mediator. This is optional if the certificate is already installed.

* x-ntap-createOnly: true
* Introduced in: 9.8
* x-nullable: true


|connection_type
|string
a|Connection type from ONTAP MetroCluster to mediator. Applicable only to on-prem mediator used in ONTAP MetroCluster configurations.

* Default value: 1
* enum: ["iscsi_mediator", "https_mediator"]
* Introduced in: 9.19
* readCreate: 1
* x-nullable: true


|dr_group
|link:#dr_group[dr_group]
a|DR group reference.


|ip_address
|string
a|The IP address of the mediator.


|local_mediator_connectivity
|string
a|Indicates the mediator connectivity status of the local cluster. Possible values are connected, unreachable, unusable and down-high-latency. This field is only applicable to the mediators in SnapMirror active sync configuration.


|org_id
|string
a|NetApp Console organization ID. This field is only applicable to the ONTAP cloud mediator.

* x-ntap-createOnly: true
* Introduced in: 9.19
* x-nullable: true


|password
|string
a|The password used to connect to the REST server on the mediator.


|peer_cluster
|link:#peer_cluster[peer_cluster]
a|The peer cluster that the mediator service is used for.


|peer_mediator_connectivity
|string
a|Indicates the mediator connectivity status of the peer cluster. Possible values are connected, unreachable, unknown and down-high-latency.


|port
|integer
a|The REST server's port number on the mediator.


|reachable
|boolean
a|Indicates the connectivity status of the mediator.


|service_account_client_id
|string
a|Client ID of the NetApp Console service account. This field is only applicable to the ONTAP cloud mediator.

* x-ntap-createOnly: true
* Introduced in: 9.17
* x-nullable: true


|service_account_client_secret
|string
a|Client secret token of the NetApp Console service account. This field is only applicable to the ONTAP cloud mediator.

* x-ntap-createOnly: true
* Introduced in: 9.17
* x-nullable: true


|strict_cert_validation
|boolean
a|Indicates if strict validation of certificates is performed while making REST API calls to the mediator. This field is only applicable to the ONTAP Cloud Mediator.

* Default value:
* example: true
* Introduced in: 9.17
* x-nullable: true


|type
|string
a|Mediator type. This field is only applicable to the mediators in SnapMirror active sync configuration.


|use_http_proxy_local
|boolean
a|Indicates if the local cluster should use an http-proxy server while making REST API calls to the mediator. This field is only applicable to the ONTAP cloud mediator.

* Default value:
* example: true
* Introduced in: 9.17
* x-nullable: true


|use_http_proxy_remote
|boolean
a|Indicates if the remote cluster should use an http-proxy server while making REST API calls to the mediator. This field is only applicable to the ONTAP cloud mediator.

* Default value:
* example: true
* Introduced in: 9.17
* writeOnly: 1
* x-nullable: true


|user
|string
a|The username used to connect to the REST server on the mediator.


|uuid
|string
a|The unique identifier for the mediator service.


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
