---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-protocols-nvme-subsystems-hosts.html'
summary: 'Add NVMe subsystem hosts'
---

= Add NVMe subsystem hosts

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/protocols/nvme/subsystems/{subsystem.uuid}/hosts`#

*Introduced In:* 9.6

Adds NVMe subsystem host(s) to an NVMe subsystem.

== Required properties

* `nqn` or `records.nqn` - NVMe host(s) NQN(s) to add to the NVMe subsystem.

== Related ONTAP commands

* `vserver nvme subsystem host add`

== Learn more

* link:protocols_nvme_subsystems_endpoint_overview.html[DOC /protocols/nvme/subsystems]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|subsystem.uuid
|string
|path
|True
a|The unique identifier of the NVMe subsystem.


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|dh_hmac_chap
|link:#dh_hmac_chap[dh_hmac_chap]
a|A container for the configuration of NVMe in-band authentication using the DH-HMAC-CHAP protocol for a host.


|io_queue
|link:#io_queue[io_queue]
a|The properties of the submission queue used to submit I/O commands for execution by the NVMe controller.


|nqn
|string
a|The NVMe qualified name (NQN) used to identify the NVMe storage target.


|priority
|string
a|The host priority setting allocates appropriate NVMe I/O queues (count and depth) for the host to submit I/O commands. Absence of this property in GET implies io_queue count and I/O queue depth are being used.


|proximity
|link:#proximity[proximity]
a|Properties that define the SVMs to which the host is proximal. This information is used to properly report active optimized and active non-optimized network paths using an NVMe controller. If no configuration has been specified for the host, the sub-object is not present in GET requests.

These properties apply to all instances of the host in the NVMe subsystem in the SVM and its peers.


|records
|array[link:#records[records]]
a|An array of NVMe hosts specified to add multiple NVMe hosts to an NVMe subsystem in a single API call. Valid in POST only.


|subsystem
|link:#subsystem[subsystem]
a|The NVMe subsystem to which the NVMe host has been provisioned.


|tls
|link:#tls[tls]
a|A container for the configuration for NVMe/TCP-TLS transport session for the host.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "dh_hmac_chap": {
    "controller_secret_key": "DHHC-1:00:ia6zGodOr4SEG0Zzaw398rpY0wqipUWj4jWjUh4HWUz6aQ2n:",
    "group_size": "string",
    "hash_function": "string",
    "host_secret_key": "DHHC-1:00:ia6zGodOr4SEG0Zzaw398rpY0wqipUWj4jWjUh4HWUz6aQ2n:",
    "mode": "bidirectional"
  },
  "io_queue": {
    "count": 4,
    "depth": 32
  },
  "nqn": "nqn.1992-01.example.com:string",
  "priority": "string",
  "proximity": {
    "peer_svms": [
      {
        "name": "peer1",
        "uuid": "4204cf77-4c82-9bdb-5644-b5a841c097a9"
      }
    ]
  },
  "records": [
    {
      "dh_hmac_chap": {
        "controller_secret_key": "DHHC-1:00:ia6zGodOr4SEG0Zzaw398rpY0wqipUWj4jWjUh4HWUz6aQ2n:",
        "group_size": "string",
        "hash_function": "string",
        "host_secret_key": "DHHC-1:00:ia6zGodOr4SEG0Zzaw398rpY0wqipUWj4jWjUh4HWUz6aQ2n:",
        "mode": "bidirectional"
      },
      "io_queue": {
        "count": 4,
        "depth": 32
      },
      "nqn": "nqn.1992-01.example.com:string",
      "subsystem": {
        "name": "subsystem1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "tls": {
        "configured_psk": "NVMeTLSkey-1:01:VRLbtnN9AQb2WXW3c9+wEf/DRLz0QuLdbYvEhwtdWwNf9LrZ:",
        "key_type": "configured"
      }
    }
  ],
  "subsystem": {
    "name": "subsystem1",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "tls": {
    "configured_psk": "NVMeTLSkey-1:01:VRLbtnN9AQb2WXW3c9+wEf/DRLz0QuLdbYvEhwtdWwNf9LrZ:",
    "key_type": "configured"
  }
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|The number of records in the response.


|records
|array[link:#nvme_subsystem_host[nvme_subsystem_host]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "num_records": 1,
  "records": [
    {
      "dh_hmac_chap": {
        "controller_secret_key": "DHHC-1:00:ia6zGodOr4SEG0Zzaw398rpY0wqipUWj4jWjUh4HWUz6aQ2n:",
        "group_size": "string",
        "hash_function": "string",
        "host_secret_key": "DHHC-1:00:ia6zGodOr4SEG0Zzaw398rpY0wqipUWj4jWjUh4HWUz6aQ2n:",
        "mode": "bidirectional"
      },
      "io_queue": {
        "count": 4,
        "depth": 32
      },
      "nqn": "nqn.1992-01.example.com:string",
      "priority": "string",
      "proximity": {
        "peer_svms": [
          {
            "name": "peer1",
            "uuid": "4204cf77-4c82-9bdb-5644-b5a841c097a9"
          }
        ]
      },
      "records": [
        {
          "dh_hmac_chap": {
            "controller_secret_key": "DHHC-1:00:ia6zGodOr4SEG0Zzaw398rpY0wqipUWj4jWjUh4HWUz6aQ2n:",
            "group_size": "string",
            "hash_function": "string",
            "host_secret_key": "DHHC-1:00:ia6zGodOr4SEG0Zzaw398rpY0wqipUWj4jWjUh4HWUz6aQ2n:",
            "mode": "bidirectional"
          },
          "io_queue": {
            "count": 4,
            "depth": 32
          },
          "nqn": "nqn.1992-01.example.com:string",
          "subsystem": {
            "name": "subsystem1",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          },
          "tls": {
            "configured_psk": "NVMeTLSkey-1:01:VRLbtnN9AQb2WXW3c9+wEf/DRLz0QuLdbYvEhwtdWwNf9LrZ:",
            "key_type": "configured"
          }
        }
      ],
      "subsystem": {
        "name": "subsystem1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "tls": {
        "configured_psk": "NVMeTLSkey-1:01:VRLbtnN9AQb2WXW3c9+wEf/DRLz0QuLdbYvEhwtdWwNf9LrZ:",
        "key_type": "configured"
      }
    }
  ]
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 262186
| The "records" array and other host properties are mutually exclusive.

| 72089705
| The NVMe subsystem host already exists for the NVMe subsystem.

| 72089716
| The DH-HMAC-CHAP secret property is invalid. DH-HMAC-CHAP secrets must be in the format "DHHC-1:0X:<Base 64 encoded key and CRC>:", where X represents 0, 1, or 3 indicating no hash function, SHA-256, and SHA-512 respectively.

| 72089771
| The NQN is invalid. A non-empty qualifier is required after the prefix. An example of a valid NQN is _nqn.1992-01.com.example:string_.

| 72089772
| The NQN is invalid. Add the prefix _'nqn'_. An example of a valid NQN is _nqn.1992-01.com.example:string_.

| 72089773
| The NQN is invalid. The date field must be formatted _yyyy-mm_. An example of a valid NQN is _nqn.1992-01.com.example:string_.

| 72090001
| The NVMe subsystem does not exist.

| 72090003
| A host to be added to an NVMe subsystem is missing the "nqn" property.

| 72090036
| An NVMe subsystem host NQN is duplicated in the input.

| 72090041
| An element in the "records" array contains an invalid property.

| 72090042
| The DH-HMAC-CHAP secret property is required when setting any other NVMe in-band authentication properties for a host.

| 72090151
| NVMe/TCP-TLS is not supported for the effective version of the cluster.

| 72090202
| A provided NVMe subsystem host TLS configured PSK is not valid.

| 72090204
| A TLS configured PSK was not provided when adding an NVMe subsystem host with the configured key type.

| 72090205
| An invalid combination for the TLS key type and configured PSK values was provided when adding an NVMe subsystem host. When key type is "none", no configured PSK is allowed. When key type is "configured", a configured PSK is required.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#dh_hmac_chap]
[.api-collapsible-fifth-title]
dh_hmac_chap

A container for the configuration of NVMe in-band authentication using the DH-HMAC-CHAP protocol for a host.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|controller_secret_key
|string
a|The controller secret for NVMe in-band authentication. The value of this property is used by the NVMe host to authenticate the NVMe controller while establishing a connection. If unset, the controller is not authenticated. When supplied, the property `host_secret_key` must also be supplied. Optional in POST.

This property is write-only. The `mode` property can be used to identify if a controller secret has been set for the host, but the controller secret value cannot be read. To change the value, the host must be deleted from the subsystem and re-added.


|group_size
|string
a|The Diffie-Hellman group size for NVMe in-band authentication. When property `host_secret_key` is provided, this property defaults to `2048_bit`. When supplied, the property `host_secret_key` must also be supplied. Optional in POST.


|hash_function
|string
a|The hash function for NVMe in-band authentication. When property `host_secret_key` is provided, this property defaults to `sha_256`. When supplied, the property `host_secret_key` must also be supplied. Optional in POST.


|host_secret_key
|string
a|The host secret for NVMe in-band authentication. The value of this property is used by the NVMe controller to authenticate the NVMe host while establishing a connection. If unset, no authentication is performed by the host or controller. This property must be supplied if any other NVMe in-band authentication properties are supplied. Optional in POST.

This property is write-only. The `mode` property can be used to identify if a host secret has been set for the host, but the host secret value cannot be read. To change the value, the host must be deleted from the subsystem and re-added.


|mode
|string
a|The expected NVMe in-band authentication mode for the host. This property is an indication of which secrets are configured for the host. When set to:

* none: The host has neither the host nor controller secret configured, and no authentication is performed.
* unidirectional: The host has a host secret configured. The controller will authenticate the host.
* bidirectional: The host has both a host and controller secret configured. The controller will authenticate the host and the host will authenticate the controller.


|===


[#io_queue]
[.api-collapsible-fifth-title]
io_queue

The properties of the submission queue used to submit I/O commands for execution by the NVMe controller.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|The number of I/O queue pairs. Absence of this property in GET implies property priority is set and platform and transport protocol specific values for I/O queue count is being used. Valid in GET only.


|depth
|integer
a|The I/O queue depth. Absence of this property in GET implies property priority is set and platform and transport protocol specific values for I/O queue depth is being used. Valid in GET only.


|===


[#peer_svms]
[.api-collapsible-fifth-title]
peer_svms

A reference to an SVM peer relationship.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The local name of the peer SVM. This name is unique among all local and peer SVMs.


|uuid
|string
a|The unique identifier of the SVM peer relationship. This is the UUID of the relationship, not the UUID of the peer SVM itself.


|===


[#proximity]
[.api-collapsible-fifth-title]
proximity

Properties that define the SVMs to which the host is proximal. This information is used to properly report active optimized and active non-optimized network paths using an NVMe controller. If no configuration has been specified for the host, the sub-object is not present in GET requests.

These properties apply to all instances of the host in the NVMe subsystem in the SVM and its peers.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|local_svm
|boolean
a|A boolean that indicates if the host is proximal to the SVM for which it is configured.


|peer_svms
|array[link:#peer_svms[peer_svms]]
a|An array of remote peer SVMs to which the host is proximal.


|===


[#io_queue]
[.api-collapsible-fifth-title]
io_queue

The properties of the submission queue used to submit I/O commands for execution by the NVMe controller.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|The number of I/O queue pairs. The default value is inherited from the owning NVMe subsystem.


|depth
|integer
a|The I/O queue depth. The default value is inherited from the owning NVMe subsystem.


|===


[#subsystem]
[.api-collapsible-fifth-title]
subsystem

The NVMe subsystem to which the NVMe host has been provisioned.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the NVMe subsystem.


|uuid
|string
a|The unique identifier of the NVMe subsystem.


|===


[#tls]
[.api-collapsible-fifth-title]
tls

A container for the configuration for NVMe/TCP-TLS transport session for the host.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|configured_psk
|string
a|A user supplied pre-shared key (PSK) value in PSK Interchange Format. Optional in POST.

The values for property `key_type` and property `configured_psk` must logically agree. This property is only allowed when `key_type` is `configured`. If `configured_psk` is supplied and `key_type` is unset, `key_type` defaults to `configured`.

This property is write-only. The `key_type` property can be used to identify if a configured PSK has been set for the host, but the PSK value cannot be read. To change the value, the host must be deleted from the subsystem and re-added.


|key_type
|string
a|The method by which the TLS pre-shared key (PSK) is configured for the host. Optional in POST.

The values for property `key_type` and property `configured_psk` must logically agree.

Possible values:

* `none` - TLS is not configured for the host connection. No value is allowed for property `configured_psk`.
* `configured` - A user supplied PSK is configured for the NVMe/TCP-TLS transport connection between the host and the NVMe subsystem. A valid value for property `configured_psk` is required.

This property defaults to `none` unless a value is supplied for `configured_psk` in which case it defaults to `configured`.


|===


[#records]
[.api-collapsible-fifth-title]
records

The NVMe host provisioned to access NVMe namespaces mapped to a subsystem.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|dh_hmac_chap
|link:#dh_hmac_chap[dh_hmac_chap]
a|A container for the configuration of NVMe in-band authentication using the DH-HMAC-CHAP protocol for a host.


|io_queue
|link:#io_queue[io_queue]
a|The properties of the submission queue used to submit I/O commands for execution by the NVMe controller.


|nqn
|string
a|The NVMe qualified name (NQN) used to identify the NVMe storage target. Not allowed in POST when the `records` property is used.


|subsystem
|link:#subsystem[subsystem]
a|The NVMe subsystem to which the NVMe host has been provisioned.


|tls
|link:#tls[tls]
a|A container for the configuration for NVMe/TCP-TLS transport session for the host.


|===


[#nvme_subsystem_host]
[.api-collapsible-fifth-title]
nvme_subsystem_host

The NVMe host provisioned to access NVMe namespaces mapped to a subsystem.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|dh_hmac_chap
|link:#dh_hmac_chap[dh_hmac_chap]
a|A container for the configuration of NVMe in-band authentication using the DH-HMAC-CHAP protocol for a host.


|io_queue
|link:#io_queue[io_queue]
a|The properties of the submission queue used to submit I/O commands for execution by the NVMe controller.


|nqn
|string
a|The NVMe qualified name (NQN) used to identify the NVMe storage target.


|priority
|string
a|The host priority setting allocates appropriate NVMe I/O queues (count and depth) for the host to submit I/O commands. Absence of this property in GET implies io_queue count and I/O queue depth are being used.


|proximity
|link:#proximity[proximity]
a|Properties that define the SVMs to which the host is proximal. This information is used to properly report active optimized and active non-optimized network paths using an NVMe controller. If no configuration has been specified for the host, the sub-object is not present in GET requests.

These properties apply to all instances of the host in the NVMe subsystem in the SVM and its peers.


|records
|array[link:#records[records]]
a|An array of NVMe hosts specified to add multiple NVMe hosts to an NVMe subsystem in a single API call. Valid in POST only.


|subsystem
|link:#subsystem[subsystem]
a|The NVMe subsystem to which the NVMe host has been provisioned.


|tls
|link:#tls[tls]
a|A container for the configuration for NVMe/TCP-TLS transport session for the host.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
