---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-storage-snaplock-file-fingerprints.html'
summary: 'Create a fingerprint computation session'
---

= Create a fingerprint computation session

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/storage/snaplock/file-fingerprints`#

*Introduced In:* 9.7

Creates a fingerprint computation session on the file and returns a session-id. This session-id is a unique identifier that you can use to retrieve the progress of an ongoing fingerprint operation. When the operation is complete, you can use the session-id to retrieve the complete fingerprint output for the file .

== Required properties

* `svm.uuid` or `svm.name` - Name or UUID of the SVM.
* `volume.name` or `volume.uuid` - Name or UUID of the volume.
* `path` - Path of the file.

== Default property values

If not specified in POST, the follow default property values are assigned:

* `algorithm` - _sha256_

== Related ONTAP commands

* `volume file fingerprint start`

== Example

----
POST "/api/storage/snaplock/file-fingerprints" '{"svm":{"uuid":"23940494-3f3a-11e9-8675-0050568e8f89"},"volume": {"uuid":"26cdb58c-3f3a-11e9-8675-0050568e8f89"},"path":"/vol/a1.txt","algorithm":"md5"}'
----

== Learn more

* link:storage_snaplock_file-fingerprints_endpoint_overview.html[DOC /storage/snaplock/file-fingerprints]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|algorithm
|string
a|The digest algorithm which is used for the fingerprint computation


|data_fingerprint
|string
a|The digest value of data of the file. The fingerprint is base64 encoded. This field is not included if the scope is metadata-only.


|file_size
|integer
a|The size of the file in bytes.


|file_type
|string
a|The type of the file.


|id
|integer
a|A unique identifier for the fingerprint operation


|metadata_fingerprint
|string
a|The digest value of metadata of the file. The metadata fingerprint is calculated for file size, file ctime, file mtime, file crtime, file retention time, file uid, file gid, and file type. The fingerprint is base64 encoded. This field is not included if the scope is data-only.


|path
|string
a|Specifies the path on which file fingerprint operation is running or has completed. Specifies the path relative to the output volume root, of the form "/path". The path can be path to a file or a directory.


|scope
|string
a|The scope of the file which is used for the fingerprint computation


|state
|string
a|Specifies the status of fingerprint operation.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|volume
|link:#volume[volume]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "algorithm": "sha256",
  "data_fingerprint": "MOFJVevxNSJm3C/4Bn5oEEYH51CrudOzZYK4r5Cfy1g=",
  "file_size": 1048576,
  "file_type": "worm",
  "id": 17039367,
  "metadata_fingerprint": "8iMjqJXiNcqgXT5XuRhLiEwIrJEihDmwS0hrexnjgmc=",
  "path": "/homedir/dir1",
  "scope": "data_only",
  "state": "completed",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "volume": {
    "name": "volume1",
    "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
  }
}
====

== Response

```
Status: 201, Created
```

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 2
| An invalid value was entered for one of the fields

| 2621519
| Invalid SVM name format

| 14090347
| Invalid path format

| 14090443
| Invalid volume name

| 14090444
| Invalid Vserver name

| 14090447
| Invalid volume UUID

| 14090448
| Invalid key values. Provide valid Vserver name and volume name or Vserver UUID and volume UUID
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume. This field cannot be specified in a PATCH method.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6
* x-nullable: true


|===


[#snaplock_file_fingerprint]
[.api-collapsible-fifth-title]
snaplock_file_fingerprint

[cols=3*,options=header]
|===
|Name
|Type
|Description

|algorithm
|string
a|The digest algorithm which is used for the fingerprint computation


|data_fingerprint
|string
a|The digest value of data of the file. The fingerprint is base64 encoded. This field is not included if the scope is metadata-only.


|file_size
|integer
a|The size of the file in bytes.


|file_type
|string
a|The type of the file.


|id
|integer
a|A unique identifier for the fingerprint operation


|metadata_fingerprint
|string
a|The digest value of metadata of the file. The metadata fingerprint is calculated for file size, file ctime, file mtime, file crtime, file retention time, file uid, file gid, and file type. The fingerprint is base64 encoded. This field is not included if the scope is data-only.


|path
|string
a|Specifies the path on which file fingerprint operation is running or has completed. Specifies the path relative to the output volume root, of the form "/path". The path can be path to a file or a directory.


|scope
|string
a|The scope of the file which is used for the fingerprint computation


|state
|string
a|Specifies the status of fingerprint operation.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|volume
|link:#volume[volume]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
