---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-support-configuration-backup-backups.html'
summary: 'Create a configuration backup'
---

= Create a configuration backup

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/support/configuration-backup/backups`#

*Introduced In:* 9.7

Creates a configuration backup. The required backup file name must end with .7z extension. In clusters with greater than 32 nodes, a multi-part backup will be generated with each part containing the cluster-wide replica and up to 32 individual node backups.

== Required properties

* `node.uuid` or `node.name` - The node UUID or node name on which the configuration backup will be created.
* `name` - The backup file name

== Related ONTAP commands

* `system configuration backup create`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|auto
|boolean
a|Indicates if the backup was created automatically.


|backup_nodes
|array[link:#backup_node[backup_node]]
a|The list of nodes included in the backup.


|download_link
|string
a|The link to download the backup file.


|name
|string
a|The backup name.


|node
|link:#node[node]
a|The node that owns the configuration backup.


|size
|integer
a|The size of the backup in bytes.


|time
|string
a|The backup creation time.


|type
|string
a|The backup type.


|version
|string
a|The software version.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "backup_nodes": [
    {
      "name": "string"
    }
  ],
  "download_link": "https://10.224.65.198/backups/backup_file.7z",
  "name": "backup_file.7z",
  "node": {
    "name": "node1",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "size": 4787563,
  "time": "2019-02-04 13:33:48 -0500",
  "type": "string",
  "version": "9.7.0"
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Response

```
Status: 201, Created
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 5963818
| Failed to queue private job.

| 5963819
| Failed to queue cluster job.

| 5963871
| Requested backup name is missing .7z suffix.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#backup_node]
[.api-collapsible-fifth-title]
backup_node

The node name in the backup.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|===


[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#node]
[.api-collapsible-fifth-title]
node

The node that owns the configuration backup.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#configuration_backup_file]
[.api-collapsible-fifth-title]
configuration_backup_file

The configuration backup file.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|auto
|boolean
a|Indicates if the backup was created automatically.


|backup_nodes
|array[link:#backup_node[backup_node]]
a|The list of nodes included in the backup.


|download_link
|string
a|The link to download the backup file.


|name
|string
a|The backup name.


|node
|link:#node[node]
a|The node that owns the configuration backup.


|size
|integer
a|The size of the backup in bytes.


|time
|string
a|The backup creation time.


|type
|string
a|The backup type.


|version
|string
a|The software version.


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
