---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-protocols-san-igroups.html'
summary: 'Create an initiator group'
---

= Create an initiator group

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/protocols/san/igroups`#

*Introduced In:* 9.6

Creates an initiator group.

== Required properties

* `svm.uuid` or `svm.name` - Existing SVM in which to create the initiator group.
* `name` - Name of the initiator group.
* `os_type` - Operating system of the initiator group's initiators.

== Recommended optional properties

* `initiators.name` - Name(s) of initiator group's initiators. This property can be used to create the initiator group and populate it with initiators in a single request.

== Default property values

If not specified in POST, the following default property values are assigned.

* `protocol` - _mixed_ - Data protocol of the initiator group's initiators.

== Related ONTAP commands

* `lun igroup create`

== Learn more

* link:protocols_san_igroups_endpoint_overview.html[DOC /protocols/san/igroups]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment available for use by the administrator. Valid in POST and PATCH.


|connectivity_tracking
|link:#connectivity_tracking[connectivity_tracking]
a|An overview of the connections to ONTAP by the initiators in this group.

* readOnly: 1
* Introduced in: 9.11


|delete_on_unmap
|boolean
a|An option that causes the initiator group to be deleted when the last LUN map associated with it is deleted. Optional in POST and PATCH. This property defaults to _false_ when the initiator group is created.


|igroups
|array[link:#igroup_child[igroup_child]]
a|The existing initiator groups that are members of the group. Optional in POST.

This property is mutually exclusive with the _initiators_ property during POST.

This array contains only the direct children of the initiator group. If the member initiator groups have further nested initiator groups, those are reported in the `igroups` property of the child initiator group.

Zero or more nested initiator groups can be supplied when the initiator group is created. The initiator group will act as if it contains the aggregation of all initiators in any nested initiator groups.

After creation, nested initiator groups can be added or removed from the initiator group using the `/protocols/san/igroups/{igroup.uuid}/igroups` endpoint. See link:post-protocols-san-igroups-igroups(#-san-igroup-nested-create)anddelete-protocols-san-igroups-igroups-.html<</SAN/igroup_nested_create,POST /protocols/san/igroups/{igroup.uuid}/igroups>> and [DELETE /protocols/san/igroups/{igroup.uuid}/igroups/\{uuid}]  for more details.


|initiators
|array[link:#initiators[initiators]]
a|The initiators that are members of the group or any group nested below this group. Optional in POST.

This property is mutually exclusive with the _igroups_ property during POST.

During GET, this array contains initiators that are members of this group or any nested initiator groups below this group. When initiators of nested groups are returned, they include links to the initiator group that directly contains the initiator.

Zero or more initiators can be supplied when the initiator group is created. After creation, initiators can be added or removed from the initiator group using the `/protocols/san/igroups/{igroup.uuid}/initiators` endpoint. See link:post-protocols-san-igroups-initiators(#-san-igroup-initiator-create)anddelete-protocols-san-igroups-initiators-.html<</SAN/igroup_initiator_create,POST /protocols/san/igroups/{igroup.uuid}/initiators>> and [DELETE /protocols/san/igroups/{igroup.uuid}/initiators/\{name}]  for more details.


|lun_maps
|array[link:#lun_maps[lun_maps]]
a|All LUN maps with which the initiator is associated.

If the requested igroup is part of a remote, non-local, MetroCluster SVM, the LUN maps are not retrieved.

There is an added computational cost to retrieving property values for `lun_maps`. They are not populated for a GET request unless explicitly requested using the `fields` query parameter. See link:getting_started_with_the_ontap_rest_api.html#Requesting_specific_fields[Requesting specific fields] to learn more.


|name
|string
a|The name of the initiator group. Required in POST; optional in PATCH.


|os_type
|string
a|The host operating system of the initiator group. All initiators in the group should be hosts of the same operating system. Required in POST; optional in PATCH.


|parent_igroups
|array[link:#igroup_parent[igroup_parent]]
a|The initiator groups that contain this initiator group as a member.


|portset
|link:#portset[portset]
a|The portset to which the initiator group is bound. Binding the initiator group to a portset restricts the initiators of the group to accessing mapped LUNs only through network interfaces in the portset.

In a nested initiator group hierarchy, only a portset bound to the initiator group at the same level at which it is mapped, applies; portsets bound to parent or child initiator groups are ignored.

Optional in POST and PATCH. To unbind a portset from the initiator group, PATCH the `portset` object to  `null`, or PATCH `portset.name` to an empty string ("").


|protocol
|string
a|The protocols supported by the initiator group. This restricts the type of initiators that can be added to the initiator group. Optional in POST; if not supplied, this defaults to _mixed_.

The protocol of an initiator group cannot be changed after creation of the group.


|replication
|link:#replication[replication]
a|Properties related to initiator group replication.


|supports_igroups
|boolean
a|An initiator group may contain either initiators or other initiator groups, but not both simultaneously. This property is _true_ when initiator groups can be added to this initiator group. The `initiators.name` property cannot be used to determine this via a query because it reports initiators inherited from nested igroups.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|target
|link:#target[target]
a|Properties of the SCSI target to which the initiator group provides access.


|uuid
|string
a|The unique identifier of the initiator group.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "comment": "string",
  "connectivity_tracking": {
    "alerts": [
      {}
    ],
    "connection_state": "string",
    "required_nodes": [
      {
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      }
    ]
  },
  "igroups": [
    {
      "comment": "string",
      "igroups": [
        null
      ],
      "name": "igroup1",
      "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "initiators": [
    {
      "comment": "string",
      "connectivity_tracking": {
        "connection_state": "string"
      },
      "igroup": {
        "name": "igroup1",
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      },
      "name": "iqn.1998-01.com.corp.iscsi:name1",
      "proximity": {
        "peer_svms": [
          {
            "name": "peer1",
            "uuid": "4204cf77-4c82-9bdb-5644-b5a841c097a9"
          }
        ]
      }
    }
  ],
  "lun_maps": [
    {
      "logical_unit_number": 0,
      "lun": {
        "name": "lun1",
        "node": {
          "name": "node1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      }
    }
  ],
  "name": "igroup1",
  "os_type": "string",
  "parent_igroups": [
    {
      "comment": "string",
      "name": "igroup1",
      "parent_igroups": [
        null
      ],
      "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "portset": {
    "name": "portset1",
    "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
  },
  "protocol": "string",
  "replication": {
    "error": {
      "igroup": {
        "name": "igroup1",
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      }
    },
    "peer_svm": {
      "name": "peer1",
      "uuid": "4204cf77-4c82-9bdb-5644-b5a841c097a9"
    },
    "state": "string"
  },
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "target": {
    "firmware_revision": "9111",
    "product_id": "LUN C-Mode",
    "vendor_id": "NETAPP"
  },
  "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|The number of records in the response.


|records
|array[link:#igroup[igroup]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "num_records": 1,
  "records": [
    {
      "comment": "string",
      "connectivity_tracking": {
        "alerts": [
          {}
        ],
        "connection_state": "string",
        "required_nodes": [
          {
            "name": "node1",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          }
        ]
      },
      "igroups": [
        {
          "comment": "string",
          "igroups": [
            null
          ],
          "name": "igroup1",
          "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
        }
      ],
      "initiators": [
        {
          "comment": "string",
          "connectivity_tracking": {
            "connection_state": "string"
          },
          "igroup": {
            "name": "igroup1",
            "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
          },
          "name": "iqn.1998-01.com.corp.iscsi:name1",
          "proximity": {
            "peer_svms": [
              {
                "name": "peer1",
                "uuid": "4204cf77-4c82-9bdb-5644-b5a841c097a9"
              }
            ]
          }
        }
      ],
      "lun_maps": [
        {
          "logical_unit_number": 0,
          "lun": {
            "name": "lun1",
            "node": {
              "name": "node1",
              "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
            },
            "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
          }
        }
      ],
      "name": "igroup1",
      "os_type": "string",
      "parent_igroups": [
        {
          "comment": "string",
          "name": "igroup1",
          "parent_igroups": [
            null
          ],
          "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
        }
      ],
      "portset": {
        "name": "portset1",
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      },
      "protocol": "string",
      "replication": {
        "error": {
          "igroup": {
            "name": "igroup1",
            "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
          }
        },
        "peer_svm": {
          "name": "peer1",
          "uuid": "4204cf77-4c82-9bdb-5644-b5a841c097a9"
        },
        "state": "string"
      },
      "svm": {
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "target": {
        "firmware_revision": "9111",
        "product_id": "LUN C-Mode",
        "vendor_id": "NETAPP"
      },
      "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 2621462
| The supplied SVM does not exist.

| 2621706
| The specified `svm.uuid` and `svm.name` do not refer to the same SVM.

| 2621707
| No SVM was specified. Either `svm.name` or `svm.uuid` must be supplied.

| 5373958
| An invalid initiator group name was supplied.

| 5373966
| An initiator group cannot be created in an SVM that is configured for NVMe.

| 5373969
| A supplied initiator name looks like an iSCSI IQN initiator, but the portions after the prefix are missing.

| 5373971
| A supplied initiator name looks like an iSCSI IQN initiator, but the date portion is invalid.

| 5373972
| A supplied initiator name looks like an iSCSI IQN initiator, but the naming authority portion is invalid.

| 5373977
| A supplied initiator name looks like an iSCSI EUI initiator, but the length is invalid.

| 5373978
| A supplied initiator name looks like an iSCSI EUI initiator, but the format is invalid.

| 5373982
| An invalid WWN was specified. The length is incorrect.

| 5373983
| An invalid WWN was specified. The format is incorrect.

| 5373992
| A supplied initiator name was too long to be valid.

| 5373993
| A supplied initiator name did not match any valid format.

| 5374023
| An initiator group with the same name already exists.

| 5374027
| An attempt was made to bind a portset with no member network interfaces to the initiator group.

| 5374028
| An attempt was made to bind a portset with an incompatible protocol to the initiator group.

| 5374038
| An invalid Fibre Channel WWPN was supplied.

| 5374039
| An invalid iSCSI initiator name was supplied.

| 5374040
| Initiators and child initiator groups were both supplied, but only one option is allowed.

| 5374732
| An initiator is already in another initiator group with a conflicting operating system type.

| 5374735
| An attempt was made to add a child igroup that would exceed the maximum allowable depth.

| 5374737
| A supplied child initiator group already exists in another initiator group's hierarchy.

| 5374739
| A supplied child initiator group has an operating system type that differs from the parent initiator group.

| 5374740
| A supplied child initiator group has an protocol that differs from the parent initiator group.

| 5374741
| A supplied child initiator group is already owned by a different child in the initiator group's hierarchy.

| 5374742
| A supplied child initiator group contains an initiator that is already owned by another initiator group in the hierarchy.

| 5374745
| Initiator group cannot be added as a child to itself.

| 5374746
| The cluster is currently running in a mixed version and nested initiator groups cannot be created until the effective cluster version reaches 9.9.1.

| 5374747
| The cluster is currently running in a mixed version and initiator group comments cannot be created until the effective cluster version reaches 9.9.1.

| 5374758
| An error was reported by the peer cluster while creating a replicated initiator group. The specific error will be included as a nested error.

| 5374878
| The supplied child initiator group does not exist.

| 5374911
| The supplied portset does not exist.

| 5374917
| Duplicated initiators have conflicting property values.

| 5375055
| The `local_svm` property of an initiator proximity was not specified.

| 5375056
| An SVM peering relationship that does not have the initiator group's SVM as the local SVM was specified.

| 5375258
| The igroup is already replicated to a different peer SVM.

| 5375261
| Setting initiator proximity is not supported for the SVM type.

| 5376057
| Setting initiator proximity is not supported for the ONTAP version.

| 5376059
| Setting initiator proximity to a peer that is either the destination of an SVM DR relationship or in a Metrocluster configuration is not supported.

| 5376253
| Initiator group replication requires an effective cluster version of 9.15.1.

| 5376255
| Initiator group replication requires the peer cluster to have an effective cluster version of 9.15.1.

| 5376488
| An NVMe over Fabrics subsystem already exists with the requested name.

| 6620376
| SVM peering information is unavailable.

| 6620384
| The supplied SVMs are not peered.

| 26345672
| The specified SVM peering relationship was not found.

| 26345673
| An SVM peering relationship between the initiator group's SVM and specified peer SVM was not found.

| 26345675
| An SVM peering relationship UUID and name were specified and they do not refer to the same SVM peering relationship.

| 26345680
| Supplied SVM peer is on the local cluster. The operation requires a peer on a remote cluster.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#summary]
[.api-collapsible-fifth-title]
summary

A user friendly message describing the connection state of the initiator group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|===


[#alerts]
[.api-collapsible-fifth-title]
alerts
[#required_nodes]
[.api-collapsible-fifth-title]
required_nodes

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#connectivity_tracking]
[.api-collapsible-fifth-title]
connectivity_tracking

An overview of the connections to ONTAP by the initiators in this group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|alerts
|array[link:#alerts[alerts]]
a|

|connection_state
|string
a|Connection state.


|required_nodes
|array[link:#required_nodes[required_nodes]]
a|Nodes to which the initiators in this group should be connected to ensure reliable service. This is the collection of any node hosting a LUN mapped to this igroup as well as the HA partners of those nodes.


|===


[#igroup_child]
[.api-collapsible-fifth-title]
igroup_child

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment available for use by the administrator.


|igroups
|array[link:#igroup_child[igroup_child]]
a|Further nested initiator groups.


|name
|string
a|The name of the initiator group.


|uuid
|string
a|The unique identifier of the initiator group.


|===


[#connectivity_tracking]
[.api-collapsible-fifth-title]
connectivity_tracking

A link to the initiator with connectivity information relevant to its membership of this initiator group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#self]
[.api-collapsible-fifth-title]
self

A link to the initiator where mutations can be made. If the initiator is inherited from a nested initiator group, the link refers to the initiator in the nested initiator group. In this case, mutations of the initiator will be applied to all initiator groups referencing the same nested initiator group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#connectivity_tracking]
[.api-collapsible-fifth-title]
connectivity_tracking

Overview of the initiator's connections to ONTAP.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|connection_state
|string
a|Connection state.


|===


[#igroup]
[.api-collapsible-fifth-title]
igroup

The initiator group that directly owns the initiator, which is where modification of the initiator is supported. This property will only be populated when the initiator is a member of a nested initiator group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the initiator group.


|uuid
|string
a|The unique identifier of the initiator group.


|===


[#peer_svms]
[.api-collapsible-fifth-title]
peer_svms

A reference to an SVM peer relationship.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The local name of the peer SVM. This name is unique among all local and peer SVMs.


|uuid
|string
a|The unique identifier of the SVM peer relationship. This is the UUID of the relationship, not the UUID of the peer SVM itself.


|===


[#proximity]
[.api-collapsible-fifth-title]
proximity

Properties that define to what SVMs the initiator is proximal. This information is used to properly report active optimized and active non-optimized network paths via ALUA. If no configuration has been specified for an initiator, the sub-object will not be present in GET.

These properties can be set via initiator group POST and PATCH and apply to all instances of the initiator in all initiator groups in the SVM and its peers. The `proximity` sub-object for an initiator is set in POST and PATCH in its entirety and replaces any previously set proximity for the initiator within the SVM for the initiator within the SVM. The `local_svm` property must always be set to `true` or `false` when setting the `proximity` property. To clear any previously set proximity, POST or PATCH the `proximity` object to `null`.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|local_svm
|boolean
a|A boolean that indicates if the initiator is proximal to the SVM of the containing initiator group. This is required for any POST or PATCH that includes the `proximity` sub-object.


|peer_svms
|array[link:#peer_svms[peer_svms]]
a|An array of remote peer SVMs to which the initiator is proximal.


|===


[#initiators]
[.api-collapsible-fifth-title]
initiators

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|comment
|string
a|A comment available for use by the administrator. Valid in POST and PATCH.


|connectivity_tracking
|link:#connectivity_tracking[connectivity_tracking]
a|Overview of the initiator's connections to ONTAP.

* readOnly: 1
* Introduced in: 9.11


|igroup
|link:#igroup[igroup]
a|The initiator group that directly owns the initiator, which is where modification of the initiator is supported. This property will only be populated when the initiator is a member of a nested initiator group.


|name
|string
a|The FC WWPN, iSCSI IQN, or iSCSI EUI that identifies the host initiator. Valid in POST only and not allowed when the `records` property is used.

An FC WWPN consists of 16 hexadecimal digits grouped as 8 pairs separated by colons. The format for an iSCSI IQN is _iqn.yyyy-mm.reverse_domain_name:any_. The iSCSI EUI format consists of the _eui._ prefix followed by 16 hexadecimal characters.


|proximity
|link:#proximity[proximity]
a|Properties that define to what SVMs the initiator is proximal. This information is used to properly report active optimized and active non-optimized network paths via ALUA. If no configuration has been specified for an initiator, the sub-object will not be present in GET.

These properties can be set via initiator group POST and PATCH and apply to all instances of the initiator in all initiator groups in the SVM and its peers. The `proximity` sub-object for an initiator is set in POST and PATCH in its entirety and replaces any previously set proximity for the initiator within the SVM for the initiator within the SVM. The `local_svm` property must always be set to `true` or `false` when setting the `proximity` property. To clear any previously set proximity, POST or PATCH the `proximity` object to `null`.


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#lun]
[.api-collapsible-fifth-title]
lun

The LUN to which the initiator group is mapped.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the LUN.


|node
|link:#node[node]
a|

|uuid
|string
a|The unique identifier of the LUN.


|===


[#lun_maps]
[.api-collapsible-fifth-title]
lun_maps

A LUN map with which the initiator group is associated.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|logical_unit_number
|integer
a|The logical unit number assigned to the LUN for initiators in the initiator group.


|lun
|link:#lun[lun]
a|The LUN to which the initiator group is mapped.


|===


[#igroup_parent]
[.api-collapsible-fifth-title]
igroup_parent

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment available for use by the administrator.


|name
|string
a|The name of the initiator group.


|parent_igroups
|array[link:#igroup_parent[igroup_parent]]
a|The initiator groups that contain this initiator group as a member.


|uuid
|string
a|The unique identifier of the initiator group.


|===


[#portset]
[.api-collapsible-fifth-title]
portset

The portset to which the initiator group is bound. Binding the initiator group to a portset restricts the initiators of the group to accessing mapped LUNs only through network interfaces in the portset.

In a nested initiator group hierarchy, only a portset bound to the initiator group at the same level at which it is mapped, applies; portsets bound to parent or child initiator groups are ignored.

Optional in POST and PATCH. To unbind a portset from the initiator group, PATCH the `portset` object to  `null`, or PATCH `portset.name` to an empty string ("").


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the portset.


|uuid
|string
a|The unique identifier of the portset.


|===


[#igroup]
[.api-collapsible-fifth-title]
igroup

[cols=3*,options=header]
|===
|Name
|Type
|Description

|local_svm
|boolean
a|Indicates whether the reported igroup is on the local SVM or the peer SVM. When deleting a replicated igroup, the local copy is deleted first and then the peer copy is deleted. If the error is encountered between these two operations and only the peer igroup remains, the peer igroup is reported and the problem might need to be corrected on the peer cluster.


|name
|string
a|The name of the initiator group.


|uuid
|string
a|The unique identifier of the initiator group.


|===


[#summary]
[.api-collapsible-fifth-title]
summary

A user friendly message describing the error.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|===


[#error]
[.api-collapsible-fifth-title]
error

Information about asynchronous errors encountered while replicating this igroup. Igroups within a peering relationship are replicated in the same stream, so the error reported here might be related to this igroup or a prior replicated igroup that is now blocking the replication of this igroup. Both the error information and the igroup encountering the error are reported. If the error is configuration related, it can be corrected on the referenced igroup. The replication is retried using exponential backoff up to a maximum of one retry every 5 minutes. Every operation on the same stream triggers an immediate retry and restarts the exponential backoff starting with a 1 second delay. If the error is system related, the retries should correct the error when the system enters a healthy state.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|igroup
|link:#igroup[igroup]
a|

|===


[#peer_svm]
[.api-collapsible-fifth-title]
peer_svm

The peered SVM to which the initiator group should be replicated. Optional in POST and PATCH. To clear any previously set replication peer, PATCH the `replication.peer_svm` object to `null`.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The local name of the peer SVM. This name is unique among all local and peer SVMs.


|uuid
|string
a|The unique identifier of the SVM peer relationship. This is the UUID of the relationship, not the UUID of the peer SVM itself.


|===


[#replication]
[.api-collapsible-fifth-title]
replication

Properties related to initiator group replication.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|Information about asynchronous errors encountered while replicating this igroup. Igroups within a peering relationship are replicated in the same stream, so the error reported here might be related to this igroup or a prior replicated igroup that is now blocking the replication of this igroup. Both the error information and the igroup encountering the error are reported. If the error is configuration related, it can be corrected on the referenced igroup. The replication is retried using exponential backoff up to a maximum of one retry every 5 minutes. Every operation on the same stream triggers an immediate retry and restarts the exponential backoff starting with a 1 second delay. If the error is system related, the retries should correct the error when the system enters a healthy state.


|peer_svm
|link:#peer_svm[peer_svm]
a|The peered SVM to which the initiator group should be replicated. Optional in POST and PATCH. To clear any previously set replication peer, PATCH the `replication.peer_svm` object to `null`.


|state
|string
a|The state of the replication queue associated with this igroup. If this igroup is not in the replication queue, the state is reported as _ok_. If this igroup is in the replication queue, but no errors have been encountered, the state is reported as _replicating_. If this igroup is in the replication queue and the queue is blocked by an error, the state is reported as _error_. When in the _error_ state, additional context is provided by the `replication.error` property.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#target]
[.api-collapsible-fifth-title]
target

Properties of the SCSI target to which the initiator group provides access.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|firmware_revision
|string
a|The firmware revision of the SCSI target specific to the OS type of the initiator group.


|product_id
|string
a|The product ID of the SCSI target.


|vendor_id
|string
a|The vendor ID of the SCSI target.


|===


[#igroup]
[.api-collapsible-fifth-title]
igroup

An initiator group (igroup) is a collection of Fibre Channel (FC) world wide port names (WWPNs), and/or iSCSI Qualified Names (IQNs), and/or iSCSI EUIs (Extended Unique Identifiers) that identify host endpoints.

Initiator groups are used to control which hosts can access specific LUNs. To grant access to a LUN from one or more hosts, create an initiator group containing the host initiator names, then create a LUN map that associates the initiator group with the LUN.

An initiator group may contain either initiators or other initiator groups, but not both simultaneously. When a parent initiator group is mapped, it inherits all of the initiators of any initiator groups nested below it. If any nested initiator group is modified to contain different initiators, the parent initiator groups inherit the change. A parent can have many nested initiator groups and an initiator group can be nested under multiple parents. Initiators can only be added or removed from the initiator group that directly contains them. The maximum supported depth of nesting is three layers.

Best practice when using nested initiator groups is to match host hierarchies. A single initiator group should correspond to a single host. If a LUN needs to be mapped to multiple hosts, the initiator groups representing those hosts should be aggregated into a parent initiator group and the LUN should be mapped to that initiator group. For multi-ported hosts, initiators have a comment property where the port corresponding to the initiator can be documented.

An initiator can appear in multiple initiator groups. An initiator group can be mapped to multiple LUNs. A specific initiator can be mapped to a specific LUN only once. With the introduction of nestable initiator groups, best practice is to use the hierarchy such that an initiator is only a direct member of a single initiator group, and that initiator group can then be referenced by other initiator groups.

All initiators or nested initiator groups in an initiator group must be from the same operating system. The initiator group's operating system is specified when the initiator group is created.

When an initiator group is created, the `protocol` property is used to restrict member initiators to Fibre Channel (_fcp_), iSCSI (_iscsi_), or both (_mixed_). Initiator groups within a nested hierarchy may not have conflicting protocols.

Zero or more initiators or nested initiator groups can be supplied when the initiator group is created. After creation, initiators can be added or removed from the initiator group using the `/protocols/san/igroups/{igroup.uuid}/initiators` endpoint. Initiator groups containing other initiator groups report the aggregated list of initiators from all nested initiator groups, but modifications of the initiator list must be performed on the initiator group that directly contains the initiators. See link:post-protocols-san-igroups-initiators(#-san-igroup-initiator-create)anddelete-protocols-san-igroups-initiators-.html<</SAN/igroup_initiator_create,POST /protocols/san/igroups/{igroup.uuid}/initiators>> and [DELETE /protocols/san/igroups/{igroup.uuid}/initiators/\{name}]  for more details.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment available for use by the administrator. Valid in POST and PATCH.


|connectivity_tracking
|link:#connectivity_tracking[connectivity_tracking]
a|An overview of the connections to ONTAP by the initiators in this group.

* readOnly: 1
* Introduced in: 9.11


|delete_on_unmap
|boolean
a|An option that causes the initiator group to be deleted when the last LUN map associated with it is deleted. Optional in POST and PATCH. This property defaults to _false_ when the initiator group is created.


|igroups
|array[link:#igroup_child[igroup_child]]
a|The existing initiator groups that are members of the group. Optional in POST.

This property is mutually exclusive with the _initiators_ property during POST.

This array contains only the direct children of the initiator group. If the member initiator groups have further nested initiator groups, those are reported in the `igroups` property of the child initiator group.

Zero or more nested initiator groups can be supplied when the initiator group is created. The initiator group will act as if it contains the aggregation of all initiators in any nested initiator groups.

After creation, nested initiator groups can be added or removed from the initiator group using the `/protocols/san/igroups/{igroup.uuid}/igroups` endpoint. See link:post-protocols-san-igroups-igroups(#-san-igroup-nested-create)anddelete-protocols-san-igroups-igroups-.html<</SAN/igroup_nested_create,POST /protocols/san/igroups/{igroup.uuid}/igroups>> and [DELETE /protocols/san/igroups/{igroup.uuid}/igroups/\{uuid}]  for more details.


|initiators
|array[link:#initiators[initiators]]
a|The initiators that are members of the group or any group nested below this group. Optional in POST.

This property is mutually exclusive with the _igroups_ property during POST.

During GET, this array contains initiators that are members of this group or any nested initiator groups below this group. When initiators of nested groups are returned, they include links to the initiator group that directly contains the initiator.

Zero or more initiators can be supplied when the initiator group is created. After creation, initiators can be added or removed from the initiator group using the `/protocols/san/igroups/{igroup.uuid}/initiators` endpoint. See link:post-protocols-san-igroups-initiators(#-san-igroup-initiator-create)anddelete-protocols-san-igroups-initiators-.html<</SAN/igroup_initiator_create,POST /protocols/san/igroups/{igroup.uuid}/initiators>> and [DELETE /protocols/san/igroups/{igroup.uuid}/initiators/\{name}]  for more details.


|lun_maps
|array[link:#lun_maps[lun_maps]]
a|All LUN maps with which the initiator is associated.

If the requested igroup is part of a remote, non-local, MetroCluster SVM, the LUN maps are not retrieved.

There is an added computational cost to retrieving property values for `lun_maps`. They are not populated for a GET request unless explicitly requested using the `fields` query parameter. See link:getting_started_with_the_ontap_rest_api.html#Requesting_specific_fields[Requesting specific fields] to learn more.


|name
|string
a|The name of the initiator group. Required in POST; optional in PATCH.


|os_type
|string
a|The host operating system of the initiator group. All initiators in the group should be hosts of the same operating system. Required in POST; optional in PATCH.


|parent_igroups
|array[link:#igroup_parent[igroup_parent]]
a|The initiator groups that contain this initiator group as a member.


|portset
|link:#portset[portset]
a|The portset to which the initiator group is bound. Binding the initiator group to a portset restricts the initiators of the group to accessing mapped LUNs only through network interfaces in the portset.

In a nested initiator group hierarchy, only a portset bound to the initiator group at the same level at which it is mapped, applies; portsets bound to parent or child initiator groups are ignored.

Optional in POST and PATCH. To unbind a portset from the initiator group, PATCH the `portset` object to  `null`, or PATCH `portset.name` to an empty string ("").


|protocol
|string
a|The protocols supported by the initiator group. This restricts the type of initiators that can be added to the initiator group. Optional in POST; if not supplied, this defaults to _mixed_.

The protocol of an initiator group cannot be changed after creation of the group.


|replication
|link:#replication[replication]
a|Properties related to initiator group replication.


|supports_igroups
|boolean
a|An initiator group may contain either initiators or other initiator groups, but not both simultaneously. This property is _true_ when initiator groups can be added to this initiator group. The `initiators.name` property cannot be used to determine this via a query because it reports initiators inherited from nested igroups.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|target
|link:#target[target]
a|Properties of the SCSI target to which the initiator group provides access.


|uuid
|string
a|The unique identifier of the initiator group.


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
