---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-snapmirror-relationships-transfers.html'
summary: 'Start a SnapMirror transfer operation'
---

= Start a SnapMirror transfer operation

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/snapmirror/relationships/{relationship.uuid}/transfers`#

*Introduced In:* 9.6

Starts a SnapMirror transfer operation. This API initiates a restore operation if the SnapMirror relationship is of type "restore". Otherwise, it initiates a SnapMirror "initialize" operation or "update" operation based on the current SnapMirror state.

== Default property values

* `storage_efficiency_enabled` - _true_

== Related ONTAP commands

* `snapmirror update`
* `snapmirror initialize`
* `snapmirror restore`

== Examples

The following examples show how to perform SnapMirror "initialize", "update", and "restore" operations.

Perform SnapMirror initialize or update

----
 POST "/api/snapmirror/relationships/e4e7e130-0279-11e9-b566-0050568e9909/transfers" '{}'
----

Perform SnapMirror initialize, update or restore with throttle value set

----
 POST "/api/snapmirror/relationships/e4e7e130-0279-11e9-b566-0050568e9909/transfers" '{"throttle":"100"}'
----

Perform SnapMirror restore transfer of a file

----
 POST "/api/snapmirror/relationships/c8c62a90-0fef-11e9-b09e-0050568e7067/transfers" '{"source_snapshot": "src", "files":[{"source_path": "/a1.txt.0", "destination_path": "/a1-renamed.txt.0"}]}'
----

Performing a SnapMirror initialize or update using a particular snapshot.

----
 POST "/api/snapmirror/relationships/e4e7e130-0279-11e9-b566-0050568e9909/transfers" '{"source_snapshot":"snap1"}'
----

== Learn more

* link:snapmirror_relationships_relationship.uuid_transfers_endpoint_overview.html[DOC /snapmirror/relationships/{relationship.uuid}/transfers]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|relationship.uuid
|string
|path
|True
a|SnapMirror relationship UUID


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|bytes_transferred
|integer
a|Bytes transferred


|checkpoint_size
|integer
a|Amount of data transferred in bytes as recorded in the restart checkpoint.


|end_time
|string
a|End time of the transfer.


|error_info
|link:#error_info[error_info]
a|Error information for the transfer.


|files
|array[link:#files[files]]
a|This is supported for transfer of restore relationship only. This specifies the list of files or LUNs to be restored. Can contain up to eight files or LUNs.


|last_updated_time
|string
a|Last updated time of the bytes transferred in an active transfer.


|network_compression_ratio
|string
a|Specifies the compression ratio achieved for the data sent over the wire with network compression enabled. This property is only valid for active transfers.


|on_demand_attrs
|string
a|Specifies whether or not an on-demand restore is being carried out. This is only supported for the transfer of restore relationships for entire volumes from the object store. A value for read_write_with_user_data_pull should be provided to start an on-demand restore. A file restore from the object store does not support this option.


|options
|array[link:#options[options]]
a|Options for snapmirror transfer.


|relationship
|link:#relationship[relationship]
a|

|snapshot
|string
a|Name of snapshot being transferred.


|source_snapshot
|string
a|Specifies the snapshot on the source to be transferred to the destination.


|storage_efficiency_enabled
|boolean
a|This is supported for transfer of restore relationship only. Set this property to "false" to turn off storage efficiency for data transferred over the wire and written to the destination.


|throttle
|integer
a|Throttle, in KBs per second. This "throttle" overrides the "throttle" set on the SnapMirror relationship or SnapMirror relationship's policy. If neither of these are set, defaults to 0, which is interpreted as unlimited.


|total_duration
|string
a|Elapsed transfer time.


|uuid
|string
a|Unique identifier of the SnapMirror transfer.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "bytes_transferred": 0,
  "checkpoint_size": 0,
  "end_time": "2020-12-02 18:36:19 -0800",
  "error_info": {
    "code": 6620046,
    "message": "Transfer aborted"
  },
  "files": [
    {
      "destination_path": "/dirb/file2",
      "source_path": "/dira/file1"
    }
  ],
  "last_updated_time": "2023-09-15 16:58:39 -0700",
  "network_compression_ratio": 61,
  "on_demand_attrs": "read_write_with_user_data_pull",
  "options": [
    {}
  ],
  "relationship": {
    "destination": {
      "cluster": {
        "name": "cluster1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "consistency_group_volumes": [
        {
          "name": "volume1",
          "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
        }
      ],
      "ipspace": "Default",
      "luns": {
        "name": "/vol/volume1/lun1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "path": "svm1:volume1",
      "svm": {
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    },
    "uuid": "d2d7ceea-ab52-11e8-855e-00505682a4c7"
  },
  "snapshot": "string",
  "source_snapshot": "string",
  "throttle": 0,
  "total_duration": "PT28M41S",
  "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
}
====

== Response

```
Status: 201, Created
```

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 13303845
| Restore operation failed

| 13303812
| Initialize operation failed

| 13303844
| Update operation failed

| 13303846
| Empty source path file list

| 13303847
| Invalid property

| 13304040
| Throttle not supported for update of Synchronous SnapMirror relationships

| 6620237
| SnapMirror relationship database write failed

| 6620238
| SnapMirror relationship database read failed
|===

| 13304134    | The overwrite property specified does not match the value specified in the previous request. ||
| 6619720     | Relationship information has been updated and is being propagated. Wait a few minutes and try the operation again. |
| 13303816    | Could not retrieve the state or status values for the relationship. Wait a few minutes and try the operation again. |
| 13304159    | Could not retrieve the state or status values for the relationship. Wait a few minutes and try the operation again. If the error persists, address the error condition shown. |


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#error_info]
[.api-collapsible-fifth-title]
error_info

Error information for the transfer.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|integer
a|Error code


|message
|string
a|Error message


|===


[#files]
[.api-collapsible-fifth-title]
files

Specifies a file or LUN consisting of a source_path and an optional destination_path. If not specified, the destination_path is the same as the source_path. File restore is not supported if the source_path or destination_path contains commas in its directory or file name.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|destination_path
|string
a|

|source_path
|string
a|

|===


[#options]
[.api-collapsible-fifth-title]
options
[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#consistency_group_volumes]
[.api-collapsible-fifth-title]
consistency_group_volumes

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|uuid
|string
a|Unique identifier of the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* x-ntap-createOnly: true
* Introduced in: 9.8
* x-nullable: true


|===


[#luns]
[.api-collapsible-fifth-title]
luns

Optional property for a SnapMirror endpoint. Specifies the list of source LUNs and optionally list of destination LUNs during SnapMirror Consistency Group LUN restore operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of a LUN.
A LUN is located within a volume. Optionally, it can be located within a qtree in a volume.

LUN names are paths of the form "/vol/<volume>[/<qtree>]/<namespace>" where the qtree name is optional.


|uuid
|string
a|The unique identifier of the LUN.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#snapmirror_endpoint]
[.api-collapsible-fifth-title]
snapmirror_endpoint

Endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to create the destination SVM endpoint or to establish an SVM DR relationship must have the property "cluster" populated with the remote cluster details. A POST request to create the destination FlexVol volume, FlexGroup volume, Consistency Group, ONTAP S3 bucket and NON-ONTAP object-store endpoints can optionally specify the "cluster" property when the source SVM and the destination SVM are peered. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster[cluster]
a|

|consistency_group_volumes
|array[link:#consistency_group_volumes[consistency_group_volumes]]
a|This property specifies the list of FlexVol volumes or LUNs of a Consistency Group. Optional on the ASA r2 platform. Mandatory for all other platforms.


|ipspace
|string
a|Optional property to specify the IPSpace of the SVM.


|luns
|link:#luns[luns]
a|Optional property for a SnapMirror endpoint. Specifies the list of source LUNs and optionally list of destination LUNs during SnapMirror Consistency Group LUN restore operation.


|path
|string
a|ONTAP FlexVol/FlexGroup - svm1:volume1
ONTAP SVM               - svm1:
ONTAP Consistency Group - svm1:/cg/cg_name
ONTAP S3                - svm1:/bucket/bucket1
NON-ONTAP               - objstore1:/objstore

* example: svm1:volume1
* Introduced in: 9.6
* x-nullable: true


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#relationship]
[.api-collapsible-fifth-title]
relationship

[cols=3*,options=header]
|===
|Name
|Type
|Description

|destination
|link:#snapmirror_endpoint[snapmirror_endpoint]
a|Endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to create the destination SVM endpoint or to establish an SVM DR relationship must have the property "cluster" populated with the remote cluster details. A POST request to create the destination FlexVol volume, FlexGroup volume, Consistency Group, ONTAP S3 bucket and NON-ONTAP object-store endpoints can optionally specify the "cluster" property when the source SVM and the destination SVM are peered. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.

* Introduced in: 9.6


|restore
|boolean
a|Is the relationship for restore?


|uuid
|string
a|Unique identifier of the SnapMirror relationship.


|===


[#snapmirror_transfer]
[.api-collapsible-fifth-title]
snapmirror_transfer

SnapMirror transfer information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|bytes_transferred
|integer
a|Bytes transferred


|checkpoint_size
|integer
a|Amount of data transferred in bytes as recorded in the restart checkpoint.


|end_time
|string
a|End time of the transfer.


|error_info
|link:#error_info[error_info]
a|Error information for the transfer.


|files
|array[link:#files[files]]
a|This is supported for transfer of restore relationship only. This specifies the list of files or LUNs to be restored. Can contain up to eight files or LUNs.


|last_updated_time
|string
a|Last updated time of the bytes transferred in an active transfer.


|network_compression_ratio
|string
a|Specifies the compression ratio achieved for the data sent over the wire with network compression enabled. This property is only valid for active transfers.


|on_demand_attrs
|string
a|Specifies whether or not an on-demand restore is being carried out. This is only supported for the transfer of restore relationships for entire volumes from the object store. A value for read_write_with_user_data_pull should be provided to start an on-demand restore. A file restore from the object store does not support this option.


|options
|array[link:#options[options]]
a|Options for snapmirror transfer.


|relationship
|link:#relationship[relationship]
a|

|snapshot
|string
a|Name of snapshot being transferred.


|source_snapshot
|string
a|Specifies the snapshot on the source to be transferred to the destination.


|storage_efficiency_enabled
|boolean
a|This is supported for transfer of restore relationship only. Set this property to "false" to turn off storage efficiency for data transferred over the wire and written to the destination.


|throttle
|integer
a|Throttle, in KBs per second. This "throttle" overrides the "throttle" set on the SnapMirror relationship or SnapMirror relationship's policy. If neither of these are set, defaults to 0, which is interpreted as unlimited.


|total_duration
|string
a|Elapsed transfer time.


|uuid
|string
a|Unique identifier of the SnapMirror transfer.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
