---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-protocols-active-directory.html'
summary: 'Create an Active Directory account for an SVM'
---

= Create an Active Directory account for an SVM

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/protocols/active-directory`#

*Introduced In:* 9.12

Creates an Active Directory account for a given SVM.

== Related ONTAP commands

* `vserver active-directory create`

== Important notes

* Active Directory account creation is asynchronous. Response contains Task UUID and Link that can be queried to get the status.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|discovered_servers
|array[link:#discovered_servers[discovered_servers]]
a|Specifies the discovered servers records.


|force_account_overwrite
|boolean
a|If set to true and a machine account exists with the same name as specified in "name" in Active Directory, it will be overwritten and reused.


|fqdn
|string
a|Fully qualified domain name.


|name
|string
a|Active Directory (AD) account NetBIOS name.


|organizational_unit
|string
a|Organizational unit under which the Active Directory account will be created.


|password
|string
a|Administrator password required for Active Directory account creation, modification and deletion.


|preferred_dcs
|array[link:#preferred_dcs[preferred_dcs]]
a|Specifies the preferred domain controller (DC) records.


|security
|link:#active_directory_security[active_directory_security]
a|

|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|username
|string
a|Administrator username required for Active Directory account creation, modification and deletion.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "discovered_servers": [
    {
      "domain": "server1.com",
      "node": {
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "preference": "preferred",
      "server": {
        "ip": "7.4.3.1",
        "name": "scspk0659102001",
        "type": "kerberos"
      },
      "state": "ok"
    }
  ],
  "force_account_overwrite": "",
  "fqdn": "server1.com",
  "name": "account1",
  "organizational_unit": "CN=Test",
  "password": "testpwd",
  "preferred_dcs": [
    {
      "fqdn": "test.com",
      "server_ip": "4.4.4.4"
    }
  ],
  "security": {
    "advertised_kdc_encryptions": [
      "string"
    ]
  },
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "username": "admin"
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|discovered_servers
|array[link:#discovered_servers[discovered_servers]]
a|Specifies the discovered servers records.


|force_account_overwrite
|boolean
a|If set to true and a machine account exists with the same name as specified in "name" in Active Directory, it will be overwritten and reused.


|fqdn
|string
a|Fully qualified domain name.


|name
|string
a|Active Directory (AD) account NetBIOS name.


|organizational_unit
|string
a|Organizational unit under which the Active Directory account will be created.


|password
|string
a|Administrator password required for Active Directory account creation, modification and deletion.


|preferred_dcs
|array[link:#preferred_dcs[preferred_dcs]]
a|Specifies the preferred domain controller (DC) records.


|security
|link:#active_directory_security[active_directory_security]
a|

|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|username
|string
a|Administrator username required for Active Directory account creation, modification and deletion.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "discovered_servers": [
    {
      "domain": "server1.com",
      "node": {
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "preference": "preferred",
      "server": {
        "ip": "7.4.3.1",
        "name": "scspk0659102001",
        "type": "kerberos"
      },
      "state": "ok"
    }
  ],
  "force_account_overwrite": "",
  "fqdn": "server1.com",
  "name": "account1",
  "organizational_unit": "CN=Test",
  "password": "testpwd",
  "preferred_dcs": [
    {
      "fqdn": "test.com",
      "server_ip": "4.4.4.4"
    }
  ],
  "security": {
    "advertised_kdc_encryptions": [
      "string"
    ]
  },
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "username": "admin"
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 655562
| The NetBIOS name cannot be longer than 15 characters.

| 655915
| A CIFS server for this SVM already exists. Having both a CIFS server and an Active Directory account for the same SVM is not supported. Use the \"vserver cifs delete\" command to delete the existing CIFS server and try the command again.

| 656464
| Failed to create the Active Directory machine account. Reason: Invalid Credentials.

| 656465
| Failed to create the Active Directory machine account. Reason: An account with this name already exists.

| 656466
| Failed to create the Active Directory machine account. Reason: Unable to connect to any domain controllers.

| 656467
| Failed to create the Active Directory machine account. Reason: Organizational-Unit not found.

| 656490
| Unable to create the Active Directory account. The Active Directory account name is already used by another SVM.

| 656491
| Failed to create the Active Directory machine account. Reason: This operation is supported only on data SVMs.

| 656494
| The Active Directory was created but was not fully configured.

| 656495
| Failed to update Active Directory security settings for SVM.

| 656496
| Failed to update Active Directory security settings for SVM. Reason: KDC has no support for encryption type.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#active_directory_discovered_server_reference]
[.api-collapsible-fifth-title]
active_directory_discovered_server_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|string
a|The IP address of the server that was discovered.


|name
|string
a|Server Name


|type
|string
a|The type of the server that was discovered.


|===


[#discovered_servers]
[.api-collapsible-fifth-title]
discovered_servers

[cols=3*,options=header]
|===
|Name
|Type
|Description

|domain
|string
a|The Active Directory domain that the discovered server is a member of.


|node
|link:#node[node]
a|

|preference
|string
a|The preference level of the server that was discovered.


|server
|link:#active_directory_discovered_server_reference[active_directory_discovered_server_reference]
a|

|state
|string
a|The status of the connection to the server that was discovered.


|===


[#preferred_dcs]
[.api-collapsible-fifth-title]
preferred_dcs

[cols=3*,options=header]
|===
|Name
|Type
|Description

|fqdn
|string
a|Fully Qualified Domain Name.


|server_ip
|string
a|IP address of the preferred DC. The address can be either an IPv4 or an IPv6 address.


|===


[#active_directory_security]
[.api-collapsible-fifth-title]
active_directory_security

[cols=3*,options=header]
|===
|Name
|Type
|Description

|advertised_kdc_encryptions
|array[string]
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#active_directory]
[.api-collapsible-fifth-title]
active_directory

[cols=3*,options=header]
|===
|Name
|Type
|Description

|discovered_servers
|array[link:#discovered_servers[discovered_servers]]
a|Specifies the discovered servers records.


|force_account_overwrite
|boolean
a|If set to true and a machine account exists with the same name as specified in "name" in Active Directory, it will be overwritten and reused.


|fqdn
|string
a|Fully qualified domain name.


|name
|string
a|Active Directory (AD) account NetBIOS name.


|organizational_unit
|string
a|Organizational unit under which the Active Directory account will be created.


|password
|string
a|Administrator password required for Active Directory account creation, modification and deletion.


|preferred_dcs
|array[link:#preferred_dcs[preferred_dcs]]
a|Specifies the preferred domain controller (DC) records.


|security
|link:#active_directory_security[active_directory_security]
a|

|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|username
|string
a|Administrator username required for Active Directory account creation, modification and deletion.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
