---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-network-http-proxy.html'
summary: 'Create an HTTP proxy configuration for an SVM or cluster IPspace'
---

= Create an HTTP proxy configuration for an SVM or cluster IPspace

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/network/http-proxy`#

*Introduced In:* 9.7

Creates an HTTP proxy configuration for an SVM or a Cluster IPspace.
Important notes:

* IPv6 must be enabled if IPv6 family addresses are specified in the "server" field.
* The server and the port combination specified using the "server" and "port" fields is validated during this operation. The validation will fail in the following scenarios:

*** The HTTP proxy service is not configured on the server.

*** The HTTP proxy service is not running on the specified port.

*** The server is unreachable.

== Required properties

* SVM-scoped HTTP proxy

*** `svm.uuid` or `svm.name` - Existing SVM in which to create the HTTP proxy.

* Cluster-scoped HTTP proxy

*** `ipspace.uuid` or `ipspace.name` - Existing Cluster IPspace in which to create the HTTP proxy.

* `server` - HTTP proxy server FQDN or IP address.
* `port` - HTTP proxy server port.

== Optional properties

* `authentication_enabled` - Specifies if authentication is required for the HTTP proxy server.
* `username` - Username used to authenticate with the HTTP proxy server.
* `password` - Password used to authenticate with the HTTP proxy server.

== Related ONTAP commands

* `vserver http-proxy create`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|authentication_enabled
|boolean
a|Specifies whether or not authentication with the HTTP proxy server is enabled.


|ipspace
|link:#ipspace[ipspace]
a|Applies to both SVM and cluster-scoped objects. Either the UUID or name is supplied on input. This is mutually exclusive with SVM during POST and PATCH.


|password
|string
a|Password to authenticate with the HTTP proxy server when authentication_enabled is set to "true".


|port
|integer
a|The port number on which the HTTP proxy service is configured on the
proxy server.


|scope
|string
a|Set to "`svm`" for HTTP proxy owned by an SVM. Otherwise, set to "cluster".


|server
|string
a|Fully qualified domain name (FQDN) or IP address of the HTTP proxy server.


|svm
|link:#svm[svm]
a|This is mutually exclusive with IPspace during POST and PATCH.


|username
|string
a|Username to authenticate with the HTTP proxy server when authentication_enabled is set to "true".


|uuid
|string
a|The UUID that uniquely identifies the HTTP proxy.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "ipspace": {
    "name": "Default",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "password": "string",
  "port": 3128,
  "scope": "string",
  "server": "string",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "username": "string",
  "uuid": "string"
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|Number of HTTP proxy records


|records
|array[link:#network_http_proxy[network_http_proxy]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "num_records": 1,
  "records": [
    {
      "ipspace": {
        "name": "Default",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "password": "string",
      "port": 3128,
      "scope": "string",
      "server": "string",
      "svm": {
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "username": "string",
      "uuid": "string"
    }
  ]
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 26214473
| HTTP proxy configuration is not valid.

| 26214476
| The "IPspace" parameter should not be specified in the SVM context.

| 26214477
| The specified IPspace does not exist.

| 23724130
| Cannot use an IPv6 name server address because there are no IPv6 interfaces.

| 26214481
| Username and password cannot be empty when HTTP proxy authentication is enabled.

| 26214482
| Username and password cannot be specified when HTTP proxy authentication is disabled.

| 26214480
| One of "svm.name", "svm.uuid", "ipspace.name" or "ipspace.uuid" must be specified.

| 2621462
| SVM "vs0" does not exist.

| 262186
| Field "svm.name" cannot be used with field "ipspace.name".
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#ipspace]
[.api-collapsible-fifth-title]
ipspace

Applies to both SVM and cluster-scoped objects. Either the UUID or name is supplied on input. This is mutually exclusive with SVM during POST and PATCH.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|IPspace name


|uuid
|string
a|IPspace UUID


|===


[#svm]
[.api-collapsible-fifth-title]
svm

This is mutually exclusive with IPspace during POST and PATCH.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#network_http_proxy]
[.api-collapsible-fifth-title]
network_http_proxy

[cols=3*,options=header]
|===
|Name
|Type
|Description

|authentication_enabled
|boolean
a|Specifies whether or not authentication with the HTTP proxy server is enabled.


|ipspace
|link:#ipspace[ipspace]
a|Applies to both SVM and cluster-scoped objects. Either the UUID or name is supplied on input. This is mutually exclusive with SVM during POST and PATCH.


|password
|string
a|Password to authenticate with the HTTP proxy server when authentication_enabled is set to "true".


|port
|integer
a|The port number on which the HTTP proxy service is configured on the
proxy server.


|scope
|string
a|Set to "`svm`" for HTTP proxy owned by an SVM. Otherwise, set to "cluster".


|server
|string
a|Fully qualified domain name (FQDN) or IP address of the HTTP proxy server.


|svm
|link:#svm[svm]
a|This is mutually exclusive with IPspace during POST and PATCH.


|username
|string
a|Username to authenticate with the HTTP proxy server when authentication_enabled is set to "true".


|uuid
|string
a|The UUID that uniquely identifies the HTTP proxy.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
