---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-svm-svms.html'
summary: 'Create and provision an SVM'
---

= Create and provision an SVM

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/svm/svms`#

*Introduced In:* 9.6

Creates and provisions an SVM. If no IPspace is provided, then the SVM is created on the `Default` IPspace.

* The number of parallel SVMs that can be created must not be greater than five.
* If a sixth SVM POST request is issued, the following error message is generated: "Maximum allowed SVM jobs exceeded. Wait for the existing SVM jobs to complete and try again."

== Required properties

* `name` - Name of the SVM to be created.

== Recommended optional properties

* `ipspace.name` or `ipspace.uuid` - IPspace of the SVM
* `is_space_reporting_logical` - Logical Space Reporting parameter of the SVM
* `is_space_enforcement_logical` - Logical Space Enforcement parameter of the SVM
* `ip_interfaces` - If provided, the following fields are required:
* `ip_interfaces.name` - Name of the interface
* `ip_interfaces.ip.address` - IP address
* `ip_interfaces.ip.netmask` - Netmask length or IP address
* `ip_interfaces.location.broadcast_domain.uuid` or `ip_interfaces.location.broadcast_domain.name` - Broadcast domain name or UUID belonging to the same IPspace of the SVM.
* `ip_interfaces.location.home_port.name` - Home port name
* `ip_interfaces.location.home_port.uuid` - Home port uuid
* `subnet.uuid` or `subnet.name` - Either name or UUID of the subnet to create.
* `routes` - If provided, the following field is required:

*** `routes.gateway` - Gateway IP address

* `cifs` - If provided, interfaces, routes and DNS must be provided. The following fields are also required:

*** `cifs.name` - Name of the CIFS server to be created for the SVM.

*** `cifs.ad_domain.fqdn` - Fully qualified domain name

*** `cifs.ad_domain.user` - Administrator username

*** `cifs.ad_domain.password` - User password

* `ldap` - If provided, the following fields are required:

*** `ldap.servers` or `ldap.ad_domain` - LDAP server list or Active Directory domain

*** `ldap.bind_dn` - Bind DN

*** `ldap.base_dn` - Base DN

* `nis` - If provided, the following fields are required:

*** `nis.servers` - NIS servers

*** `nis.domain` - NIS domain

* `dns` - If provided, the following fields are required:

*** `dns.servers` - Name servers

*** `dns.domains` - Domains

* `fc_interfaces` - If provided, the following fields are required:

*** `fc_interfaces.name` - Fibre Channel interface name

*** `fc_interfaces.data_protocol` - Fibre Channel interface data protocol

*** `fc_interfaces.location.port.uuid` or `fc_interfaces.location.port.name` and `fc_interfaces.location.port.node.name` - Either port UUID or port name and node name together must be provided.

* `s3` - If provided, the following field should also be specified:

*** `s3.name` - Name of the S3 server. If ``s3.name' is not specified while ``s3.enabled` is set to 'true', the S3 server will be created with the default name '+++<svm.name>+++_S3Server'.+++</svm.name>+++

*** `s3.port` - S3 server listener port.

*** `s3.secure_port` - S3 server listener port for HTTPS.

*** `s3.is_http_enabled` - S3 server connections over HTTP.

*** `s3.is_https_enabled` - S3 server connections over HTTPS.

*** `s3.certificate.name` - S3 server certificate name. This is required if the S3 server runs over HTTPS.

*** `s3.certificate.uuid` - S3 server certificate UUID. This is required if the S3 server runs over HTTPS.

* `auto_enable_analytics` - Auto-enable file system analytics on new volumes created in the SVM.
* `auto_enable_activity_tracking` - Auto-enable volume activity-tracking on new volumes created in the SVM.
* `storage.limit` - Maximum storage permitted on a single SVM.
* `storage.limit_threshold_alert` - At what percentage of storage capacity, alert message needs to be sent.

== Default property values

If not specified in POST, the following default property values are assigned:

* `language` - _C.UTF-8_
* `ipspace.name` - _Default_
* `snapshot_policy.name` - _Default_
* `subtype` - _Default_ ( _sync-source_ if MetroCluster configuration )
* `anti_ransomware_default_volume_state` - _disabled_
* `qos_adaptive_policy_group_template` - _extreme_ ( if using a platform with disaggregated storage and neither qos_policy_group_template nor qos_adaptive_policy_group_template are provided)

== Related ONTAP commands

* `vserver create`
* `vserver add-aggregates`
* `network interface create`
* `network route create`
* `vserver services name-service dns create`
* `vserver nfs create`
* `vserver services name-service ldap client create`
* `vserver cifs create`
* `vserver services name-service nis-domain create`
* `vserver iscsi create`
* `vserver nvme create`
* `vserver fcp create`
* `vserver services name-service ns-switch create`
* `vserver object-store-server create`
* `vserver add-protocols`
* `vserver remove-protocols`

== Examples

* Creates an SVM with default "snapshot_policy".
+
----
POST "/api/svm/svms" '{"name":"testVs", "snapshot_policy":{"name":"default"}}'
----

* Creates an SVM and configures NFS, CIFS, and S3.
+
----
POST "/api/svm/svms" '{"name":"testVs", "nfs":{"enabled":"true"}, "cifs":{"enabled":"true"}, "s3":{"enabled":"true"}}'
----

* Creates an SVM and configures NVMe.
+
----
POST "/api/svm/svms" '{"name":"testVs", "nvme":{"enabled":"true"}}'
----

* Creates an SVM and configures LDAP.
+
----
POST "/api/svm/svms" '{"name":"testVs", "snapshot_policy":{"name":"default"}, "ldap":{"servers":["10.140.101.1","10.140.101.2"], "ad_domain":"abc.com", "base_dn":"dc=netapp,dc=com", "bind_dn":"dc=netapp,dc=com"}}'
----

* Creates an SVM and configures NIS.
+
----
POST "/api/svm/svms" '{"name":"testVs", "snapshot_policy":{"name":"default"}, "nis":{"enabled":"true", "domain":"def.com","servers":["10.224.223.130", "10.224.223.131"]}}'
----

* Creates an SVM and configures DNS.
+
----
POST "/api/svm/svms" '{"name":"testVs", "snapshot_policy":{"name":"default"}, "dns":{"domains":["abc.com","def.com"], "servers":["10.224.223.130", "10.224.223.131"]}}'
----

* Creates an SVM and configures a LIF.
+
----
POST "/api/svm/svms" '{"name":"testVs", "ip_interfaces": [{"name":"lif1", "ip":{"address":"10.10.10.7", "netmask": "255.255.255.0"}, "location":{"broadcast_domain":{"name":"bd1"}, "home_node":{"name":"node1"}}, "service_policy": "default-management"}]}'
----

* Creates an SVM and configures a LIF with IPV6 address.
+
----
POST "/api/svm/svms" '{"name":"testVs", "ip_interfaces": [{"name":"lif2", "ip":{"address":"fd22:8b1e:b255:202:2a0:98ff:fe01:7d5b", "netmask":"24"}, "location":{"broadcast_domain":{"name":"bd1"}, "home_node":{"name":"node1"}}, "service_policy": "default-management"}]}'
----

* Creates an SVM and configures CIFS.
+
----
POST "/api/svm/svms" '{"name":"testVs", "cifs":{"name":"CIFDOC", "ad_domain":{"fqdn":"abc.def.com", "organizational_unit":"CN=Computers", "user":"cif_admin", "password":"abc123"}}, "ip_interfaces":[{"name":"lif1", "ip":{"address":"10.10.10.7", "netmask": "255.255.255.0"}, "location":{"broadcast_domain":{"name":"bd1"}, "home_node":{"name":"node1"}}, "service_policy": "default-management"}],"routes": [{"destination": {"address": "0.0.0.0", "netmask": "0"}, "gateway": "10.10.10.7"}], "dns":{"domains":["abc.def.com", "def.com"], "servers":["10.224.223.130", "10.224.223.131"]}}'
----

* Creates an SVM with an S3 server enabled and configured.
+
----
POST "/api/svm/svms" '{"name":"svm5", "s3":{"name":"s3-server-1", "enabled":true, "allowed":true, "is_http_enabled": true, "is_https_enabled":false}}'
----

* Creates an SVM and disallows NVMe service for the SVM.
+
----
POST "/api/svm/svms" '{"name":"testVs", "nvme":{"allowed":"false"}}'
----

* Creates an SVM, allows and configures the NFS service for the SVM.
+
----
POST "/api/svm/svms" '{"name":"testVs", "nfs":{"allowed":"true", "enabled":true}}'
----

* Create an SVM and set the max volume limit for the SVM.
+
----
POST "/api/svm/svms/" '{"name":"testVs", "max_volumes":"200"}'
----

* Creates an SVM and disallows the NDMP service for the SVM.
+
----
POST "/api/svm/svms" '{"name":"testVs", "ndmp":{"allowed":"false"}}'
----

* Creates an SVM and specifies whether file system analytics is enabled on all newly created volumes in the SVM.
+
----
POST "/api/svm/svms" '{"name":"testVs", "auto_enable_analytics":true}}'
----

* Creates an SVM and specifies whether volume_activity_tracking is enabled on all newly created volumes in the SVM.
+
----
POST "/api/svm/svms" '{"name":"testVs", "auto_enable_activity_tracking":true}}'
----

* Creates an SVM and specifies whether file system analytics is enabled on all newly created volumes in the SVM.
+
----
POST "/api/svm/svms" '{"name":"testVs", "auto_enable_analytics":true}}'
----

* Creates an SVM and specifies the maximum storage limit for a single SVM.
+
----
POST "/api/svm/svms" '{"name":"testVs", "storage": {"limit":"4GB"}}'
----

* Creates an SVM and specifies at what percentage of storage capacity an alert message is sent. Default value is 90.
+
----
POST "/api/svm/svms" '{"name":"testVs", "storage": {"limit":"20GB", "limit_threshold_alert":"95"}}'
----

* Creates an SVM and specifies the QoS policy group template to be assigned to the SVM.
+
----
POST "/api/svm/svms" '{"name":"testVs", "qos_policy_group_template":{"name":"performance-fixed"}}'
----

* Creates an SVM and specifies the QoS adaptive policy group template to be assigned to the SVM.
+
----
POST "/api/svm/svms" '{"name":"testVs", "qos_adaptive_policy_group_template":{"name":"performance"}}'
----

== Learn more

* link:svm_svms_endpoint_overview.html[DOC /svm/svms]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregates
|array[link:#aggregates[aggregates]]
a|List of allowed aggregates for SVM volumes. An administrator is allowed to create volumes on these aggregates.


|aggregates_delegated
|boolean
a|This property is true when the administrator has delegated the aggregates for the SVM volumes.


|anti_ransomware
|link:#arw_vserver[arw_vserver]
a|Anti-ransomware related information for the SVM.


|anti_ransomware_auto_switch_duration_without_new_file_extension
|integer
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that no new file-extensions are observed in the volume in recent time. This parameter optionally specifies the recent time duration (in days) to be considered during which no new file-extension should be observed in a given volume to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". This field will no longer be supported in a future release.


|anti_ransomware_auto_switch_from_learning_to_enabled
|boolean
a|This property specifies whether anti-ransomware state of the volumes in this SVM are automatically switched by the system from "`learning`" (dry-run) to "`enabled`" (active) state after sufficient learning. This field will no longer be supported in a future release.


|anti_ransomware_auto_switch_minimum_file_count
|integer
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should have a minimum file count in "`learning`" state. This parameter optionally specifies the minimum number of newly created files in "`learning`" state in a given volume to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". This field will no longer be supported in a future release.


|anti_ransomware_auto_switch_minimum_file_extension
|integer
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should have minimum number of file extensions in "`learning`" state. This parameter optionally specifies the minimum number of new file extensions in "`learning`" state in a given volume to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". This field will no longer be supported in a future release.


|anti_ransomware_auto_switch_minimum_incoming_data
|string
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should have sufficient data ingested to do the learning. This parameter optionally specifies the minimum amount of data (in GB) to be written to a given volume during the learning period to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". The amount of data considered as ingested also includes the data that is deleted or overwritten after ingestion. This field will no longer be supported in a future release.


|anti_ransomware_auto_switch_minimum_learning_period
|integer
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should be in "`learning`" state for sufficient time period. This parameter optionally specifies the minimum number of days a given volume should be in "`learning`" state to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". This field will no longer be supported in a future release.


|anti_ransomware_default_volume_state
|string
a|Specifies the default anti-ransomware state of the volumes in the SVM. The default "anti_ransomware_default_volume_state" property is disabled for POST operations. If this value is "disabled", anti-ransomware protection is disabled by default on the new volumes that are created in the SVM. If this value is "dry_run", anti-ransomware protection is in learning mode by default on the new volumes that are created in the SVM.  When the anti-ransomware license is not present, this property is ignored and volumes will be created with the "disabled" state. This value "dry_run" will no longer be supported in a future release.


|anti_ransomware_incoming_write_threshold
|string
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should have sufficient data ingested to do the learning. This parameter optionally specifies the minimum amount of data (in GB) to be written to a given volume during the learning period to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". The amount of data considered as ingested also includes the data that is deleted or overwritten after ingestion. This field is no longer supported.


|anti_ransomware_incoming_write_threshold_percent
|string
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should have sufficient data ingested to do the learning. This parameter optionally specifies the minimum amount of data (in percentage) to be written to a given volume during the learning period to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". The amount of data considered as ingested also includes the data that is deleted or overwritten after ingestion. This field will no longer be supported in a future release.


|auto_enable_activity_tracking
|boolean
a|Specifies whether volume activity tracking is automatically enabled on volumes that are created in the SVM.


|auto_enable_analytics
|boolean
a|Specifies whether file system analytics is automatically enabled on volumes that are created in the SVM.


|cifs
|link:#cifs[cifs]
a|

|comment
|string
a|Comment


|dns
|link:#dns[dns]
a|

|fc_interfaces
|array[link:#fc_interface_svm[fc_interface_svm]]
a|FC Interface for the SVM


|fcp
|link:#fcp[fcp]
a|Available for GET, POST, and PATCH requests.


|ip_interfaces
|array[link:#ip_interface_svm[ip_interface_svm]]
a|IP interfaces for the SVM


|ipspace
|link:#ipspace[ipspace]
a|Either the UUID or name may be supplied on input.


|is_space_enforcement_logical
|boolean
a|Indicates whether logical space enforcement for the SVM is enabled.


|is_space_reporting_logical
|boolean
a|Indicates whether logical space reporting for the SVM is enabled.


|iscsi
|link:#iscsi[iscsi]
a|Available for GET, POST, and PATCH requests.


|language
|string
a|Default volume language code. UTF-8 encoded languages are valid in POST or PATCH. Non UTF-8 language encodings are for backward compatibility and are not valid input for POST and PATCH requests.


|ldap
|link:#ldap[ldap]
a|

|max_volumes
|string
a|This property is used by cluster administrator to specify the limit on maximum number of volumes allowed in the SVM. The value can be either the string "unlimited" or a number.


|name
|string
a|The name of the SVM.


|ndmp
|link:#ndmp[ndmp]
a|

|nfs
|link:#nfs[nfs]
a|

|nis
|link:#nis[nis]
a|

|nsswitch
|link:#nsswitch[nsswitch]
a|Name service switch configuration


|number_of_volumes_in_recovery_queue
|integer
a|Number of volumes in the recovery queue.


|nvme
|link:#nvme[nvme]
a|Available for GET, POST, and PATCH requests.


|qos_adaptive_policy_group_template
|link:#qos_adaptive_policy_group_template[qos_adaptive_policy_group_template]
a|This optionally specifies which QoS adaptive policy group to apply to the SVM as a template. This policy group will then be assigned to volumes created or rehosted into this SVM. This policy group defines measurable service level objectives (SLOs) and Service Level Agreements (SLAs) that adjust based on the volume allocated space or used space.


|qos_policy_group_template
|link:#qos_policy_group_template[qos_policy_group_template]
a|This optionally specifies which QoS non-shared policy group to apply to the SVM as a template. This policy group is then assigned to volumes created or rehosted into this SVM. This policy group defines measurable service level objectives (SLOs) and Service Level Agreements (SLAs).


|routes
|array[link:#network_route_for_svm[network_route_for_svm]]
a|Optional array of routes for the SVM


|s3
|link:#s3[s3]
a|

|snapmirror
|link:#snapmirror[snapmirror]
a|Specifies attributes for SVM DR protection.


|snapshot_policy
|link:#snapshot_policy[snapshot_policy]
a|This is a reference to the snapshot policy.


|storage
|link:#storage[storage]
a|

|subtype
|string
a|SVM subtype. The SVM subtype sync_destination is created automatically when an SVM of subtype sync_source is created on the source MetroCluster cluster. A POST request with sync_destination as SVM subtype is invalid. SVM of subtype data_engine cannot be explicitly created by the admin and most management changes are not allowed on it.


|total_volume_size_in_recovery_queue
|integer
a|Sum of the sizes of the volumes in the recovery queue.


|uuid
|string
a|The unique identifier of the SVM.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "aggregates": [
    {
      "available_size": 10156560384,
      "name": "aggr1",
      "snaplock_type": "string",
      "state": "string",
      "type": "string",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "anti_ransomware_auto_switch_minimum_incoming_data": "string",
  "anti_ransomware_default_volume_state": "string",
  "anti_ransomware_incoming_write_threshold": "string",
  "anti_ransomware_incoming_write_threshold_percent": "string",
  "cifs": {
    "ad_domain": {
      "default_site": "string",
      "fqdn": "example.com",
      "organizational_unit": "string",
      "password": "string",
      "user": "string"
    },
    "auth-style": "domain",
    "domain_workgroup": "string",
    "name": "CIFS1",
    "workgroup": "workgrp1"
  },
  "comment": "string",
  "dns": {
    "domains": [
      "example.com",
      "example2.example3.com"
    ],
    "servers": [
      "10.224.65.20",
      "2001:db08:a0b:12f0::1"
    ]
  },
  "fc_interfaces": [
    {
      "data_protocol": "string",
      "location": {
        "port": {
          "name": "0a",
          "node": {
            "name": "node1"
          },
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      },
      "name": "lif1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "ip_interfaces": [
    {
      "ip": {
        "address": "10.10.10.7",
        "netmask": "24"
      },
      "location": {
        "broadcast_domain": {
          "name": "bd1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "home_node": {
          "name": "node1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "home_port": {
          "name": "e1b",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      },
      "name": "lif1",
      "service_policy": "string",
      "services": [
        "data_nfs"
      ],
      "subnet": {
        "name": "subnet1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "ipspace": {
    "name": "Default",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "language": "c.utf_8",
  "ldap": {
    "ad_domain": "string",
    "base_dn": "string",
    "bind_dn": "string",
    "servers": [
      "string"
    ]
  },
  "max_volumes": "string",
  "name": "svm1",
  "nis": {
    "domain": "string",
    "servers": [
      "string"
    ]
  },
  "nsswitch": {
    "group": [
      "string"
    ],
    "hosts": [
      "string"
    ],
    "namemap": [
      "string"
    ],
    "netgroup": [
      "string"
    ],
    "passwd": [
      "string"
    ]
  },
  "number_of_volumes_in_recovery_queue": 0,
  "qos_adaptive_policy_group_template": {
    "max_throughput": [
      "900KB/s",
      "500MB/s",
      "120GB/s",
      "5000IOPS",
      "5000IOPS,500KB/s",
      "2500IOPS,100MB/s",
      "1000IOPS,25MB/s"
    ],
    "max_throughput_iops": 10000,
    "max_throughput_mbps": 500,
    "min_throughput": [
      "900KB/s",
      "500MB/s",
      "120GB/s",
      "5000IOPS",
      "5000IOPS,500KB/s",
      "2500IOPS,100MB/s",
      "1000IOPS,25MB/s"
    ],
    "min_throughput_iops": 2000,
    "min_throughput_mbps": 500,
    "name": "performance",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "qos_policy_group_template": {
    "max_throughput": [
      "900KB/s",
      "500MB/s",
      "120GB/s",
      "5000IOPS",
      "5000IOPS,500KB/s",
      "2500IOPS,100MB/s",
      "1000IOPS,25MB/s"
    ],
    "max_throughput_iops": 10000,
    "max_throughput_mbps": 500,
    "min_throughput": [
      "900KB/s",
      "500MB/s",
      "120GB/s",
      "5000IOPS",
      "5000IOPS,500KB/s",
      "2500IOPS,100MB/s",
      "1000IOPS,25MB/s"
    ],
    "min_throughput_iops": 2000,
    "min_throughput_mbps": 500,
    "name": "performance",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "routes": [
    {
      "destination": {
        "address": "10.10.10.7",
        "netmask": "24"
      },
      "gateway": "10.1.1.1"
    }
  ],
  "s3": {
    "certificate": {
      "name": "string",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    },
    "default_unix_user": "string",
    "default_win_user": "string",
    "name": "s3-server-1"
  },
  "snapmirror": {
    "protected_consistency_group_count": 0,
    "protected_volumes_count": 0
  },
  "snapshot_policy": {
    "name": "default",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "storage": {
    "allocated": 0,
    "available": 0,
    "used_percentage": 0
  },
  "subtype": "string",
  "total_volume_size_in_recovery_queue": 0,
  "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Response

```
Status: 201, Created
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error codes | Description

| 2621580
| Cannot specify options other than SVM name, comment and ipspace for a Vserver that is being configured as the destination for SVM DR.

| 2621634
| "sync-source" SVM can only be created in a MetroCluster configuration.

| 2621657
| "sync-destination" SVM can only be created by the system.

| 13434884
| Cannot create an SVM because of incorrect fields.

| 13434885
| Non-UTF8 language(s) not supported.

| 13434888
| IPspace UUID and IPspace name mismatch.

| 13434889
| Internal Error. Wait and retry.

| 13434894
| Maximum allowed SVM jobs exceeded. Wait for the existing SVM jobs to complete and try again.

| 13434908
| Invalid SVM name. The name is already in use by another SVM, IPSpace or cluster.

| 13434909
| Internal Error. Failed to identify the aggregate to host SVM root volume.

| 13434910
| Internal Error. Failed to allocate new SVM ID.

| 13434911
| Invalid SVM name. Maximum supported length is 41 if SVM is of type \"sync-source\", otherwise 47.

| 13434912
| Failed to find IPspace.

| 13434913
| Internal error: Failed to check if an SVM create operation is in progress. Contact technical support for assistance.

| 13434914
| Request to create the root volume of the SVM failed because there is not enough space in specified aggregate.

| 13434915
| Failed to unlock the SVM because SVM create or delete job is in progress. Wait a few minutes, and then try the command again.

| 13434916
| SVM is in the process of being created. Wait a few minutes, and then try the command again.

| 13434917
| SVM creation successful.

| 13434918
| IPspace name not provided for creating an SVM.

| 458753
| Destination and gateway must belong to the same address family.

| 23724038
| Invalid source for the provided ns-switch database.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#aggregates]
[.api-collapsible-fifth-title]
aggregates

[cols=3*,options=header]
|===
|Name
|Type
|Description

|available_size
|integer
a|Space available, in bytes.


|name
|string
a|

|snaplock_type
|string
a|SnapLock type.


|state
|string
a|Aggregate state.


|type
|string
a|Type of aggregate.


|uuid
|string
a|

|===


[#event_log]
[.api-collapsible-fifth-title]
event_log

[cols=3*,options=header]
|===
|Name
|Type
|Description

|is_enabled_on_new_file_extension_seen
|boolean
a|Specifies whether to send an EMS when a new file extension is discovered.


|is_enabled_on_snapshot_copy_creation
|boolean
a|Specifies whether to send an EMS when a snapshot is created.


|===


[#arw_vserver]
[.api-collapsible-fifth-title]
arw_vserver

Anti-ransomware related information for the SVM.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|event_log
|link:#event_log[event_log]
a|

|===


[#certificate]
[.api-collapsible-fifth-title]
certificate

Support for this field will be removed in a future release. Please use /svm/svms/{svm.uuid}/web for this field. Certificate for incoming TLS connection requests.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Certificate name


|uuid
|string
a|Certificate UUID


|===


[#ad_domain]
[.api-collapsible-fifth-title]
ad_domain

[cols=3*,options=header]
|===
|Name
|Type
|Description

|default_site
|string
a|The default site used by LIFs that do not have a site membership.


|fqdn
|string
a|The fully qualified domain name of the Windows Active Directory to which this CIFS server belongs. A CIFS server appears as a member of Windows server object in the Active Directory store.


|organizational_unit
|string
a|Specifies the organizational unit within the Active Directory domain to associate with the CIFS server.


|password
|string
a|The account password used to add this CIFS server to the Active Directory. This is not audited. Valid in POST only.


|user
|string
a|The user account used to add this CIFS server to the Active Directory. Valid in POST only.


|===


[#cifs]
[.api-collapsible-fifth-title]
cifs

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ad_domain
|link:#ad_domain[ad_domain]
a|

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the CIFS service. If it is false, only the cluster administrator can manage the service.


|auth-style
|string
a|Authentication type.


|domain_workgroup
|string
a|The NetBIOS name of the domain or workgroup associated with the CIFS server.


|enabled
|boolean
a|If allowed, setting to true enables the CIFS service.


|name
|string
a|The NetBIOS name of the CIFS server.


|workgroup
|string
a|The workgroup name.


|===


[#dns]
[.api-collapsible-fifth-title]
dns

[cols=3*,options=header]
|===
|Name
|Type
|Description

|domains
|array[string]
a|A list of DNS domains.
Domain names have the following requirements:

* The name must contain only the following characters: A through Z,
a through z, 0 through 9, ".", "-" or "_".
* The first character of each label, delimited by ".", must be one
of the following characters: A through Z or a through z or 0
through 9.
* The last character of each label, delimited by ".", must be one of
the following characters: A through Z, a through z, or 0 through 9.
* The top level domain must contain only the following characters: A
through Z, a through z.
* The system reserves the following names:"all", "local", and "localhost".


|servers
|array[string]
a|The list of IP addresses of the DNS servers. Addresses can be either
IPv4 or IPv6 addresses.


|===


[#node]
[.api-collapsible-fifth-title]
node

The node on which the FC port is located.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the node on which the FC port is located.


|===


[#fc_port_reference]
[.api-collapsible-fifth-title]
fc_port_reference

An FC port is the physical port of an FC adapter on a cluster node that can be connected to an FC network.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the FC port.


|node
|link:#node[node]
a|The node on which the FC port is located.


|uuid
|string
a|The unique identifier of the FC port.


|===


[#location]
[.api-collapsible-fifth-title]
location

The location of the Fibre Channel interface is defined by the location of its port.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|port
|link:#fc_port_reference[fc_port_reference]
a|An FC port is the physical port of an FC adapter on a cluster node that can be connected to an FC network.


|===


[#fc_interface_svm]
[.api-collapsible-fifth-title]
fc_interface_svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|data_protocol
|string
a|The data protocol for which the Fibre Channel interface is configured.


|location
|link:#location[location]
a|The location of the Fibre Channel interface is defined by the location of its port.


|name
|string
a|The name of the Fibre Channel interface.


|uuid
|string
a|The unique identifier of the Fibre Channel interface.


|===


[#fcp]
[.api-collapsible-fifth-title]
fcp

Available for GET, POST, and PATCH requests.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the FCP service. If it is false, only the cluster administrator can manage the service.


|enabled
|boolean
a|If allowed, setting to true enables the FCP service.


|===


[#ip]
[.api-collapsible-fifth-title]
ip

IP information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|netmask
|string
a|Input as netmask length (16) or IPv4 mask (255.255.0.0).


|===


[#broadcast_domain]
[.api-collapsible-fifth-title]
broadcast_domain

Broadcast domain UUID along with a readable name.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the broadcast domain, scoped to its IPspace


|uuid
|string
a|Broadcast domain UUID


|===


[#home_node]
[.api-collapsible-fifth-title]
home_node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#port_svm]
[.api-collapsible-fifth-title]
port_svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#location]
[.api-collapsible-fifth-title]
location

Home_node is optional.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|broadcast_domain
|link:#broadcast_domain[broadcast_domain]
a|Broadcast domain UUID along with a readable name.


|home_node
|link:#home_node[home_node]
a|

|home_port
|link:#port_svm[port_svm]
a|

|===


[#ip_subnet_reference]
[.api-collapsible-fifth-title]
ip_subnet_reference

A named subnet. Either UUID or name can be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the subnet. If only the name is provided, the IPspace scope
must be provided by the object this object is embedded in.


|uuid
|string
a|The UUID that uniquely identifies the subnet.


|===


[#ip_interface_svm]
[.api-collapsible-fifth-title]
ip_interface_svm

Interface parameters.  Name and home_node are optional.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#ip[ip]
a|IP information


|location
|link:#location[location]
a|Home_node is optional.


|name
|string
a|The name of the interface (optional).


|service_policy
|string
a|Built-in service policies for SVMs.


|services
|array[string]
a|The services associated with the interface.


|subnet
|link:#ip_subnet_reference[ip_subnet_reference]
a|A named subnet. Either UUID or name can be supplied on input.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#ipspace]
[.api-collapsible-fifth-title]
ipspace

Either the UUID or name may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|IPspace name


|uuid
|string
a|IPspace UUID


|===


[#iscsi]
[.api-collapsible-fifth-title]
iscsi

Available for GET, POST, and PATCH requests.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the iSCSI service. If it is false, only the cluster administrator can manage the service.


|enabled
|boolean
a|If allowed, setting to true enables the iSCSI service.


|===


[#ldap]
[.api-collapsible-fifth-title]
ldap

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ad_domain
|string
a|This parameter specifies the name of the Active Directory domain
used to discover LDAP servers for use by this client.
This is mutually exclusive with `servers` during POST.


|base_dn
|string
a|Specifies the default base DN for all searches.


|bind_dn
|string
a|Specifies the user that binds to the LDAP servers. SVM API supports anonymous binding. For Simple and SASL LDAP binding, use the LDAP API endpoint.


|enabled
|boolean
a|Enable LDAP? Setting to true creates a configuration if not already created.


|restrict_discovery_to_site
|boolean
a|Specifies whether or not LDAP server discovery is restricted to site-scope.


|servers
|array[string]
a|

|===


[#ndmp]
[.api-collapsible-fifth-title]
ndmp

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the NDMP service. If it is false, only the cluster administrator can manage the service.


|===


[#nfs]
[.api-collapsible-fifth-title]
nfs

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the NFS service. If it is false, only the cluster administrator can manage the service.


|enabled
|boolean
a|If allowed, setting to true enables the NFS service.


|===


[#nis]
[.api-collapsible-fifth-title]
nis

[cols=3*,options=header]
|===
|Name
|Type
|Description

|domain
|string
a|The NIS domain to which this configuration belongs.


|enabled
|boolean
a|Enable NIS? Setting to true creates a configuration if not already created.


|servers
|array[string]
a|A list of hostnames or IP addresses of NIS servers used
by the NIS domain configuration.


|===


[#nsswitch]
[.api-collapsible-fifth-title]
nsswitch

Name service switch configuration


[cols=3*,options=header]
|===
|Name
|Type
|Description

|group
|array[string]
a|Group sources


|hosts
|array[string]
a|Host sources


|namemap
|array[string]
a|NameMap sources


|netgroup
|array[string]
a|NetGroup sources


|passwd
|array[string]
a|Password sources


|===


[#nvme]
[.api-collapsible-fifth-title]
nvme

Available for GET, POST, and PATCH requests.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the NVMe service. If it is false, only the cluster administrator can manage the service.


|enabled
|boolean
a|If allowed, setting to true enables the NVMe service.


|===


[#qos_adaptive_policy_group_template]
[.api-collapsible-fifth-title]
qos_adaptive_policy_group_template

This optionally specifies which QoS adaptive policy group to apply to the SVM as a template. This policy group will then be assigned to volumes created or rehosted into this SVM. This policy group defines measurable service level objectives (SLOs) and Service Level Agreements (SLAs) that adjust based on the volume allocated space or used space.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|max_throughput
|string
a|Specifies the maximum throughput in Kilobytes per sec, Megabytes per sec or Gigabytes per sec along with or without IOPS. 0 means none. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when either max_throughput_mbps or max_throughput_iops are set during POST or PATCH. During GET, the returned value is rounded to the largest unit with a value greater than 1.


|max_throughput_iops
|integer
a|Specifies the maximum throughput in IOPS, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when max_throughput is set during POST or PATCH.


|max_throughput_mbps
|integer
a|Specifies the maximum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when max_throughput is set during POST or PATCH.


|min_throughput
|string
a|Specifies the minimum throughput in Kilobytes per sec, Megabytes per sec or Gigabytes per sec along with or without IOPS. 0 means none.Setting "min_throughput" is supported on AFF platforms only, unless FabricPool tiering policies are set. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when either min_throughput_mbps or min_throughput_iops are set during POST or PATCH. During GET, the returned value is rounded to the largest unit with a value greater than 1.


|min_throughput_iops
|integer
a|Specifies the minimum throughput in IOPS, 0 means none. Setting "min_throughput" is supported on AFF platforms only, unless FabricPool tiering policies are set. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when min_throughput is set during POST or PATCH.


|min_throughput_mbps
|integer
a|Specifies the minimum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.This cannot be set when min_throughput is set during POST or PATCH.


|name
|string
a|The QoS policy group name. This is mutually exclusive with UUID and other QoS attributes during POST and PATCH.


|uuid
|string
a|The QoS policy group UUID. This is mutually exclusive with name and other QoS attributes during POST and PATCH.


|===


[#qos_policy]
[.api-collapsible-fifth-title]
qos_policy

This optionally specifies which QoS policy group to apply to the Vserver. This policy group defines measurable service level objectives (SLOs) that apply to the storage objects with which the policy group is associated.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|max_throughput
|string
a|Specifies the maximum throughput in Kilobytes per sec, Megabytes per sec or Gigabytes per sec along with or without IOPS. 0 means none. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when either max_throughput_mbps or max_throughput_iops are set during POST or PATCH. During GET, the returned value is rounded to the largest unit with a value greater than 1.


|max_throughput_iops
|integer
a|Specifies the maximum throughput in IOPS, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when max_throughput is set during POST or PATCH.


|max_throughput_mbps
|integer
a|Specifies the maximum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when max_throughput is set during POST or PATCH.


|min_throughput
|string
a|Specifies the minimum throughput in Kilobytes per sec, Megabytes per sec or Gigabytes per sec along with or without IOPS. 0 means none.Setting "min_throughput" is supported on AFF platforms only, unless FabricPool tiering policies are set. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when either min_throughput_mbps or min_throughput_iops are set during POST or PATCH. During GET, the returned value is rounded to the largest unit with a value greater than 1.


|min_throughput_iops
|integer
a|Specifies the minimum throughput in IOPS, 0 means none. Setting "min_throughput" is supported on AFF platforms only, unless FabricPool tiering policies are set. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when min_throughput is set during POST or PATCH.


|min_throughput_mbps
|integer
a|Specifies the minimum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.This cannot be set when min_throughput is set during POST or PATCH.


|name
|string
a|The QoS policy group name. This is mutually exclusive with UUID and other QoS attributes during POST and PATCH.


|uuid
|string
a|The QoS policy group UUID. This is mutually exclusive with name and other QoS attributes during POST and PATCH.


|===


[#qos_policy_group_template]
[.api-collapsible-fifth-title]
qos_policy_group_template

This optionally specifies which QoS non-shared policy group to apply to the SVM as a template. This policy group is then assigned to volumes created or rehosted into this SVM. This policy group defines measurable service level objectives (SLOs) and Service Level Agreements (SLAs).


[cols=3*,options=header]
|===
|Name
|Type
|Description

|max_throughput
|string
a|Specifies the maximum throughput in Kilobytes per sec, Megabytes per sec or Gigabytes per sec along with or without IOPS. 0 means none. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when either max_throughput_mbps or max_throughput_iops are set during POST or PATCH. During GET, the returned value is rounded to the largest unit with a value greater than 1.


|max_throughput_iops
|integer
a|Specifies the maximum throughput in IOPS, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when max_throughput is set during POST or PATCH.


|max_throughput_mbps
|integer
a|Specifies the maximum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when max_throughput is set during POST or PATCH.


|min_throughput
|string
a|Specifies the minimum throughput in Kilobytes per sec, Megabytes per sec or Gigabytes per sec along with or without IOPS. 0 means none.Setting "min_throughput" is supported on AFF platforms only, unless FabricPool tiering policies are set. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when either min_throughput_mbps or min_throughput_iops are set during POST or PATCH. During GET, the returned value is rounded to the largest unit with a value greater than 1.


|min_throughput_iops
|integer
a|Specifies the minimum throughput in IOPS, 0 means none. Setting "min_throughput" is supported on AFF platforms only, unless FabricPool tiering policies are set. This is mutually exclusive with name and UUID during POST and PATCH. This cannot be set when min_throughput is set during POST or PATCH.


|min_throughput_mbps
|integer
a|Specifies the minimum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.This cannot be set when min_throughput is set during POST or PATCH.


|name
|string
a|The QoS policy group name. This is mutually exclusive with UUID and other QoS attributes during POST and PATCH.


|uuid
|string
a|The QoS policy group UUID. This is mutually exclusive with name and other QoS attributes during POST and PATCH.


|===


[#ip_info]
[.api-collapsible-fifth-title]
ip_info

IP information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|netmask
|string
a|Input as netmask length (16) or IPv4 mask (255.255.0.0). For IPv6, the default value is 64 with a valid range of 1 to 127. Output is always the netmask length.


|===


[#network_route_for_svm]
[.api-collapsible-fifth-title]
network_route_for_svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|destination
|link:#ip_info[ip_info]
a|IP information


|gateway
|string
a|The IP address of the gateway router leading to the destination.


|===


[#certificate]
[.api-collapsible-fifth-title]
certificate

Specifies the certificate that will be used for creating HTTPS connections to the S3 server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Certificate name


|uuid
|string
a|Certificate UUID


|===


[#s3]
[.api-collapsible-fifth-title]
s3

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the S3 service. If it is false, only the cluster administrator can manage the service.


|certificate
|link:#certificate[certificate]
a|Specifies the certificate that will be used for creating HTTPS connections to the S3 server.


|default_unix_user
|string
a|Specifies the default UNIX user for NAS Access.


|default_win_user
|string
a|Specifies the default Windows user for NAS Access.


|enabled
|boolean
a|Specifies whether or not to enable S3. Setting this value to true creates a service if one is not yet created.


|is_http_enabled
|boolean
a|Specifies whether HTTP is enabled on the S3 server. By default, HTTP is disabled on the S3 server.


|is_https_enabled
|boolean
a|Specifies whether HTTPS is enabled on the S3 server. By default, HTTPS is enabled on the S3 server.


|name
|string
a|Specifies the name of the S3 server. A server name length can range from 1 to 253 characters and can only contain the following combination of characters 0-9, A-Z, a-z, ".", and "-".


|port
|integer
a|Specifies the HTTP listener port for the S3 server. By default, HTTP is enabled on port 80.


|secure_port
|integer
a|Specifies the HTTPS listener port for the S3 server. By default, HTTPS is enabled on port 443.


|===


[#snapmirror]
[.api-collapsible-fifth-title]
snapmirror

Specifies attributes for SVM DR protection.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|is_protected
|boolean
a|Specifies whether the SVM is a SnapMirror source SVM, using SnapMirror to protect its data.


|protected_consistency_group_count
|integer
a|Specifies the number of SVM DR protected consistency groups in the SVM.


|protected_volumes_count
|integer
a|Specifies the number of SVM DR protected volumes in the SVM.


|===


[#snapshot_policy]
[.api-collapsible-fifth-title]
snapshot_policy

This is a reference to the snapshot policy.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#storage]
[.api-collapsible-fifth-title]
storage

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allocated
|integer
a|Total size of the volumes in SVM, in bytes.


|available
|integer
a|Currently available storage capacity in SVM, in bytes.


|limit
|integer
a|Maximum storage permitted on a single SVM, in bytes.


|limit_threshold_alert
|integer
a|Indicates at what percentage of storage capacity an alert message is sent. The default value is 90.


|limit_threshold_exceeded
|boolean
a|Indicates whether the total storage capacity exceeds the alert percentage.


|used_percentage
|integer
a|The percentage of storage capacity used.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregates
|array[link:#aggregates[aggregates]]
a|List of allowed aggregates for SVM volumes. An administrator is allowed to create volumes on these aggregates.


|aggregates_delegated
|boolean
a|This property is true when the administrator has delegated the aggregates for the SVM volumes.


|anti_ransomware
|link:#arw_vserver[arw_vserver]
a|Anti-ransomware related information for the SVM.


|anti_ransomware_auto_switch_duration_without_new_file_extension
|integer
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that no new file-extensions are observed in the volume in recent time. This parameter optionally specifies the recent time duration (in days) to be considered during which no new file-extension should be observed in a given volume to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". This field will no longer be supported in a future release.


|anti_ransomware_auto_switch_from_learning_to_enabled
|boolean
a|This property specifies whether anti-ransomware state of the volumes in this SVM are automatically switched by the system from "`learning`" (dry-run) to "`enabled`" (active) state after sufficient learning. This field will no longer be supported in a future release.


|anti_ransomware_auto_switch_minimum_file_count
|integer
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should have a minimum file count in "`learning`" state. This parameter optionally specifies the minimum number of newly created files in "`learning`" state in a given volume to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". This field will no longer be supported in a future release.


|anti_ransomware_auto_switch_minimum_file_extension
|integer
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should have minimum number of file extensions in "`learning`" state. This parameter optionally specifies the minimum number of new file extensions in "`learning`" state in a given volume to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". This field will no longer be supported in a future release.


|anti_ransomware_auto_switch_minimum_incoming_data
|string
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should have sufficient data ingested to do the learning. This parameter optionally specifies the minimum amount of data (in GB) to be written to a given volume during the learning period to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". The amount of data considered as ingested also includes the data that is deleted or overwritten after ingestion. This field will no longer be supported in a future release.


|anti_ransomware_auto_switch_minimum_learning_period
|integer
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should be in "`learning`" state for sufficient time period. This parameter optionally specifies the minimum number of days a given volume should be in "`learning`" state to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". This field will no longer be supported in a future release.


|anti_ransomware_default_volume_state
|string
a|Specifies the default anti-ransomware state of the volumes in the SVM. The default "anti_ransomware_default_volume_state" property is disabled for POST operations. If this value is "disabled", anti-ransomware protection is disabled by default on the new volumes that are created in the SVM. If this value is "dry_run", anti-ransomware protection is in learning mode by default on the new volumes that are created in the SVM.  When the anti-ransomware license is not present, this property is ignored and volumes will be created with the "disabled" state. This value "dry_run" will no longer be supported in a future release.


|anti_ransomware_incoming_write_threshold
|string
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should have sufficient data ingested to do the learning. This parameter optionally specifies the minimum amount of data (in GB) to be written to a given volume during the learning period to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". The amount of data considered as ingested also includes the data that is deleted or overwritten after ingestion. This field is no longer supported.


|anti_ransomware_incoming_write_threshold_percent
|string
a|One of the many conditions to be satisfied to automatically switch the anti-ransomware state of the volumes in this SVM from "`learning`" (dry-run) to "`enabled`" is that the volume should have sufficient data ingested to do the learning. This parameter optionally specifies the minimum amount of data (in percentage) to be written to a given volume during the learning period to automatically switch the anti-ransomware state from "`learning`" to "`enabled`". The amount of data considered as ingested also includes the data that is deleted or overwritten after ingestion. This field will no longer be supported in a future release.


|auto_enable_activity_tracking
|boolean
a|Specifies whether volume activity tracking is automatically enabled on volumes that are created in the SVM.


|auto_enable_analytics
|boolean
a|Specifies whether file system analytics is automatically enabled on volumes that are created in the SVM.


|cifs
|link:#cifs[cifs]
a|

|comment
|string
a|Comment


|dns
|link:#dns[dns]
a|

|fc_interfaces
|array[link:#fc_interface_svm[fc_interface_svm]]
a|FC Interface for the SVM


|fcp
|link:#fcp[fcp]
a|Available for GET, POST, and PATCH requests.


|ip_interfaces
|array[link:#ip_interface_svm[ip_interface_svm]]
a|IP interfaces for the SVM


|ipspace
|link:#ipspace[ipspace]
a|Either the UUID or name may be supplied on input.


|is_space_enforcement_logical
|boolean
a|Indicates whether logical space enforcement for the SVM is enabled.


|is_space_reporting_logical
|boolean
a|Indicates whether logical space reporting for the SVM is enabled.


|iscsi
|link:#iscsi[iscsi]
a|Available for GET, POST, and PATCH requests.


|language
|string
a|Default volume language code. UTF-8 encoded languages are valid in POST or PATCH. Non UTF-8 language encodings are for backward compatibility and are not valid input for POST and PATCH requests.


|ldap
|link:#ldap[ldap]
a|

|max_volumes
|string
a|This property is used by cluster administrator to specify the limit on maximum number of volumes allowed in the SVM. The value can be either the string "unlimited" or a number.


|name
|string
a|The name of the SVM.


|ndmp
|link:#ndmp[ndmp]
a|

|nfs
|link:#nfs[nfs]
a|

|nis
|link:#nis[nis]
a|

|nsswitch
|link:#nsswitch[nsswitch]
a|Name service switch configuration


|number_of_volumes_in_recovery_queue
|integer
a|Number of volumes in the recovery queue.


|nvme
|link:#nvme[nvme]
a|Available for GET, POST, and PATCH requests.


|qos_adaptive_policy_group_template
|link:#qos_adaptive_policy_group_template[qos_adaptive_policy_group_template]
a|This optionally specifies which QoS adaptive policy group to apply to the SVM as a template. This policy group will then be assigned to volumes created or rehosted into this SVM. This policy group defines measurable service level objectives (SLOs) and Service Level Agreements (SLAs) that adjust based on the volume allocated space or used space.


|qos_policy_group_template
|link:#qos_policy_group_template[qos_policy_group_template]
a|This optionally specifies which QoS non-shared policy group to apply to the SVM as a template. This policy group is then assigned to volumes created or rehosted into this SVM. This policy group defines measurable service level objectives (SLOs) and Service Level Agreements (SLAs).


|routes
|array[link:#network_route_for_svm[network_route_for_svm]]
a|Optional array of routes for the SVM


|s3
|link:#s3[s3]
a|

|snapmirror
|link:#snapmirror[snapmirror]
a|Specifies attributes for SVM DR protection.


|snapshot_policy
|link:#snapshot_policy[snapshot_policy]
a|This is a reference to the snapshot policy.


|storage
|link:#storage[storage]
a|

|subtype
|string
a|SVM subtype. The SVM subtype sync_destination is created automatically when an SVM of subtype sync_source is created on the source MetroCluster cluster. A POST request with sync_destination as SVM subtype is invalid. SVM of subtype data_engine cannot be explicitly created by the admin and most management changes are not allowed on it.


|total_volume_size_in_recovery_queue
|integer
a|Sum of the sizes of the volumes in the recovery queue.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
