---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-support-autosupport-messages.html'
summary: 'Create and send an AutoSupport message'
---

= Create and send an AutoSupport message

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/support/autosupport/messages`#

*Introduced In:* 9.6

Creates and sends an AutoSupport message with the provided input parameters.

Important note:

* By default, the response is an empty object. If `return_records=true` is passed in the request, the response includes information about the node and the index of the invoked AutoSupport message.

== Recommended optional properties

* `message` - Message included in the AutoSupport subject. Use this to identify the generated AutoSupport message.

== Default property values

If not specified in POST, the following are the default property values:

* `type` - _all_
* `node.name` or `node.uuid` - Not specifying these properties invokes AutoSupport on all nodes in the cluster.

== Related ONTAP commands

* `system node autosupport invoke`

== Learn more

* link:support_autosupport_messages_endpoint_overview.html[DOC /support/autosupport/messages]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|destination
|string
a|Destination for the AutoSupport


|error
|link:#error[error]
a|Last error during delivery attempt. Empty if "status=sent-successful".


|generated_on
|string
a|Date and Time of AutoSupport generation in ISO-8601 format


|index
|integer
a|Sequence number of the AutoSupport


|message
|string
a|Message included in the AutoSupport subject


|node
|link:#node[node]
a|

|state
|string
a|State of AutoSupport delivery


|subject
|string
a|Subject line for the AutoSupport


|type
|string
a|Type of AutoSupport collection to issue


|uri
|string
a|Alternate destination for the AutoSupport


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "destination": "http",
  "error": {
    "code": "53149746",
    "message": "Could not resolve host: test.com"
  },
  "generated_on": "2019-03-25 17:30:04 -0400",
  "index": 9,
  "message": "invoked_test_autosupport_rest",
  "node": {
    "name": "node1",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "state": "sent_successful",
  "subject": "WEEKLY_LOG",
  "type": "test",
  "uri": "https://1.2.3.4/delivery_uri"
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|Number of records


|records
|array[link:#autosupport_message[autosupport_message]]
a|List of messages invoked on the node


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "num_records": 1,
  "records": [
    {
      "destination": "http",
      "error": {
        "code": "53149746",
        "message": "Could not resolve host: test.com"
      },
      "generated_on": "2019-03-25 17:30:04 -0400",
      "index": 9,
      "message": "invoked_test_autosupport_rest",
      "node": {
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "state": "sent_successful",
      "subject": "WEEKLY_LOG",
      "type": "test",
      "uri": "https://1.2.3.4/delivery_uri"
    }
  ]
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 8650851
| AutoSupport invocation failed because AutoSupport collection is disabled

| 8650852
| AutoSupport invocation failed because the trigger is disabled

| 8650853
| AutoSupport invocation failed because the trigger rate is higher than the maximum supported value

| 8650866
| The message parameter is not supported with performance AutoSupports

| 8650884
| The specified field is not allowed for the current operation

| 8650885
| The specified field cannot be empty

| 53149748
| The destination URI provided for the invoked AutoSupport is invalid
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#self_link]
[.api-collapsible-fifth-title]
self_link
[#error]
[.api-collapsible-fifth-title]
error

Last error during delivery attempt. Empty if "status=sent-successful".


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|integer
a|Error code


|message
|string
a|Error message


|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#autosupport_message]
[.api-collapsible-fifth-title]
autosupport_message

[cols=3*,options=header]
|===
|Name
|Type
|Description

|destination
|string
a|Destination for the AutoSupport


|error
|link:#error[error]
a|Last error during delivery attempt. Empty if "status=sent-successful".


|generated_on
|string
a|Date and Time of AutoSupport generation in ISO-8601 format


|index
|integer
a|Sequence number of the AutoSupport


|message
|string
a|Message included in the AutoSupport subject


|node
|link:#node[node]
a|

|state
|string
a|State of AutoSupport delivery


|subject
|string
a|Subject line for the AutoSupport


|type
|string
a|Type of AutoSupport collection to issue


|uri
|string
a|Alternate destination for the AutoSupport


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
