---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-storage-flexcache-flexcaches.html'
summary: 'Create a FlexCache volume in the cluster'
---

= Create a FlexCache volume in the cluster

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/storage/flexcache/flexcaches`#

*Introduced In:* 9.6

Creates a FlexCache in the cluster.

== Required properties

* `name` - Name of FlexCache volume.
* `origins.volume.name` - Name of the origin volume. This volume can only be identified by its name, not by its UUID.
* `origins.svm.name` - Name of origin Vserver.
* `svm.name` or `svm.uuid` - Name or UUID of Vserver where FlexCache will be created.

== Recommended optional properties

* `path` - Path to mount the FlexCache volume
* `prepopulate.dir_paths` - List of directory-paths to be prepopulated for the FlexCache volume.
* `prepopulate.exclude_dir_paths` - List of directory-paths to be excluded from prepopulation for the FlexCache volume.

== Default property values

If not specified in POST, the following default property values are assigned:

* `size` - 10% of origin volume size or 1GB per constituent, whichever is greater.
* `guarantee.type` - none. FlexCache is thin provisioned by default.
* `constituents_per_aggregate` - 4 if aggregates.name or aggregates.uuid is used.
* `use_tiered_aggregate` - false if aggr-list is not used. This property is only used when auto-provisioning a FlexCache volume.
* `is_disconnected_mode_off_for_locks` - false. This property specifies if the origin will honor the cache side locks when doing the lock checks in the disconnected mode.
* `dr_cache` - false if FlexCache is not a DR cache. This property is used to create a DR FlexCache.
* `global_file_locking_enabled` - false. This property specifies whether global file locking is enabled on the FlexCache volume.
* `writeback.enabled` - false. This property specifies whether writeback is enabled for the FlexCache volume.
* `relative_size.enabled` - false. This property specifies whether the relative sizing is enabled for the FlexCache volume.
* `relative_size.percentage` - 10. This property specifies the percent size FlexCache volume should have relative to the total size of the origin volume.
* `override_encryption` - false. If true, this property is used to create a plaintext FlexCache volume for an encrypted origin volume.
* `atime_scrub.enabled` - false. This property specifies whether scrubbing of inactive files based on atime is enabled for the FlexCache volume.
* `atime_scrub.period` - 30. This property specifies the atime duration in days after which the file can be scrubbed from the FlexCache volume if it stays unused beyond the duration.
* `nfsv4.enabled` - false. This property specifies whether NFSv4 is enabled for the FlexCache volume.
* `cifs.enabled` - false. This property specifies whether CIFS is enabled for the FlexCache volume.
* `s3.enabled` - false. This property specifies whether S3 is enabled for the FlexCache volume.
* `write.absorption_enabled` - false. This property specifies whether Write Absorption is enabled for the FlexCache volume.
* `mtime_scrubber.enabled` - false. This property specifies whether the mtime-based scrubber is enabled for the FlexCache volume.
* `mtime_scrubber.threshold` - 120. This property specifies the mtime threshold in seconds for the scrubber. Valid range is 5 to 2592000 seconds (5 seconds to 30 days).
* `cifs_change_notify.enabled` - false. This property specifies whether a CIFS change notification is enabled for the FlexCache volume.

== Related ONTAP commands

* `volume flexcache create`
* `volume flexcache prepopulate start`

== Learn more

* link:storage_flexcache_flexcaches_endpoint_overview.html[DOC /storage/flexcache/flexcaches]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregates
|array[link:#aggregates[aggregates]]
a|

|atime_scrub
|link:#atime_scrub[atime_scrub]
a|FlexCache volume atime-based scrub


|cifs
|link:#cifs[cifs]
a|FlexCache CIFS


|cifs_change_notify
|link:#cifs_change_notify[cifs_change_notify]
a|Notifies that a change has been made to the FlexCache volume CIFS.


|constituents_per_aggregate
|integer
a|Number of FlexCache constituents per aggregate when the 'aggregates' field is mentioned.


|dr_cache
|boolean
a|If set to true, a DR cache is created.


|global_file_locking_enabled
|boolean
a|Specifies whether or not a FlexCache volume has global file locking mode enabled. Global file locking mode is a mode where protocol read locking semantics are enforced across all FlexCaches and origins of a FlexCache volume. When global file locking mode is enabled, the "is_disconnected_mode_off_for_locks" flag is always set to "true".


|guarantee
|link:#guarantee[guarantee]
a|

|mtime_scrubber
|link:#mtime_scrubber[mtime_scrubber]
a|Flexcache Mtime Scrubber


|name
|string
a|FlexCache name


|nfsv4
|link:#nfsv4[nfsv4]
a|FlexCache NFSv4


|origins
|array[link:#flexcache_relationship[flexcache_relationship]]
a|

|override_encryption
|boolean
a|If set to true, a plaintext FlexCache volume for an encrypted origin volume is created.


|path
|string
a|The fully-qualified path in the owning SVM's namespace at which the FlexCache is mounted. The path is case insensitive and must be unique within a SVM's namespace. Path must begin with '/' and must not end with '/'. Only one FlexCache be mounted at any given junction path.


|prepopulate
|link:#prepopulate[prepopulate]
a|FlexCache prepopulate


|relative_size
|link:#relative_size[relative_size]
a|FlexCache Relative Size


|s3
|link:#s3[s3]
a|Flexcache S3


|size
|integer
a|Physical size of the FlexCache. The recommended size for a FlexCache is 10% of the origin volume. The minimum FlexCache constituent size is 1GB.


|svm
|link:#svm[svm]
a|FlexCache SVM


|use_tiered_aggregate
|boolean
a|Specifies whether or not a Fabricpool-enabled aggregate can be used in FlexCache creation. The use_tiered_aggregate is only used when auto-provisioning a FlexCache volume.


|uuid
|string
a|FlexCache UUID. Unique identifier for the FlexCache.


|write
|link:#write[write]
a|Flexcache Write settings


|writeback
|link:#writeback[writeback]
a|FlexCache Writeback


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "aggregates": [
    {
      "name": "aggr1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "constituents_per_aggregate": 1,
  "guarantee": {
    "type": "string"
  },
  "name": "vol1",
  "origins": [
    {
      "cluster": {
        "name": "cluster1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "create_time": "2018-06-04 19:00:00 +0000",
      "ip_address": "10.10.10.7",
      "size": 0,
      "state": "string",
      "svm": {
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "volume": {
        "name": "volume1",
        "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
      }
    }
  ],
  "path": "/user/my_fc",
  "prepopulate": {
    "dir_paths": [
      "/dir1"
    ],
    "exclude_dir_paths": [
      "/dir1/dir2"
    ]
  },
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Response

```
Status: 201, Created
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 11
| Provided value is smaller than the required minimum flexvolume size.

| 262186
| Invalid combination with field "aggregates".

| 917937
| The root path "/" is an invalid value for the field "path".

| 918723
| Aggregate value cannot be used to create a volume on this platform.

| 66846735
| The peer state of the relationship is not peered or the FlexCache application is not supported by the relationship

| 66846762
| The origin volume in the SVM is offline

| 66846767
| Volume does not exist in SVM.

| 66846867
| Global file locking (GFL) mode is already disabled for origin of a FlexCache volume in SVM. Enabling GFL is only supported when the first FlexCache volume is created for an origin. Set is_global_file_locking_enabled" to "false".

| 66846768
| Volume already exists in SVM.

| 66846863
| The "preserve-msid" parameter is not supported when creating the FlexCache volume in the same SVM as the origin of a FlexCache volume

| 66846870
| Either the SVM name or origin volume name is missing

| 66846871
| Constituents per aggregate are specified but aggregate name is missing

| 66846872
| More than one origin volume is specified

| 66846873
| The specified SVM UUID is incorrect for the specified SVM name

| 66846874
| The specified name and SVM uuid refer to different aggregates.

| 66846875
| The specified aggregate name does not exist

| 66846876
| The specified SVM does not exist or is not peered

| 66846877
| The specified origin SVM name is of zero length

| 66846878
| The specified SVM UUID is invalid

| 66846787
| The specified aggregate is a SnapLock aggregate

| 66846812
| The specified aggregate is a Composite aggregate

| 66846812
| The specified junction path is under a FlexCache volume

| 66846834
| FlexCache encryption requires a cluster version of 9.6 or higher

| 66846835
| A volume encryption license is not found

| 66847013
| Creating a FlexCache volume with override-encryption property set to true requires an effective cluster version of 9.14.0 or later on both origin and cache clusters

| 66846844
| An object store server volume cannot be the origin of a FlexCache volume

| 66846902
| FlexCache is not supported on an All SAN Array system.

| 66846915
| The "use_tiered_aggregate" option is only supported when auto provisioning the FlexCache volume.

| 66847026
| Failed to enable the atime-scrub-enabled property for the FlexCache volume because the atime-update-property is false

| 66847105
| Creating a FlexCache volume with Write Absorption mode requires an effective cluster version of 9.19.1 or later on all nodes in the origin and cache clusters.

| 66847153
| Failing to modify the -mtime-scrubber-enabled or -mtime-scrubber-threshold property requires an effective cluster version of 9.19.1 or later on all nodes in the origin and cache clusters.

| 66847149
| Failed to modify the mtime-scrubber-threshold property because the value is outside the valid range. Range is 5 to 2592000 seconds (5 seconds to 30 days).

| 66847151
| Failed to modify the mtime-scrubber-threshold property because mtime-scrubber is not enabled

| 66847155
| Failed to modify the -is-write-absorption-enabled property because -is-writeback-enabled is not enabled.

| 66847223
| Cannot create FlexCache volume because the origin volume in Vserver has the nvfail option enabled.

| 23003182
| Cannot create FlexCache volume because it is not permitted on a SVM that is configured as the destination of a SnapMirror Active Sync NAS relationship.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#aggregates]
[.api-collapsible-fifth-title]
aggregates

Aggregate


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#atime_scrub]
[.api-collapsible-fifth-title]
atime_scrub

FlexCache volume atime-based scrub


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Specifies whether scrubbing of inactive files based on atime is enabled for the FlexCache volume. When scrubbing is enabled, files whose atime is older than the specified duration are evicted from the cache volume. The scrubber runs once a day and looks for files whose atime has exceeded the provisioned value.


|period
|integer
a|Specifies the atime duration in days after which a cached file is considered inactive. Inactive files are purged from the FlexCache volumes when the scrubber runs once a day.


|===


[#cifs]
[.api-collapsible-fifth-title]
cifs

FlexCache CIFS


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Specifies whether CIFS access is enabled on the FlexCache volume.


|===


[#cifs_change_notify]
[.api-collapsible-fifth-title]
cifs_change_notify

Notifies that a change has been made to the FlexCache volume CIFS.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Specifies whether a CIFS change notification is enabled for the FlexCache volume.


|===


[#guarantee]
[.api-collapsible-fifth-title]
guarantee

[cols=3*,options=header]
|===
|Name
|Type
|Description

|type
|string
a|The type of space guarantee of this volume in the aggregate.


|===


[#mtime_scrubber]
[.api-collapsible-fifth-title]
mtime_scrubber

Flexcache Mtime Scrubber


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Indicates whether mtime-based scrubber is enabled on the FlexCache volume. The mtime scrubber automatically scrubs files from the cache based on their modification time.


|threshold
|integer
a|Specifies the mtime threshold in seconds. Files that have not been modified within this threshold duration are eligible for scrubbing from the FlexCache volume. Valid range is 900 to 86400 seconds (15 minutes to 24 hours).


|===


[#nfsv4]
[.api-collapsible-fifth-title]
nfsv4

FlexCache NFSv4


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Specifies whether NFSv4 access is enabled on the FlexCache volume.


|===


[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume. This field cannot be specified in a PATCH method.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6
* x-nullable: true


|===


[#flexcache_relationship]
[.api-collapsible-fifth-title]
flexcache_relationship

[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster[cluster]
a|

|create_time
|string
a|Creation time of the relationship.


|ip_address
|string
a|Cluster management IP of the remote cluster.


|size
|integer
a|Size of the remote volume.


|state
|string
a|Volume state


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|volume
|link:#volume[volume]
a|

|===


[#prepopulate]
[.api-collapsible-fifth-title]
prepopulate

FlexCache prepopulate


[cols=3*,options=header]
|===
|Name
|Type
|Description

|dir_paths
|array[string]
a|

|exclude_dir_paths
|array[string]
a|

|recurse
|boolean
a|Specifies whether or not the prepopulate action should search through the `dir_paths` recursively. If not set, the default value _true_ is used.


|===


[#relative_size]
[.api-collapsible-fifth-title]
relative_size

FlexCache Relative Size


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Specifies whether the relative sizing is enabled for the FlexCache volume. Relative sizing is introduced as a part of follow the origin feature. When relative sizing is enabled, it blocks any modifications done manually in the absolute size of the FlexCache volume. The size of the FlexCache volume is calculated and entered automatically based on the size of the origin volume.


|percentage
|integer
a|Specifies the percent size the FlexCache volume should have relative to the total size of the origin volume. This property is only relevant to a FlexCache volume that has the relative size property enabled.


|===


[#s3]
[.api-collapsible-fifth-title]
s3

Flexcache S3


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Indicates whether S3 access is enabled on the Flexcache volume.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

FlexCache SVM


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#write]
[.api-collapsible-fifth-title]
write

Flexcache Write settings


[cols=3*,options=header]
|===
|Name
|Type
|Description

|absorption_enabled
|boolean
a|Indicates whether Write Absorption is enabled on the FlexCache volume. Write Absorption enables the FlexCache volume to absorb writes locally and synchronize them with the origin volume.


|===


[#writeback]
[.api-collapsible-fifth-title]
writeback

FlexCache Writeback


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Indicates whether or not writeback is enabled for the FlexCache volume. Writeback is a storage method where data is first written to the FlexCache volume and then written to the origin of a FlexCache volume.


|===


[#flexcache]
[.api-collapsible-fifth-title]
flexcache

Defines the cache endpoint of FlexCache.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregates
|array[link:#aggregates[aggregates]]
a|

|atime_scrub
|link:#atime_scrub[atime_scrub]
a|FlexCache volume atime-based scrub


|cifs
|link:#cifs[cifs]
a|FlexCache CIFS


|cifs_change_notify
|link:#cifs_change_notify[cifs_change_notify]
a|Notifies that a change has been made to the FlexCache volume CIFS.


|constituents_per_aggregate
|integer
a|Number of FlexCache constituents per aggregate when the 'aggregates' field is mentioned.


|dr_cache
|boolean
a|If set to true, a DR cache is created.


|global_file_locking_enabled
|boolean
a|Specifies whether or not a FlexCache volume has global file locking mode enabled. Global file locking mode is a mode where protocol read locking semantics are enforced across all FlexCaches and origins of a FlexCache volume. When global file locking mode is enabled, the "is_disconnected_mode_off_for_locks" flag is always set to "true".


|guarantee
|link:#guarantee[guarantee]
a|

|mtime_scrubber
|link:#mtime_scrubber[mtime_scrubber]
a|Flexcache Mtime Scrubber


|name
|string
a|FlexCache name


|nfsv4
|link:#nfsv4[nfsv4]
a|FlexCache NFSv4


|origins
|array[link:#flexcache_relationship[flexcache_relationship]]
a|

|override_encryption
|boolean
a|If set to true, a plaintext FlexCache volume for an encrypted origin volume is created.


|path
|string
a|The fully-qualified path in the owning SVM's namespace at which the FlexCache is mounted. The path is case insensitive and must be unique within a SVM's namespace. Path must begin with '/' and must not end with '/'. Only one FlexCache be mounted at any given junction path.


|prepopulate
|link:#prepopulate[prepopulate]
a|FlexCache prepopulate


|relative_size
|link:#relative_size[relative_size]
a|FlexCache Relative Size


|s3
|link:#s3[s3]
a|Flexcache S3


|size
|integer
a|Physical size of the FlexCache. The recommended size for a FlexCache is 10% of the origin volume. The minimum FlexCache constituent size is 1GB.


|svm
|link:#svm[svm]
a|FlexCache SVM


|use_tiered_aggregate
|boolean
a|Specifies whether or not a Fabricpool-enabled aggregate can be used in FlexCache creation. The use_tiered_aggregate is only used when auto-provisioning a FlexCache volume.


|uuid
|string
a|FlexCache UUID. Unique identifier for the FlexCache.


|write
|link:#write[write]
a|Flexcache Write settings


|writeback
|link:#writeback[writeback]
a|FlexCache Writeback


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
