---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-support-ems-destinations.html'
summary: 'Create an event destination'
---

= Create an event destination

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/support/ems/destinations`#

*Introduced In:* 9.6

Creates an event destination.

== Required properties

* `name` - String that uniquely identifies the destination.
* `type` - Type of destination that is to be created.
* `destination` - String that identifies the destination. The contents of this property changes depending on type.

== Recommended optional properties

* `filters.name` - List of filter names that should direct to this destination.
* `certificate` - When specifying a rest api destination, a client certificate can be provided.
* `syslog` - When specifying a syslog destination, a port, transport protocol, message format, timestamp format and hostname format can be provided.

== Related ONTAP commands

* `event notification destination create`
* `event notification create`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|access_control_role
|link:#access_control_role[access_control_role]
a|Indicates the access control role that created the event destination and is used to control access to the destination based on role-based access control (RBAC) rules. If created by the 'admin' user, the field is unset.


|certificate
|link:#certificate[certificate]
a|Specifies the client-side certificate used by the ONTAP system when mutual authentication is required. This object is only applicable for *rest_api* type destinations. Both the `ca` and `serial_number` fields must be specified when configuring a certificate in a PATCH or POST request. The `name` field is read-only and cannot be used to configure a client-side certificate.

* Introduced in: 9.6


|connectivity
|link:#connectivity[connectivity]
a|

|destination
|string
a|Event destination


|filters
|array[link:#filters[filters]]
a|

|name
|string
a|Destination name.  Valid in POST.


|syslog
|link:#syslog[syslog]
a|

|system_defined
|boolean
a|Flag indicating system-defined destinations.


|type
|string
a|Type of destination. Valid in POST.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "access_control_role": {
    "name": "admin"
  },
  "certificate": {
    "ca": "VeriSign",
    "name": "string",
    "serial_number": 1234567890
  },
  "connectivity": {
    "errors": [
      {
        "message": {
          "arguments": [
            {
              "code": "string",
              "message": "string"
            }
          ],
          "code": "4",
          "message": "entry doesn't exist"
        },
        "node": {
          "name": "node1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      }
    ],
    "state": "fail"
  },
  "destination": "administrator@mycompany.com",
  "filters": [
    {
      "name": "important-events"
    }
  ],
  "name": "Admin_Email",
  "syslog": {
    "format": {
      "hostname_override": "string",
      "message": "string",
      "timestamp_override": "string"
    },
    "port": 514,
    "transport": "string"
  },
  "system_defined": 1,
  "type": "email"
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|Number of records


|records
|array[link:#records[records]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "num_records": 1,
  "records": [
    {
      "access_control_role": {
        "name": "admin"
      },
      "certificate": {
        "ca": "VeriSign",
        "name": "string",
        "serial_number": 1234567890
      },
      "connectivity": {
        "errors": [
          {
            "message": {
              "arguments": [
                {
                  "code": "string",
                  "message": "string"
                }
              ],
              "code": "4",
              "message": "entry doesn't exist"
            },
            "node": {
              "name": "node1",
              "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
            }
          }
        ],
        "state": "fail"
      },
      "destination": "administrator@mycompany.com",
      "filters": [
        {
          "name": "important-events"
        }
      ],
      "name": "Admin_Email",
      "syslog": {
        "format": {
          "hostname_override": "string",
          "message": "string",
          "timestamp_override": "string"
        },
        "port": 514,
        "transport": "string"
      },
      "system_defined": 1,
      "type": "email"
    }
  ]
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 983104
| The syslog destination provided is invalid

| 983107
| A provided filter does not exist

| 983116
| The number of notifications has reached maximum capacity

| 983117
| The number of destinations has reached maximum capacity

| 983129
| The rest-api destination provided must contain a valid scheme, such as http// or https//

| 983130
| The rest-api destination provided contains an invalid URL

| 983131
| The rest-api destination provided contains an invalid IPv6 URL

| 983144
| The security certificate information provided is incomplete. Provide the certificate and serial number

| 983145
| The rest-api destination provided has an 'http://' scheme. It is invalid to provide certificate information

| 983149
| New SNMP destinations cannot be created

| 983152
| Default destinations cannot be modified or removed

| 983153
| The security certificate provided does not exist

| 983154
| The necessary private key is not installed on the system

| 983170
| Connectivity check is not supported for the specified destination type on the node

| 983171
| Connectivity check failed for the specified destination on the node

| 983176
| Connectivity check is only supported for TCP-based syslog destinations

| 983179
| The value for the destination field cannot be empty

| 983180
| The destination name provided cannot be empty

| 983181
| The destination name provided cannot contain spaces

| 983182
| The destination name provided is invalid. The destination name must contain between 2 and 64 characters and start and end with an alphanumeric symbol or _(underscore). The allowed special characters are _(underscore) and -(hyphen)

| 983184
| A provided property cannot be configured on the requested destination type

| 983200
| Access control role compatibility issue with provided filters
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#access_control_role]
[.api-collapsible-fifth-title]
access_control_role

Indicates the access control role that created the event destination and is used to control access to the destination based on role-based access control (RBAC) rules. If created by the 'admin' user, the field is unset.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Role name


|===


[#certificate]
[.api-collapsible-fifth-title]
certificate

Specifies the client-side certificate used by the ONTAP system when mutual authentication is required. This object is only applicable for *rest_api* type destinations. Both the `ca` and `serial_number` fields must be specified when configuring a certificate in a PATCH or POST request. The `name` field is read-only and cannot be used to configure a client-side certificate.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|ca
|string
a|Client certificate issuing CA


|name
|string
a|Certificate name


|serial_number
|string
a|Client certificate serial number


|===


[#arguments]
[.api-collapsible-fifth-title]
arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#message]
[.api-collapsible-fifth-title]
message

Information to be displayed to the user.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#arguments[arguments]]
a|Message arguments


|code
|string
a|Unique message code.


|message
|string
a|User message.


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#errors]
[.api-collapsible-fifth-title]
errors

Error object included in the event of connectivity failure.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|message
|link:#message[message]
a|Information to be displayed to the user.


|node
|link:#node[node]
a|

|===


[#connectivity]
[.api-collapsible-fifth-title]
connectivity

[cols=3*,options=header]
|===
|Name
|Type
|Description

|errors
|array[link:#errors[errors]]
a|A list of errors encountered during connectivity checks.


|state
|string
a|Current connectivity state.


|===


[#filters]
[.api-collapsible-fifth-title]
filters

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|===


[#format]
[.api-collapsible-fifth-title]
format

[cols=3*,options=header]
|===
|Name
|Type
|Description

|hostname_override
|string
a|Syslog Hostname Format Override. The supported hostname formats are no_override (hostname format based on the syslog.format.message property i.e. fqdn if syslog.format.message is rfc_5424, hostname_only if syslog.format.message is legacy_netapp), fqdn (Fully Qualified Domain Name) and hostname_only.


|message
|string
a|Syslog Message Format. The supported message formats are legacy_netapp (format: <PRIVAL>TIMESTAMP [HOSTNAME:Event-name:Event-severity]: MSG) and rfc_5424 (format: <PRIVAL>VERSION TIMESTAMP HOSTNAME Event-source - Event-name - MSG).


|timestamp_override
|string
a|Syslog Timestamp Format Override. The supported timestamp formats are no_override (timestamp format based on the syslog.format.message property i.e. rfc_3164 if syslog.format.message is legacy_netapp, iso_8601_local_time if syslog.format.message is rfc_5424), rfc_3164 (format: Mmm dd hh:mm:ss), iso_8601_local_time (format: YYYY-MM-DDThh:mm:ss+/-hh:mm) and iso_8601_utc (format: YYYY-MM-DDThh:mm:ssZ).


|===


[#syslog]
[.api-collapsible-fifth-title]
syslog

[cols=3*,options=header]
|===
|Name
|Type
|Description

|format
|link:#format[format]
a|

|port
|integer
a|Syslog Port.


|transport
|string
a|Syslog Transport Protocol.


|===


[#ems_destination]
[.api-collapsible-fifth-title]
ems_destination

[cols=3*,options=header]
|===
|Name
|Type
|Description

|access_control_role
|link:#access_control_role[access_control_role]
a|Indicates the access control role that created the event destination and is used to control access to the destination based on role-based access control (RBAC) rules. If created by the 'admin' user, the field is unset.


|certificate
|link:#certificate[certificate]
a|Specifies the client-side certificate used by the ONTAP system when mutual authentication is required. This object is only applicable for *rest_api* type destinations. Both the `ca` and `serial_number` fields must be specified when configuring a certificate in a PATCH or POST request. The `name` field is read-only and cannot be used to configure a client-side certificate.

* Introduced in: 9.6


|connectivity
|link:#connectivity[connectivity]
a|

|destination
|string
a|Event destination


|filters
|array[link:#filters[filters]]
a|

|name
|string
a|Destination name.  Valid in POST.


|syslog
|link:#syslog[syslog]
a|

|system_defined
|boolean
a|Flag indicating system-defined destinations.


|type
|string
a|Type of destination. Valid in POST.


|===


[#records]
[.api-collapsible-fifth-title]
records

[cols=3*,options=header]
|===
|Name
|Type
|Description

|access_control_role
|link:#access_control_role[access_control_role]
a|Indicates the access control role that created the event destination and is used to control access to the destination based on role-based access control (RBAC) rules. If created by the 'admin' user, the field is unset.


|certificate
|link:#certificate[certificate]
a|Specifies the client-side certificate used by the ONTAP system when mutual authentication is required. This object is only applicable for *rest_api* type destinations. Both the `ca` and `serial_number` fields must be specified when configuring a certificate in a PATCH or POST request. The `name` field is read-only and cannot be used to configure a client-side certificate.

* Introduced in: 9.6


|connectivity
|link:#connectivity[connectivity]
a|

|destination
|string
a|Event destination


|filters
|array[link:#filters[filters]]
a|

|name
|string
a|Destination name.  Valid in POST.


|syslog
|link:#syslog[syslog]
a|

|system_defined
|boolean
a|Flag indicating system-defined destinations.


|type
|string
a|Type of destination. Valid in POST.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
