---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-storage-snaplock-litigations-operations.html'
summary: 'Create or remove litigations for a path'
---

= Create or remove litigations for a path

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/storage/snaplock/litigations/{litigation.id}/operations`#

*Introduced In:* 9.7

Creates or removes litigations for the specified path.

== Required properties

* `type` - Legal-Hold operation type.
* `path` - Litigation path.

== Related ONTAP commands

* `snaplock legal-hold begin`
* `snaplock legal-hold end`

== Learn more

* link:storage_snaplock_litigations_litigation.id_operations_endpoint_overview.html[DOC /storage/snaplock/litigations/{litigation.id}/operations]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|litigation.id
|string
|path
|True
a|Litigation ID


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|integer
a|Operation ID.


|num_files_failed
|string
a|Specifies the number of files on which legal-hold operation failed.


|num_files_processed
|string
a|Specifies the number of files on which legal-hold operation was successful.


|num_files_skipped
|string
a|Specifies the number of files on which legal-hold begin operation was skipped. The legal-hold begin operation is skipped on a file if it is already under hold for a given litigation.


|num_inodes_ignored
|string
a|Specifies the number of inodes on which the legal-hold operation was not attempted because they were not regular files.


|path
|string
a|Specifies the path on which legal-hold operation is applied.


|state
|string
a|Specifies the status of legal-hold operation.


|type
|string
a|Specifies the type of legal-hold operation.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "id": 16842759,
  "num_files_failed": 0,
  "num_files_processed": 30,
  "num_files_skipped": 10,
  "num_inodes_ignored": 10,
  "path": "/dir1",
  "state": "completed",
  "type": "begin"
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|integer
a|Operation ID.


|num_files_failed
|string
a|Specifies the number of files on which legal-hold operation failed.


|num_files_processed
|string
a|Specifies the number of files on which legal-hold operation was successful.


|num_files_skipped
|string
a|Specifies the number of files on which legal-hold begin operation was skipped. The legal-hold begin operation is skipped on a file if it is already under hold for a given litigation.


|num_inodes_ignored
|string
a|Specifies the number of inodes on which the legal-hold operation was not attempted because they were not regular files.


|path
|string
a|Specifies the path on which legal-hold operation is applied.


|state
|string
a|Specifies the status of legal-hold operation.


|type
|string
a|Specifies the type of legal-hold operation.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "id": 16842759,
  "num_files_failed": 0,
  "num_files_processed": 30,
  "num_files_skipped": 10,
  "num_inodes_ignored": 10,
  "path": "/dir1",
  "state": "completed",
  "type": "begin"
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 13763280
| Only a user with security login role "vsadmin-snaplock" is allowed to perform this operation.

| 14090343
| Invalid Field

| 14090346
| Internal Error. Wait a few minutes, then try the command again
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#snaplock_legal_hold_operation]
[.api-collapsible-fifth-title]
snaplock_legal_hold_operation

[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|integer
a|Operation ID.


|num_files_failed
|string
a|Specifies the number of files on which legal-hold operation failed.


|num_files_processed
|string
a|Specifies the number of files on which legal-hold operation was successful.


|num_files_skipped
|string
a|Specifies the number of files on which legal-hold begin operation was skipped. The legal-hold begin operation is skipped on a file if it is already under hold for a given litigation.


|num_inodes_ignored
|string
a|Specifies the number of inodes on which the legal-hold operation was not attempted because they were not regular files.


|path
|string
a|Specifies the path on which legal-hold operation is applied.


|state
|string
a|Specifies the status of legal-hold operation.


|type
|string
a|Specifies the type of legal-hold operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
