---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-security-multi-admin-verify-rules.html'
summary: 'Create a multi-admin-verify rule'
---

= Create a multi-admin-verify rule

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/security/multi-admin-verify/rules`#

*Introduced In:* 9.11

Creates a multi-admin-verify rule.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|approval_expiry
|string
a|Time for requests to be approved, in ISO-8601 duration format. If not set, the global setting is used.


|approval_groups
|array[link:#approval_groups[approval_groups]]
a|List of approval groups that are allowed to approve requests for rules that don't have approval groups.


|auto_request_create
|boolean
a|When true, ONTAP automatically creates a request for any failed operation where there is no matching pending request.

* Default value: 1
* Introduced in: 9.11
* x-nullable: true


|create_time
|string
a|

|execution_expiry
|string
a|Time for requests to be executed once approved, in ISO-8601 duration format. If not set, the global setting is used.


|operation
|string
a|Command that requires one or more approvals.


|owner
|link:#owner[owner]
a|The owner of the rule. The only valid owner is currently the cluster.


|query
|string
a|When specified, this property limits the entries that require approvals to those that match the specified query.


|required_approvers
|integer
a|The number of required approvers, excluding the user that made the request.


|system_defined
|boolean
a|Specifies whether the rule is system-defined or user-defined.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "approval_expiry": "string",
  "approval_groups": [
    {
      "name": "string"
    }
  ],
  "create_time": "string",
  "execution_expiry": "string",
  "operation": "string",
  "owner": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "query": "string"
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|Number of records


|records
|array[link:#multi_admin_verify_rule[multi_admin_verify_rule]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "num_records": 1,
  "records": [
    {
      "approval_expiry": "string",
      "approval_groups": [
        {
          "name": "string"
        }
      ],
      "create_time": "string",
      "execution_expiry": "string",
      "operation": "string",
      "owner": {
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "query": "string"
    }
  ]
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 262148
| The specified command is not recognized.

| 262308
| The specified command is not supported by this feature.

| 262309
| The feature must be enabled first.

| 262311
| Value must be greater than zero.

| 262312
| Number of required approvers must be less than the total number of unique approvers in the approval-groups.

| 262313
| Number of unique approvers in the approval-groups must be greater than the number of required approvers.

| 262314
| Some approval-groups were not found.

| 262316
| Value must be in the range two minutes to two weeks.

| 262326
| Failed to parse query.

| 262335
| The query string must be contained in either the "operation" or "query" parameters but not in both.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#approval_groups]
[.api-collapsible-fifth-title]
approval_groups

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the approval group.


|===


[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#owner]
[.api-collapsible-fifth-title]
owner

The owner of the rule. The only valid owner is currently the cluster.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a POST or PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#multi_admin_verify_rule]
[.api-collapsible-fifth-title]
multi_admin_verify_rule

[cols=3*,options=header]
|===
|Name
|Type
|Description

|approval_expiry
|string
a|Time for requests to be approved, in ISO-8601 duration format. If not set, the global setting is used.


|approval_groups
|array[link:#approval_groups[approval_groups]]
a|List of approval groups that are allowed to approve requests for rules that don't have approval groups.


|auto_request_create
|boolean
a|When true, ONTAP automatically creates a request for any failed operation where there is no matching pending request.

* Default value: 1
* Introduced in: 9.11
* x-nullable: true


|create_time
|string
a|

|execution_expiry
|string
a|Time for requests to be executed once approved, in ISO-8601 duration format. If not set, the global setting is used.


|operation
|string
a|Command that requires one or more approvals.


|owner
|link:#owner[owner]
a|The owner of the rule. The only valid owner is currently the cluster.


|query
|string
a|When specified, this property limits the entries that require approvals to those that match the specified query.


|required_approvers
|integer
a|The number of required approvers, excluding the user that made the request.


|system_defined
|boolean
a|Specifies whether the rule is system-defined or user-defined.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
