---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-security-roles--privileges.html'
summary: 'Add a privilege tuple to an existing role'
---

= Add a privilege tuple to an existing role

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/security/roles/{owner.uuid}/{name}/privileges`#

*Introduced In:* 9.6

Adds a privilege tuple (of REST URI or command/command directory path, its access level and an optional query, if the "path" refers to a command/command directory path) to an existing role or creates a new role with the provided tuple.

== Required parameters

* `owner.uuid` - UUID of the SVM that houses this role.
* `name` - Name of the role to be updated.
* `path` - REST URI path (example: _/api/storage/volumes_) or command/command directory path (example: _snaplock compliance-clock_). Can be a resource-qualified endpoint (example: _/api/storage/volumes/43256a71-be02-474d-a2a9-9642e12a6a2c/snapshots_). Currently, resource-qualified endpoints are limited to the following&#58;

== Snapshots APIs

&ndash; _/api/storage/volumes/{volume.uuid}/snapshots_

== File System Analytics APIs

&ndash; _/api/storage/volumes/{volume.uuid}/files_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/clients_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/directories_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/files_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/users_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/clients_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/directories_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/files_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/users_

== Artificial Intelligence Data Engine (AIDE) APIs

== Data Compute Node (DCN) APIs

&ndash; _/api/dcn/cluster/nodes/{node.uuid}/metrics_

&ndash; _/api/dcn/network/ports/{port.uuid}/metrics_

== Data-Engine APIs

&ndash; _/api/data-engine/policies/{policy.uuid}/versions_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/acls_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections/{datacollection.uuid}/acls_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections/{entity.uuid}/entities_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections/{datacollection.uuid}/search_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections/{datacollection.uuid}/versions_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections/{datacollection.uuid}/versions/{version.uuid}/diffs_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-sources_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/entities_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/entities/{entity.uuid}/custom-attributes_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/queries_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/queries/{query.uuid}/entities_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/versions_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/versions/{version.uuid}/diffs_

When used in the context of data collection APIs, _{version.uuid}_ refers to a data collection version. In the context of workspace APIs, it refers to a workspace version.

In the APIs above, and in the context of REST roles, the wildcard character &#42; can be used in place of _{volume.uuid}_ or _{svm.uuid}_ to represent _all_ volumes or _all_ SVMs, depending on whether the REST endpoint references volumes or SVMs. The _{volume.uuid}_ corresponds to the _-instance-uuid_ field in the output of the "volume show" command at the diagnostic privilege level. It can also be retrieved through the REST endpoint _/api/storage/volumes_.

In the AIDE APIs described above, and in the context of REST roles, the wildcard character &#42; can be used in place of variable components in the Uniform Resource Identifier (URI) path, such as _{node.uuid}_, _{port.uuid}_, _{policy.uuid}_, _{workspace.uuid}_, _{datacollection.uuid}_, _{entity.uuid}_, _{version.uuid}_, or _{query.uuid}_. The specific variable to be replaced depends on whether the REST endpoint references nodes, ports, policies, workspaces, data collections, entities, versions, or queries.

However, when using the wildcard character &#42; in place of a variable component in a URI path, it must replace

*all* variable components in that path. Mixing wildcards and specific values for different variable components within the same URI path is not supported in REST roles. For example, a URI path such as _/api/data-engine/workspaces/c6e1b325-4125-11f0-abb5-bc2411f6fd43/data-collections/*/search_ is not supported.

In summary, only the following two types of resource-qualified endpoints are supported in a REST role:

* All variable components in the URI path are specific values. Example: _/api/data-engine/workspaces/c6e1b325-4125-11f0-abb5-bc2411f6fd43/data-collections/b09b6d25-4126-11f0-abb5-bc2411f6fd43/search_
* All variable components in the URI path are wildcards. Example: _/api/data-engine/workspaces/*/data-collections/*/search_

AIDE APIs are supported only in cluster-scoped REST roles, not in SVM-scoped REST roles.

* `access` - Desired access level for the REST URI path or command/command directory.

== Related ONTAP commands

* `security login rest-role create`
* `security login role create`

== Learn more

* link:security_roles_owner.uuid_name_privileges_endpoint_overview.html[DOC /security/roles/{owner.uuid}/\{name}/privileges]
* link:security_roles_endpoint_overview.html[DOC /security/roles]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|owner.uuid
|string
|path
|True
a|Role owner UUID


|name
|string
|path
|True
a|Role name


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|access
|string
a|Access level for the REST endpoint or command/command directory path. If it denotes the access level for a command/command directory path, the only supported enum values are 'none','readonly' and 'all'.


|path
|string
a|Either of REST URI/endpoint OR command/command directory path.


|query
|string
a|Optional attribute that can be specified only if the "path" attribute refers to a command/command directory path. The privilege tuple implicitly defines a set of objects the role can or cannot access at the specified access level. The query further reduces this set of objects to a subset of objects that the role is allowed to access. The query attribute must be applicable to the command/command directory specified by the "path" attribute. It is defined using one or more parameters of the command/command directory path specified by the "path" attribute.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "access": "all",
  "path": "volume move start",
  "query": "-vserver vs1|vs2|vs3 -destination-aggregate aggr1|aggr2"
}
====

== Response

```
Status: 201, Created
```

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 1263347
| Cannot modify pre-defined roles.

| 5636129
| A role with given name has not been defined.

| 5636143
| A Vserver admin cannot use the API with this access level.

| 5636144
| The value specified for the access level is not valid.

| 5636168
| This role is mapped to a REST role and can only be modified by updating the REST role.

| 5636169
| A character in the URI is not valid.

| 5636170
| The URI does not exist.

| 5636173
| This feature requires an effective cluster version of 9.6 or later.

| 5636175
| Vserver admin cannot have access to given API.

| 5636184
| The expanded REST roles for granular resource control feature is currently disabled.

| 5636185
| The specified UUID was not found.

| 5636186
| Expanded REST roles for granular resource control requires an effective cluster version of 9.10.1 or later.

| 5636192
| The query parameter cannot be specified for the privileges tuple with API endpoint entries.

| 5636200
| The specified value of the access parameter is invalid, if a command or command directory is specified in the path parameter.

| 5636259
| The specified child AIDE object was not found within the specified parent AIDE object.

| 5636261
| The specified grandchild AIDE object was not found within the specified child AIDE object that belongs to the specified parent AIDE object.

| 5636262
| Cannot create a role with the specified role name because it is reserved by the system.

| 13434890
| Vserver-ID failed for Vserver roles.

| 13434891
| UUID LookUp failed for Vserver roles.

| 13434892
| Roles is a required field.

| 13434893
| The SVM does not exist.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#role_privilege]
[.api-collapsible-fifth-title]
role_privilege

A tuple containing a REST endpoint or a command/command directory path and the access level assigned to that endpoint or command/command directory. If the "path" attribute refers to a command/command directory path, the tuple could additionally contain an optional query. The REST endpoint can be a resource-qualified endpoint. At present, the only supported resource-qualified endpoints are the following

Snapshots APIs

* _/api/storage/volumes/{volume.uuid}/snapshots_

File System Analytics APIs

* _/api/storage/volumes/{volume.uuid}/files_
* _/api/storage/volumes/{volume.uuid}/top-metrics/clients_
* _/api/storage/volumes/{volume.uuid}/top-metrics/directories_
* _/api/storage/volumes/{volume.uuid}/top-metrics/files_
* _/api/storage/volumes/{volume.uuid}/top-metrics/users_
* _/api/svm/svms/{svm.uuid}/top-metrics/clients_
* _/api/svm/svms/{svm.uuid}/top-metrics/directories_
* _/api/svm/svms/{svm.uuid}/top-metrics/files_
* _/api/svm/svms/{svm.uuid}/top-metrics/users_
* _/api/protocols/s3/services/{svm.uuid}/users_

In the above APIs, wildcard character * could be used in place of _{volume.uuid}_ or _{svm.uuid}_ to denote _all_ volumes or _all_ SVMs, depending upon whether the REST endpoint references volumes or SVMs. The _{volume.uuid}_ refers to the _-instance-uuid_ field value in the "volume show" command output at diagnostic privilege level. It can also be fetched through REST endpoint _/api/storage/volumes_.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|access
|string
a|Access level for the REST endpoint or command/command directory path. If it denotes the access level for a command/command directory path, the only supported enum values are 'none','readonly' and 'all'.


|path
|string
a|Either of REST URI/endpoint OR command/command directory path.


|query
|string
a|Optional attribute that can be specified only if the "path" attribute refers to a command/command directory path. The privilege tuple implicitly defines a set of objects the role can or cannot access at the specified access level. The query further reduces this set of objects to a subset of objects that the role is allowed to access. The query attribute must be applicable to the command/command directory specified by the "path" attribute. It is defined using one or more parameters of the command/command directory path specified by the "path" attribute.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
