---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-support-snmp-traphosts.html'
summary: 'Create SNMP traphosts'
---

= Create SNMP traphosts

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/support/snmp/traphosts`#

*Introduced In:* 9.7

Creates SNMP traphosts. While adding an SNMPv3 traphost, an SNMPv3 user configured in ONTAP must be specified. ONTAP uses this user's credentials to authenticate and/or encrypt traps sent to this SNMPv3 traphost. While adding an SNMPv1/SNMPv2c traphost, SNMPv1/SNMPv2c user or community need not be specified.

== Required properties

* `host` - Fully Qualified Domain Name (FQDN), IPv4 address or IPv6 address of SNMP traphost.

== Recommended optional properties

* If `host` refers to an SNMPv3 traphost, the following field is required:

*** `user` - SNMPv3 or User-based Security Model (USM) user.

* For an SNMPv1/SNMPv2c traphost, ONTAP automatically uses 'public' if 'public' is configured or no community is configured. Otherwise, ONTAP uses the first configured community.

== Related ONTAP commands

* `system snmp traphost add`

== Learn more

* link:support_snmp_traphosts_endpoint_overview.html[DOC /support/snmp/traphosts]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|host
|string
a|Fully qualified domain name (FQDN), IPv4 address or IPv6 address of SNMP traphost.


|user
|link:#user[user]
a|Optional SNMP user parameter. For an SNMPv3 traphost, this property refers to an SNMPv3 or User-based Security Model (USM) user. For an SNMPv1 or SNMPv2c traphost, this property refers to an SNMP community.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "host": "traphost.example.com",
  "user": {
    "name": "snmpv3user3"
  }
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|Number of records.


|records
|array[link:#snmp_traphost[snmp_traphost]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "num_records": 1,
  "records": [
    {
      "host": "traphost.example.com",
      "user": {
        "name": "snmpv3user3"
      }
    }
  ]
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 8847365
| Unknown host.

| 9043969
| Duplicate traphost entry.

| 9043980
| IPv6 support is disabled.

| 9043991
| Not a USM user.

| 9043993
| Current cluster version does not support SNMPv3 traps.

| 9044001
| Failed to create SNMPv1 traphost.

| 9044002
| Failed to create SNMPv3 traphost.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#user]
[.api-collapsible-fifth-title]
user

Optional SNMP user parameter. For an SNMPv3 traphost, this property refers to an SNMPv3 or User-based Security Model (USM) user. For an SNMPv1 or SNMPv2c traphost, this property refers to an SNMP community.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Optional SNMPv1/SNMPv2c or SNMPv3 user name. For an SNMPv3 traphost, this object refers to an SNMPv3 or User-based Security Model (USM) user. For an SNMPv1 or SNMPv2c traphost, this object refers to an SNMP community. For an SNMPv3 traphost, this object is mandatory and refers to an SNMPv3 or User-based Security Model (USM) user. For an SNMPv1 or SNMPv2c traphost, ONTAP automatically uses "public", if the same is configured, or any other configured community as user. So, for an SNMPv1 or SNMPv2c traphost, this property should not be provided in the "POST" method. However, the configured community for the SNMPv1/SNMPv2c traphost is returned by the "GET" method.

* example: snmpv3user3
* Introduced in: 9.7
* x-nullable: true


|===


[#snmp_traphost]
[.api-collapsible-fifth-title]
snmp_traphost

SNMP manager or host machine that receives SNMP traps from ONTAP.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|host
|string
a|Fully qualified domain name (FQDN), IPv4 address or IPv6 address of SNMP traphost.


|user
|link:#user[user]
a|Optional SNMP user parameter. For an SNMPv3 traphost, this property refers to an SNMPv3 or User-based Security Model (USM) user. For an SNMPv1 or SNMPv2c traphost, this property refers to an SNMP community.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
