---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-storage-quota-rules.html'
summary: 'Create a quota policy rule for a FlexVol or a FlexGroup volume'
---

= Create a quota policy rule for a FlexVol or a FlexGroup volume

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/storage/quota/rules`#

*Introduced In:* 9.6

Creates a quota policy rule for a FlexVol or a FlexGroup volume.

Important notes:

* Unlike CLI/ONTAPI, the `quota policy` input is not needed for POST.

== Required properties

* `svm.uuid` or `svm.name` - Existing SVM in which to create the qtree.
* `volume.uuid` or `volume.name` - Existing volume in which to create the qtree.
* `type` - Quota type for the rule. This type can be `user`, `group`, or `tree`.
* `users.name` or `user.id` -  If the quota type is user, this property takes the user name or user ID. For default user quota rules, the user name must be specified as "".
* `group.name` or `group.id` - If the quota type is group, this property takes the group name or group ID. For default group quota rules, the group name must be specified as "".
* `qtree.name` - Qtree for which to create the rule. For default tree rules, the qtree name must be specified as "".

== Recommended optional properties

* `space.hard_limit` - Specifies the space hard limit, in bytes. If less than 1024 bytes, the value is rounded up to 1024 bytes.
* `space.soft_limit` - Specifies the space soft limit, in bytes. If less than 1024 bytes, the value is rounded up to 1024 bytes.
* `files.hard_limit` - Specifies the hard limit for files.
* `files.soft_limit` - Specifies the soft limit for files.
* `user_mapping` - Specifies the user_mapping. This property is valid only for quota policy rules of type `user`.

== Related ONTAP commands

* `quota policy rule create`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|files
|link:#files[files]
a|

|group
|link:#group[group]
a|This parameter specifies the target group to which the group quota policy rule applies. This parameter takes a group name or identifier. This parameter is only valid for the POST operation of a group quota policy rule. The POST operation will fail with an appropriate error if this parameter is used as an input to create a user or a tree quota policy rule. This input parameter for POST takes either a group name or a group identifier, but not both. For default quota rules, the group name must be chosen and should be specified as "". For explicit group quota rules, this parameter can contain a UNIX group name or a UNIX group identifier.


|qtree
|link:#qtree[qtree]
a|This parameter specifies the target qtree to which the user/group/tree quota policy rule applies. For a user/group quota policy rule at qtree level, this parameter takes a qtree name and is valid in GET or POST. For a user/group quota policy rule at volume level, this parameter is not valid in GET or POST. For a tree quota policy rule, this parameter is mandatory and is valid in both POST and GET. For a default tree quota policy rule, this parameter needs to be specified as "". For a tree quota policy rule at qtree level, this parameter takes a qtree name and is valid in GET or POST.


|space
|link:#space[space]
a|

|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|type
|string
a|This parameter specifies the quota policy rule type. This is required in POST only and can take either one of the "user", "group" or "tree" values.


|user_mapping
|boolean
a|This parameter enables user mapping for user quota policy rules. This is valid in POST or PATCH for user quota policy rules only.


|users
|array[link:#users[users]]
a|This parameter specifies the target user to which the user quota policy rule applies. This parameter takes single or multiple user names or identifiers. This parameter is valid only for the POST operation of a user quota policy rule. If this parameter is used as an input to create a group or a tree quota policy rule, the POST operation will fail with an appropriate error. For POST, this input parameter takes either a user name or a user identifier, not both. For default quota rules, the user name must be chosen and specified as "". For explicit user quota rules, this parameter can indicate either a user name or user identifier. The user name can be a UNIX user name or a Windows user name. If a name contains a space, enclose the entire value in quotes. A UNIX user name cannot include a backslash () or an @ sign; user names with these characters are treated as Windows names. The user identifier can be a UNIX user identifier or a Windows security identifier. For multi-user quota, this parameter can contain multiple user targets separated by a comma.


|uuid
|string
a|Unique identifier for the quota policy rule. This field is generated when the quota policy rule is created.


|volume
|link:#volume[volume]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "group": {
    "id": "string",
    "name": "string"
  },
  "qtree": {
    "id": 1,
    "name": "qt1"
  },
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "type": "string",
  "users": [
    {
      "id": "string",
      "name": "string"
    }
  ],
  "uuid": "5f1d13a7-f401-11e8-ac1a-005056a7c3b9",
  "volume": {
    "name": "volume1",
    "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
  }
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

=== Headers

[cols=3*,options=header]
|===
//header
|Name
|Description
|Type
//end header

//start row
|Location
|Useful for tracking the resource location
|string
//end row
//end table
|=== 

== Response

```
Status: 201, Created
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 917927
| The specified volume was not found.

| 918232
| Either `volume.name` or `volume.uuid` must be provided.

| 918236
| The specified `volume.uuid` and `volume.name` refer to different volumes.

| 2621462
| The specified SVM does not exist.

| 2621706
| The specified `svm.uuid` and `svm.name` do not refer to the same SVM.

| 2621707
| No SVM was specified. Either `svm.name` or `svm.uuid` must be supplied.

| 5308469
| User mapping can be specified only for a user quota rule.

| 5308496
| The specified user name was not found.

| 5308501
| Mapping from Windows user to UNIX user for user rule was unsuccessful.

| 5308502
| Mapping from UNIX user to Windows user for user rule was unsuccessful.

| 5308552
| Failed to get default quota policy name for SVM.

| 5308561
| Failed to obtain volume quota state or invalid quota state obtained for volume.

| 5308562
| users is a required input for creating a user rule and group is not allowed.

| 5308563
| group is a required input for creating a group rule and users is not allowed.

| 5308564
| qtree.name is a required input for creating a tree rule and users and group are not allowed.

| 5308565
| Only one of name or id is allowed for each entry in the users array.

| 5308566
| Only one of name or id is allowed for group.

| 5308568
| Quota policy rule create operation succeeded, but quota resize failed due to internal error. To activate the rule, disable and enable quotas for this volume.

| 5308571
| Quota policy rule create operation succeeded, but quota resize is skipped. To activate the rule, disable and enable quotas for this volume.

| 5308573
| Input value is greater than limit for field.

| 5308574
| Input value is out of range for field.

| 5308575
| Input value is incorrectly larger than listed field.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#files]
[.api-collapsible-fifth-title]
files

[cols=3*,options=header]
|===
|Name
|Type
|Description

|hard_limit
|integer
a|This parameter specifies the hard limit for files. This is valid in POST or PATCH.


|soft_limit
|integer
a|This parameter specifies the soft limit for files. This is valid in POST or PATCH.


|===


[#group]
[.api-collapsible-fifth-title]
group

This parameter specifies the target group to which the group quota policy rule applies. This parameter takes a group name or identifier. This parameter is only valid for the POST operation of a group quota policy rule. The POST operation will fail with an appropriate error if this parameter is used as an input to create a user or a tree quota policy rule. This input parameter for POST takes either a group name or a group identifier, but not both. For default quota rules, the group name must be chosen and should be specified as "". For explicit group quota rules, this parameter can contain a UNIX group name or a UNIX group identifier.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|string
a|Quota target group ID


|name
|string
a|Quota target group name


|===


[#qtree]
[.api-collapsible-fifth-title]
qtree

This parameter specifies the target qtree to which the user/group/tree quota policy rule applies. For a user/group quota policy rule at qtree level, this parameter takes a qtree name and is valid in GET or POST. For a user/group quota policy rule at volume level, this parameter is not valid in GET or POST. For a tree quota policy rule, this parameter is mandatory and is valid in both POST and GET. For a default tree quota policy rule, this parameter needs to be specified as "". For a tree quota policy rule at qtree level, this parameter takes a qtree name and is valid in GET or POST.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|integer
a|The unique identifier for a qtree.


|name
|string
a|The name of the qtree.


|===


[#space]
[.api-collapsible-fifth-title]
space

[cols=3*,options=header]
|===
|Name
|Type
|Description

|hard_limit
|integer
a|This parameter specifies the space hard limit, in bytes. If less than 1024 bytes, the value is rounded up to 1024 bytes. Valid in POST or PATCH. For a POST operation where the parameter is either empty or set to -1, no limit is applied. For a PATCH operation where a limit is configured, use a value of -1 to clear the limit.


|soft_limit
|integer
a|This parameter specifies the space soft limit, in bytes. If less than 1024 bytes, the value is rounded up to 1024 bytes. Valid in POST or PATCH. For a POST operation where the parameter is either empty or set to -1, no limit is applied. For a PATCH operation where a limit is configured, use a value of -1 to clear the limit.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#users]
[.api-collapsible-fifth-title]
users

[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|string
a|Quota target user ID


|name
|string
a|Quota target user name


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume. This field cannot be specified in a PATCH method.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6
* x-nullable: true


|===


[#quota_rule]
[.api-collapsible-fifth-title]
quota_rule

[cols=3*,options=header]
|===
|Name
|Type
|Description

|files
|link:#files[files]
a|

|group
|link:#group[group]
a|This parameter specifies the target group to which the group quota policy rule applies. This parameter takes a group name or identifier. This parameter is only valid for the POST operation of a group quota policy rule. The POST operation will fail with an appropriate error if this parameter is used as an input to create a user or a tree quota policy rule. This input parameter for POST takes either a group name or a group identifier, but not both. For default quota rules, the group name must be chosen and should be specified as "". For explicit group quota rules, this parameter can contain a UNIX group name or a UNIX group identifier.


|qtree
|link:#qtree[qtree]
a|This parameter specifies the target qtree to which the user/group/tree quota policy rule applies. For a user/group quota policy rule at qtree level, this parameter takes a qtree name and is valid in GET or POST. For a user/group quota policy rule at volume level, this parameter is not valid in GET or POST. For a tree quota policy rule, this parameter is mandatory and is valid in both POST and GET. For a default tree quota policy rule, this parameter needs to be specified as "". For a tree quota policy rule at qtree level, this parameter takes a qtree name and is valid in GET or POST.


|space
|link:#space[space]
a|

|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|type
|string
a|This parameter specifies the quota policy rule type. This is required in POST only and can take either one of the "user", "group" or "tree" values.


|user_mapping
|boolean
a|This parameter enables user mapping for user quota policy rules. This is valid in POST or PATCH for user quota policy rules only.


|users
|array[link:#users[users]]
a|This parameter specifies the target user to which the user quota policy rule applies. This parameter takes single or multiple user names or identifiers. This parameter is valid only for the POST operation of a user quota policy rule. If this parameter is used as an input to create a group or a tree quota policy rule, the POST operation will fail with an appropriate error. For POST, this input parameter takes either a user name or a user identifier, not both. For default quota rules, the user name must be chosen and specified as "". For explicit user quota rules, this parameter can indicate either a user name or user identifier. The user name can be a UNIX user name or a Windows user name. If a name contains a space, enclose the entire value in quotes. A UNIX user name cannot include a backslash () or an @ sign; user names with these characters are treated as Windows names. The user identifier can be a UNIX user identifier or a Windows security identifier. For multi-user quota, this parameter can contain multiple user targets separated by a comma.


|uuid
|string
a|Unique identifier for the quota policy rule. This field is generated when the quota policy rule is created.


|volume
|link:#volume[volume]
a|

|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
