---
sidebar: sidebar
api: true
explorer: false
permalink: 'protocols_fpolicy_svm.uuid_engines_endpoint_overview.html'
summary: 'Manage FPolicy engine configuration'
---

= Manage FPolicy engine configuration



== Overview

The FPolicy engine allows you to configure the external servers to which the file access notifications are sent. As part of FPolicy engine configuration, you can configure a server or servers to which the notification is sent, an optional set of secondary servers (one or more) to which the notification is sent if the primary servers fail, the port number for FPolicy application, the type of the engine, which is either synchronous or asynchronous, and the format of the notifications, which is either XML or protobuf.

For the synchronous engine, ONTAP will wait for a response from the FPolicy application before it allows the operation. With an asynchronous engine, ONTAP proceeds with the operation processing after sending the notification to the FPolicy application. An engine can belong to multiple FPolicy policies. If the format is not specified, the default format, xml, is configured.

== Examples

=== Creating an FPolicy engine

'''

----

# The API:
POST /protocols/fpolicy/{svm.uuid}/engines

#The call:
curl -X POST "https://<mgmt-ip>/api/protocols/fpolicy/4f643fb4-fd21-11e8-ae49-0050568e2c1e/engines/" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"name\": \"engine0\", \"port\": 9876, \"primary_servers\": [ \"10.132.145.22\", \"10.140.101.109\" ], \"secondary_servers\": [ \"10.132.145.20\", \"10.132.145.21\" ], \"type\": \"synchronous\", \"format\": \"xml\", \"request_abort_timeout\": \"PT3M\", \"request_cancel_timeout\": \"PT29S\",  \"server_progress_timeout\": \"PT1M\",  \"status_request_interval\": \"PT23S\", \"keep_alive_interval\": \"PT2M\", \"session_timeout\": \"PT10S\", \"max_connection_retries\": 5 }"

# The response:
{
"num_records": 1,
"records": [
  {
    "name": "engine0",
    "primary_servers": [
      "10.132.145.22",
      "10.140.101.109"
    ],
    "secondary_servers": [
      "10.132.145.20",
      "10.132.145.21"
    ],
    "port": 9876,
    "type": "synchronous",
    "format": "xml"
  }
]
}
----

'''

=== Creating an FPolicy engine with the minimum required fields

'''

----

# The API:
POST /protocols/fpolicy/{svm.uuid}/engines

#The call:
curl -X POST "https://<mgmt-ip>/api/protocols/fpolicy/4f643fb4-fd21-11e8-ae49-0050568e2c1e/engines/" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"name\": \"engine0\", \"port\": 9876, \"primary_servers\": [ \"10.132.145.22\", \"10.140.101.109\" ], \"type\": \"synchronous\"}"

# The response:
{
"num_records": 1,
"records": [
  {
    "name": "engine0",
    "primary_servers": [
      "10.132.145.22",
      "10.140.101.109"
    ],
    "port": 9876,
    "type": "synchronous",
    "format": "xml"
  }
]
}
----

'''

=== Retrieving an FPolicy engine configuration for a particular SVM

'''

----

# The API:
GET /protocols/fpolicy/{svm.uuid}/engines

# The call:
curl -X GET "https://<mgmt-ip>/api/protocols/fpolicy/4f643fb4-fd21-11e8-ae49-0050568e2c1e/engines/?fields=*&return_records=true&return_timeout=15" -H "accept: application/json"

# The response:
{
"records": [
  {
    "svm": {
      "uuid": "4f643fb4-fd21-11e8-ae49-0050568e2c1e"
    },
    "name": "cifs",
    "primary_servers": [
      "10.20.20.10"
    ],
    "port": 9876,
    "type": "synchronous"
  },
  {
    "svm": {
      "uuid": "4f643fb4-fd21-11e8-ae49-0050568e2c1e"
    },
    "name": "nfs",
    "primary_servers": [
      "10.23.140.64",
      "10.140.101.109"
    ],
    "secondary_servers": [
      "10.132.145.20",
      "10.132.145.22"
    ],
    "port": 9876,
    "type": "synchronous",
    "format": "xml",
    "ssl_option": "no_auth",
    "resiliency": {
      "enabled": false,
      "retention_duration": "PT3M"
    },
    "buffer_size": {
      "recv_buffer": 262144,
      "send_buffer": 1048576
    },
    "max_server_requests": 500,
    "request_cancel_timeout": "PT29S",
    "request_abort_timeout": "PT3M",
    "server_progress_timeout": "PT1M",
    "status_request_interval": "PT23S",
    "keep_alive_interval": "PT2M",
    "session_timeout": "PT10S",
    "max_connection_retries": 5
  }
],
"num_records": 2
}
----

'''

=== Retrieving a specific FPolicy engine configuration for an SVM

'''

----

# The Api:
GET /protocols/fpolicy/{svm.uuid}/engines/{name}

#The call:
curl -X GET "https://<mgmt-ip>/api/protocols/fpolicy/4f643fb4-fd21-11e8-ae49-0050568e2c1e/engines/cifs?fields=*" -H "accept: application/json"

# The response:
{
"svm": {
  "uuid": "4f643fb4-fd21-11e8-ae49-0050568e2c1e"
 },
 "name": "cifs",
 "primary_servers": [
   "10.20.20.10"
 ],
 "port": 9876,
 "type": "synchronous",
 "format": "xml"
}
----

'''

=== Updating an FPolicy engine for an SVM

'''

----

# The API:
PATCH /protocols/fpolicy/{svm.uuid}/engines/{name}

# The call:
curl -X PATCH "https://<mgmt-ip>/api/protocols/fpolicy/4f643fb4-fd21-11e8-ae49-0050568e2c1e/engines/cifs" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"port\": 6666, \"secondary_servers\": [ \"10.132.145.20\", \"10.132.145.21\" ], \"type\": \"synchronous\"}"
----

'''

=== Updating all the attributes of a specific FPolicy engine for an SVM

'''

----

# The API:
PATCH /protocols/fpolicy/{svm.uuid}/engines/{name}

# The call:
curl -X PATCH "https://<mgmt-ip>/api/protocols/fpolicy/4f643fb4-fd21-11e8-ae49-0050568e2c1e/engines/cifs" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"port\": 9876, \"primary_servers\": [ \"10.132.145.20\", \"10.140.101.109\" ], \"secondary_servers\": [ \"10.132.145.23\", \"10.132.145.21\" ], \"type\": \"synchronous\", \"format\": \"protobuf\"}"
----

'''

=== Deleting a specific FPolicy engine for an SVM

'''

----

# The API:
DELETE /protocols/fpolicy/{svm.uuid}/engines/{name}

# The call:
curl -X DELETE "https://<mgmt-ip>/api/protocols/fpolicy/4f643fb4-fd21-11e8-ae49-0050568e2c1e/engines/cifs" -H "accept: application/json"
----

'''


