---
sidebar: sidebar
api: true
explorer: false
permalink: 'protocols_nvme_interfaces_endpoint_overview.html'
summary: 'View NVMe interfaces'
---

= View NVMe interfaces



== Overview

NVMe interfaces are network interfaces configured to support an NVMe over Fabrics (NVMe-oF) protocol. The NVMe interfaces can be Fibre Channel interfaces or IP (Internet Protocol) interfaces supporting any of the supported NVMe-oF data protocols. Regardless of the underlying physical and data protocol, NVMe interfaces are treated equally for host-side application configuration. This endpoint provides a consolidated view of all NVMe interfaces for the purpose of configuring host-side applications.

The `interface_type` field discriminates which type of interface is being returned and an additional field with the same name as the `interface_type` contains additional type-specific information about the interface.

NVMe interfaces must be created using the protocol-specific endpoints for Fibre Channel or IP interfaces. See link:post-network-fc-interfaces(#-networking-fc-interface-create)andpost-network-ip-interfaces.html<</networking/fc_interface_create,POST /network/fc/interfaces>> and [POST /network/ip/interfaces] . After creation, the interfaces are available via this interface.

== Examples

=== Retrieving summary information for all NVMe interfaces

----

# The API:
GET /api/protocols/nvme/interfaces

# The call:
curl -X GET 'https://<mgmt-ip>/api/protocols/nvme/interfaces' -H 'Accept: application/hal+json'

# The response:
{
"records": [
  {
    "svm": {
      "uuid": "013e2c44-0d30-11e9-a684-005056bbdb14",
      "name": "svm1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/013e2c44-0d30-11e9-a684-005056bbdb14"
        }
      }
    },
    "uuid": "74d69872-0d30-11e9-a684-005056bbdb14",
    "name": "nvme1",
    "_links": {
      "self": {
        "href": "/api/protocols/nvme/interfaces/74d69872-0d30-11e9-a684-005056bbdb14"
      }
    }
  },
  {
    "svm": {
      "uuid": "013e2c44-0d30-11e9-a684-005056bbdb14",
      "name": "svm1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/013e2c44-0d30-11e9-a684-005056bbdb14"
        }
      }
    },
    "uuid": "77ded991-0d30-11e9-a684-005056bbdb14",
    "name": "nvme2",
    "_links": {
      "self": {
        "href": "/api/protocols/nvme/interfaces/77ded991-0d30-11e9-a684-005056bbdb14"
      }
    }
  }
],
"num_records": 2,
"_links": {
  "self": {
    "href": "/api/protocols/nvme/interfaces"
  }
}
}
----

'''

=== Retrieving detailed information for a specific NVMe interface

----

# The API:
GET /api/protocols/nvme/interfaces/{uuid}

# The call:
curl -X GET 'https://<mgmt-ip>/api/protocols/nvme/interfaces/77ded991-0d30-11e9-a684-005056bbdb14' -H 'Accept: application/hal+json'

# The response:
{
"svm": {
  "uuid": "013e2c44-0d30-11e9-a684-005056bbdb14",
  "name": "svm1",
  "_links": {
    "self": {
      "href": "/api/svm/svms/013e2c44-0d30-11e9-a684-005056bbdb14"
    }
  }
},
"uuid": "77ded991-0d30-11e9-a684-005056bbdb14",
"name": "nvme2",
"enabled": true,
"node": {
  "name": "node1",
  "uuid": "cd4d47fd-0d2e-11e9-a684-005056bbdb14",
  "_links": {
    "self": {
      "href": "/api/cluster/nodes/cd4d47fd-0d2e-11e9-a684-005056bbdb14"
    }
  }
},
"transport_address": "nn-0x2003005056bbdb14:pn-0x2005005056bbdb14",
"fc_interface": {
  "wwnn": "20:03:00:50:56:bb:db:14",
  "wwpn": "20:05:00:50:56:bb:db:14",
  "port": {
    "name": "1a",
    "uuid": "081ec491-0d2f-11e9-a684-005056bbdb14",
    "node": {
      "name": "node1"
    },
    "_links": {
      "self": {
        "href": "/api/network/fc/ports/081ec491-0d2f-11e9-a684-005056bbdb14"
      }
    }
  },
  "_links": {
    "self": {
      "href": "/api/network/fc/interfaces/77ded991-0d30-11e9-a684-005056bbdb14"
    }
  }
},
"_links": {
  "self": {
    "href": "/api/protocols/nvme/interfaces/77ded991-0d30-11e9-a684-005056bbdb14"
  }
}
}
----

'''


