---
sidebar: sidebar
api: true
explorer: false
permalink: 'security_authentication_password_endpoint_overview.html'
summary: 'Update the user account password'
---

= Update the user account password



== Overview

This API changes the password for a local user account.

Only cluster administrators with the _"admin"_ role can change the password for other cluster or SVM user accounts. If you are not a cluster administrator, you can only change your own password.

== Examples

=== Changing the password of another cluster or SVM user account by a cluster administrator

Specify the user account name and the new password in the body of the POST request. The owner.uuid or owner.name are not required to be specified for a cluster-scoped user account.

For an SVM-scoped account, along with new password and user account name, specify either the SVM name as the owner.name or SVM uuid as the owner.uuid in the body of the POST request. These indicate the SVM for which the user account is created and can be obtained from the response body of a GET request performed on the _/api/svm/svms_ API.

----

# The API:
POST "/api/security/authentication/password"

# The call to change the password of another cluster user:
curl -X POST "https://<mgmt-ip>/api/security/authentication/password" -d '{"name":"cluster_user1","password":"<USER-PASSWORD>"}'
----

----

# The call to change the password of another SVM user:
curl -X POST "https://<mgmt-ip>/api/security/authentication/password" -d '{"owner.name":"svm1","name":"svm_user1","password":"<USER-PASSWORD>"}'
----

----

# The call to change the password hash algorithm of the cluster user:
curl -X POST "https://<mgmt-ip>/api/security/authentication/password" -d '{"name":"cluster_user1","password":"<USER-PASSWORD>","password_hash_algorithm":"sha256"}'
----

----

# The call to change the password hash algorithm of another SVM user:
curl -X POST "https://<mgmt-ip>/api/security/authentication/password" -d '{"owner.name":"svm1","name":"svm_user1","password":"<USER-PASSWORD>","password_hash_algorithm":"sha256"}'
----

=== Changing the password of an SVM-scoped user

NOTE: The IP address in the URI must be same as one of the interfaces owned by the SVM.

----

# The API:
POST "/api/security/authentication/password"

# The call:
curl -X POST "https://<SVM-ip>/api/security/authentication/password" -d '{"name":"svm_user1","password":"<USER-PASSWORD>"}'
----

'''


