---
sidebar: sidebar
api: true
explorer: false
permalink: 'security_roles_owner.uuid_name_privileges_endpoint_overview.html'
summary: 'Manage role privilege details'
---

= Manage role privilege details



== Overview

This API is used to configure the role privileges (tuples of REST URI paths or command/command directory paths, their access levels and optional queries, where the tuples refer to command/command directory paths). It also retrieves all of the privilege tuples for a role and can add a tuple to an existing role or creates a new role with the provided tuple. The "path" attribute can be a resource-qualified endpoint. Currently, the only supported resource-qualified endpoints are the following&#58;

=== Snapshots APIs

&ndash; _/api/storage/volumes/{volume.uuid}/snapshots_

=== File System Analytics APIs

&ndash; _/api/storage/volumes/{volume.uuid}/files_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/clients_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/directories_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/files_

&ndash; _/api/storage/volumes/{volume.uuid}/top-metrics/users_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/clients_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/directories_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/files_

&ndash; _/api/svm/svms/{svm.uuid}/top-metrics/users_

==== ONTAP S3 APIs

&ndash; _/api/protocols/s3/services/{svm.uuid}/users_

==== Artificial Intelligence Data Engine (AIDE) APIs

===== Data Compute Node (DCN) APIs

&ndash; _/api/dcn/cluster/nodes/{node.uuid}/metrics_

&ndash; _/api/dcn/network/ports/{port.uuid}/metrics_

===== Data-Engine APIs

&ndash; _/api/data-engine/policies/{policy.uuid}/versions_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/acls_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections/{datacollection.uuid}/acls_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections/{entity.uuid}/entities_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections/{datacollection.uuid}/search_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections/{datacollection.uuid}/versions_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-collections/{datacollection.uuid}/versions/{version.uuid}/diffs_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/data-sources_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/entities_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/entities/{entity.uuid}/custom-attributes_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/queries_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/queries/{query.uuid}/entities_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/versions_

&ndash; _/api/data-engine/workspaces/{workspace.uuid}/versions/{version.uuid}/diffs_

When used in the context of data collection APIs, _{version.uuid}_ refers to a data collection version. In the context of workspace APIs, it refers to a workspace version.

In the APIs above, and in the context of REST roles, the wildcard character &#42; can be used in place of _{volume.uuid}_ or _{svm.uuid}_ to represent _all_ volumes or _all_ SVMs, depending on whether the REST endpoint references volumes or SVMs. The _{volume.uuid}_ corresponds to the _-instance-uuid_ field in the output of the "volume show" command at the diagnostic privilege level. It can also be retrieved through the REST endpoint _/api/storage/volumes_.

In the AIDE APIs described above, and in the context of REST roles, the wildcard character &#42; can be used in place of variable components in the Uniform Resource Identifier (URI) path, such as _{node.uuid}_, _{port.uuid}_, _{policy.uuid}_, _{workspace.uuid}_, _{datacollection.uuid}_,  _{entity.uuid}_, _{version.uuid}_, or _{query.uuid}_. The specific variable to be replaced depends on whether the REST endpoint references nodes, ports, policies, workspaces, data collections, entities, versions, or queries.

However, when using the wildcard character &#42; in place of a variable component in a URI path, it must replace

*all* variable components in that path. Mixing wildcards and specific values for different variable components within the same URI path is not supported in REST roles. For example, a URI path such as _/api/data-engine/workspaces/c6e1b325-4125-11f0-abb5-bc2411f6fd43/data-collections/*/search_ is not supported.

In summary, only the following two types of resource-qualified endpoints are supported in a REST role:

* All variable components in the URI path are specific values. Example: _/api/data-engine/workspaces/c6e1b325-4125-11f0-abb5-bc2411f6fd43/data-collections/b09b6d25-4126-11f0-abb5-bc2411f6fd43/search_
* All variable components in the URI path are wildcards. Example: _/api/data-engine/workspaces/*/data-collections/*/search_

AIDE APIs are supported only in cluster-scoped REST roles, not in SVM-scoped REST roles.

The role can be SVM-scoped or cluster-scoped.

Specify the owner UUID and the role name in the URI path. The owner UUID corresponds to the UUID of the SVM for which the role has been created and can be obtained from the response body of a GET request performed on one of the following APIs&#58;

* _/api/security/roles_ for all the roles
* _/api/security/roles/?scope=svm_ for SVM-scoped roles
* _/api/security/roles/?owner.name=+++<svm-name>+++</i> for roles in a specific SVM This API response contains the complete URI for each role and can be used after suffixing it with _"privileges"_.+++</svm-name>+++_

NOTE: The pre-defined roles can be retrieved but cannot be updated.

== Examples

=== Adding a privilege tuple for a REST URI/endpoint to an existing custom role

----

# The API:
POST "/security/roles/{owner.uuid}/{name}/privileges"

# The call:
curl -X POST "https://<mgmt-ip>/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges" -d '{"access":"readonly","path":"/api/protocols"}'
----

=== Adding a privilege tuple for a command or command directory to an existing custom role

----

# The API:
POST "/security/roles/{owner.uuid}/{name}/privileges"

# The call:
curl -X POST "https://<mgmt-ip>/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges" -d '{"access":"all","path":"statistics volume show","query":"-vserver vs1&#124;vs2 -aggregate aggr1&#124;aggr2"}'
----

=== Retrieving all the privilege tuples for a REST role

----

# The API:
GET "/api/security/roles/{owner.uuid}/{name}/privileges"

# The call:
curl -X GET "https://<mgmt-ip>/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges"

# The response:
{
"records": [
  {
    "path": "/api/application",
    "access": "all",
    "_links": {
      "self": {
        "href": "/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges/%2Fapi%2Fapplication"
      }
    }
  },
  {
    "path": "/api/protocols",
    "access": "readonly",
    "_links": {
      "self": {
        "href": "/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges/%2Fapi%2Fprotocols"
      }
    }
  },
  {
    "path": "/api/storage/volumes/1385d680-74fc-4adb-a348-9a740e83702a/snapshots",
    "access": "all",
    "_links": {
      "self": {
        "href": "/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges/%2Fapi%2Fstorage%2Fvolumes%2F1385d680-74fc-4adb-a348-9a740e83702a%2Fsnapshots"
      }
    }
  },
  {
    "path": "/api/storage/volumes/*/top-metrics/users",
    "access": "read_create_modify",
    "_links": {
      "self": {
        "href": "/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges/%2Fapi%2Fstorage%2Fvolumes%2F%2A%2Ftop-metrics%2Fusers"
      }
    }
  }
],
"num_records": 4,
"_links": {
  "self": {
    "href": "/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges"
  }
}
}
----

=== Retrieving all the privilege tuples for a custom legacy role

----

# The API:
GET "/api/security/roles/{owner.uuid}/{name}/privileges"

# The call:
curl -X GET "https://<mgmt-ip>/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges"

# The response:
{
"records": [
  {
    "path": "network interface",
    "access": "readonly",
    "_links": {
      "self": {
        "href": "/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges/network%20interface"
      }
    }
  },
  {
    "path": "security",
    "access": "readonly",
    "_links": {
      "self": {
        "href": "/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges/security"
      }
    }
  },
  {
    "path": "security certificate"
    "access": "all",
    "_links": {
      "self": {
        "href": "/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges/security%20certificate"
      }
    }
  },
  {
    "path": "security password"
    "access": "all",
    "_links": {
      "self": {
        "href": "/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges/security%20password"
      }
    }
  }
],
"num_records": 4,
"_links": {
  "self": {
    "href": "/api/security/roles/aaef7c38-4bd3-11e9-b238-0050568e2e25/svm_role1/privileges"
  }
}
}
----


