---
sidebar: sidebar
api: true
explorer: false
permalink: 'security_authentication_duo_groups_endpoint_overview.html'
summary: 'View and create Duo groups'
---

= View and create Duo groups



== Overview

This API configures the group to be included in Duo authentication.

== Examples

=== Creating a Duo group

Specify the group name and other necessary information in the body of the POST request. The owner.uuid or owner.name are not required for a cluster-scoped account.

----

# The API:
POST "/api/security/authentication/duo/groups"

# The call:
curl -k https://<mgmt-ip>/api/security/authentication/duo/groups --request POST --data '{"name": "test",  "comment": "test post"}'

# The response:
{
}
----

=== Creating a Duo group for SVM-scoped account

For an SVM-scoped account, specify either the SVM name as the owner.name or the SVM UUID as the owner.uuid along with other parameters for the group. These parameters indicate the SVM that contains the user group and can be obtained from the response body of the GET request performed on the API "/api/svm/svms".

----

# The API:
POST "/api/security/authentication/duo/groups"

# The call:
curl -k https://<mgmt-ip>/api/security/authentication/duo/groups --request POST --data '{"name": "test",  "comment": "test post", "owner.name":"vs0" }'

# The response:
{
}
----

=== Retrieving the configured Duo groups

Retrieves the Duo groups associated with the owners or filtered list (for a specific SVM and so on).

----

# The API:
GET "/api/security/authentication/duo/groups"

# The call to retrieve Duo groups with the cluster or SVM:
curl -k https://<mgmt-ip>/api/security/authentication/duo/groups

# the response:
{
"records": [
{
  "owner": {
  "uuid": "5f618c80-d90a-11ed-a6e6-0050568e8ef2",
  "name": "vs0"
}
},
{
"owner": {
"uuid": "f810005a-d908-11ed-a6e6-0050568e8ef2",
"name": "cluster-1"
}
}
],
"num_records": 2
}
----


