---
sidebar: sidebar
api: true
explorer: false
permalink: 'storage_volumes_volume.uuid_top-metrics_users_endpoint_overview.html'
summary: 'View I/O activity for users'
---

= View I/O activity for users



== Overview

You can use this API to retrieve a list of users with the most I/O activity for a specified volume, within the past several seconds. Use the `top_metric` parameter to specify which type of I/O activity to filter for. This API is used to provide insight into I/O activity and supports ordering by I/O activity types, namely `iops` or `throughput` metrics. This API also supports only returning one I/O activity type per request.

== Approximate accounting and error bars

When too many users have recent activity, some users might be dropped from the list. In this situation, the spread of values in the `error` field increases, indicating that there are larger error bars on the value for `iops` or `throughput`. As the list becomes increasingly more approximate due to dropped entries, some of the users that would have otherwise been included might not be present in the final list returned by the API.

== Failure to return list of users with most I/O activity

The API can sometimes fail to return the list of users with the most I/O activity, due to the following reasons:

&ndash; The volume does not have the activity tracking feature enabled.

&ndash; The volume has not had any recent NFS/CIFS client traffic.

&ndash; The NFS/CIFS client operations are being served by the client-side filesystem cache.

&ndash; The NFS/CIFS client operations are being buffered by the client operating system.

&ndash; On rare occasions, the incoming traffic pattern is not suitable to obtain the list of users with the most I/O activity.

== Failure to return the usernames

The API can sometimes fail to obtain the usernames for the list of userid entries, due to internal transient errors.
In such cases, instead of the username, the API will return "{+++<user-id>+++}" for the user entry.+++</user-id>+++

== Retrieve a list of the users with the most I/O activity

For a report on the users with the most I/O activity returned in descending order, specify the I/O activity type you want to filter for by passing the `iops` or `throughput` property into the top_metric parameter. If the I/O activity type is not specified, by default the API returns a list of the users with the greatest number of the average read operations per second. The current maximum number of users returned by the API for an I/O activity type is 25.

&ndash; GET   /api/storage/volumes/{volume.uuid}/top-metrics/users

== Examples

=== Retrieving a list of the users with the greatest average number of read bytes received per second:

----

# The API:
GET /api/storage/volumes/{volume.uuid}/top-metrics/users

# The Call:
curl -X GET "https://<mgmt-ip>/api/storage/volumes/{volume.uuid}/top-metrics/users?top_metric=throughput.read"

# The Response:
{
"records": [
  {
    "volume": {
      "name": "vol1"
    },
    "throughput": {
      "read": 1495,
      "error": {
        "lower_bound": 1495,
        "upper_bound": 1502
      }
    },
    "user_id": "S-1-5-21-256008430-3394229847-3930036330-1001",
    "user_name": "John",
    "svm": {
      "uuid": "572361f3-e769-439d-9c04-2ba48a08ff43",
      "name": "vs1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/572361f3-e769-439d-9c04-2ba48a08ff43"
        }
      }
    }
  },
  {
    "volume": {
      "name": "vol1"
    },
    "throughput": {
      "read": 1022,
      "error": {
        "lower_bound": 1022,
        "upper_bound": 1025
      }
    },
    "user_id": "1988",
    "user_name": "Ryan",
    "svm": {
      "uuid": "572361f3-e769-439d-9c04-2ba48a08ff43",
      "name": "vs1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/572361f3-e769-439d-9c04-2ba48a08ff43"
        }
      }
    }
  },
  {
    "volume": {
      "name": "vol1"
    },
    "throughput": {
      "read": 345,
      "error": {
        "lower_bound": 345,
        "upper_bound": 348
      }
    },
    "user_id": "S-1-5-21-256008430-3394229847-3930036330-1003",
    "user_name": "Julie",
    "svm": {
      "uuid": "572361f3-e769-439d-9c04-2ba48a08ff43",
      "name": "vs1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/572361f3-e769-439d-9c04-2ba48a08ff43"
        }
      }
    }
  }
],
"num_records": 3,
"_links": {
  "self": {
    "href": "/api/storage/volumes/73b293df-e9d7-46cc-a9ce-2df8e52ef864/top-metrics/users?top_metric=throughput.read"
  }
}
}
----

== Example showing the behavior of the API when there is no read/write traffic:

----

# The Call:
curl -X GET "https://<mgmt-ip>/api/storage/volumes/{volume.uuid}/top-metrics/users?top_metric=throughput.write"

# The Response:
{
"records": [
],
"num_records": 0,
"notice": {
  "message": "The activity tracking report for volume \"FV\" in SVM \"vs0\" returned zero records. Check whether the volume have read/write traffic. Refer to the REST API documentation for more information on why there might be no records.",
  "code": "124518418"
},
"_links": {
  "self": {
    "href": "/api/storage/volumes/9af63729-8ac8-11ec-b1bc-005056a79da4/top-metrics/users?top_metric=throughput.write"
  }
}
}
----


