---
sidebar: sidebar
api: true
explorer: false
permalink: 'storage_volumes_volume.uuid_top-metrics_clients_endpoint_overview.html'
summary: 'View I/O activity for clients'
---

= View I/O activity for clients



== Overview

You can use this API to retrieve a list of clients with the most I/O activity for a specified volume, within the past several seconds. Use the `top_metric` parameter to specify which type of I/O activity to filter for. This API is used to provide insight into I/O activity and supports ordering by I/O activity types, namely `iops` and `throughput` metrics. This API supports only returning one I/O activity type per request.

== Approximate accounting and error bars

When too many clients have recent activity, some clients might be dropped from the list. In this situation, the spread of values in the `error` field increases, indicating that there are larger error bars on the value for `iops` or `throughput`. As the list becomes increasingly more approximate due to dropped entries, some of the clients that would have otherwise been included might not be present in the final list returned by the API.

== Failure to return list of clients with most I/O activity

The API can sometimes fail to return the list of clients with the most I/O activity, due to the following reasons:

&ndash; The volume does not have the activity tracking feature enabled.

&ndash; The volume has not had any recent NFS/CIFS client traffic.

&ndash; The NFS/CIFS client operations are being served by the client-side filesystem cache.

&ndash; The NFS/CIFS client operations are being buffered by the client operating system.

&ndash; On rare occasions, the incoming traffic pattern is not suitable to obtain the list of clients with the most I/O activity.

&ndash; NFSv4 client read operations using Multi-Processor I/O (MPIO) are not tracked.

== Retrieve a list of the clients with the most I/O activity

For a report on the clients with the most I/O activity returned in descending order, specify the I/O activity type you want to filter for by passing the `iops` or `throughput` I/O activity type into the top_metric parameter. If the I/O activity type is not specified, by default the API returns a list of clients with the greatest number of average read operations per second. The current maximum number of clients returned by the API for an I/O activity type is 25.

&ndash; GET   /api/storage/volumes/{volume.uuid}/top-metrics/clients

== Examples

=== Retrieving a list of the clients with the greatest average number of write operations per second:

----

# The API:
GET /api/storage/volumes/{volume.uuid}/top-metrics/clients

# The Call:
curl -X GET "https://<mgmt-ip>/api/storage/volumes/{volume.uuid}/top-metrics/clients?top_metric=iops.write"

# The Response:
{
"records": [
  {
    "volume": {
      "name": "vol1"
    },
    "iops": {
      "write": 1495,
      "error": {
        "lower_bound": 1495,
        "upper_bound": 1505
      }
    },
    "client_ip": "172.28.71.128",
    "svm": {
      "uuid": "572361f3-e769-439d-9c04-2ba48a08ff43",
      "name": "vs1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/572361f3-e769-439d-9c04-2ba48a08ff43"
        }
      }
    }
  },
  {
    "volume": {
      "name": "vol1"
    },
    "iops": {
      "write": 1022,
      "error": {
        "lower_bound": 1022,
        "upper_bound": 1032
      }
    },
    "client_ip": "172.28.71.179",
    "svm": {
      "uuid": "572361f3-e769-439d-9c04-2ba48a08ff43",
      "name": "vs1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/572361f3-e769-439d-9c04-2ba48a08ff43"
        }
      }
    }
  },
  {
    "volume": {
      "name": "vol1"
    },
    "iops": {
      "write": 345,
      "error": {
        "lower_bound": 345,
        "upper_bound": 355
      }
    },
    "client_ip": "172.28.51.62",
    "svm": {
      "uuid": "572361f3-e769-439d-9c04-2ba48a08ff43",
      "name": "vs1",
      "_links": {
        "self": {
          "href": "/api/svm/svms/572361f3-e769-439d-9c04-2ba48a08ff43"
        }
      }
    }
  }
],
"num_records": 3,
"_links": {
  "self": {
    "href": "/api/storage/volumes/73b293df-e9d7-46cc-a9ce-2df8e52ef864/top-metrics/clients?top_metric=iops.write"
  }
}
}
----

== Example showing the behavior of the API when there is no read/write traffic:

----

# The Call:
curl -X GET "https://<mgmt-ip>/api/storage/volumes/{volume.uuid}/top-metrics/clients?top_metric=throughput.write"

# The Response:
{
"records": [
],
"num_records": 0,
"notice": {
  "message": "The activity tracking report for volume \"FV\" in SVM \"vs0\" returned zero records. Check whether the volume have read/write traffic. Refer to the REST API documentation for more information on why there might be no records.",
  "code": "124518418"
},
"_links": {
  "self": {
    "href": "/api/storage/volumes/9af63729-8ac8-11ec-b1bc-005056a79da4/top-metrics/clients?top_metric=throughput.write"
  }
}
}
----


