---
sidebar: sidebar
api: true
explorer: false
permalink: 'storage_file_clone_endpoint_overview.html'
summary: 'Manage storage file clones'
---

= Manage storage file clones



== Overview

You can use these API's to create file clones, retrieve split status and manage split loads. These endpoints are used for cloning files within a volume, without taking much of extra space. Child and parent clones shares the unchanged blocks of data. REST support for sis clone creation for Flex Group volumes is blocked.

A file clone split operation detach child clone from its parent. Split operations use space. To ensure that file clone create operation is not affected by split, file clone tokens are use to reserve space. API endpoints can be used to update the validity and space reserved by token.

== File clone APIs

The following APIs are used to perform the following operations:

&ndash; POST      /api/storage/file/clone

&ndash;  GET      /api/storage/file/clone/split-status

&ndash; PATCH     /api/storage/file/clone/split-loads/{node.uuid}

&ndash;  GET      /api/storage/file/clone/split-loads/{node.uuid}

&ndash;  GET      /api/storage/file/clone/split-loads

&ndash;  GET      /api/storage/file/clone/tokens/

&ndash; DELETE    /api/storage/file/clone/tokens/{node.uuid}/{token.uuid}

&ndash; PATCH     /api/storage/file/clone/tokens/{node.uuid}/{token.uuid}


