---
sidebar: sidebar
api: true
explorer: false
permalink: 'storage_volume-efficiency-policies_endpoint_overview.html'
summary: 'Manage volume efficiency policies'
---

= Manage volume efficiency policies



=== Overview

Volume efficiency policies specify information about efficiency policies that are applied to the volume.

== Volume efficiency policy APIs

The following APIs are used to perform operations related to volume efficiency policy information:

&ndash; POST      /api/storage/volume-efficiency-policies

&ndash; GET       /api/storage/volume-efficiency-policies

&ndash; GET       /api/storage/volume-efficiency-policies/\{uuid}

&ndash; PATCH     /api/storage/volume-efficiency-policies/\{uuid}

&ndash; DELETE    /api/storage/volume-efficiency-policies/\{uuid}

== Examples

=== Creating a volume efficiency policy

The POST operation is used to create a volume efficiency policy with the specified attributes.

----

# The API:
/api/storage/volume-efficiency-policies

# The call:
curl -X POST  "https://<mgmt-ip>/api/storage/volume-efficiency-policies" -H "accept: application/hal+json" -d '{"name": "new_policy", "type": "scheduled", "schedule": { "name": "daily" }, "duration": "2", "qos_policy": "best_effort", "enabled": "true", "comment": "schedule-policy", "svm": { "name": "vs1"}}'

# The response:
HTTP/1.1 201 Created
Date: Tue, 12 Mar 2019 21:20:24 GMT
Server: libzapid-httpd
X-Content-Type-Options: nosniff
Cache-Control: no-cache,no-store,must-revalidate
Location: /api/storage/volume-efficiency-policies/a69d8173-450c-11e9-aa44-005056bbc848
Content-Length: 369
Content-Type: application/json
{
"num_records": 1,
"records": [
  {
    "uuid": "a69d8173-450c-11e9-aa44-005056bbc848",
    "svm": {
      "name": "vs1"
    },
    "name": "new_policy",
    "type": "scheduled",
    "schedule":{
      "name": "daily"
    },
    "duration": "2",
    "qos_policy": "best_effort",
    "enabled": "true",
    "comment": "schedule-policy"
  }
]
}
----

=== Retrieving volume efficiency policy attributes

The GET operation is used to retrieve volume efficiency policy attributes.

----

# The API:
/api/storage/volume-efficiency-policies

# The call:
curl -X GET "https://<mgmt-ip>/api/storage/volume-efficiency-policies" -H "accept: application/hal+json"

# The response:
HTTP/1.1 200 OK
Date: Tue, 12 Mar 2019 21:17:17 GMT
Server: libzapid-http
X-Content-Type-Options: nosniff
Cache-Control: no-cache,no-store,must-revalidate
Content-Length: 686
Content-Type: application/json
{
"records": [
  {
    "uuid": "3c112527-2fe8-11e9-b55e-005056bbf1c8",
    "name": "default",
    "_links": {
      "self": {
        "href": "/api/storage/volume-efficiency-policies/3c112527-2fe8-11e9-b55e-005056bbf1c8"
      }
    }
  },
  {
    "uuid": "3c1c1656-2fe8-11e9-b55e-005056bbf1c8",
    "name": "default-1weekly",
    "_links": {
      "self": {
        "href": "/api/storage/volume-efficiency-policies/3c1c1656-2fe8-11e9-b55e-005056bbf1c8"
      }
    }
  },
  {
    "uuid": "3c228b82-2fe8-11e9-b55e-005056bbf1c8",
    "name": "none",
    "_links": {
      "self": {
        "href": "/api/storage/volume-efficiency-policies/3c228b82-2fe8-11e9-b55e-005056bbf1c8"
      }
    }
  }
],
"num_records": 3,
"_links": {
  "self": {
    "href": "/api/storage/volume-efficiency-policies/"
  }
}
}
----

=== Retrieving the attributes of a specific volume efficiency policy

The GET operation is used to retrieve the attributes of a specific volume efficiency policy.

----

# The API:
/api/storage/volume-efficiency-policies/{uuid}

# The call:
curl -X GET "https://<mgmt-ip>/api/storage/volume-efficiency-policies/3c112527-2fe8-11e9-b55e-005056bbf1c8" -H "accept: application/hal+json"

# The response:
HTTP/1.1 200 OK
Date: Tue, 12 Mar 2019 21:24:48 GMT
Server: libzapid-httpd
X-Content-Type-Options: nosniff
Cache-Control: no-cache,no-store,must-revalidate
Content-Length: 381
Content-Type: application/json
{
"uuid": "3c112527-2fe8-11e9-b55e-005056bbf1c8",
"name": "new_policy",
"type": "scheduled",
"schedule": {
  "name": "daily"
},
"duration": "2",
"qos_policy": "best_effort",
"enabled": "true",
"comment": "schedule-policy",
"svm": {
  "name": "vs1"
},
"_links": {
  "self": {
    "href": "/api/storage/volume-efficiency-policies/3c112527-2fe8-11e9-b55e-005056bbf1c8"
  }
}
}
----

=== Updating a volume efficiency policy

The PATCH operation is used to update the specific attributes of a volume efficiency policy.

----

# The API:
/api/storage/volume-efficiency-policies/{uuid}

# The call:
curl -X PATCH  "https://<mgmt-ip>/api/storage/volume-efficiency-policies/ae9e65c4-4506-11e9-aa44-005056bbc848" -d '{"duration": "3" }' -H "accept: application/hal+json"

# The response:
HTTP/1.1 200 OK
Date: Tue, 12 Mar 2019 21:27:04 GMT
Server: libzapid-httpd
X-Content-Type-Options: nosniff
Cache-Control: no-cache,no-store,must-revalidate
Content-Length: 3
Content-Type: application/json
----

=== Deleting a volume efficiency policy

The DELETE operation is used to delete a volume efficiency policy.

----

# The API:
/api/storage/volume-efficiency-policies/{uuid}

# The call:
curl -X DELETE "https://<mgmt-ip>/api/storage/volume-efficiency-policies/  ae9e65c4-4506-11e9-aa44-005056bbc848" -H "accept: application/hal+json"

# The response:
HTTP/1.1 200 OK
Date: Tue, 12 Mar 2019 21:19:04 GMT
Server: libzapid-httpd
X-Content-Type-Options: nosniff
Cache-Control: no-cache,no-store,must-revalidate
Content-Length: 3
Content-Type: application/json
----


