---
sidebar: sidebar
api: true
explorer: false
permalink: 'svm_peer-permissions_endpoint_overview.html'
summary: 'Manage SVM peer permissions'
---

= Manage SVM peer permissions



== Managing SVM peer permissions

A cluster administrator can provide permissions for use during intercluster SVM peer relationship creation. Once this permission exists for a local SVM and peer cluster combination on a local cluster, no explicit SVM peer accept (or REST PATCH) API is required for any incoming SVM peer relationship creation requests from a remote cluster for that local SVM. Peer relationship directly changes the state to peered on both clusters. Use an SVM name as "*" to create permissions that apply to all local SVMs.

=== SVM peer permission APIs

The following APIs are used to manage SVM peer permissions:

* GET /api/svm/peer-permissions
* POST /api/svm/peer-permissions
* GET /api/svm/peer-permissions/{cluster_peer.uuid}/{svm.uuid}
* PATCH /api/svm/peer-permissions/{cluster_peer.uuid}/{svm.uuid}
* DELETE /api/svm/peer-permissions/{cluster_peer.uuid}/{svm.uuid}


